pkg/processor/eventsource/eventsource.go

Workers are now released on processing errors / panics, after a recent PR broke this behavior.

Bugfix: Release workers on error conditions

---

cmd/nuctl/main.go
hack/processor/build/onbuild/nubuilder.sh
pkg/nubuild/build/build.go
pkg/nubuild/build/docker.go
pkg/nuctl/command/nuctl.go
vendor/github.com/iguazio/v3io-go-http/synccontainer.go
vendor/github.com/iguazio/v3io-go-http/synccontext_test.go
vendor/github.com/iguazio/v3io-go-http/types.go

Clearly show compilation errors in nuctl build/run

---

pkg/processor/eventsource/http/event.go
pkg/processor/runtime/golang/event_handler/demo.go
pkg/processor/runtime/python/encode_test.go
vendor/github.com/nuclio/nuclio-sdk/event.go

Support HTTP query args through event "Field"

---

pkg/functioncr/function.go
pkg/functioncr/types.go
pkg/nuctl/command/run.go
pkg/nuctl/runner/function.go
pkg/nuctl/runner/types.go
pkg/processor/runtime/python/encode_test.go

nuctl run can use name from function spec

---

pkg/processor/eventsource/eventsource.go
pkg/processor/eventsource/http/eventsource.go
pkg/processor/runtime/golang/event_handler/demo.go
pkg/processor/runtime/golang/runtime.go
pkg/processor/webadmin/resource/eventsources.go
pkg/processor/webadmin/resource/resource.go
pkg/processor/webadmin/resource/resource_test.go
vendor/github.com/nuclio/nuclio-sdk/error.go

1. Web admin resource supports create, update, delete
2. Web admin resource supports status code in custom routes
3. Functions can use `nuclio.ErrX` (e.g. `nuclio.ErrNotFound` -> 404) to return status codes in HTTP

Web admin extensions, functions can return status codes through errors

---

pkg/processor/runtime/python/runtime.go

Socket path was generated several times, Python was broken but tests passed due to stale base image.

Fix py socket path

---

Makefile
pkg/processor/runtime/python/doc.go
pkg/processor/runtime/python/test_wrapper.py
pkg/processor/runtime/python/wrapper.py

- Use record.getMessage() to get full formatted log message
- Make Python tests pass
- Add test-python Makefile

Fix Python logging & more

---

pkg/functiondep/client.go

Controller will wait for 60s if it needs to create a deployment/service and the resource is deleting

Controller waits for deleting resources before creating

---

pkg/nuctl/command/deploy.go
pkg/nuctl/command/nuctl.go
pkg/nuctl/test/build_test.go
pkg/nuctl/test/deploy_test.go
pkg/nuctl/test/reverser/reverser.go
pkg/nuctl/test/suite.go
pkg/platform/invoker.go

1. Build -> Deploy (using run-image) -> Invoke -> Delete
2. Deploy -> Invoke -> Delete

Support basic nuctl integration tests

---

pkg/zap/logger.go

Remove testing flags from processor

---

pkg/nuctl/command/build.go
pkg/nuctl/command/deploy.go
pkg/nuctl/command/invoke.go
pkg/nuctl/command/nuctl.go
pkg/nuctl/command/version.go

@pavius Please merge and re-generate the *docs/reference/nuctl/* MD files.

[DOC REVIEW] Minor fixes to the nuctl CLI reference help text

---

Makefile
pkg/common/url.go
pkg/errors/errors.go
pkg/nuctl/test/build_test.go
pkg/processor/build/inlineparser/parser.go
pkg/processor/build/runtime/golang/runtime.go
pkg/processor/build/runtime/pypy/docker/Dockerfile.handler-pypy
pkg/processor/build/runtime/pypy/docker/Dockerfile.processor-pypy
pkg/processor/build/runtime/pypy/docker/pypy.pc
pkg/processor/build/util/copy.go

Build refactor cleanup

---

pkg/dockerclient/shell.go
pkg/nuctl/command/get.go
pkg/platform/kube/function.go
pkg/platform/local/platform.go

Fixes #422 and adds support for storing/retrieving spec in local platform

Fix nuctl get -o yaml/json

---

pkg/cmdrunner/cmdrunner.go

ShellRunner.Run() Error Includes Stdout And Stderr

---

hack/k8s/helm/nuclio/Chart.yaml
hack/k8s/helm/nuclio/README.md
hack/k8s/helm/nuclio/templates/NOTES.txt
hack/k8s/helm/nuclio/values.yaml

Once approved, need to update the `gh-pages` branch with new chart index

updated chart with alignment to k8s charts

---

pkg/common/helper.go
pkg/processor/trigger/http/event.go

Fixes #277, discovered by @cstockton

Safe conversion from []byte to string

---

README.md

I added info about the nuclio global hackathon at the request of Tamar, who approved the text.
@pavius Please merge and ping Tamar and me when it's done. Thanks.

Add nuclio global hackaton info

---

pkg/processor/build/runtime/shell/test/shell_test.go
pkg/processor/runtime/shell/runtime.go
pkg/processor/runtime/shell/test/shell_test.go

Add support for set response headers in function spec for shell scripts

---

ROADMAP.md

included node.js assuming we add it

Updated roadmap (for 2.2)

---

cmd/playground/static/assets/app.js

- Add "Paths" to HTTP-kind trigger. For now only one host is available.
- Fix log issue where sometimes function invocation is not printed

Add "Paths" to HTTP-kind trigger; Fix log issue (not printing sometimes)

---

cmd/playground/static/assets/app.css
cmd/playground/static/assets/app.js

Playground: wrap lines of "Commands" field

---

cmd/playground/static/assets/app.js

Playground: enforce all lowercase for function name

---

pkg/processor/build/builder.go

Error message on function.yaml exists, no runtime and path is dir

---

cmd/playground/static/assets/app.js

Playground: Deleting trigger from UI does not actually delete trigger

---

pkg/functionconfig/reader.go
pkg/processor/build/builder.go

Camel case inline config

---

pkg/processor/build/builder.go
pkg/processor/build/builder_test.go
pkg/processor/build/template.go
pkg/processor/build/test/build_test.go

Fixes #475 
Added `DEBIAN_FRONTEND noninteractive` environment variable to images based on Jessie

image-specific environment variables

---

cmd/playground/main.go
cmd/playground/static/assets/app.js
pkg/playground/resource/function.go

Playground reject simultaneous deploys

---

pkg/processor/build/builder.go
pkg/processor/build/builder_test.go

Add "ca-certificates" package to alpine-based images

---

pkg/playground/resource/function.go

Playground recover from panic

---

docs/setup/gke/getting-started-gke.md
pkg/dockercreds/dockercred.go
pkg/dockercreds/dockercreds_test.go

1. Fixes #550
2. Updates to GKE / GCR getting started guide

Support old style dockerconfig

---

README.md

README: Remove global hackathon references

---

.travis.yml
vendor/github.com/inconshreveable/mousetrap/LICENSE
vendor/github.com/inconshreveable/mousetrap/README.md
vendor/github.com/inconshreveable/mousetrap/trap_others.go
vendor/github.com/inconshreveable/mousetrap/trap_windows.go
vendor/github.com/inconshreveable/mousetrap/trap_windows_1.4.go

Travis will build nuctl for windows on release

---

pkg/functionconfig/types.go
pkg/nuctl/command/build.go
pkg/processor/build/builder.go
pkg/processor/build/builder_test.go
pkg/processor/build/runtime/test/suite/suite.go
pkg/processor/build/test/build_test.go

Revert "Add FunctionSourceCode to function build config"

---

hack/minikube/scripts/push_images.py
pkg/functionconfig/types.go
pkg/platform/kube/controller/function.go
pkg/platform/kube/deployer.go
pkg/playground/resource/function.go
pkg/processor/test/suite/suite.go

Change state names to better reflect function lifecycle + prepare for the builder service

Add function states

---

pkg/dashboard/server.go
pkg/playground/server.go
pkg/processor/webadmin/server.go
pkg/restful/resource.go
pkg/restful/server.go

Restful servers implemented install middleware, but this was never called. Changed restful.Server to be an interface implemented by AbstractServer, just like everywhere else in the code.

restful server actually calls install middlewares

---

pkg/nuctl/command/invoke.go
pkg/nuctl/test/function_test.go
test/_functions/common/logging/golang/logging.go

Add 2 nuctl tests, fix issue with nuctl invoke logging output

---

pkg/dashboard/ui/build.config.js
pkg/dashboard/ui/gulpfile.js
pkg/dashboard/ui/package-lock.json
pkg/dashboard/ui/package.json
pkg/dashboard/ui/resources/gulpErrorHandler/package-lock.json
pkg/dashboard/ui/resources/previewServer/package-lock.json
pkg/dashboard/ui/src/app/components/default/default.component.js
pkg/dashboard/ui/src/app/components/default/default.tpl.html
pkg/dashboard/ui/src/app/components/monaco-editor/monaco-editor.component.js
pkg/dashboard/ui/src/index.html

Steps:
* add monaco-editor npm package
* add a simple copy of the monaco-editor to the assets folder - do you want to look at packaging this differently?
* add a monaco-editor directive to create the editor on a div and bind code and language properties. Currently it is using $interval to sync editor changes back to the scope - needs further research to explore monaco events 
* update DefaultController to have filename, code and language. Currently has csharp code, but also has commented out javascript option to demonstrate that, too
* update default.tpl.html to have div with monaco-editor directive, as well as a text area to show binding to the code property

Starting point for monaco editor integration

---

pkg/dashboard/ui/src/app/components/default/default.component.js
pkg/dashboard/ui/src/app/components/default/default.tpl.html
pkg/dashboard/ui/src/app/components/monaco-editor/monaco-editor.component.js

Refactor settings into a codefile object (code, language, filename, useSpaces)
Add theme switcher
Add python codefile

Add theme and code switcher

---

pkg/dashboard/ui/src/app/components/monaco-editor/monaco-editor.component.js
pkg/dashboard/ui/src/index.html

Add a `def` snippet for python

Add python snippet

---

pkg/dashboard/resource/function.go
pkg/dashboard/resource/project.go
pkg/processor/webadmin/resource/triggers.go
pkg/restful/resource.go
pkg/restful/resource_test.go

Makes the code much clearer and less error prone.

restful.CustomRouteFuncResponse

---

pkg/platform/local/store.go

Fix regression: If no project created and get projects was called in local platform, 500 was returned

---

hack/examples/README.md

Java examples in examples README

---

cmd/processor/app/processor.go
docs/tasks/configuring-a-platform.md
pkg/processor/loggersink/appinsights/factory.go
pkg/processor/loggersink/appinsights/types.go
pkg/processor/loggersink/registry.go
pkg/processor/loggersink/stdout/factory.go
pkg/processor/loggersink/stdout/types.go
pkg/processor/loggersink/types.go
pkg/processor/metricsink/appinsights/types.go
vendor/github.com/nuclio/logger-appinsights/appinsightlogger.go

Support appinsights log sink

---

cmd/processor/app/processor.go
docs/tasks/configuring-a-platform.md
pkg/processor/loggersink/appinsights/factory.go
pkg/processor/loggersink/appinsights/types.go
pkg/processor/metricsink/appinsights/metricsink.go
pkg/processor/metricsink/appinsights/types.go

maxBatchIntervalSeconds (number) became maxBatchInterval (string)

Align appinsights logger config with metrics

---

pkg/dashboard/resource/function.go
pkg/dashboard/test/server_test.go

Disable put function dashboard

---

pkg/dashboard/ui/bower.json
pkg/dashboard/ui/build.config.js
pkg/dashboard/ui/src/app/app.module.js

'ngFileUpload' package added to dependency list.

'ngFileUpload' package added to dependency list

---

hack/examples/golang/regexscan/regexscan.go
hack/examples/python/encrypt/function.yaml
hack/examples/python/facerecognizer/function.yaml
hack/examples/python/sentiments/sentiments.py
pkg/dashboard/functiontemplates/generated.go
pkg/platform/kube/platform.go

1. Fix function event display name in k8s
2. Fix regex template
3. Fix sentiments template

Fix function event display name in k8s

---

README.md
ROADMAP.md
docs/concepts/configuring-a-function.md
docs/concepts/k8s/function-ingress.md
docs/devel/coding-conventions.md
docs/devel/contributing.md
docs/devel/minikube/developing-on-minikube.md
docs/reference/function-configuration/function-configuration-reference.md
docs/reference/runtimes/dotnetcore/writing-a-dotnetcore-function.md
docs/reference/runtimes/shell/writing-a-shell-function.md
docs/reference/triggers/cron.md
docs/reference/triggers/eventhub.md
docs/reference/triggers/http.md
docs/reference/triggers/kafka.md
docs/reference/triggers/kinesis.md
docs/reference/triggers/nats.md
docs/reference/triggers/rabbitmq.md
docs/reference/triggers/v3iostream.md
docs/setup/aks/getting-started-aks.md
docs/setup/gke/getting-started-gke.md
docs/setup/k8s/getting-started-k8s.md
docs/setup/minikube/getting-started-minikube.md
docs/tasks/benchmarking.md
docs/tasks/configuring-a-platform.md
docs/tasks/deploying-functions.md
docs/tasks/deploying-pre-built-functions.md
hack/examples/README.md

Revert "[DOC REVIEW] Doc-review changes for nuclio v0.34 — #2"

---

pkg/dashboard/ui/bower.json
pkg/dashboard/ui/build.config.js
pkg/dashboard/ui/src/app/app.module.js

https://github.com/iguazio/dashboard-controls/issues/58

Angular slider

---

pkg/dashboard/ui/bower.json
pkg/dashboard/ui/build.config.js
pkg/dashboard/ui/src/app/app.module.js

IG-1789 [Nuclio] Support function import / export.
Added packages for YAML parsing.

IG-1789 [Nuclio] Support function import / export

---

pkg/functionconfig/types.go
pkg/platform/kube/functionres/lazy.go
pkg/platform/kube/functionres/lazy_test.go
pkg/processor/build/runtime/test/suite/suite.go
test/_functions/common/json-parser-with-function-config/python/parser.py
test/_functions/common/json-parser-with-inline-function-config/python/parser.py

Documentation will follow.
Piggybacking an integration test fix.
Fixes #518.

Support ingress annotations

---

pkg/dashboard/ui/src/less/typography.less

IG-1751 [General] Get rid of "Raleway" font

IG-1751 [General] Get rid of "Raleway" font

---

pkg/platform/abstract/platform.go

To allow users to specify images in the dashboard, the backend builder needs to apply the following logic:
```
create_function:
if spec.build.functionSourceCode != "":
spec.image = build(spec.build.functionSourceCode)
elif spec.build.path != "":
spec.image = build(spec.build.path)
elif spec.build.image != "":
spec.image = build(spec.build.path)
elif spec.image == "":
error()
deploy(spec.image)
```

Perform build even if spec.build is passed

---

README.md

Hi,
Just making it a bit easier to start with.

Improve README.md with Docker testing procedure

---

hack/examples/dotnetcore/helloworld/function.yaml
hack/examples/dotnetcore/helloworld/helloworld.cs
hack/examples/dotnetcore/reverser/function.yaml
hack/examples/golang/eventhub/function.yaml
hack/examples/golang/helloworld/function.yaml
hack/examples/golang/image/function.yaml
hack/examples/golang/rabbitmq/function.yaml
hack/examples/golang/regexscan/function.yaml
hack/examples/nodejs/dates/function.yaml
hack/examples/python/encrypt/function.yaml
hack/examples/python/facerecognizer/function.yaml
hack/examples/python/helloworld/function.yaml
hack/examples/python/tensorflow/function.yaml
pkg/dashboard/functiontemplates/generated.go

Templates were created with 0 replicas, this addresses that and a few other template fixes

Fix templates

---

pkg/dashboard/ui/package.json

- Fix: Deploy block disappears on switching tabs Code/Configuration/Triggers (on first deploy only)
- Make "Create new function" screen responsive for smaller viewports

Update dashboard-controls version to 0.0.52

---

hack/examples/dotnetcore/helloworld/function.yaml
hack/examples/dotnetcore/reverser/function.yaml
hack/examples/golang/eventhub/function.yaml
hack/examples/golang/helloworld/function.yaml
hack/examples/golang/image/function.yaml
hack/examples/golang/rabbitmq/function.yaml
hack/examples/golang/regexscan/function.yaml
hack/examples/nodejs/dates/function.yaml
hack/examples/python/encrypt/function.yaml
hack/examples/python/facerecognizer/function.yaml
hack/examples/python/helloworld/function.yaml
hack/examples/python/tensorflow/function.yaml
pkg/dashboard/functiontemplates/generated.go

Use min/max replicas in templates, fix TensorFlow base image

---

pkg/dashboard/ui/package.json

- Update function name validation pattern
- Disable Deploy button on new item creation until apply/discard
- Add Runtime Attributes for Java (for repositories)
- Allow user to configure dependencies
- Add "Archive" and "Jar" Entry Types
- Do not send "x-nuclio-*-namespace" headers
- Do not populate `metadata.namespace` on frontend for new entities
- Project becomes unchecked on creating new one (it should not)
- Stuck on "Deploying..." on failed deploy (before polling ever starts)
- Breadcrumbs arrow-head styling is stuck after its drop-down closes
- "Actions" disappears on action selection ("Export" is there instead)
- "Key" field is not a required field in key-value lists (it should be)

Update dashboard-controls version to 0.0.55

---

Makefile
pkg/processor/runtime/rpc/rpc_test.go
pkg/processor/runtime/rpc/runtime.go

Handle logging at any point in RPC runtime

---

pkg/dashboard/ui/package.json

- Add new tab "Status & Monitoring"

Update dashboard-controls version to 0.0.58

---

pkg/dashboard/ui/package.json

- Move Logging left if no Runtime Attributes
- "Deploying..." not displayed on deploying
- "Delete" action removes only one project when more than one are checked
- Error messages are displayed in "Edit project" dialog
- Set 0 to empty number inputs of v3io stream trigger
- Code editor not working properly when there's only one line
- Horizontal scroll-bar is not displayed on code editor
- No warning when leaving function screen via breadcrumbs and there are some unsaved changes
- Tooltip on status tab isn't properly aligned
- v3io stream trigger: Make some fields not required and add defaults
- Move the "Theme" drop-down to demo mode only (can't use different themes on different editor instances)

UI: Update dashboard-controls version to 0.0.62

---

pkg/dashboard/ui/dashboard-config.json
pkg/dashboard/ui/package.json

Update dashboard-controls version to 0.0.63

---

pkg/dashboard/ui/dashboard-config.json

And by that, save the entire human race.
Plus, I'm silly.

UI: Revert dashboard-config.json change

---

hack/k8s/resources/nuclio-rbac.yaml
pkg/platform/kube/functionres/lazy.go

Check if unavailable replicas exist before declaring deployment is ready

---

pkg/dashboard/ui/package.json
pkg/dashboard/ui/src/app/app.run.js
pkg/dashboard/ui/src/app/components/header/header.component.js
pkg/dashboard/ui/src/app/shared/services/nuclio-client.service.js
pkg/dashboard/ui/src/app/shared/services/nuclio-event-data.servie.js
pkg/dashboard/ui/src/app/shared/services/nuclio-projects-data.service.js

Dependent on https://github.com/iguazio/dashboard-controls/pull/191

UI: Update dashboard-controls version to 0.1.3 + Fix API issues

---

pkg/dashboard/ui/bower.json
pkg/dashboard/ui/build.config.js
pkg/dashboard/ui/src/app/shared/services/third-party-components.service.js

fix https://github.com/iguazio/dashboard-controls/issues/186 .
can be merged after https://github.com/iguazio/dashboard-controls/pull/189 is merged.

UI: Use js-base64 instead of atob/btoa for utf-8 characters

---

pkg/dashboard/ui/package.json

- Add "Username" and "Password" fields to v3io data-binding instead of a single "Secret" field.
- Fix some minor issues in test pane.

Update dashboard-config version to 0.1.7

---

pkg/dashboard/ui/package.json

- Make "Templates" the first and default option for creating new functions.
- No error message is displayed on failed function deploy, and the loading spinner keeps spinning forever.

UI: Update dashboard-controls version to 0.1.15

---

hack/k8s/helm/nuclio/Chart.yaml
hack/k8s/helm/nuclio/templates/crd/function-event.yaml
hack/k8s/helm/nuclio/templates/crd/function.yaml
hack/k8s/helm/nuclio/templates/crd/project.yaml
hack/k8s/helm/nuclio/templates/deployment/controller.yaml
hack/k8s/helm/nuclio/templates/serviceaccount/service-account.yaml
hack/k8s/helm/nuclio/values.yaml
pkg/errors/errors.go
pkg/nuctl/command/invoke.go
pkg/renderer/renderer.go

This is for scripts that want granularity of choosing installing crd (which are cluster wide) and rbac rules and services (that can be per namespace)

New helm flags for enablement of crd and controller

---

pkg/dashboard/ui/dashboard-config.json
pkg/dashboard/ui/package.json
pkg/dashboard/ui/src/app/app.route.js
pkg/dashboard/ui/src/app/components/data-wrappers/create-function-data-wrapper/create-function-data-wrapper.component.js
pkg/dashboard/ui/src/app/components/data-wrappers/create-function-data-wrapper/create-function-data-wrapper.tpl.html

Depends on https://github.com/iguazio/dashboard-controls/pull/247

IG-1953 [Nuclio] Add "New function" to Projects screen

---

pkg/dashboard/ui/package.json

Monaco fix

---

pkg/dashboard/ui/package.json

Monaco pointer fixed

---

pkg/nuctl/command/build.go
pkg/nuctl/command/create.go
pkg/nuctl/command/delete.go
pkg/nuctl/command/deploy.go
pkg/nuctl/command/get.go
pkg/nuctl/command/invoke.go
pkg/nuctl/command/nuctl.go
pkg/nuctl/command/update.go
pkg/platform/kube/platform.go

Default namespace taken from platform, project display name defaults to project name

---

pkg/dashboard/ui/package.json

Depends on https://github.com/iguazio/dashboard-controls/pull/276

UI: Make test pane collapsible

---

pkg/dashboard/ui/dashboard-config.json
pkg/dashboard/ui/package.json
pkg/dashboard/ui/src/app/app.run.js

Depends on https://github.com/iguazio/dashboard-controls/pull/279

UI: Remove falsely displayed warning dialog (on new function)

---

pkg/dashboard/ui/dashboard-config.json

This was unintentional: https://github.com/nuclio/nuclio/pull/975/files#diff-a400c7aed2563eae98cc55e9b0892e44L4

UI: Revert dashboard-config.json that was unintentionally changed

---

pkg/processor/trigger/kafka/logger.go
pkg/processor/trigger/kafka/trigger.go

by forwarding them to Nuclio logger.

Enable Sarama logs

---

pkg/processor/build/runtime/test/suite/suite.go

Fix to build runtime integ. tests

---

pkg/dockerclient/dockerclient.go
pkg/dockerclient/mock.go
pkg/dockerclient/shell.go
pkg/nuctl/command/build.go
pkg/nuctl/command/deploy.go
pkg/nuctl/test/function_test.go
pkg/nuctl/test/suite.go
pkg/platform/local/platform.go
pkg/platform/types.go
pkg/processor/build/builder.go

At build you can now ask nuctl to create an archive of the builded docker image
And at deploy to ask nuctl to load an archive and deploy the image inside of it
Also if `--offline` is passed, set `--no-pull` to true as well

Support load and save of docker archives

---

pkg/dashboard/ui/package.json

- Added "Volumes" (key-value list)
- Added fields to "Build" block:
- "Image name" (text)
- "Readiness timeout (seconds)" (number)
- "Disable cache" (checkbox)
- "No internet access" (checkbox)
- for "Java" runtime only:
- "Repositories" (text list)
- "Dependencies" (text list)
Added these fields:
- "Worker allocator name" (text)
- for "HTTP" only:
- "Worker availability timeout (seconds)" (number)
- "Annotations" (key-value list)
- for "Kafka" only:
- "Consumer group" (text)
- "Initial offset" (drop-down: Earliest/Latest)
- "SASL":
- "Enabled" (checkbox)
- "Username" (text)
- "Password" (password)
- for "NATS" only:
- "Queue name" (text)
- "Username" (text)
- "Password" (password)

UI: Add new fields to Configuration and Triggers (see desc.)

---

pkg/dashboard/ui/package.json

- "Code Entry Type" Field:
- For "Archive" option:
- Added "Work Dir" field (optional)
(e.g. "/path/to/function/in/archive")
- Added a new "GitHub" option with the following fields:
- "URL" (e.g. "https://github.com/nuclio/nuclio")
- "Branch"
- "Work Dir" (optional) (e.g. "/path/to/function/in/archive")
Relates to https://github.com/iguazio/dashboard-controls/pull/299

UI: Add "GitHub" code entry type; Add "Work Dir" to "Archive"

---

pkg/dashboard/ui/package.json
pkg/dashboard/ui/src/app/shared/services/nuclio-event-data.service.js

- Add "Log Level" drop-down to Test pane
- Kafka:
- Change "Topic" to "Topics" as a list of strings
Various fixes in lately added fields.

Added "Log Level" drop-down menu in event pane

---

pkg/dashboard/ui/package.json
pkg/dashboard/ui/src/app/components/data-wrappers/create-function-data-wrapper/create-function-data-wrapper.component.js
pkg/dashboard/ui/src/app/components/data-wrappers/functions-data-wrapper/functions-data-wrapper.component.js
pkg/dashboard/ui/src/app/components/data-wrappers/functions-data-wrapper/functions-data-wrapper.tpl.html
pkg/dashboard/ui/src/app/components/data-wrappers/projects-data-wrapper/projects-data-wrapper.component.js
pkg/dashboard/ui/src/app/shared/services/nuclio-client.service.js
pkg/dashboard/ui/src/app/shared/services/nuclio-event-data.service.js
pkg/dashboard/ui/src/app/shared/services/nuclio-functions-data.service.js
pkg/dashboard/ui/src/app/shared/services/nuclio-namespaces-data.service.js
pkg/dashboard/ui/src/app/shared/services/nuclio-projects-data.service.js

Also:
Fix issue where scrollbars keep scrolling to the bottom after function deploy and navigating away from the function screen.
Depends on https://github.com/iguazio/dashboard-controls/pull/319

UI: Fix issue where deploy error is not displayed in logger

---

pkg/dashboard/ui/package.json

- Code Entry Type:
- On switching option clear all the option's relevant fields
- On deploy/export - include only the code entry attributes that are relevant to the selected option
- On init, if "Image" is the selected option, then load the value of `spec.image` into the "URL" field
- Data Bindings:
- Remove "Worker Allocator Name"
-  For Kafka only:
- Remove "URL"
- Remove "Partitions"
- Add "Brokers" (list of strings)
Depends on: https://github.com/iguazio/dashboard-controls/pull/325

UI: Fix Code Entry Type errors; Change Kafka trigger fields

---

pkg/dashboard/ui/src/app/components/data-wrappers/function-events-data-wrapper/function-events-data-wrapper.component.js
pkg/dashboard/ui/src/app/components/data-wrappers/function-events-data-wrapper/function-events-data-wrapper.tpl.html

Invocation port changes, it is not reflected in status pane
https://trello.com/c/nHxnR18x
Depends on https://github.com/iguazio/dashboard-controls/pull/315, https://github.com/iguazio/dashboard-controls/pull/331

Invocation port changes, it is not reflected in status pane

---

pkg/dashboard/ui/package.json
pkg/dashboard/ui/src/app/shared/services/angular-yamljs.service.js

Depends on: https://github.com/iguazio/dashboard-controls/pull/343
Implements this Trello card: https://trello.com/c/qoDcK33e

IG-2017 [Nuclio] Add "Export" button to project screen

---

pkg/dashboard/ui/package.json

- Create function: Import: "Create" button moved near "Import" button
- Added tooltip to "Target CPU" field: "Exceeding this threshold will increase the number of replicas"

UI: Add "Change text size" button to code editor (+ see desc.)

---

cmd/processor/app/processor.go
pkg/processor/build/builder.go
pkg/processor/runtime/golang/builtin.go
pkg/processor/trigger/cron/event.go
pkg/processor/trigger/kickstart/event.go
pkg/processor/trigger/kickstart/factory.go
pkg/processor/trigger/kickstart/trigger.go
pkg/processor/trigger/kickstart/types.go

A simple trigger that will invoke the handler once when the processor replica comes up, passing the event configured.

Kickstart trigger

---

docs/reference/function-configuration/function-configuration-reference.md
pkg/functionconfig/types.go

Adding to function spec a Base64 representation of an icon to be shown in UI for the function

Add avatar

---

pkg/dashboard/ui/package.json

- Project's function list screen:
- Added "View YAML" action to functions.
- Triggers:
- For "Cron" kind only:
- Added descriptive placeholder to "Interval" text box field.

UI: Add "View YAML" for functions;Add cron interval placeholder

---

pkg/dashboard/ui/package.json
pkg/dashboard/ui/src/app/components/data-wrappers/create-function-data-wrapper/create-function-data-wrapper.component.js
pkg/dashboard/ui/src/app/components/data-wrappers/create-function-data-wrapper/create-function-data-wrapper.tpl.html
pkg/dashboard/ui/src/app/shared/services/nuclio-functions-data.service.js

Reverts PR #1038 because back-end is not ready yet.
Reverts commit 5e79c2c2db86db885f818f3869916fb319ec4c72.
Depends on PR https://github.com/iguazio/dashboard-controls/pull/362

Revert "UI: Add support to function templates with parameters"

---

pkg/dashboard/ui/package.json

Depends on: https://github.com/iguazio/dashboard-controls/pull/366

UI: Enter key to submit new function form; Sort projects by name

---

pkg/dashboard/ui/package.json
pkg/dashboard/ui/src/app/components/data-wrappers/create-function-data-wrapper/create-function-data-wrapper.component.js
pkg/dashboard/ui/src/app/components/data-wrappers/create-function-data-wrapper/create-function-data-wrapper.tpl.html
pkg/dashboard/ui/src/app/shared/services/nuclio-functions-data.service.js

Depends on https://github.com/iguazio/dashboard-controls/pull/373 https://github.com/iguazio/dashboard-controls/pull/372
Re-applies PR #1038
Cancels PR #1046

UI: Add support to function templates with parameters

---

pkg/nuctl/command/deploy.go
pkg/nuctl/command/deploy_test.go

Any volume related parsing was discarded till now in nuctl deploy

Fix - Parsing volumes in nuctl deploy 

---

pkg/dashboard/functiontemplates/githubfunctiontemplatefetcher.go
pkg/dashboard/resource/invocation.go
pkg/restful/resource.go

Also fix issue with not getting source code for github functions that have only `function.yaml` and source code

have source code pass in template for template response

---

pkg/platform/kube/deployer.go

Image tag was prepended with run registry when not needed

Fix issue with image tag

---

pkg/platform/kube/scaler/autoscaler.go

To lower the chances of failing reports

Change to buffered channel in scaler

---

pkg/dashboard/ui/build.config.js
pkg/dashboard/ui/package.json
pkg/dashboard/ui/src/app/app.module.js

IG-2041 [Nuclio] White background in description cell on hover
Relates to: https://github.com/iguazio/dashboard-controls/pull/391

IG-2041 [Nuclio] White background in description cell on hover

---

pkg/dashboard/ui/package.json

Depends on: https://github.com/iguazio/dashboard-controls/pull/396

UI: shift "Logging" to prod; Fix Test Pane error on response JSON body

---

pkg/dashboard/ui/package.json

- Fix: Invocation URL is N/A for deployed functions.
- Fix: Test pane > Request > File: breaks Text/JSON.
- Display "Scaled to zero", "Enabling" & "Disabling" in function "Status" column.

UI: new function statuses; fix N/A invocation URL

---

pkg/dashboard/ui/package.json

- Add ability to order parameters by specifying an `order` property.
- Add "more info" icon with contents of `description` in case it is non-empty.
- Add red asterisk in case `required` is `true`.
- Limit dialog's height and add vertical scrollbar.
- Skip params whose `kind` is not one of the defined available values (currently: `'string'`, `'number'` and `'choice'`).
- `kind` is now case-INsensitive.
- Ignore duplicate params by key. In case there are more than one params sharing the same key, then the first one will be used and the others will be skipped.
- Bugfix: "Apply" button works although it looks disabled.
Depends on PR https://github.com/iguazio/dashboard-controls/pull/412

UI: Function template parameters tweaks (see desc.)

---

pkg/dashboard/ui/package.json

Depends on https://github.com/iguazio/dashboard-controls/pull/414

UI: Fix: Logs are missing in Test pane

---

hack/k8s/helm/nuclio/templates/role/function-deployer.yaml

To support the dynamic nature of custom metrics

update helm metrics resources to be all

---

pkg/dashboard/ui/package.json

- "Create new function" screen:
- From template:
- Parameters dialog:
- Bugfix: drop-down menu parameters do not populate the target value properly (in HTTP request to /api/render).
- "Code" tab:
- "Test" pane:
- Bugfix: "pinned" mode is broken (visually distorted).
- Bugfix: the request body is not cleared on clicking "+" button.
Depends on PR https://github.com/iguazio/dashboard-controls/pull/419

UI: Fix bugs in Test pane and in Template Parameters dialog

---

hack/examples/java/reverser/src/main/java/ReverseEventHandler.java
pkg/playground/fixtures/source.go
pkg/processor/runtime/java/docker/src/main/java/io/nuclio/processor/JsonEvent.java
pkg/processor/runtime/java/docker/src/main/java/io/nuclio/processor/ResponseEncoder.java
pkg/processor/runtime/java/docker/src/main/java/io/nuclio/processor/WrapperLogger.java
pkg/processor/runtime/java/test/outputter/Outputter.java

As using the default system encoding is a common pitfall.

getBytes using UTF-8 rather than system default encoding.

---

pkg/dashboard/ui/package.json
pkg/dashboard/ui/src/less/mixins.less

Depends on https://github.com/iguazio/dashboard-controls/pull/429

IG-2073 [General] Apply action icons styles by design

---

cmd/dashboard/app/dashboard.go
cmd/dashboard/main.go
pkg/common/zip.go
pkg/dashboard/functiontemplates/basefunctiontemplatefetcher.go
pkg/dashboard/functiontemplates/fetcher_test.go
pkg/dashboard/functiontemplates/gitfunctiontemplatefetcher.go
pkg/dashboard/functiontemplates/types.go
pkg/dashboard/functiontemplates/zipfunctiontemplatefetcher.go

Description:
Added a fetcher that can receive templates as a zip file.
Changes:
- added ZipFunctionTemplateFetcher
- added a base class to function template fetchers (BaseFunctionTemplateFetcher) to be used by both git and zip fetchers (keeps common logic)
- updated GitFunctionTemplateFetcher to use BaseFunctionTemplateFetcher

Zip function template fetcher

---

pkg/dashboard/ui/package.json

- Function screen » Code tab » Test pane:
- Bugfix: when closing test pane and re-opening it, it doesn't "push" the rest of the screen, but overlay it.
- Bugfix: minor visual bug on expanding log entries in Log tab in Response section.
Depends on PR https://github.com/iguazio/dashboard-controls/pull/434

UI: Fix test pane bugs

---

pkg/dashboard/ui/package.json
pkg/dashboard/ui/src/app/components/data-wrappers/version-data-wrapper/version-data-wrapper.component.js
pkg/dashboard/ui/src/app/components/data-wrappers/version-data-wrapper/version-data-wrapper.tpl.html
pkg/dashboard/ui/src/app/shared/services/nuclio-functions-data.service.js

Relates to PR https://github.com/nuclio/nuclio/pull/1114
Depends on PR https://github.com/iguazio/dashboard-controls/pull/437

UI: Use PUT when updating functions

---

pkg/dashboard/ui/package.json

- Projects: added display name uniqueness violation error message on project creation/edition (HTTP 409 Conflict).
- Function:
- Added function name uniqueness violation error message on function deploy (HTTP 409 Conflict).
- Moved error messages on deploy (POST/PUT requests) to pop-up dialog instead of using the deploy process logger.

UI: Show function/project name uniqueness violation error messages

---

hack/aks/resources/nuclio.yaml
hack/gke/resources/nuclio.yaml
hack/k8s/helm/nuclio/templates/crd/function-event.yaml
hack/k8s/helm/nuclio/templates/crd/function.yaml
hack/k8s/helm/nuclio/templates/crd/project.yaml
hack/k8s/resources/nuclio.yaml

fixes https://github.com/nuclio/nuclio/issues/1129

Remove description from resources

---

pkg/processor/trigger/partitioned/v3io/partition.go

Continue reading from v3io stream after error.

---

pkg/processor/runtime/python/py/_nuclio_wrapper.py
pkg/processor/runtime/python/py/requirements.txt
pkg/processor/runtime/python/runtime.go
pkg/processor/runtime/runtime.go
pkg/processor/runtime/types.go
pkg/processor/trigger/cron/factory.go
pkg/processor/trigger/http/factory.go
pkg/processor/trigger/kickstart/factory.go
pkg/processor/trigger/mqtt/basic/factory.go
pkg/processor/trigger/mqtt/iotcore/factory.go
pkg/processor/trigger/registry.go

Revert "Add trigger name to context"

---

pkg/dashboard/ui/package.json

Depends on PR https://github.com/iguazio/dashboard-controls/pull/452

UI: Show "Delete" action without 3-dot menu icon (1 less click)

---

pkg/dashboard/ui/package.json

- Function list:
- bugfix: Status and Invocation URL's port number are not updated on clicking the "Refresh" button.
Depends on PR https://github.com/iguazio/dashboard-controls/pull/456

UI: Status and port number not updating on Refresh

---

cmd/dashboard/app/dashboard.go
cmd/dashboard/main.go
hack/k8s/helm/nuclio/templates/deployment/dashboard.yaml

changes in helm and env stuff. for integration with provazio

Nuclio zip fetcher helm fixes

---

pkg/dashboard/ui/package.json

- Bugfix: corrupted function config YAML when a single-quote character is entered in "Build Commands".
- Bugfix: "Build Log" not updated in "Status" tab in function screen while/after deploying function.
Depends on PR https://github.com/iguazio/dashboard-controls/pull/480

UI: Function > Status > Build Log not updating while deploying

---

vendor/github.com/nuclio/logger-appinsights/appinsightlogger.go
vendor/github.com/nuclio/zap/logger.go
vendor/github.com/nuclio/zap/mux.go

Aligned with latest changes on:
- `nuclio/zap`
- `nuclio/logger-appinsights`
* support of logging with context

Vendor packages update

---

pkg/dashboard/ui/package.json

- Function:
- Configuration:
- Resources: split CPU and Memory into "Request" and "Limit". Change sliders to number inputs.
Depends on PR https://github.com/iguazio/dashboard-controls/pull/485

UI: Configuration: Resources: Add request+limit

---

pkg/processor/runtime/rpc/doc.go

Fix spelling mistake :)

---

pkg/dashboard/ui/package.json
pkg/dashboard/ui/src/less/mixins.less

- Projects: use pencil icon instead of cogwheel icon for "Edit" action
- Bugfix: Function » Code » Test pane icon is corrupted
Depends on PR https://github.com/iguazio/dashboard-controls/pull/493

IG-1295 [General] Fix three dot menu appearance

---

pkg/dashboard/ui/package.json

- Function:
- "Code" tab:
- for "Archive" code-entry type: add "Session key"
- "Configuration" tab:
- Volumes:
- for V3IO type:
- Change "Secret Name" to "Session Key", and make it password box
- Add "Container Name" text box
- Add "Sub Path" text box
Depends on PR https://github.com/iguazio/dashboard-controls/pull/503

UI: Add Session Key to Archive code-entry type & to V3IO volumes

---

pkg/dashboard/ui/package.json
pkg/dashboard/ui/src/less/mixins.less

Depends on PR https://github.com/iguazio/dashboard-controls/pull/505

IG-2166 [General] Add tenant name for all-seeing tenants

---

pkg/dashboard/ui/package.json

Depends on PR https://github.com/iguazio/dashboard-controls/pull/507

UI: Bugfix: Expanded items collapse on drop-down selection

---

pkg/dashboard/ui/package.json

- Function » Configuration » Resources:
- Change the layout of Replicas Min & Max fields like the Request & Limit fields of CPU and Memory.
- Move Target CPU below Replicas.
- Set minimum value of Request & Limit fields of Memory to 1 (instead of 0 or undefined).
- Before:
- After:
- Number input field: functionality improvements:
- When empty and clicking on up/down arrows of field — set first available value from [min, max] range in the relevant direction (up/down). If [min, max] range doesn't exist, use `0 +/- step`.
- Clicking on up/down arrows of field will not let the value cross the min/max limits, if they're defined.
Depends on PR https://github.com/iguazio/dashboard-controls/pull/521

UI: Improve Resources layout and number input field functionality

---

pkg/dashboard/ui/src/app/components/main-side-menu/main-side-menu.component.js

Bug originated in PR https://github.com/nuclio/nuclio/pull/1012

UI: Bugfix: Wrong version is displayed on left nav menu

---

pkg/dashboard/ui/package.json

Depends on PR https://github.com/iguazio/dashboard-controls/pull/536

UI: Reload function UI fields on deploy complete

---

pkg/dashboard/ui/package.json

- Function configuration & Triggers: Hide column headers when list is empty
- "Template Parameters" dialog: move labels to the left of fields
Depends on PR https://github.com/iguazio/dashboard-controls/pull/548

UI: Template Parameters dialog: move labels to the left of fields

---

pkg/processor/build/builder.go
pkg/processor/build/builder_test.go

Build commands support for multi-line commands

---

cmd/dashboard/app/dashboard.go
cmd/dashboard/main.go
pkg/dashboard/functiontemplates/gitfunctiontemplatefetcher.go

Added 3 new ENV vars:
- NUCLIO_TEMPLATES_GIT_USERNAME
- NUCLIO_TEMPLATES_GIT_PASSWORD
- NUCLIO_TEMPLATES_GITHUB_ACCESS_TOKEN

Fetch nuclio templates from private repository

---

pkg/functionconfig/types.go
pkg/platform/kube/functionres/lazy.go

Following #1200
Please merge matching PR in schemas before merging this one (iguazio repo)

Service account in function spec

---

pkg/functionconfig/types.go
pkg/platform/kube/functionres/lazy.go

Reverts nuclio/nuclio#1215
Will reopen and merge against development for consistency

Revert "Service account in function spec"

---

pkg/functionconfig/types.go
pkg/platform/kube/functionres/lazy.go

Following #1200
Please merge matching PR in schemas before merging this one (iguazio repo)

Service account in function spec (base: development)

---

pkg/dashboard/ui/package.json

Depends on PR https://github.com/iguazio/dashboard-controls/pull/573

UI: Reduce clickable area of "(+) Create a new X..." buttons

---

pkg/common/url.go
pkg/common/url_test.go
pkg/processor/build/builder.go

Addressing issues such as #1207

Allow downloading archive with long path

---

pkg/dashboard/ui/package.json

- Function » Configuration » Basic Settings: Added "Service Account" field
- Function » Configuration » Volumes: Added PVC type
Depends on PR https://github.com/iguazio/dashboard-controls/pull/576
Closes https://github.com/nuclio/nuclio/issues/1206

UI: Add "Service Account"; Add "PVC" volume type

---

pkg/dashboard/ui/package.json
pkg/dashboard/ui/src/app/components/data-wrappers/version-data-wrapper/version-data-wrapper.component.js
pkg/dashboard/ui/src/app/components/data-wrappers/version-data-wrapper/version-data-wrapper.tpl.html
pkg/dashboard/ui/src/app/shared/services/nuclio-projects-data.service.js

Closes https://github.com/nuclio/nuclio/issues/1202
Relates to PR https://github.com/nuclio/nuclio/pull/1223
Depends on PR https://github.com/iguazio/dashboard-controls/pull/581

UI: Triggers: HTTP: Ingresses: Auto-fill Host field

---

pkg/dockerclient/shell.go

Minor tweak on @tombastianello's PR #1191 to support building on amazon EKS, by allowing docker build using host networking
Thank you @tombastianello for the contribution!

Allow Nuclio build on EKS 2/2

---

cmd/dashboard/app/dashboard.go
cmd/dashboard/main.go
pkg/dashboard/resource/function.go
pkg/dashboard/server.go
pkg/dashboard/test/server_test.go
pkg/platform/abstract/platform.go
pkg/platform/types.go
pkg/processor/build/builder.go
pkg/processor/build/builder_test.go

Support replacing build / onbuild image registry URLs for air gapped environments

---

pkg/dashboard/ui/package.json

- Function » Code » GitHub code entry type: Rename "Work dir" to "Work directory"
- Function » Configuration: Remove "Data Bindings" pane
Depends on PR https://github.com/iguazio/dashboard-controls/pull/590

UI: Remove Data Bindings

---

pkg/dashboard/ui/package.json

Fix: Function » Configuration » Annotations, Labels & Environment Variables: latest changes in focused input field are not taken on "Deploy".
Depends on PR https://github.com/iguazio/dashboard-controls/pull/595

UI: Fix: Latest changes to focused field not taken on Deploy

---

pkg/dashboard/ui/package.json

- Projects: bugfix: function filter not working
- Function:
- Configuration » Build: Removed "No internet access" checkbox
- Triggers » for HTTP type only » Ingresses: default "Paths" field to "/" on creating a new ingress

UI: Config:Build: remove "No internet access" checkbox

---

pkg/common/url.go
pkg/dashboard/resource/function.go
pkg/processor/build/builder.go

Changes:
1. Returning error on non successful status code
2. (Irrelevant) Return image name on GET functions

Return error on download file failure

---

pkg/processor/runtime/java/docker/src/main/java/io/nuclio/processor/ResponseEncoder.java
pkg/processor/runtime/java/docker/src/main/java/io/nuclio/processor/Wrapper.java

#1248 Solves Java Metrics
Added minimum duration seconds to dodge returning value to zero.

Add Java Runtime with events_duration_milliseconds

---

pkg/nuctl/command/deploy.go
pkg/platform/kube/controller/nucliofunction.go
pkg/platform/kube/functionres/lazy.go
pkg/platform/local/platform.go

Revert "Remove HostPath from function resource (and default readiness timeout update)"

---

pkg/common/url.go
pkg/dashboard/resource/function.go
pkg/processor/build/builder.go

Revert "Return error on download file failure"

---

pkg/nuctl/command/deploy.go
pkg/platform/kube/controller/nucliofunction.go
pkg/platform/kube/functionres/lazy.go
pkg/platform/local/platform.go

exactly like #1251 - passed integration test

Remove HostPath from function resource (and default readiness timeout update) Tested

---

docs/reference/function-configuration/function-configuration-reference.md

Doc review for **docs/reference/function-configuration/function-configuration-reference.md** changes in PR #1250 commit c253284

Function-configuration reference

---

pkg/dashboard/ui/package.json
pkg/dashboard/ui/src/less/mixins.less

Also fix broken build.
Depends on PR: https://github.com/iguazio/dashboard-controls/pull/625

UI: Configuration: Add/edit some tooltips

---

docs/reference/triggers/v3iostream.md

@omesser / @liranbg please merge.

[DOC] Product name change: "Iguazio Continuous Data Platform" > "Iguazio Data-Science Platform" [IG-11333]

---

pkg/dashboard/ui/package.json

- Projects: bugfix: Import function not working
Depends on PR https://github.com/iguazio/dashboard-controls/pull/628

UI: Fix function import not working from Projects screen

---

pkg/dashboard/ui/package.json
pkg/dashboard/ui/src/app/components/header/header.tpl.html

https://trello.com/c/JQ4IkdYc/31-i18n-move-messages-from-dashboard-controls-to-dashboard

[i18n] Move messages from dashboard-controls to dashboard

---

pkg/dashboard/ui/build.config.js
pkg/dashboard/ui/gulpfile.js
pkg/dashboard/ui/src/app/app.run.js

https://trello.com/c/EyorsKeU/30-i18n-remove-i18n-warnings-from-unit-tests-output

[i18n] Remove i18n warnings from unit-tests output

---

pkg/dashboard/ui/package.json

- Create new function » from template: redesign and new UI/UX flow (first select template, then enter function name and project, if applicable)
Depends on PR https://github.com/iguazio/dashboard-controls/pull/658

UI: Create new function from template redesigned

---

pkg/dashboard/ui/gulpfile.js

Implements Trello ticket [[i18n] Add watcher to rebuild on changes in i18n dir](https://trello.com/c/JL5NffX6)

[i18n] Add watcher to rebuild on changes in i18n dir

---

pkg/dashboard/ui/package.json
pkg/dashboard/ui/src/app/components/header/header.less

Implements Trello ticket [[Nuclio] Wrong breadcrumbs color on hover](https://trello.com/c/sNCWcTce)
Depends on PR https://github.com/iguazio/dashboard-controls/pull/669

Wrong breadcrumbs color on hover

---

pkg/dashboard/ui/package.json
pkg/dashboard/ui/src/app/components/header/header.component.js
pkg/dashboard/ui/src/app/components/header/header.less
pkg/dashboard/ui/src/app/components/header/header.tpl.html

Also:
- [bugfix] Create New Function » from Template: "Template Parameters" dialog not opening when clicking on "Create" button.
Depends on PR https://github.com/iguazio/dashboard-controls/pull/676

[i18n] Redesign the language selector drop-down field

---

pkg/dashboard/ui/package.json

Depends on PR https://github.com/iguazio/dashboard-controls/pull/679

UI: Fix cropped template box when expanded on last template line

---

docs/reference/function-configuration/code-entry-types.md

[PR #3111 completion] Code-entry types function configuration: fix archive example & archive & S3 workDirectory requirement

---

cmd/processor/app/processor.go
docs/devel/contributing.md
pkg/platformconfig/platformconfig.go
pkg/processor/build/builder_test.go
pkg/processor/trigger/kafka/factory.go
pkg/processor/trigger/kafka/test/kafka_test.go
pkg/processor/trigger/kafka/trigger.go
pkg/processor/trigger/kafka/types.go
pkg/registry/registry.go

Fix kafka max workers

---

docs/reference/runtimes/dotnetcore/dotnetcore-reference.md

@liranbg this my review PR for the doc changes done in PR #1289. Preview review and merge.

[DOC-REVIEW] .NET Core Reference: Minor project-file doc edits for PR #1289

---

docs/devel/contributing.md

[DOC-REVIEW] Nuclio-contribution doc review

---

pkg/dashboard/ui/package.json

Depends on PR https://github.com/iguazio/dashboard-controls/pull/691

UI: Disallow editing labels for deployed functions

---

pkg/dashboard/ui/package.json

- “Code” tab:
- “Code entry type”: added tooltips to drop-down menu options
- For input fields of each code entry type:
- Add a tooltip
- Mark the mandatory fields with a red asterisk
- Change placeholder text (for some)
- Reorder some fields
- “Configuration” tab:
- “Base image”: change tooltip text
- “Onbuild image”: change tooltip text
- “Triggers” tab:
- “Class” drop-down field: rename “Eventhub” to “Azure Event Hubs”
- General: make web browser not show its own inherent form fields validation messages.

UI: Text changes and additions (tooltips, placeholders)

---

pkg/dashboard/ui/package.json
pkg/dashboard/ui/src/less/mixins.less

https://trello.com/c/Lf2CU1ez/94-services-presto-custom-params-add-advanced-section
Depends on PR https://github.com/iguazio/dashboard-controls/pull/702

[Services] Presto: Custom Params: Add Advanced section

---

pkg/nuctl/command/deploy.go
pkg/nuctl/command/get.go
pkg/nuctl/test/project_test.go
pkg/platform/abstract/invoker.go
pkg/platform/kube/deployer.go
pkg/platform/kube/platform.go
pkg/processor/runtime/dotnetcore/test/dotnetcore_test.go

Preserving function http port while building & if function build has failed

[IG-9003] Preserve function http port

---

pkg/dashboard/ui/package.json

- Create new function » from scratch » for Shell runtime only: set source code to "echo Hello, from nuclio" instead of empty source code
- Function » Triggers » for Cron trigger only » Schedule field: Remove the milliseconds part from the placeholder text

UI: Update Cron schedule placeholder; Add source code to Shell

---

pkg/dashboard/ui/package.json
pkg/dashboard/ui/src/app/components/data-wrappers/functions-data-wrapper/functions-data-wrapper.component.js
pkg/dashboard/ui/src/app/components/data-wrappers/functions-data-wrapper/functions-data-wrapper.tpl.html
pkg/dashboard/ui/src/less/mixins.less

Depends on PR https://github.com/iguazio/dashboard-controls/pull/711

[Nuclio] Add Invocation, Memory & CPU columns

---

pkg/dashboard/ui/package.json

Depends on PR https://github.com/iguazio/dashboard-controls/pull/713

UI: Display error messages from back-end as-is

---

cmd/autoscaler/Dockerfile
pkg/processor/build/builder.go

Propagate a more specific error message on function path resolve failure

Accurate error message on function path resolve failure

---

pkg/dashboard/ui/package.json

Depends on PR https://github.com/iguazio/dashboard-controls/pull/716

UI: Fix values in CPU column cells to represent K8s CPU cores

---

pkg/dashboard/ui/package.json

- Function: added tooltip to Deploy button when it is disabled, to explain the reason it is disabled (some invalid configuration exists)
- Function » Test Pane: Remove “File” option from request body types drop-down menu (available in demo mode only)
- New function from template: [bugfix] Some characters are not properly entered into the “Name” field
- Duplicate function dialog: [bugfix] Character counter is missing from “Name” field
- Triggers: [bugfix] “Class” drop-down menu is fixed, it does not scroll together with the rest of the screen
Depends on PR https://github.com/iguazio/dashboard-controls/pull/762

UI: Various minor fixes

---

pkg/dashboard/ui/package.json

Depends on PR https://github.com/iguazio/dashboard-controls/pull/767

UI: Fix: Disabled deploy button is bypassed by switching tabs

---

README.md
docs/concepts/best-practices-and-common-pitfalls.md

@pavius please review. You can see the updated [**best-practices-and-common-pitfalls.md**](https://github.com/Sharon-iguazio/nuclio/blob/doc-review-best-practices/docs/concepts/best-practices-and-common-pitfalls.md) guide on my PR branch. Note that I also added a link to the new guide from the "Further reading" section of the [**README.md**](https://github.com/Sharon-iguazio/nuclio/blob/doc-review-best-practices/README.md#further-reading) file (under "Concepts").

[DOC REVIEW]  best-practices-and-common-pitfalls.md (PR #1382)

---

pkg/dashboard/ui/package.json

- Function list: on hovering a function’s Name cell — a tooltip will display its full name (helps when the function name is long and gets truncated). The function’s description will be displayed below it.
- Projects: added checkboxes for functions and projects in projects screen. It is impossible to check a combination of functions and projects. You can either check projects or functions, separately
- [bugfix] Action menu: when some actions has an icon and some not — the text of the options with an icon is not horizontally aligned to the text of the options without an icon
Depends on PR https://github.com/iguazio/dashboard-controls/pull/784

UI: Projects: Add checkboxes to projects and functions

---

pkg/containerimagebuilderpusher/kaniko.go

- Restart policy: Never
- Backoff limit: 0
- Max execution time 1h

Added limits to kaniko job

---

pkg/dashboard/ui/package.json

- Projects:
- Hide expand icon for empty projects (projects that has no functions nested in them)
- [bugfix] on screen init, the expand button was not working properly (only after selecting “Projects” in “View by” field did the expand work properly)
- [bugfix] when view by projects, sorting by column sorted the projects instead of sorting the functions within the projects, and projects should just be sorted alphabetically in ascending order
- Functions list:
- “Invocation per sec” column:
- renamed to “Invocation/s”
- moved after “Invocation URL” column
- “Invocation #” moved to be last column
- [bugfix] Columns with charts break on smaller resolution
- [bugfix] Charts in table cells were broken after completing deletion of a function
Depends on PR …

UI: Projects/Functions lists: Various bug fixes and changes

---

pkg/dashboard/ui/package.json

- Function » Triggers: added tooltips to the “Class” drop-down menu options, and ellipsis is shown when option label overflows its horizontal space

UI: Triggers: Class drop-down options partially hidden

---

pkg/dashboard/ui/src/app/shared/services/import.service.js

Resolves Trello ticket [[Nuclio] Import project fails (display name instead of name)](https://trello.com/c/i8u0ghIk)

[Nuclio] Import project fails (display name instead of name)

---

pkg/dashboard/ui/package.json

- Projects » view by functions: make “Project” column sortable 
- Projects: [bugfix] list is not sorted by any column on init
Depends on PR https://github.com/iguazio/dashboard-controls/pull/803

UI: Functions: make Project col sortable; Projects: default sort

---

pkg/processor/runtime/python/runtime.go
pkg/processor/runtime/rpc/abstract.go

Watch wrapper process

---

hack/k8s/helm/nuclio/Chart.yaml

- bumping the right version: app version still 0.3.0

Fixing helm version

---

README.md
hack/examples/golang/callfunction/fibonacci/fibonacci.go
hack/examples/golang/callfunction/fibonacci/fibonaccisum.go
hack/examples/golang/helloworld/helloworld.go
hack/examples/golang/ingress/ingress.go
hack/examples/python/encrypt/encrypt.py
hack/examples/python/encrypt/function.yaml
hack/examples/python/sentiments/function.yaml
hack/examples/python/sentiments/sentiments.py
hack/examples/shell/img-convert/img-convert.sh
pkg/common/helper.go
pkg/dashboard/functiontemplates/generated.go
pkg/dashboard/functiontemplates/generator/generator.go

Examples generator fix

---

Makefile
hack/docker/tool-builder/Dockerfile

Makes things less complicated until we get to the safe shore of go modules

Build nuctl in docker

---

pkg/processor/timeout/timeout_test.go

Failed on travis ci for being too fast 😕

Fixed unittest timeout

---

README.md
docs/reference/runtimes/dotnetcore/dotnetcore-reference.md
docs/reference/runtimes/dotnetcore/writing-a-dotnetcore-function.md
hack/examples/README.md
pkg/processor/build/runtime/dotnetcore/docker/onbuild/Dockerfile
pkg/processor/build/runtime/dotnetcore/docker/onbuild/handler.csproj
pkg/processor/build/runtime/dotnetcore/runtime.go
pkg/processor/runtime/dotnetcore/test/_outputter/handler.csproj
pkg/processor/runtime/dotnetcore/wrapper.csproj
pkg/processor/trigger/kafka/test/kafka_test.go

- bump dotnet to 3.1
- fixed kafka ci tests

[1.1.x] Backport fixes

---

pkg/dashboard/ui/package.json
pkg/dashboard/ui/src/app/shared/services/import.service.js

https://trello.com/c/Q4FZJEPe/252-nuclio-import-add-error-message-on-error-parsing-yaml

[Nuclio] Import: Add error message on error parsing YAML

---

pkg/dashboard/ui/build.config.js
pkg/dashboard/ui/gulpfile.js

EranN is stupid.
Bug originates in this PR https://github.com/nuclio/nuclio/pull/1429

UI: Fix broken build

---

pkg/dashboard/ui/package.json
pkg/dashboard/ui/src/app/shared/services/import.service.js

- Projects: if a **409 Conflict** error is received due to name conflict when attempting to create a new project while importing, instead of failing just merge its functions into the existing project
- Export: [bugfix] empty projects are not exported on “Export all”
- Function » Code » “Archive” code-entry type » URL: reword placeholder
Depends on PR https://github.com/iguazio/dashboard-controls/pull/838

UI: Import: Merge projects with an existing name; Export: fix bug

---

docs/concepts/k8s/function-ingress.md
docs/setup/aks/setup-aks-appinsights-grafana.md

- Fixing Docs and yamls
- Adding helm install reference
Addressing issue #1435

Docs / concepts - ingress controller - fixing traefik links

---

pkg/dashboard/ui/package.json

- Functions » Invocation URL: added copy-to-clipboard button
- Function:
- Configuration » Labels, Environment Variables & Annotations: [bugfix] couldn't add new items because key uniqueness check failed
- Status » Invocation URL: added copy-to-clipboard button
Depends on PR https://github.com/iguazio/dashboard-controls/pull/847

UI: Fix: key uniqueness violation falsely detected

---

pkg/dashboard/ui/package.json

Function » Configuration » Labels & Annotations » Key: [bugfix] UI is stuck when entering long values into the text box
Depends on PR https://github.com/iguazio/dashboard-controls/pull/849

UI: Fix: UI stuck on long values in labels/annotations keys

---

pkg/dashboard/ui/src/app/components/projects/projects.component.js

https://trello.com/c/jcIwBezt/290-projects-initial-sort-doesnt-work

[Projects] Initial sort doesn't work

---

pkg/dashboard/ui/package.json
pkg/dashboard/ui/src/app/components/data-wrappers/create-function-data-wrapper/create-function-data-wrapper.component.js
pkg/dashboard/ui/src/app/components/projects/edit-project-dialog/edit-project-dialog.tpl.html
pkg/dashboard/ui/src/app/components/projects/new-project-dialog/new-project-dialog.tpl.html
pkg/dashboard/ui/src/app/components/projects/projects.tpl.html
pkg/dashboard/ui/src/less/mixins.less

- Complete rebranding
- Fix error on creating a new project from Project drop-down in Create New Function screen
Depends on PR https://github.com/iguazio/dashboard-controls/pull/866

UI: Accommodate to Iguazio rebrand changes

---

pkg/processor/runtime/python/py/_nuclio_wrapper.py

[Backport] Catch All Exceptions raised by Python wrapper

---

pkg/dashboard/ui/package.json

Depends on PR https://github.com/iguazio/dashboard-controls/pull/875

UI: Triggers > Kafka > Consumer Group: make mandatory

---

pkg/processor/runtime/python/runtime.go
pkg/processor/runtime/rpc/abstract.go

Panic on wrapper ps crash [1.1.x backport]

---

pkg/processor/runtime/rpc/abstract.go

Panic on runtime processWrapper crash

---

pkg/processor/runtime/python/py/_nuclio_wrapper.py
pkg/processor/runtime/python/py/requirements.txt
pkg/processor/trigger/http/event.go

Moved event parsing to https://github.com/nuclio/nuclio-sdk-py/pull/3

Move event inintializing to nuclio sdk py

---

pkg/processor/runtime/python/py/_nuclio_wrapper.py
pkg/processor/runtime/python/py/requirements.txt
pkg/processor/trigger/http/event.go

Backport https://github.com/nuclio/nuclio/pull/1475

[Backport] Move event inintializing to nuclio sdk py

---

pkg/processor/runtime/rpc/abstract_test.go

Stop runtime, don't kill process ( == panic)

CI runtime abstract fix

---

pkg/dashboard/ui/src/less/mixins.less

Relates to PR https://github.com/iguazio/dashboard-controls/pull/889

[Services] Add flow: Wake up scaled-to-zero services

---

pkg/processor/runtime/rpc/abstract_test.go

Backporting fix made by pr #1481

[backport] CI runtime abstract fix 

---

docs/reference/triggers/nats.md

@liranbg / @omesser please merge (minor typo fixes).

[DOC REVIEW] NATS trigger: fix typos

---

hack/k8s/helm/nuclio/README.md

As per latest credentials usage updates

Helm readme fixes

---

pkg/dashboard/ui/src/app/components/projects/project-table-row/project-table-row.less

UI: Projects: Remove spacing between project rows

---

README.md
docs/setup/k8s/getting-started-k8s.md
docs/setup/k8s/running-in-production-k8s.md
hack/k8s/helm/nuclio/values.yaml

@omesser please review. You can view the updated docs on my PR branch (e.g., https://github.com/Sharon-iguazio/nuclio/blob/doc-review-pr512-run-in-prod/docs/setup/k8s/running-in-production-k8s.md).

[DOC REVIEW: PR 1512] Running in production over k8s

---

pkg/platform/abstract/platform.go

no logical changes were made, only code prettification for next prs

Break create-nuclio-function validations into smaller functions

---

pkg/dashboard/ui/package.json
pkg/dashboard/ui/src/app/components/projects/edit-project-dialog/edit-project-dialog.tpl.html
pkg/dashboard/ui/src/app/components/projects/new-project-dialog/new-project-dialog.tpl.html
pkg/dashboard/ui/src/less/mixins.less

https://trello.com/c/hBaaVkFv/365-services-api-urls-open-menu-when-multiple-options
Depends on PR https://github.com/iguazio/dashboard-controls/pull/929

[Nuclio] Triggers: Host: Validation rule menu hidden

---

pkg/dashboard/ui/src/app/components/projects/edit-project-dialog/edit-project-dialog.component.js
pkg/dashboard/ui/src/app/components/projects/edit-project-dialog/edit-project-dialog.tpl.html
pkg/dashboard/ui/src/app/components/projects/new-project-dialog/new-project-dialog.component.js
pkg/dashboard/ui/src/app/components/projects/new-project-dialog/new-project-dialog.tpl.html

https://trello.com/c/bA1CVqVS/371-projectsapi-gws-name-change-validation-to-dns-1035

[Projects][API GWs] Name: Change validation to DNS-1035

---

pkg/dashboard/ui/package.json
pkg/dashboard/ui/src/app/app.config.js
pkg/dashboard/ui/src/app/app.run.js
pkg/dashboard/ui/src/app/shared/services/nuclio-projects-data.service.js

Depends on PR https://github.com/iguazio/dashboard-controls/pull/936

UI: Configuration: Fix broken Resources pane

---

pkg/dashboard/ui/package.json
pkg/dashboard/ui/src/app/components/data-wrappers/functions-data-wrapper/functions-data-wrapper.component.js

https://trello.com/c/HJvYEw4a/364-i18n-add-n-a-to-common-namespace
Depends on PR https://github.com/iguazio/dashboard-controls/pull/941

[i18n] Add "N/A" to common namespace

---

pkg/platform/kube/functionres/lazy.go
pkg/platform/kube/functionres/lazy_test.go
pkg/platformconfig/platformconfig_test.go

Fixed nil pointer when missing k8s augmented deployment

---

pkg/containerimagebuilderpusher/kaniko.go
pkg/functionconfig/types.go
pkg/processor/build/builder.go

Lowercasing buildTimeoutSeconds 

---

pkg/platform/kube/functionres/lazy.go

Prevents a case where function is ready but nginx ingress is not yet stable

Wait a grace period after creation/update of function ingress

---

test/docker/Dockerfile

Following up with latest changes made on https://github.com/nuclio/nuclio/pull/1588

Fix integration test

---

pkg/dashboard/ui/package.json

- Function › Configuration › Resources › Target CPU: [bugfix] value not set when changing slider pointer.
Depends on PR https://github.com/iguazio/dashboard-controls/pull/958

UI: Fix Target CPU value not set on changing slider

---

pkg/processor/trigger/http/test/suite/suite.go

bug introduced on previous pr 3d3f6fd31aaf5d192cf07f99d7c7e69ccc425f61

Fix integration test error message

---

pkg/platform/kube/deployer.go
pkg/platform/kube/function.go
pkg/platform/kube/functionres/lazy.go

Backporting https://github.com/nuclio/nuclio/pull/1602 to 1.3.x

Reduce chance of k8s resource name conflicts with external resources [1.3.x backport]

---

pkg/nuctl/test/function_test.go
pkg/processor/build/builder.go

Nuctl update local directory path function as image CET [1.3.x backport] 

---

pkg/platform/kube/deployer.go

Bugfix - nil access on log [1.3.x backport]

---

docs/reference/triggers/v3iostream.md

@pavius please review. You can see the updated doc on my PR branch: https://github.com/Sharon-iguazio/nuclio/blob/doc-review-v3io-stream-trigger-ref/docs/reference/triggers/v3iostream.md

[DOC REVIEW] v3ioStream tigger reference (PR #1585 doc review)

---

cmd/autoscaler/Dockerfile
cmd/dlx/Dockerfile

Using migrated autoscaler
https://github.com/v3io/scaler/pull/34

Bump autoscaler version

---

pkg/platform/kube/function.go

Minor logging fix

---

pkg/nuctl/test/function_test.go
pkg/nuctl/test/functionevent_test.go
pkg/nuctl/test/project_test.go
pkg/nuctl/test/suite.go
test/testloop

+ made `testloop.py` runnable by python 3

Fix nuctl test function name typo

---

cmd/autoscaler/Dockerfile
cmd/dlx/Dockerfile
go.mod
go.sum
pkg/platform/kube/functionres/lazy.go
pkg/platform/kube/resourcescaler/resourcescaler.go
pkg/platform/kube/types.go

#1603 broke the Scaler's assumption that resource name == service name, Scaler 0.3.1 enables to resolve service name from resource name, this PR supports it

Support scaler 0.3.1

---

go.sum

go.sum cleanup

---

.travis.yml
cmd/autoscaler/Dockerfile
cmd/controller/Dockerfile
cmd/dashboard/docker/Dockerfile
cmd/dlx/Dockerfile
cmd/processor/Dockerfile
docs/devel/contributing.md
hack/docker/tool-builder/Dockerfile
pkg/platform/kube/functionres/lazy.go
pkg/platform/kube/resourcescaler/resourcescaler.go
pkg/platform/kube/types.go
pkg/processor/build/runtime/golang/docker/onbuild/Dockerfile
pkg/processor/build/runtime/golang/docker/onbuild/Dockerfile.alpine

https://github.com/nuclio/nuclio/pull/1603 broke the Scaler's assumption that resource name == service name, Scaler 0.2.1 enables to resolve service name from resource name, this PR supports it

Support scaler 0.2.1 [1.3.x]

---

.github/workflows/ci.yaml
Makefile
pkg/processor/timeout/timeout_test.go
test/k8s/ci_assets/helm_values.yaml

Upon a created pull request against development:
- Lint
- Run short test suites
- Build nuctl
- Build nuclio docker images
- Run k8s integration test using minikube
- Deploy a "Hello World" function
- Invoke
Note:
Lint + test + build jobs are running in parallel with `fail-fast` strategy (default on github actions)

CI - Github workflow

---

pkg/dashboard/resource/function.go
pkg/dashboard/resource/functionevent.go
pkg/dashboard/resource/project.go
pkg/dashboard/resource/resource.go
pkg/dashboard/test/server_test.go
pkg/functionconfig/types.go
pkg/functionconfig/types_test.go
pkg/platform/abstract/platform.go
pkg/platform/kube/apis/nuclio.io/v1beta1/types.go
pkg/platform/kube/controller/nucliofunction.go
pkg/platform/kube/platform.go
pkg/platform/local/platform.go
pkg/platform/local/platform_test.go
pkg/restful/resource.go

Original PR #1619 
Again - but this time to the correct branch

Import and Export Functions & Projects in backend

---

pkg/dockerclient/shell.go

Since `common.RetryUntilSuccessful` does not preserve callback origin error, `build` error were masked. (caused by https://github.com/nuclio/nuclio/pull/1644)
It affected error message propagation and integration tests.

Preserve build error

---

pkg/platform/kube/deployer.go
pkg/platform/kube/platform.go

The function status update failed because the k8s NuclioFunction resourceVersion got out of date

Fix reportCreationError failure on deployment failure

---

.github/workflows/ci.yaml
Makefile
pkg/nuctl/command/get.go
pkg/nuctl/test/function_test.go
pkg/platform/kube/function.go

missing backslash led to running nuctl tests against k8s

Fixed makefile nuctl k8s command

---

cmd/dashboard/main.go
test/k8s/ci_assets/helm_values.yaml

Skip pulling images for ci, otherwise tagged onbuild images would be pulled (undesired)

CI Helm values fix

---

pkg/dashboard/ui/package.json
pkg/dashboard/ui/src/app/components/projects/edit-project-dialog/edit-project-dialog.component.js
pkg/dashboard/ui/src/app/components/projects/edit-project-dialog/edit-project-dialog.tpl.html
pkg/dashboard/ui/src/app/components/projects/new-project-dialog/new-project-dialog.component.js
pkg/dashboard/ui/src/app/components/projects/new-project-dialog/new-project-dialog.tpl.html
pkg/dashboard/ui/src/less/mixins.less

- Function › Configuration › Resources: add a warning when Limit is filled while Request is empty 
- Use validation rules instead of a single validation pattern in some text input fields.
Depends on PR https://github.com/iguazio/dashboard-controls/pull/993

[General] Use validation rules instead of patterns

---

.travis.yml
cmd/autoscaler/Dockerfile
cmd/controller/Dockerfile
cmd/dashboard/docker/Dockerfile
cmd/dlx/Dockerfile
cmd/playground/Dockerfile
cmd/processor/Dockerfile
docs/devel/contributing.md
hack/docker/tool-builder/Dockerfile
pkg/processor/build/runtime/golang/docker/onbuild/Dockerfile
pkg/processor/build/runtime/golang/docker/onbuild/Dockerfile.alpine
pkg/processor/build/runtime/pypy/docker/Dockerfile.processor-pypy
test/docker/Dockerfile

As per later interface changes

Freezing nuclio-go-sdk to v0.0.1 [1.3.x]

---

pkg/dashboard/ui/package.json
pkg/dashboard/ui/src/app/components/projects/projects.component.js

Depends on PR https://github.com/iguazio/dashboard-controls/pull/999

[Nuclio] Triggers: Layout breaks on removing a trigger

---

pkg/dashboard/ui/package.json
pkg/dashboard/ui/src/app/components/projects/new-project-dialog/new-project-dialog.component.js
pkg/dashboard/ui/src/less/mixins.less

Depends on PR https://github.com/iguazio/dashboard-controls/pull/1010

UI: Fix: Saving function event not working in test pane

---

pkg/nuctl/command/invoke.go

Today, when nuctl invokes a function with an input body it uses `GET` as default http method.
This pr defaults to POST when invocation body is given

Default nuctl invoke http method to post when body is given

---

pkg/dashboard/ui/package.json

UI: Add support to new "imported" function state

---

pkg/nuctl/command/build.go
pkg/nuctl/command/common/helpers.go
pkg/nuctl/command/deploy.go
pkg/nuctl/command/import.go
pkg/nuctl/test/function_test.go
test/_functions/common/json-parser-with-function-config/python/function-different-spec.yaml

Deploy will handle a given file in this order:
- First reads from file if given, and loads the configuration.
- Next, overrides empty fields with defaults.
- Finally, overrides fields with given args.

Deploy handles given functionConfig file

---

.dockerignore
Makefile
cmd/processor/Dockerfile
cmd/processor/app/processor.go
cmd/processor/main.go
pkg/containerimagebuilderpusher/kaniko.go
pkg/processor/build/builder.go
pkg/processor/build/runtime/golang/docker/onbuild/Dockerfile
pkg/processor/build/runtime/golang/docker/onbuild/Dockerfile.alpine
pkg/version/version.go

Print processor compiled version info upon nuclio function startup

Nuclio function to print its processor version upon start

---

.dockerignore
Makefile
cmd/processor/Dockerfile
cmd/processor/app/processor.go
cmd/processor/main.go
pkg/containerimagebuilderpusher/kaniko.go
pkg/processor/build/builder.go
pkg/processor/build/runtime/golang/docker/onbuild/Dockerfile
pkg/processor/build/runtime/golang/docker/onbuild/Dockerfile.alpine
pkg/version/version.go
test/docker/Dockerfile

Backport print processor version upon start (#1702)

---

pkg/dashboard/ui/package.json
pkg/dashboard/ui/src/app/components/projects/project-table-row/project-table-row.component.js
pkg/dashboard/ui/src/app/components/projects/project-table-row/project-table-row.component.spec.js
pkg/dashboard/ui/src/app/components/projects/projects.component.js
pkg/dashboard/ui/src/app/components/projects/projects.component.spec.js
pkg/dashboard/ui/src/app/components/projects/projects.tpl.html

Depends on PR https://github.com/iguazio/dashboard-controls/pull/1027

UI: Fix sort dropdown control in Projects screen

---

pkg/nuctl/command/common/renderers.go

Make it look the same way users sees it in UI dashboard

Nuctl present function in standby if ready&disabled

---

.github/workflows/ci.yaml
.run/(kube) nuctl test.run.xml
pkg/platform/abstract/invoker.go

Added `$(minikube ip)` to resolve current CI breakage for k8s tests

Fix and Tweak CI

---

pkg/platform/kube/deployer.go

Take Function HTTP port from the updated instance

Fix returned http port for deployed function

---

pkg/common/helper.go
pkg/processor/trigger/http/test/suite/suite.go

Also changed `MatchStringPatterns` to use `MustCompile`

Fix CI transient failure due to "server closed idle connection"

---

pkg/dashboard/ui/build.config.js
pkg/dashboard/ui/gulpfile.js
pkg/dashboard/ui/package.json

https://trello.com/c/4IdtT8AB/432-api-gatewaybrowse-bottom-edge-scroll-slider-defect
Relates to PR https://github.com/iguazio/dashboard-controls/pull/1045

[API Gateway][Browse] Bottom Edge Scroll Slider defect

---

pkg/dashboard/ui/gulpfile.js
pkg/dashboard/ui/package.json

Depends on PR https://github.com/iguazio/dashboard-controls/pull/1048

UI: Fix - UI does not come up

---

pkg/processor/build/builder.go

Use s3 item key as functionPath when getting function tempFile.
This fixes the bug where the tempFile is created with the wrong file extension. (`.zip` by default)

Fix - S3 Code entry type function fail to deploy because tempFile created with wrong extension

---

.github/workflows/pr_label.yaml

Fix labeler typo

---

pkg/dashboard/ui/package.json
pkg/dashboard/ui/src/app/app.route.js
pkg/dashboard/ui/src/app/components/data-wrappers/version-data-wrapper/version-data-wrapper.component.js
pkg/dashboard/ui/src/app/components/data-wrappers/version-data-wrapper/version-data-wrapper.tpl.html

https://trello.com/c/FP5hQkuj/460-function-add-refresh-button
Depends on PR https://github.com/iguazio/dashboard-controls/pull/1061

[Function] Add refresh button

---

pkg/dashboard/ui/src/app/shared/services/nuclio-functions-data.service.js

https://trello.com/c/XNSdWFXO/510-nuclio-add-namespace-http-header-on-post-put-functions

[Nuclio] Add namespace HTTP header on POST/PUT functions

---

pkg/platform/local/platform.go

Allow processor config to be read by other users

---

pkg/dashboard/ui/.gitignore
pkg/dashboard/ui/package-lock.json

Backports PR https://github.com/nuclio/nuclio/pull/1793 from branch `development` to branch `1.4.x`

UI: Lock NPM packages

---

cmd/controller/app/controller.go
cmd/controller/main.go
pkg/dashboard/resource/apigateway.go
pkg/functionconfig/types.go
pkg/platform/abstract/platform.go
pkg/platform/apigateway.go
pkg/platform/errors.go
pkg/platform/kube/apigatewayres/lazy.go
pkg/platform/kube/apigatewayres/types.go
pkg/platform/kube/apis/nuclio.io/v1beta1/types.go
pkg/platform/kube/controller/apigateway.go
pkg/platform/kube/controller/controller.go
pkg/platform/kube/ingress/types.go
pkg/platform/kube/platform.go
pkg/platform/mock/platform.go
pkg/platform/platform.go
pkg/platform/types.go

Part 2 of adding api-gateways to nuclio, Added all api-gateways CRUD operations to nuclio dashboard

Support API Gateways on nuclio (Part.2 - Platform + REST dashboard)

---

hack/k8s/helm/nuclio/templates/_helpers.tpl
hack/k8s/helm/nuclio/values.yaml

After this 0.7.0 chart will be re-released

Helm chart - Aligning to v3io conventions

---

hack/k8s/helm/nuclio/templates/_helpers.tpl

Helm chart - another change

---

hack/k8s/helm/nuclio/Chart.yaml
hack/k8s/helm/nuclio/templates/_helpers.tpl
hack/k8s/helm/nuclio/templates/configmap/registry-url.yaml

Chart fix - Current breakge in CI for CRD only use case.
Fix - mustache correctly - trim leading and trailing whitespaces from the computed named template

Helm chart - CRDs only fix

---

hack/scripts/releaser/README.md
hack/scripts/releaser/releaser.go

Upon nuclio release, ensure appVersion is aligned with release version

Releaser: explicitly bump app version on helm chart

---

pkg/processor/trigger/kafka/trigger.go
pkg/processor/trigger/kafka/types.go

Cherry-pick #1843 from 1.4.x to development

Add support for TLS and certificate authentication in Kafka trigger

---

pkg/dashboard/ui/package-lock.json
pkg/dashboard/ui/package.json

- `gulp-protractor`: from `^3.0.0` to `^4.1.1`
- `protractor`: from `^4.0.13` to `^5.4.4`

UI: Upgrade dependency packages to remedy vulnerabilities

---

pkg/dashboard/ui/package-lock.json
pkg/dashboard/ui/package.json

Depends on PR https://github.com/iguazio/dashboard-controls/pull/1101

UI: Fix: Test button is disabled when service type is Cluster IP

---

pkg/nuctl/command/export.go
pkg/platform/kube/platform.go

do not print >= Info level for export flow

Fix: exported project might be  malformed with logger outputs

---

hack/k8s/resources/nuclio-rbac.yaml
hack/k8s/resources/nuclio.yaml

Fix #1901 - Update k8s resources yaml to support api gateways

---

pkg/processor/build/runtime/java/docker/onbuild/Dockerfile

Fix building java onbuild image [backport 1.4.x]

---

Makefile
pkg/processor/runtime/python/py/_nuclio_wrapper.py
pkg/processor/runtime/python/py/test_wrapper.py
pkg/processor/runtime/python/test/Dockerfile
pkg/processor/runtime/python/test/python_test.go
pkg/processor/runtime/python/test/test.sh

Python runtime to recover from msgpack decoding exceptions [backport 1.4.x]

---

.github/workflows/ci.yaml
.github/workflows/release.yaml

Following https://github.com/nuclio/nuclio/pull/1856, backporting relevant fixes to 1.4.x

Fix github action set-env errors [backport 1.4.x]

---

pkg/platform/local/platform.go

When function failed to be built correctly, it might not set up its port and address which lead to resolving container http port to failed. this should not happen, and validation should be less strict with respect to that.
Added some logs + updated current one to allow leftover deletion be more informative.

Fix cleanup for failed function deployments

---

pkg/common/errors.go
pkg/dashboard/resource/apigateway.go
pkg/dashboard/test/server_test.go
pkg/platform/kube/apigateway.go
pkg/platform/kube/platform.go
pkg/platform/kube/platform_test.go
pkg/restful/resource.go

Used the same validation, to fail earlier if possible

API Gateways - Add spec validation api gateway on dashboard

---

.travis.yml
cmd/autoscaler/Dockerfile
cmd/controller/Dockerfile
cmd/dashboard/docker/Dockerfile
cmd/dlx/Dockerfile
cmd/processor/Dockerfile
docs/devel/contributing.md
hack/docker/tool-builder/Dockerfile
pkg/processor/build/runtime/golang/docker/onbuild/Dockerfile
pkg/processor/build/runtime/golang/docker/onbuild/Dockerfile.alpine
pkg/processor/runtime/python/py/_nuclio_wrapper.py
pkg/processor/runtime/python/test/python_test.go
test/docker/Dockerfile

backporting (mainly the fix) #1914 to 1.3.x

Python runtime to recover from msgpack decoding exceptions [backport 1.3.x]

---

hack/scripts/releaser/releaser.go

- Waiting for release completion is fixed by waiting for "success"
- Added prompt for action (skip / retry) in case of waiting for release has failed

Releaser script: Fix resolving whether a release workflow has failed

---

Makefile

add parenthesis to avoid commands execution after `&&`

Fix makefile lint command

---

pkg/dashboard/ui/package-lock.json
pkg/dashboard/ui/package.json

Depends on PR https://github.com/iguazio/dashboard-controls/pull/1149

UI: API gateways: Get auth type options from backend (for realz)

---

docs/reference/triggers/http.md

@quaark please approve the `ServiceType` doc edits (PR #1874 doc review). => UPDATE: APPROVED
@liranbg / @omesser please review all edits (very short) and merge the PR.

[DOC REVIEW] HTTP trigger doc edits for PR 1874 (ServiceTag) and PRs 1640 & 1689 (minor)

---

README.md
docs/reference/runtimes/python/python-reference.md
docs/reference/triggers/mqtt.md
docs/setup/gke/getting-started-gke.md

[DOC REVIEW] Minor miscellaneous doc edits

---

docs/tasks/exporting-and-importing.md
pkg/nuctl/command/deploy.go
pkg/nuctl/command/export.go
pkg/nuctl/command/import.go
pkg/nuctl/test/project_test.go
pkg/platform/project.go

Doc review for PR #1657, which added **docs/tasks/exporting-and-importing.md**.
@quaark please review. Please also verify the `nuctl` compilation after the changes.

[DOC-REVIEW] Importing and exporting Nuclio functions and projects

---

docs/reference/function-configuration/function-configuration-reference.md

Doc review for PR 1820 & PR 1824
@liranbg / @omesser please check and merge.

[DOC REVIEW] Function-configuration reference: security context and Docker mount mode & restart policy

---

docs/setup/k8s/running-in-production-k8s.md

Fix for `nuclio` Issue #1745 comment #1

[DOC] Running K8s in production: fix Git clone doc

---

pkg/dashboard/ui/src/app/shared/services/nuclio-projects-data.service.js

https://trello.com/c/abOhxvX7/641-nuclio-omit-specdisplayname-on-create-update-project

[Nuclio] Omit `spec.displayName` on create/update project

---

pkg/dashboard/ui/package-lock.json
pkg/dashboard/ui/package.json
pkg/dashboard/ui/src/app/app.route.js
pkg/dashboard/ui/src/app/components/data-wrappers/api-gateways-data-wrapper/api-gateways-data-wrapper.component.js
pkg/dashboard/ui/src/app/components/data-wrappers/api-gateways-data-wrapper/api-gateways-data-wrapper.tpl.html
pkg/dashboard/ui/src/app/components/data-wrappers/functions-data-wrapper/functions-data-wrapper.component.js
pkg/dashboard/ui/src/app/components/data-wrappers/functions-data-wrapper/functions-data-wrapper.tpl.html
pkg/dashboard/ui/src/app/components/data-wrappers/version-data-wrapper/version-data-wrapper.component.js
pkg/dashboard/ui/src/app/components/data-wrappers/version-data-wrapper/version-data-wrapper.tpl.html

Depends on PR https://github.com/iguazio/dashboard-controls/pull/1169

UI: Pass project from parent instead of fetching async-ly

---

pkg/common/helper.go
pkg/common/url.go
pkg/common/url_test.go
pkg/platform/errors.go
pkg/platform/kube/platform.go
pkg/platform/kube/platform_test.go

Validate that there's no ingress with the same host+path when creating/updating api-gateway/function

Validate ingress host and path availability before creation AGW/Function

---

docs/tasks/exporting-and-importing.md
pkg/nuctl/command/create.go
pkg/nuctl/command/import.go

Doc review for PR #1971

---

pkg/restful/server.go

Added missing `Handled request` lines to some endpoints

Update request handling logs

---

pkg/dashboard/ui/src/app/components/projects/projects.component.js

Bug stupidly originated in PR #2012

UI: Un-break my heart (Nuclio)

---

pkg/platform/kube/apigatewayres/lazy.go
pkg/platform/kube/ingress/ingress.go
pkg/platform/kube/ingress/types.go
pkg/platform/kube/test/platform_test.go

Ensure resources owned / managed by Nuclio are labeled correctly to allow easier fetching

Enrich resources created by apigateway with nuclio labels

---

pkg/dashboard/ui/package-lock.json
pkg/dashboard/ui/package.json

- Use the same text and colors in Status tab header just like in the Status column in the functions list.
- [bugfix] when attempting to overwrite a function but the original one no longer exists when clicking the “Deploy” button — the deploy failed with “Cannot update non existing function”. Now the UI will not show this error and instead will automatically attempt to create the function as new.
- [bugfix] when attempting to deploy a function that no longer exists when clicking the “Deploy” button — the deploy failed with “Cannot update non existing function”. Now the UI will not show this error and instead will automatically attempt to create the function as new.
Depends on PR https://github.com/iguazio/dashboard-controls/pull/1177

UI: Align function states in Status tab header + fix bug on PUT

---

pkg/dashboard/server.go

Headers from PRS
- #1996
- #2016

Allow new headers on server CORS

---

pkg/dashboard/ui/package-lock.json
pkg/dashboard/ui/package.json
pkg/dashboard/ui/src/app/components/data-wrappers/api-gateways-data-wrapper/api-gateways-data-wrapper.component.js
pkg/dashboard/ui/src/app/components/data-wrappers/api-gateways-data-wrapper/api-gateways-data-wrapper.tpl.html
pkg/dashboard/ui/src/app/components/data-wrappers/functions-data-wrapper/functions-data-wrapper.component.js
pkg/dashboard/ui/src/app/components/data-wrappers/functions-data-wrapper/functions-data-wrapper.tpl.html
pkg/dashboard/ui/src/app/components/data-wrappers/ncl-breadcrumbs-data-wrapper/ncl-breadcrumbs-data-wrapper.component.js
pkg/dashboard/ui/src/app/components/data-wrappers/ncl-breadcrumbs-data-wrapper/ncl-breadcrumbs-data-wrapper.tpl.html
pkg/dashboard/ui/src/app/components/data-wrappers/version-data-wrapper/version-data-wrapper.component.js
pkg/dashboard/ui/src/app/components/data-wrappers/version-data-wrapper/version-data-wrapper.tpl.html
pkg/dashboard/ui/src/app/components/projects/project-table-row/project-table-row.component.js
pkg/dashboard/ui/src/app/components/projects/projects.component.js
pkg/dashboard/ui/src/app/shared/services/nuclio-api-gateways-data.service.js
pkg/dashboard/ui/src/app/shared/services/nuclio-client.service.js
pkg/dashboard/ui/src/app/shared/services/nuclio-functions-data.service.js
pkg/dashboard/ui/src/app/shared/services/nuclio-namespaces-data.service.js

- Functions: enrich function list response only when necessary via new header `x-nuclio-function-enrich-apigateways`.:
- Enrich on:
- Function list on function tab of a project
- Function list of API gateway wizard
- Do not enrich on:
- Breadcrumb dropdown menu to switch to another function
- On exporting a project to YAML file
- API Gateways: [bugfix] Polling of API gateway creation/update not stopping when leaving screen.
Depends in PR https://github.com/iguazio/dashboard-controls/pull/1179

UI: Enrich function list with API GW only when needed

---

pkg/platform/kube/monitoring/test/function_test.go
pkg/platform/kube/test/suite.go
pkg/platform/local/platform.go

Name may be prefixed with "/".

Delete container by its ID

---

pkg/dashboard/ui/package-lock.json
pkg/dashboard/ui/package.json
pkg/dashboard/ui/src/app/components/projects/project-table-row/project-table-row.component.js
pkg/dashboard/ui/src/app/components/projects/projects.component.js
pkg/dashboard/ui/src/app/shared/services/nuclio-projects-data.service.js

https://trello.com/c/ehHKWDnQ/662-projects-allow-to-forcefully-delete-a-non-empty-project
- Projects: added confirmation pop-up on deletion attempt of non-empty projects to allow forcefully deleting them anyway
Depends on PR https://github.com/iguazio/dashboard-controls/pull/1187

[Projects] Allow to forcefully delete a non-empty project

---

pkg/common/helper.go
pkg/dockerclient/shell.go
pkg/dockerclient/shell_test.go
pkg/platform/abstract/platform.go
pkg/platform/abstract/platform_test.go
pkg/restful/errorverifier.go

Backport of https://github.com/nuclio/nuclio/pull/2032

Security buff - Sanitizing function spec and protect dockerclient [1.3.x backport]

---

.github/workflows/ci.yaml
.github/workflows/release.yaml

Followup fixes to https://github.com/nuclio/nuclio/pull/2040

Github actions - added missing envs

---

hack/scripts/releaser/README.md
hack/scripts/releaser/releaser.go
hack/scripts/releaser/releaser_test.go

+ added some fixes / small test

Releaser: release 1.3.x from github action

---

hack/k8s/helm/nuclio/templates/deployment/autoscaler.yaml
hack/k8s/helm/nuclio/templates/deployment/controller.yaml
hack/k8s/helm/nuclio/templates/deployment/dashboard.yaml
hack/k8s/helm/nuclio/templates/deployment/dlx.yaml
hack/k8s/helm/nuclio/values.yaml

This change will allow to set resources requests/limits for containers deployed by nuclio helm chart.

Expose resources settings in helm chart

---

pkg/processor/util/partitionworker/allocator_test.go

by running in parallel, improved test execution time by 50% (~16s to ~8s)

Enhanced partition worker allocator unittest

---

pkg/dashboard/ui/package-lock.json
pkg/dashboard/ui/package.json
pkg/dashboard/ui/src/app/app.route.js
pkg/dashboard/ui/src/app/components/data-wrappers/functions-data-wrapper/functions-data-wrapper.component.js
pkg/dashboard/ui/src/app/components/data-wrappers/functions-data-wrapper/functions-data-wrapper.tpl.html
pkg/dashboard/ui/src/app/components/data-wrappers/version-data-wrapper/version-data-wrapper.component.js
pkg/dashboard/ui/src/app/components/data-wrappers/version-data-wrapper/version-data-wrapper.tpl.html
pkg/dashboard/ui/src/app/shared/services/nuclio-functions-data.service.js

- Functions:
- [bugfix] In “Status” column cells, the “Enabling…” and “Disabling…” messages are corrupted (ALL CAPS)
Before:
After:
- [bugfix] resource version not updating when starting/stopping a function causing an unexpected error message when attempting to stop the function:
- Function:
- Added an indication whether the function is used by an API gateway, and if so, also show its name
- Configuration › Basic Settings › Enabled:
- [bugfix] the error message that should appear when unchecking the “Enabled” checkbox for a function that belongs to an API gateway no longer appears
- When the function is currently disabled and is used by an API gateway, and the user checks the Enabled checkbox and then unchecks it, an error message is falsely displayed. It should not appear because the …

UI: Fucntion used by API GW missing error message on disabling

---

pkg/platform/abstract/platform.go

To reflect validation errors to UI, return error with status.

Fix returned errors from function validations

---

go.mod
go.sum
pkg/processor/trigger/kafka/trigger.go
pkg/processor/trigger/kafka/types.go

Forward porting [this](https://github.com/nuclio/nuclio/pull/1925)

Update Sarama to use log level, fix subscription deadlock

---

go.mod
go.sum
pkg/processor/trigger/kafka/trigger.go
pkg/processor/trigger/kafka/types.go

Backporting [this](https://github.com/nuclio/nuclio/pull/2077) to 1.5.x

Update Sarama to use log level, fix subscription deadlock [1.5.x]

---

Makefile
pkg/processor/test/suite/suite.go
pkg/processor/trigger/kafka/test/kafka_test.go
pkg/processor/trigger/test/broker.go

`shopify/kafka` docker image served us for a while but apparently not in use anymore,
this test has been broken for a while (thought covered well in manual tests).
This pr leverage the amazing kafka + zookeeper docker images maintained by `wurstmeister`.

Fix kafka broken test

---

.dockerignore
.gitignore
Makefile
pkg/platform/kube/monitoring/test/function_test.go
pkg/platform/kube/test/suite.go
pkg/processor/test/suite/suite.go
pkg/processor/trigger/kafka/test/kafka_test.go
pkg/processor/trigger/kinesis/test/kinesis_test.go
pkg/processor/trigger/mqtt/basic/test/mqtt_test.go
pkg/processor/trigger/test/broker.go
test/docker/Dockerfile
test/mqtt/artifacts/mosquitto.conf

- Fix newly broken mqtt CI test + align with recently fixed kafka test.
- Fix processor sub tests transiently failed with HTTP server not ready to take requests

Fix CI tests

---

pkg/platform/kube/test/platform_test.go
pkg/platform/kube/test/suite.go

Following up https://github.com/nuclio/nuclio/pull/2048
This PR uncommented and added cron job integration test

Fix cron job integration test

---

hack/scripts/releaser/releaser.go

Allow `--bump-X` only when _not received target version_ via run argument

Releaser: conditional bumping version

---

pkg/nuctl/command/deploy.go
pkg/nuctl/test/function_test.go

relates https://github.com/nuclio/nuclio/issues/2102

Add annotations flag to nuctl deploy

---

pkg/dashboard/ui/package-lock.json
pkg/dashboard/ui/package.json
pkg/dashboard/ui/src/app/components/projects/project-table-row/project-table-row.component.js
pkg/dashboard/ui/src/app/components/projects/project-table-row/project-table-row.tpl.html
pkg/dashboard/ui/src/app/components/projects/projects.component.js

Relates to PR https://github.com/nuclio/nuclio/pull/2066
Depends on PR https://github.com/iguazio/dashboard-controls/pull/1224
Jira ticket 17957

UI: Projects: Deprecate `spec.displayName`

---

vendor/github.com/Shopify/sarama/config.go
vendor/github.com/Shopify/sarama/consumer.go
vendor/github.com/Shopify/sarama/consumer_group.go

backporting fix from https://github.com/iguazio/sarama/pull/2

Fix sarama subscription deadlock [1.3.x backport]

---

.github/workflows/ci.yaml
.github/workflows/release.yaml

- add more cleanups to free up more space
- build during CI

Fix no space left on device during CI / Release [1.3.x]

---

docs/devel/minikube/developing-on-minikube.md
hack/k8s/helm/nuclio/README.md

Direct developers towards helm chart rather than the less maintained raw k8s yamls

Minor readme update

---

.github/workflows/release.yaml
Makefile
cmd/autoscaler/Dockerfile
cmd/controller/Dockerfile
cmd/dashboard/docker/Dockerfile
cmd/dlx/Dockerfile
hack/controller/build/Dockerfile
hack/docker/build/base-alpine/Dockerfile
hack/docker/build/base/Dockerfile
hack/docker/build/builder/Dockerfile
pkg/platform/local/store.go
pkg/processor/build/runtime/golang/docker/onbuild/Dockerfile
pkg/processor/build/runtime/java/docker/onbuild/Dockerfile
pkg/processor/build/runtime/python/docker/onbuild/Dockerfile
pkg/processor/runtime/python/test/Dockerfile

Mirror docker images for build process to gcr.io/iguazio

---

pkg/dashboard/ui/package-lock.json
pkg/dashboard/ui/package.json

- Added runtime “Python 3.9”:
- Create function › From template › Runtime filter
- Create function › From scratch › Runtime field
- Function › Code › Runtime field
- Project › Functions (list) › Runtime (column)
Relates to PRs https://github.com/nuclio/nuclio/pull/2094 https://github.com/nuclio/nuclio/pull/2155
Jira ticket IG-18430

UI: Introducing Python 3.9

---

Makefile

syntax change in newer `yq` releases

Makefile - fix helm-publish

---

.github/workflows/ci.yaml
.github/workflows/long_ci.yaml
.github/workflows/periodic.yaml
.github/workflows/release.yaml
.gitignore
hack/scripts/ci/free-space.sh

- lock ci to go 1.14 [ #2121 ]
- free up disk space [ #2175 ]

Update Github action changes [1.5.x backport]

---

pkg/platform/kube/functionres/lazy.go
pkg/platform/kube/functionres/lazy_test.go
pkg/platformconfig/types.go

Forward changes made against 1.5.x - [PR](https://github.com/nuclio/nuclio/pull/2187) to development

Add default ingress annotations for scale to zero configurations

---

cmd/dashboard/README.md
pkg/dashboard/server.go

+ added to list of allowed CORS headers

Fix function templates header documentation

---

docs/concepts/configuring-a-function.md
docs/reference/runtimes/python/python-reference.md
pkg/processor/runtime/python/py/_nuclio_wrapper.py
pkg/processor/runtime/python/py/test_wrapper.py
pkg/processor/runtime/python/test/outputter/async_outputter.py
pkg/processor/runtime/python/test/python_test.go

Continuing the work that was done by @gtopper on https://github.com/nuclio/nuclio/pull/2208
Added:
- Documentation
- UT + Integration test
- Small refactor to move code lines around

Support async def init_context and handle - part 2

---

cmd/dashboard/app/dashboard.go
cmd/dashboard/app/types.go
cmd/dashboard/main.go
pkg/dashboard/functiontemplates/gitfunctiontemplatefetcher.go
pkg/dashboard/functiontemplates/test/fetcher_test.go

aligning old PR (https://github.com/nuclio/nuclio/pull/1779) to development changes

Function template git ca cert support (cont)

---

pkg/dashboard/ui/package-lock.json
pkg/dashboard/ui/package.json

- “Function” screen › “Configuration” tab › “Resources” pane:
- Move below Memory/CPU/GPU part.
- Rename to "Node Selector".
- Rename to "Create a new entity".
Before:
After:
- API:
- Rename `status.internalInvocationURLs` to `status.internalInvocationUrls`
- Rename `status.externalInvocationURLs` to `status.externalInvocationUrls`

UI: Tweaks to Node Selector, and rename ***URLs to ***Urls

---

pkg/platform/abstract/platform.go
pkg/platform/abstract/platform_test.go

Added field validation for node selectors, both label key and label value.

IG-18766 - validate node selector

---

go.mod
pkg/processor/trigger/kafka/tokenprovider/oauth/oauth.go
pkg/processor/trigger/kafka/trigger.go
pkg/processor/trigger/kafka/types.go
pkg/processor/trigger/types.go

Add a basic support for Sasl with oauth authentication mechanism.

Kafka - Add Sasl oath support

---

go.mod
go.sum
pkg/common/aws.go
pkg/platform/kube/functionres/lazy.go
pkg/processor/build/builder.go
pkg/processor/build/builder_test.go

To allow functions running within ec2 container to fetch s3 stored functions using IAM as explained [here](https://docs.aws.amazon.com/sdk-for-go/v1/developer-guide/configuring-sdk.html)
relates https://github.com/nuclio/nuclio/issues/2213

S3 - try download functions w/o auth

---

.github/workflows/ci.yaml

CI - fix latest issues [1.5.x backport]

---

pkg/dashboard/ui/package-lock.json
pkg/dashboard/ui/package.json

- “Project” screen › “Functions” tab: Added pagination (implemented solely on frontend).
- Function › Test Pane: [bugfix] The Invocation URLs dropdown was not updated after first deploy of the function.
Jira ticket IG-19022
Depends on PR https://github.com/iguazio/dashboard-controls/pull/1261

UI: Add pagination to Functions, update Invocation URLs on deploy

---

.github/workflows/ci.yaml

Fix Kubernetes CI

---

pkg/platform/kube/controller/nucliofunction.go
pkg/platform/kube/controller/nucliofunction_test.go
pkg/platform/kube/platform.go
pkg/platform/local/platform.go

Preserve build logs [1.5.x backport]

---

cmd/dlx/app/dlx.go
cmd/dlx/main.go
hack/k8s/helm/nuclio/templates/deployment/dlx.yaml
hack/k8s/helm/nuclio/values.yaml
pkg/common/testutils/http.go
pkg/dashboard/auth/iguazio/auth_test.go
pkg/platform/kube/resourcescaler/resourcescaler.go
pkg/platform/kube/resourcescaler/test/resourcescaler_test.go
pkg/processor/trigger/http/http_test.go
pkg/processor/trigger/http/trigger.go
pkg/processor/trigger/http/types.go

forward porting #2271 onto development (currently 1.6.x)

Scale to zero - verify function readiness

---

pkg/platform/kube/controller/nucliofunction.go

Forgotten commit related to https://github.com/nuclio/nuclio/pull/2264

Preserve build logs - update

---

go.mod
go.sum
pkg/processor/trigger/test/eventrecorder.go

Bump v3io/go version

---

.github/labels.yaml

Fix CI label job typos [1.5.x]

---

cmd/processor/app/processor.go
cmd/processor/app/processor_test.go
pkg/processor/trigger/cron/factory.go
pkg/processor/trigger/factory.go
pkg/processor/trigger/http/factory.go
pkg/processor/trigger/kafka/factory.go
pkg/processor/trigger/kickstart/factory.go
pkg/processor/trigger/kinesis/factory.go
pkg/processor/trigger/mqtt/basic/factory.go
pkg/processor/trigger/mqtt/iotcore/factory.go
pkg/processor/trigger/nats/factory.go
pkg/processor/trigger/partitioned/eventhub/factory.go
pkg/processor/trigger/poller/v3ioitempoller/factory.go
pkg/processor/trigger/pubsub/factory.go
pkg/processor/trigger/rabbitmq/factory.go
pkg/processor/trigger/registry.go
pkg/processor/trigger/v3iostream/factory.go
pkg/processor/worker/factory.go
pkg/processor/worker/sync.go

Fix shared worker allocation [1.5.x]

---

pkg/opa/factory.go
pkg/opa/http.go
pkg/opa/types.go
pkg/platform/abstract/platform.go
pkg/platform/abstract/project/external/leader/iguazio/client.go
pkg/platform/abstract/project/external/leader/iguazio/client_test.go
pkg/platform/abstract/project/external/leader/iguazio/synchronizer.go
pkg/platform/abstract/project/external/leader/iguazio/types.go
pkg/platform/abstract/project/internalc/kube/kube.go
pkg/platform/kube/apis/nuclio.io/v1beta1/types.go
pkg/platform/kube/apis/nuclio.io/v1beta1/zz_generated.deepcopy.go
pkg/platform/types.go
pkg/platformconfig/platformconfig.go

This PR introduces some project updates and fixes
- bubble job creation failures from leader
- upon project creation - populate `owner` from auth session
- disable spammy "get projects from leader" on sync
- fix populating namespace on project sync
- add status to project config

Projects - updates

---

.github/workflows/ci.yaml
cmd/autoscaler/Dockerfile
cmd/controller/Dockerfile
cmd/dashboard/docker/Dockerfile
cmd/dlx/Dockerfile
cmd/playground/Dockerfile
cmd/processor/Dockerfile
docs/devel/contributing.md
hack/docker/tool-builder/Dockerfile
pkg/processor/build/runtime/golang/docker/onbuild/Dockerfile
pkg/processor/build/runtime/golang/docker/onbuild/Dockerfile.alpine
pkg/processor/build/runtime/java/docker/onbuild/Dockerfile
pkg/processor/build/runtime/pypy/docker/Dockerfile.processor-pypy
pkg/processor/runtime/dotnetcore/runtime.go
pkg/processor/runtime/java/runtime.go
pkg/processor/runtime/rpc/abstract.go
pkg/processor/runtime/ruby/runtime.go
test/docker/Dockerfile

- Fix dependencies to make build work again
- Add stdout/stderr printings coming from java
- Add logs before restarting wrapper process

[Java] Update and fixes [1.3.x]

---

pkg/processor/trigger/mqtt/basic/test/mqtt_test.go

It seems that `TestMultipleTopics` test under `pkg/processor/trigger/mqtt/basic/test` has been failing the past 2 days - for unknown reason as it works locally.

[CI] - Fix broken test

---

go.mod
go.sum

Update fasthttp 

---

pkg/nuctl/command/common/renderers.go
pkg/nuctl/command/export.go
pkg/nuctl/command/get.go
pkg/platform/abstract/platform.go
pkg/platform/kube/platform.go
pkg/platform/types.go

Nuctl - function events small fixes

---

pkg/platform/abstract/platform.go

Fix due to https://github.com/nuclio/nuclio/pull/2337

Function event - enrich headers correctly

---

hack/k8s/helm/nuclio/values.yaml
pkg/platform/kube/monitoring/function.go
pkg/platform/kube/operator/multiworker.go

Forward porting #2340 to development

Kubernetes - Turn off resync

---

pkg/dashboard/ui/src/app/shared/services/nuclio-api-gateways-data.service.js

https://trello.com/c/vjhC3zd1/1090-api-gws-add-func-exist-validation-header-on-create-update

[API GWs] Add func exist validation header on create/update

---

pkg/dashboard/ui/src/less/mixins.less

https://trello.com/c/75kzHNh8/1104-services-performance-issue-with-big-amount-of-records

[UI] Performance issue with big amount of records

---

pkg/processor/trigger/v3iostream/trigger.go

In case group of replicas (lets say X) try to assign shards and share the workload, there might be some sort of a race condition caused that one member allocate some shards while not processing it and then later on declared as stale and removed from the state file. the function that was _suppose_ to allocate those shards got exhausted waiting for those shards.
This retry makes sure that the wait is forever or until that function was found with shards to handle.

V3io - ensure consumer group start consuming

---

pkg/platform/abstract/platform.go
pkg/platform/abstract/platform_test.go
pkg/platform/kube/platform.go
pkg/platform/local/platform.go

filtered out functions are still getting deleted (when opa client is initialized)

Fix delete function even when filtered out

---

pkg/processor/trigger/v3iostream/factory.go
pkg/processor/trigger/v3iostream/types.go

Add option to change ack window size using annotations.

Add v3iostream ack window size annotation

---

pkg/processor/trigger/kafka/factory.go
pkg/processor/trigger/kafka/trigger.go
pkg/processor/trigger/kafka/types.go
pkg/processor/trigger/v3iostream/trigger.go

same as https://github.com/nuclio/nuclio/pull/2387 but for kafka trigger

Kafka - allowing predefined ack window offset 

---

pkg/processor/build/builder.go

This causes a type conflict in elasticsearch

Log alignment - reason field to type string

---

README.md

We're hiring < https://www.iguazio.com/careers

Nuclio - add hiring badge

---

README.md
hack/k8s/helm/nuclio/Chart.yaml

we're on @ https://artifacthub.io/packages/helm/nuclio/nuclio

Added artifact hub badge

---

cmd/processor/app/processor.go
cmd/processor/app/processor_test.go
pkg/processor/trigger/cron/factory.go
pkg/processor/trigger/factory.go
pkg/processor/trigger/http/factory.go
pkg/processor/trigger/kafka/factory.go
pkg/processor/trigger/kickstart/factory.go
pkg/processor/trigger/kinesis/factory.go
pkg/processor/trigger/mqtt/basic/factory.go
pkg/processor/trigger/mqtt/iotcore/factory.go
pkg/processor/trigger/nats/factory.go
pkg/processor/trigger/partitioned/eventhub/factory.go
pkg/processor/trigger/poller/v3ioitempoller/factory.go
pkg/processor/trigger/pubsub/factory.go
pkg/processor/trigger/rabbitmq/factory.go
pkg/processor/trigger/registry.go
pkg/processor/trigger/v3iostream/factory.go
pkg/processor/worker/factory.go
pkg/processor/worker/sync.go

Backports https://github.com/nuclio/nuclio/pull/2283 to 1.1.x

Backport shared worker allocation fix [1.1.x]

---

docs/reference/function-configuration/function-configuration-reference.md
pkg/dashboard/resource/frontendspec.go
pkg/functionconfig/types.go
pkg/platform/kube/functionres/lazy.go
pkg/platform/kube/platform.go
pkg/platformconfig/platformconfig_test.go
pkg/platformconfig/types.go

Allow function pods to run on matching tainted nodes

Support function pod tolerations

---

Makefile

Bump nginx alpine docker version

---

pkg/nuctl/command/import.go

since errgroup ctx would fail-fast we bail before new function record is being created, ive changed the logic to avoid using errgroup ctx and used the given function arg ctx instance

Fix ci import project test transient errors

---

pkg/functionconfig/types.go
pkg/platform/kube/platform.go

- move enrichment under functionconfig for connivency
- fix "constrain" mode to have tolerations as well

Preemptible mode - fixes and refining

---

hack/k8s/helm/nuclio/Chart.yaml
hack/k8s/helm/nuclio/templates/deployment/dashboard.yaml
hack/k8s/helm/nuclio/values.yaml

Helm - accept kaniko init container image name

---

pkg/functionconfig/types.go
pkg/platform/abstract/platform.go
pkg/platform/kube/functionres/lazy.go

Change default k8s cron trigger base image

---

hack/k8s/helm/nuclio/values.yaml

JIRA: https://jira.iguazeng.com/browse/IG-19671
Increase OPA's success threshold to make sure it is ready before it can accept requests.

IG-19671: Increase OPA readiness probe success threshold

---

pkg/platform/local/platform.go

Fixes https://github.com/nuclio/nuclio/issues/2514

Local platform - ensure no function container right before deploying the function

---

hack/docker/build/base-alpine/Dockerfile
hack/docker/build/base/Dockerfile
hack/docker/build/builder/Dockerfile
pkg/processor/build/runtime/golang/docker/onbuild/Dockerfile
pkg/processor/build/runtime/golang/docker/onbuild/Dockerfile.alpine

Golang - do not pin patch version

---

pkg/dashboard/ui/package.json
pkg/dashboard/ui/src/app/app.run.js

- **Nuclio**: UI - show default resources (mem,cpu) when first creating function
Jira: https://jira.iguazeng.com/browse/IG-20659

Fix [Nuclio] Nuclio UI - show default resources (mem,cpu) when first creating function

---

pkg/dashboard/ui/package.json
pkg/dashboard/ui/src/app/app.run.js

- **UI** - Adding spill disk param to trino
Jira: https://jira.iguazeng.com/browse/IG-20641
After:

Impl [UI] - adding spill disk param to trino

---

go.mod
go.sum

Fixing error caused by https://github.com/distribution/distribution/issues/3590

Fix docker distribution checksum error

---

pkg/processor/trigger/kafka/test/kafka_test.go

Creating a rebalance test for kafka trigger, so we can use it for testing new kafka related features.

Add kafka rebalance integration test

---

pkg/processor/trigger/kafka/test/kafka_test.go

Change topic and consumer group between different tests in the suite.

Fix Kafka integration tests

---

pkg/functionconfig/types.go
pkg/platform/abstract/platform.go
pkg/platform/abstract/platform_test.go
pkg/processor/trigger/kafka/types.go

Generalize kind for explicit ack parameters enrichment, and modify tests.

Fix kafka trigger worker termination timeout enrichment

---

pkg/containerimagebuilderpusher/kaniko.go

Kaniko - create ECR cache repo [1.9.x] (#2620)

---

pkg/processor/trigger/kafka/test/kafka_test.go
pkg/processor/trigger/test/eventrecorder.go

Kafka rebalance integration test caused periodic CI to fail, revert #2603 it until fixed.

Revert #2603 - Kafka rebalance tests

---

pkg/processor/trigger/v3iostream/types.go

Allow changing the trigger's worker allocation mode using annotations the following annotation: `"nuclio.io/v3iostream-worker-allocation-mode"`, with the options being `pool` and `static`.
Also, add explicit ack mode validations to the v3io stream trigger configuration.

V3io stream trigger - change worker allocation mode via annotations

---

docs/reference/triggers/kafka.md
docs/reference/triggers/v3iostream.md

According to https://github.com/nuclio/nuclio-sdk-py/pull/38

Update stream trigger docs with QualifiedOffset

---

pkg/auth/iguazio/auth_test.go
pkg/context/detached_test.go
pkg/platform/abstract/project/external/client_test.go
pkg/platform/abstract/project/external/leader/iguazio/client_test.go
pkg/platform/abstract/project/external/leader/iguazio/synchronizer_test.go
pkg/platform/types_test.go

Format build tags above copyright

---

cmd/dashboard/docker/runner.sh
cmd/dashboard/docker/runners/dashboard.sh
cmd/dashboard/docker/runners/nginx.sh
hack/scripts/ci/free-space.sh
hack/scripts/minikube/push_images.py
test/k8s/ci_assets/install_nginx_ingress_controller.sh
test/k8s/ci_assets/install_nuclio_crds.sh

Signed-off-by: eliyahu77 <root@linux-eliyahun.iguaz.io>

Format shebang above copyright disclaimer

---

pkg/processor/runtime/rpc/abstract.go

When a runtime restart occurs, the control output handler is unaware of it.
A new socket is created, but the control output handler goroutine still tries to read from the old socket - and fails. 
However - the event output handler gets a panic when the runtime restarts, and recovers from it.
We add a sync mechanisms between both handlers, so if one panics the other knows it should exit.
Related to https://github.com/nuclio/nuclio/issues/2657

Sync between event and control output handlers

---

.github/workflows/ci.yaml
.github/workflows/release.yaml
Makefile

Fix cache images tags, pull before build, etc

Fix release

---

pkg/cmdrunner/shellrunner_test.go
pkg/common/helper.go
pkg/dockerclient/dockerclient.go
pkg/dockerclient/mock.go
pkg/dockerclient/shell.go
pkg/platform/local/platform.go
pkg/platform/local/test/platform_test.go
pkg/platform/local/types.go
pkg/platformconfig/types.go
pkg/processor/runtime/shell/runtime_test.go

Adding platforms default for network / retry policy to enforce over all functions

Local - Function to use platform defaults

---

go.mod
go.sum

Addressing latest report of https://artifacthub.io/packages/helm/nuclio/nuclio?modal=security-report

Bump modules

---

.github/workflows/ci.yaml
Makefile
pkg/platform/abstract/project/external/leader/iguazio/client.go
pkg/platform/abstract/project/external/leader/iguazio/client_test.go

In addition, removed caching commands for now

Fix resync in case time is zero-ed

---

pkg/platform/kube/platform.go
pkg/platform/local/platform.go
pkg/platformconfig/platformconfig.go
pkg/platformconfig/types.go

Some fixes required for having platform config with local platform

Local - few fixes

---

Makefile
hack/examples/golang/callfunction/fibonacci/fibonacci.go
hack/examples/golang/callfunction/fibonaccisum/fibonaccisum.go
hack/examples/golang/ingress/ingress.go
pkg/common/helper.go
pkg/platform/kube/platform.go
pkg/platform/kube/test/functional/platform_test.go
pkg/platform/local/test/platform_test.go
pkg/processor/build/builder_test.go
pkg/processor/build/inlineparser/parser.go
pkg/processor/runtime/java/doc.go
pkg/processor/runtime/nodejs/doc.go
pkg/restful/resource_test.go

bump golangoci to 1.50
added golangci --fix to `make fmt` command

CI - linter updates

---

docs/reference/triggers/kafka.md
pkg/processor/trigger/kafka/trigger.go

Added information regarding the sasl / tls / ca-certs to kafka doc

Docs - update kafka with support for sasl

---

cmd/dashboard/docker/Dockerfile
docs/reference/runtimes/dotnetcore/dotnetcore-reference.md
docs/reference/runtimes/golang/golang-reference.md
docs/reference/runtimes/java/java-reference.md
docs/reference/runtimes/nodejs/nodejs-reference.md
docs/reference/runtimes/python/python-reference.md
docs/tasks/deploy-functions-from-dockerfile.md
pkg/processor/build/builder.go
pkg/processor/build/test/build_test.go

fixes https://github.com/nuclio/nuclio/issues/1268

Local - increase default healthcheck to 10s

---

cmd/dashboard/docker/Dockerfile
docs/reference/runtimes/dotnetcore/dotnetcore-reference.md
docs/reference/runtimes/golang/golang-reference.md
docs/reference/runtimes/java/java-reference.md
docs/reference/runtimes/nodejs/nodejs-reference.md
docs/reference/runtimes/python/python-reference.md
docs/tasks/deploy-functions-from-dockerfile.md
pkg/processor/build/builder.go
pkg/processor/build/test/build_test.go

Reverts nuclio/nuclio#2751
Will do it configurable per function

Revert "Local - increase default healthcheck to 10s"

---

docs/reference/function-configuration/function-configuration-reference.md
pkg/processor/build/builder.go
pkg/processor/build/test/build_test.go

See documentation below for more information

Local - configurable healthcheck intervals

---

pkg/processor/runtime/ruby/runtime.go
pkg/processor/runtime/ruby/test/outputter/outputter.rb
pkg/processor/runtime/ruby/test/ruby_test.go
pkg/processor/runtime/ruby/wrapper.rb

1. support `init_context`
2. fixes https://github.com/nuclio/nuclio/issues/1248

Ruby - some updates

---

pkg/platform/abstract/project/external/leader/iguazio/client.go
pkg/platform/abstract/project/external/leader/iguazio/client_test.go

Iguazio project creation might fail without indicative status, fallback to internal server error

Fix iguazio project creation failure handling

---

pkg/nuctl/command/export.go

Nuctl - move no-scrub flag to export comandeer [1.10.x]

---

pkg/dashboard/ui/src/app/app.run.js

- **UI**: nuclio scale-up metrics
Jira: https://jira.iguazeng.com/browse/IG-21268
After:

Impl [UI] nuclio scale-up metrics

---

.github/workflows/security_scan.yaml

1. fix filesystem scan folder being empty
2. exit 1 when running against PR
following up https://github.com/nuclio/nuclio/pull/2820

CI - enhance security scan feedback

---

.github/workflows/security_scan.yaml

#2823 wasnt good for fixing the fs folder scan, removing and using job defaults.

CI - enhance security scan feedback take 2

---

.github/workflows/security_scan.yaml

add exit code to image scan as well
follow up #2824

CI - enhance security scan feedback take 3

---

pkg/processor/build/runtime/dotnetcore/docker/onbuild/Dockerfile
pkg/processor/build/runtime/golang/docker/onbuild/Dockerfile
pkg/processor/build/runtime/java/docker/onbuild/Dockerfile

to include more libraries and OS packages security fixes during docker images build

Security - upgrade more packages during image build

---

hack/scripts/ci/free-space.sh

it removes core packages that we need. undo for now

CI - undo cleanup script changes

---

.github/workflows/release.yaml

first checkout, then use script. sigh

CI - release wrong order

---

.github/workflows/benchmark.yaml
.github/workflows/ci.yaml
.github/workflows/long_ci.yaml
.github/workflows/periodic.yaml
.github/workflows/release.yaml
pkg/processor/build/runtime/golang/test/golang_test.go
pkg/processor/runtime/python/test/timeout_test.go

increased python sleeptime to avoid transient issues on slow workers

CI - Ensure go version from go.mod

---

.github/workflows/ci.yaml
Makefile

and login during CI to ensure cache are fetchable

[Makefile] Fix xargs warnings

---

.github/workflows/benchmark.yaml

better read input from envvar, for security concerns

[CI] Update benchmark action

---

pkg/platform/abstract/platform.go

Followup to https://github.com/nuclio/nuclio/pull/2843

[FunctionConfig] Check nil before validating replicas

---

pkg/dashboard/ui/src/app/app.run.js

Revert https://jira.iguazeng.com/browse/IG-21268

Revert "Impl [UI] nuclio scale-up metrics (#2789)"

---

pkg/dashboard/ui/package.json
pkg/dashboard/ui/src/app/app.run.js

https://jira.iguazeng.com/browse/IG-21268

Bump dashboard-controls version

---

pkg/dashboard/ui/src/app/shared/services/nuclio-event-data.service.js

- **UI**: Unclear error reason when function invoke fails
Jira: https://jira.iguazeng.com/browse/IG-21728

Fix [UI] unclear error reason when function invoke fails

---

pkg/dashboard/ui/src/app/app.run.js
pkg/dashboard/ui/src/app/components/data-wrappers/function-events-data-wrapper/function-events-data-wrapper.component.js
pkg/dashboard/ui/src/app/components/data-wrappers/function-events-data-wrapper/function-events-data-wrapper.tpl.html
pkg/dashboard/ui/src/app/shared/services/nuclio-event-data.service.js

- **Nuclio**: Function invoke fails with "certificate verify failed"
Jira: https://jira.iguazeng.com/browse/IG-21658
Depends On: [v0.39.20](https://github.com/iguazio/dashboard-controls/releases/tag/v0.39.20)
Relates To: Dashboard: https://github.com/iguazio/dashboard/pull/4596
After:

[UI] function invoke fails with "certificate verify failed"

---

pkg/dashboard/ui/src/app/components/data-wrappers/version-data-wrapper/version-data-wrapper.component.js
pkg/dashboard/ui/src/app/components/data-wrappers/version-data-wrapper/version-data-wrapper.tpl.html
pkg/dashboard/ui/src/app/shared/services/nuclio-functions-data.service.js

- **UI**: Set timeout on nuclio function build from github to 5 min
Depends On: [v0.39.20](https://github.com/iguazio/dashboard-controls/releases/tag/v0.39.20)
Jira: https://jira.iguazeng.com/browse/IG-21713

Fix [UI] Set timeout on nuclio function build from github to 5 min

---

.github/workflows/release.yaml
.github/workflows/security_scan.yaml
Makefile

to avoid cases where make onbuild will reuse prebuilt unstable processor

[Build] Ensure processor being built

---

.github/workflows/release.yaml

[CI] Fix copy-paste mistake

---

.github/workflows/release.yaml

Add envvar to other steps (push and push cache)

[CI] Refine release 2

---

docs/reference/api-gateway/http.md
docs/reference/api-gateway/nuctl.md
docs/reference/triggers/kafka.md
docs/reference/triggers/v3iostream.md

Document api gateway deletion both with http and nuctl.

[Docs] Add delete API Gateway documentation

---

hack/k8s/helm/nuclio/values.yaml

Edit values file indentation to be a valid yaml file.
Fixes #2921

[Helm] Fix values file indentation

---

.github/workflows/long_ci.yaml

[CI] Skip steps using PR number if not given

---

.github/workflows/long_ci.yaml

This causes issues when pr number is not given.

[CI] Long CI - don't use pr number in job name

---

pkg/nuctl/command/invoke.go

Allow failing the nuctl run when a function fails invocation, by checking the invocation response status code.
This will allow us to test successful function invocation in CI and other tests.
Usage:
```
$ nuctl invoke <function-name> --raise-on-status
```
Then, if function returns a failure status code:
```
$ echo $?
1
```

[Nuctl] Add `raise-on-status` flag to invoke command

---

pkg/containerimagebuilderpusher/kaniko.go
pkg/platform/kube/test/functional/platform_test.go

Kaniko jobs are scheduled for deletion after they are completed.
The context that was used for the deletion job was canceled after the function creation was finished, causing job to fail deletion.
Using a detached context removes the dependency in the function creation context and can continue living once it is done.
NOTE: the functional test added in this PR fails atm, as it is using the `unstable` nuclio version. But it does pass when using the changes in this PR.
Fixes https://jira.iguazeng.com/browse/IG-21917

[Kaniko] Detach context when deleting jobs

---

README_zh.md

Synchronize Chinese translation
delete '-v /tmp:/tmp' 。

[Readme] Synchronize Chinese translation

---

.github/workflows/ci.yaml
pkg/platform/abstract/project/external/leader/iguazio/synchronizer.go

Apply the fix introduced in https://github.com/nuclio/nuclio/pull/2794 to updating projects as well

[Project] Filter invalid labels when updating from leader

---

docs/devel/local-development.md

- Added some notes regarding image versions when running the dashboard
- Added steps to run / debug the processor
- Format fixes

[Docs] Improve and format local-development

---

pkg/processor/trigger/kafka/trigger.go

Backport the kafka fix from https://github.com/nuclio/nuclio/pull/2988 to 1.11.x

[Kafka] Commit the offset when handler is done on rebalance [1.11.x]

---

Makefile
pkg/processor/runtime/golang/builtin.go
pkg/processor/runtime/golang/handler.go

pigz was removed from latest github runner, switched with gzip

[CI] Use gzip to compress images

---

pkg/processor/runtime/shell/test/timeout_test.go

response is now right, after fixing its code via https://github.com/nuclio/nuclio/pull/3002

[CI] Fix shell timeout test

---

hack/examples/golang/helloworld/helloworld.go

[Examples] Update helloworld.go

---

pkg/containerimagebuilderpusher/docker.go
pkg/containerimagebuilderpusher/kaniko.go
pkg/containerimagebuilderpusher/types.go
pkg/dockerclient/shell.go
pkg/dockerclient/types.go
pkg/functionconfig/reader_test.go
pkg/functionconfig/types.go
pkg/processor/build/builder.go
pkg/processor/build/builder_test.go
pkg/processor/build/test/build_test.go

Jira: IG-21698
Custom build flags can be specified in function config spec (`buildFlags`)

[Processor] Add buildFlags parameter to function config

---

Makefile
docs/devel/contributing.md
docs/devel/local-development.md
go.mod
pkg/dockercreds/dockercred.go
pkg/dockercreds/dockercreds.go
pkg/dockercreds/dockercreds_test.go
test/_functions/golang/with-modules/go.mod
test/_functions/golang/with-modules/go.sum

[Go] Bump go version to 1.21

---

docs/devel/local-docker-development.md

I recently tried to get a development setup running on my computer using docker. To save the next person trying to do the same thing some time, I wrote up my solution. Hope it helps!
I have tested this on a Linux machine running docker version 24.0.5, and on an M2 MacBook.

[Docs] Local docker development

---

README.md
README_zh.md
docs/reference/runtimes/dotnetcore/dotnetcore-reference.md
docs/reference/runtimes/dotnetcore/writing-a-dotnetcore-function.md
hack/examples/README.md
pkg/processor/build/runtime/dotnetcore/docker/onbuild/Dockerfile
pkg/processor/build/runtime/dotnetcore/docker/onbuild/handler.csproj
pkg/processor/build/runtime/dotnetcore/runtime.go
pkg/processor/runtime/dotnetcore/Wrapper.cs
pkg/processor/runtime/dotnetcore/test/_outputter/handler.csproj
pkg/processor/runtime/dotnetcore/wrapper.csproj
pkg/processor/runtime/nodejs/js/package-lock.json

Followup to the security scan: https://github.com/nuclio/nuclio/actions/runs/6314954487
- Bump NPM dependencies in `package-json.lock`
- Bump .Net framework
- Java vulnerabilities will be handled separately

[Security] Fix Node and .Net vulnerabilities

---

.github/workflows/benchmark.yaml
Makefile
docs/reference/runtimes/python/python-reference.md
docs/tasks/benchmarking.md
hack/examples/python/tensorflow/function.yaml
hack/scripts/benchmark/benchmark.py
pkg/common/helper.go
pkg/dashboard/functiontemplates/generated.go
pkg/functionconfig/reader_test.go
pkg/nuctl/test/function_test.go
pkg/platform/local/platform.go
pkg/processor/build/builder_test.go
pkg/processor/build/runtime/python/docker/onbuild/Dockerfile
pkg/processor/build/runtime/python/runtime.go
pkg/processor/build/runtime/python/test/python_test.go
pkg/processor/runtime/python/test/python_test.go

Jira tickets: [NUC-53](https://jira.iguazeng.com/browse/NUC-53), [NUC-59](https://jira.iguazeng.com/browse/NUC-59)

[Runtime] Deprecate python 3.6, add warn for python 3.7 and 3.8 

---

cmd/dashboard/README.md
docs/reference/nuctl/nuctl.md

Jira - https://jira.iguazeng.com/browse/NUC-35

[Docs] Add nuctl redeploy docs

---

docs/conf.py

change copyright from Nuclio to Iguazio

[Docs] Update readthedocs copyright

---

cmd/dashboard/app/run.go
cmd/dashboard/main.go
pkg/auth/iguazio/auth.go
pkg/auth/iguazio/auth_test.go
pkg/auth/types.go
pkg/common/helper.go
pkg/common/helper_test.go
pkg/common/testutils/http.go
pkg/dockerclient/shell.go

Making sure that some errors are being retried when trying to authenticate against iguazio idp
https://jira.iguazeng.com/browse/NUC-99

[Dashboard] Retryable Iguazio http client 

---

pkg/dashboard/resource/frontendspec.go
pkg/nuctl/command/common/renderers.go
pkg/platform/abstract/platform.go
pkg/platform/abstract/platform_test.go
pkg/platform/abstract/project/external/leader/iguazio/client.go
pkg/platform/abstract/project/external/leader/iguazio/types.go
pkg/platform/kube/platform.go
pkg/platform/kube/platform_test.go
pkg/platform/types.go

to be align with project-wide value and correctly sync when nuclio runs against an iguazio platform
https://jira.iguazeng.com/browse/NUC-71

[Project] Correct function default node selector field name

---

pkg/platform/abstract/platform.go
pkg/platform/abstract/platform_test.go
pkg/platform/kube/platform_test.go

This reverts commit 8c3c99d80fac1b767cd1ebbfb317e399fcf6aedb.

Revert "[Dashboard] Add trigger existence validation (#3074)"

---

docs/concepts/k8s/function-ingress.md
docs/conf.py
docs/devel/contributing.md
docs/reference/runtimes/dotnetcore/dotnetcore-reference.md
docs/reference/runtimes/shell/shell-reference.md
docs/requirements.txt
docs/setup/k8s/running-in-production-k8s.md
docs/tasks/benchmarking.md
docs/tasks/deploying-functions.md
docs/tasks/quick-start.md

Makes life easier using easy copy-paste experience

[Docs] Add copy button

---

pkg/processor/trigger/kafka/test/kafka_test.go

Renamed topic in TestDrainHook so we do not use the suite's one and added teardown

[Test] Add test teardown to TestDrainHook

---

cmd/processor/app/processor.go

[Bug] Fix compatibly of the last processor with dashboard < 1.12.8

---

docs/setup/k8s/running-in-production-k8s.md

- Split the commands to 2 so it will be copy-able
- Add namespace to helm install command

[Docs] Update helm commands in kubernetes production

---

pkg/processor/runtime/python/py/_nuclio_wrapper.py
pkg/processor/trigger/kafka/trigger.go

[No ticket]
Fixed comments from https://github.com/nuclio/nuclio/pull/3120#pullrequestreview-1826858572

[Processor] Introduce a fail counter for tracking the number of failed attempts during SIGCONT signaling

---

pkg/nuctl/command/parse.go
pkg/nuctl/test/function_test.go

Jira - https://jira.iguazeng.com/browse/NUC-138

[Nuctl] Do not print parsed report if it is empty

---

docs/requirements.txt

[Docs] Add `markdown` library to requirements [1.12.x]

---

pkg/platform/kube/functionres/lazy.go
pkg/platform/kube/test/platform_test.go

[Controller] Populate init and sidecar containers when updating a function [1.12.x]

---

hack/scripts/patch-remote/patch_env_template.yml

[Script] Add namespace to remote patching template

---

pkg/dashboard/ui/package.json
pkg/dashboard/ui/src/app/app.run.js

- **UI**: Support disabling default http trigger creation for a specific function
Reverts: #3237
Jira: https://iguazio.atlassian.net/browse/NUC-187

Revert [UI] - Support disabling default http trigger creation for a specific function (#3237)

---

pkg/common/headers/headers.go
pkg/dashboard/resource/invocation.go

[bluemonday](https://github.com/microcosm-cc/bluemonday)'s HTML sanitization corrupts valid HTML responses.
This PR makes sanitization configurable so we can continue working properly while looking for a better sanitization library.
Resolves https://iguazio.atlassian.net/browse/ML-6600

[Invocation] Make sanitization configurable

---

pkg/platform/kube/platform.go

jira - https://iguazio.atlassian.net/browse/NUC-197

[Dashboard] Return NewErrBadRequest when api gateway name validation failed

---

pkg/platform/local/platform.go

Do not check containers readiness when function is disabled.
closes #3257

[Dashboard] Do not check containers readiness when function is disabled

---

pkg/processor/build/runtime/test/suite/suite.go

It was decided to remove this test since after merging of this PR https://github.com/nuclio/nuclio/pull/3266 it fails (not because functionality doesn't work - it works, but because test itself is broken). This whole functionality is in deprecation now, so it was decided not to put any effort on fixing the test.

[Test] Remove TestBuildArchiveFromGithub

---

pkg/processor/trigger/registry.go

[Processor] Add more detailed error if trigger kind is not found in registry

---

pkg/platform/local/platform.go

[Local] Fix condition when dashboard does not check function readiness

---

pkg/platform/local/platform.go

Cherry-picking #3272 to 1.13.x

[Local] Fix condition when dashboard does not check function readiness [1.13.x]

---

pkg/platform/local/platform.go

Backport https://github.com/nuclio/nuclio/pull/3272

[Local] Fix condition when dashboard does not check function readiness [1.13.x] 

---

pkg/platform/kube/test/platform_test.go

[Tests] Optimize test running time

---

README_zh.md

[Docs] Fix wrong word in Readme

---

.github/workflows/ci.yaml
Makefile
pkg/platform/kube/controller/test/controller_test.go
pkg/platform/kube/monitoring/test/function_test.go
pkg/platform/kube/resourcescaler/test/resourcescaler_test.go
pkg/platform/kube/test/apigateway/api_gateway_test.go
pkg/platform/kube/test/function/function_test.go
pkg/platform/kube/test/project/project_test.go
pkg/platform/kube/test/suite/suite.go

Split tests so we can run kube tests in 2 parallel jobs

[Tests] Split platform tests and add new tag `test_functions_kube`

---

pkg/platform/kube/ingress/ingress.go

[Ingress] Override ssl redirect annotation only if it is not set

---

pkg/dashboard/ui/package.json
pkg/dashboard/ui/src/app/app.run.js

- **UI**: allow the user to disable the automatic http trigger creation in nuclio
Depends on: https://github.com/iguazio/dashboard-controls/pull/1564
Jira: https://iguazio.atlassian.net/browse/NUC-54

[UI] Allow the user to disable the automatic http trigger creation

---

pkg/dashboard/ui/src/app/app.run.js

https://iguazio.atlassian.net/browse/NUC-213

[UI] Display enriched node selector on status screen

---

pkg/nuctl/client/api.go
pkg/nuctl/client/api_test.go
pkg/nuctl/test/function_test.go

This PR improves UX by adding API URL validation in `nuctl beta` command. 
Jira - https://iguazio.atlassian.net/browse/NUC-214

[Nuctl] Validate api url parameter in nuctl beta

---

pkg/nuctl/client/api.go
pkg/nuctl/client/api_test.go
pkg/nuctl/test/function_test.go

[Nuctl] Validate api url parameter in nuctl beta [1.13.x]

---

pkg/dashboard/ui/package.json
pkg/dashboard/ui/src/app/app.run.js

https://iguazio.atlassian.net/browse/NUC-213

[UI] Bump DC version `1.0.9-1.13.x`

---

pkg/containerimagebuilderpusher/types.go

[ContainerImageBuilderPusher] Bump awscli and kaniko versions [1.13.x]

---

.github/workflows/ci.yaml
pkg/common/k8s.go
pkg/nuctl/test/suite.go
pkg/platform/kube/apis/nuclio.io/v1beta1/types.go
pkg/processor/build/builder.go

Need to revert and split into 2 PRs

Revert "[Builder] Enrich Kaniko's NodeSelector with project and platform values (#3301)"

---

pkg/common/k8s.go
pkg/nuctl/test/suite.go
pkg/platform/kube/apis/nuclio.io/v1beta1/types.go
pkg/processor/build/builder.go

Jira - https://iguazio.atlassian.net/browse/NUC-219

[Builder] Enrich Kaniko's NodeSelector with project and platform values

---

pkg/platform/kube/functionres/lazy.go

[Controller] Don't override default container annotation if exists

---

pkg/common/url.go
pkg/common/url_test.go
pkg/nuctl/test/apigagteway_test.go
pkg/platform/kube/apigateway.go
pkg/platform/kube/platform.go
pkg/platform/kube/platform_test.go

jira - https://iguazio.atlassian.net/browse/NUC-224

[Dashboard] Add path validation for api gateway

---

pkg/common/url.go
pkg/common/url_test.go
pkg/nuctl/test/apigagteway_test.go
pkg/platform/kube/apigateway.go
pkg/platform/kube/platform.go
pkg/platform/kube/platform_test.go

[Dashboard] Add path validation for api gateway [1.13.x]

---

pkg/dashboard/ui/package.json

- **UI**" Allow creating more than 1 gateway per function
Jira: https://iguazio.atlassian.net/browse/NUC-237

[UI] Allow creating more than 1 gateway per function

---

pkg/dashboard/ui/package.json

- **UI**" Allow creating more than 1 gateway per function
Backported to `1.13.x` from https://github.com/nuclio/nuclio/pull/3322
Jira: https://iguazio.atlassian.net/browse/NUC-237

[UI] Allow creating more than 1 gateway per function `1.13.x`

---

pkg/containerimagebuilderpusher/kaniko.go
pkg/containerimagebuilderpusher/types.go
pkg/processor/build/builder.go

[Dashboard] Display kaniko pod warning events in the build logs [1.13.x]

---

pkg/platform/abstract/platform.go
pkg/platform/abstract/platform_test.go
pkg/platform/kube/platform_test.go
pkg/processor/trigger/kafka/trigger.go
pkg/processor/trigger/v3iostream/trigger.go

[Processor] Fix ExplicitAck on 2 and more triggers of the same type [1.13.x]

---

pkg/nuctl/client/api.go
pkg/nuctl/command/common/patchmanifest.go
pkg/nuctl/command/redeploy.go
pkg/nuctl/test/function_test.go

[Nuctl] Fix redeploy errors and logs

---

pkg/platform/abstract/platform.go
pkg/platform/abstract/platform_test.go
pkg/platform/kube/platform_test.go

Jira - https://iguazio.atlassian.net/browse/NUC-256
Reverts part of the changes done in #3336 which broke BC with mlrun

[Processor] Do not enrich workerAllocatorName by default

---

pkg/platform/abstract/platform.go
pkg/platform/abstract/platform_test.go
pkg/platform/kube/platform_test.go

[Processor] Do not enrich workerAllocatorName by default  [1.13.x]

---

pkg/common/helper.go
pkg/containerimagebuilderpusher/docker.go
pkg/containerimagebuilderpusher/kaniko.go
pkg/processor/build/builder.go
pkg/processor/build/util/unarchive.go

As a part of psr, change mkdir permissions from 755 to 700

[Security] Change mkdir permissions from 755 to 700

---

docs/reference/triggers/v3iostream.md
pkg/processor/trigger/v3iostream/types.go
pkg/processor/trigger/v3iostream/v3iostream_test.go

[V3IOStream] Generate access key from env var

---

pkg/common/helper.go
pkg/containerimagebuilderpusher/docker.go
pkg/containerimagebuilderpusher/kaniko.go
pkg/processor/build/builder.go
pkg/processor/build/util/unarchive.go

[Security] Change mkdir permissions from 755 to 700 [1.13.x]

---

docs/reference/triggers/rabbitmq.md

- Change the name of the trigger
- Fix the default interval - 15s
- Better explain `reconnectDuration`

[Docs] RabbitMQ fixes

---

pkg/processor/trigger/v3iostream/trigger.go

[V3io] Do not filter ExplicitAck by streamPath for v3io trigger [1.13.x]

---

pkg/dashboard/ui/package.json
pkg/dashboard/ui/src/app/app.run.js

- **Services**: Wrong case for uniqueness validation message
Jira: https://iguazio.atlassian.net/browse/IG-23083

[UI] Wrong case for uniqueness validation message

---

pkg/processor/trigger/v3iostream/trigger.go
pkg/processor/trigger/v3iostream/types.go

[Processor] Align ExplicitAck log for v3io and kafka [1.13.x]

---

pkg/processor/trigger/v3iostream/trigger.go

[Processor] Filter v3io ExplicitAck by topic if passed [1.13.x]

---

pkg/dashboard/ui/resources/previewServer/package-lock.json

Fixes some Node security vulnerabilities

[UI] Bump NPM packages

---

pkg/containerimagebuilderpusher/kaniko.go
pkg/platform/kube/test/platform_test.go
pkg/processor/build/builder.go

[Security] Fix access rights for wrapper [1.13.x]

---

pkg/nuctl/test/function_test.go
pkg/platform/abstract/platform.go
test/_imports/never_run_before_export_function.yaml

[Nuctl][Dashboard] Fix importing function that was in error or building state before export [1.13.x]

---

pkg/dashboard/ui/resources/previewServer/package-lock.json

[UI] Bump NPM packages [1.13.x]

---

pkg/processor/runtime/rpc/abstract.go

[Processor] Send drain signal only if worker is ready

---

.github/workflows/ci.yaml
pkg/loggersink/types.go

Support lowercase, uppercase and full name (for warning) log levels.
Resolves [NUC-290](https://iguazio.atlassian.net/browse/NUC-290)
[NUC-290]: https://iguazio.atlassian.net/browse/NUC-290?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[LoggerSink] Support case-insensitive log levels

---

docs/reference/runtimes/python/python-reference.md

Jira - https://iguazio.atlassian.net/browse/NUC-294

[Docs] Fix termination callback documentation

---

pkg/dashboard/ui/package.json

Related to: https://github.com/iguazio/dashboard-controls/pull/1588, https://github.com/iguazio/dashboard-controls/pull/1589

Bump DC version `1.0.13`

---

pkg/common/helper.go
pkg/containerimagebuilderpusher/docker.go
pkg/containerimagebuilderpusher/kaniko.go
pkg/processor/build/builder.go
pkg/processor/build/runtime/test/suite/suite.go
pkg/processor/build/util/unarchive.go

[Security] Change directory access back to 755 [1.13.x]

---

hack/scripts/patch-remote/patch_remote.py

Since the dashboard and controller's deployments' strategy is "RollingUpdate", using `kubectl wait --for condition=Ready` sometimes times out because it waits for the terminating pod to be ready - which it never will. 
Instead, we now poll the pod status manually until it's ready.

[Patch Script] Fix wait for pod readiness

---

docs/devel/local-development.md

Numbering was off and the Note was displayed as a Header, so this PR fixes it.

[Docs] Format local development

---

pkg/processor/trigger/kafka/trigger.go
pkg/processor/trigger/v3iostream/trigger.go

Unsubscribing in case of regular ack led to panic.

[Processor] Unsubscribe only in ExplicitAckMode

---

pkg/processor/trigger/kafka/trigger.go
pkg/processor/trigger/v3iostream/trigger.go

[Processor] Unsubscribe only in ExplicitAckMode [1.13.x]

---

pkg/nuctl/command/deploy.go
pkg/nuctl/test/function_test.go
pkg/processor/build/builder.go
test/_functions/common/json-parser-with-function-config/python/function.yaml

[Nuctl] Fix config enrichment if file isn't passed explicitly [1.13.x]

---

pkg/processor/runtime/rpc/abstract.go
pkg/processor/runtime/rpc/abstract_test.go
pkg/processor/runtime/runtime.go
pkg/processor/trigger/http/test/suite/http_test.go

After merging #3378, periodic fails. This PR fixes tests (checked locally)

[Processor] Fix control message broker enrichment

---

docs/reference/triggers/kinesis.md
docs/tasks/configuring-a-platform.md

[shard-request-ML-8393](https://iguazio.atlassian.net/browse/ML-8393)

[Docs] Fix one link and shard format

---

.github/workflows/ci.yaml
pkg/processor/runtime/python/runtime.go
pkg/processor/runtime/rpc/abstract.go
pkg/processor/runtime/runtime.go

Backport #3423
https://iguazio.atlassian.net/browse/NUC-315

[Processor] Move signaling to Python runtime [1.13.x]

---

pkg/dashboard/ui/package.json
pkg/dashboard/ui/src/less/mixins.less

- **Nuclio**: Add Execution log to the Nuclio Function
Jira: https://iguazio.atlassian.net/browse/NUC-314
💡 **NOTE:** Not relevant for open source.
Display paginated logs related to the current Nuclio function.
Filtering options:
1. Message: free text to filter any text within the message.
2. Level: debug, info, warning, error.
3. Time range: Last 24 hours, Last week, Last month, or custom range.
4. Replica: Users should see a list of all different replicas of the function and choose which replica(s) to show.

[UI] Add execution log to function screen

---

hack/k8s/helm/nuclio/templates/deployment/dashboard.yaml
hack/k8s/helm/nuclio/values.yaml
pkg/dashboard/resource/frontendspec.go
pkg/dashboard/test/server_test.go
pkg/platformconfig/platformconfig.go

The dashboard will tell the UI via the Frontend spec if the logs screen is enabled by reading an env var.
https://iguazio.atlassian.net/browse/NUC-333

[Logs] Add "logsScreenEnabled" to frontend spec
