pkg/nubuild/build/build.go
pkg/nubuild/build/docker.go
pkg/nuctl/builder/function.go
pkg/nuctl/builder/types.go
pkg/nuctl/command/build.go
pkg/nuctl/command/run.go
pkg/nuctl/command/run_test.go
pkg/nuctl/runner/function.go
pkg/nuctl/runner/types.go

The first thing this PR does is perform proper cleanup during build. Nothing intermediate should be left behind.
But mostly, this solves three issues with regards to `nuctl run`:
1. Custom image names / versions are not respected (bug)
2. We magically default to running the image from `localhost:5000` under some conditions - super sneaky
3. The command can be much friendlier when the push registry is also the registry the function pulls from. This is not the case right now, but I think this will be the majority
Things user needs to pass:
1. Registry to push to
2. Optionally, image name if different than function name
3. Optionally, version name if not latest
4. Optionally registry to run the function from if different from push registry
Examples, from simple to complex:
`nuctl run -p …

nuctl run overhaul

---

pkg/processor/runtime/types.go
pkg/processor/runtime/types_test.go

Duplicating a structure results in detaching a huge chain of dependencies from processor, allowing it to compile faster.

Faster processor compilation

---

pkg/nubuild/build/env.go
pkg/nuctl/command/run.go
pkg/nuctl/kubeconsumer.go
pkg/nuctl/runner/function.go
pkg/playground/resource/function.go
pkg/processor/webadmin/resource/eventsources.go

- fixed --nuclio-src-url with a reference (e.g. `--nuclio-src-url https://github.com/nuclio/nuclio.git#development`)
- can run function when it exists (nuctl and playground) - it'll be deleted
- node port is returned as part of function run response
- function state is returned properly when run from playground

nuctl run can auto-delete existing functions and more

---

pkg/nuctl/command/delete.go
pkg/nuctl/command/run.go
pkg/nuctl/command/update.go
pkg/nuctl/runner/function.go
pkg/nuctl/runner/types.go
pkg/playground/resource/function.go
pkg/playground/resource/tunnel.go
pkg/util/common/url.go

Playground accepts a request in the form of:
```
{
"name": "<name>",
"source_url": "<source>",
"registry": "<registry>",
"run_registry": "localhost:5000",
"data_bindings": {
"db0": {
"class": "v3io",
"url": "<url>"
}
}
}
```
And creates the proper data binding

Support data bindings in playground

---

pkg/playground/server.go
pkg/processor/eventsource/rabbitmq/eventsource.go

If the exchange does not exist, the rabbit MQ event source will declare it

RabbitMQ event source declares exchange

---

pkg/processor/eventsource/eventsource.go
pkg/processor/eventsource/generator/eventsource.go
pkg/processor/eventsource/http/eventsource.go
pkg/processor/eventsource/rabbitmq/eventsource.go
pkg/processor/eventsource/types.go
pkg/processor/runtime/golang/event_handler/demo.go
pkg/processor/runtime/golang/runtime.go
pkg/processor/runtime/runtime.go
pkg/processor/runtime/types.go
pkg/processor/statistics/eventsource.go
pkg/processor/statistics/gatherer.go
pkg/processor/statistics/metricpusher.go
pkg/processor/statistics/worker.go
pkg/processor/worker/worker.go
pkg/processor/worker/worker_test.go

1. Metrics gathering refactored such that metric specifics are held in "gatherers" of which there are currently two: one for event source and one for worker
2. Added support for function duration statistics - currently only golang
3. The # of events metric is now a counter, gathered at the event source level. Should catch any and all invocations and failures
4. Default prometheus URL is now `http://prometheus-prometheus-pushgateway:9091` (*shakes fist at helm*)

More metrics

---

pkg/processor/build/runtime/golang/test/golang_test.go
pkg/processor/build/runtime/python/test/python_test.go
pkg/processor/eventsource/http/test/suite/suite.go
pkg/processor/eventsource/rabbitmq/test/rabbitmq_test.go
pkg/processor/runtime/golang/test/golang_test.go
pkg/processor/runtime/python/test/python_test.go
pkg/processor/test/suite/suite.go
pkg/processor/worker/worker_test.go

`BuildAndRunFunction` and all its derivatives accepts build and run options. This allows callers to pass less fields when they are default and inject more fields (e.g. image name) when they are not.

More options in integration test helpers

---

Makefile
cmd/controller/app/controller_test.go
cmd/processor/app/processor.go
pkg/nuctl/command/execute.go
pkg/nuctl/command/get.go
pkg/nuctl/command/nuctl.go
pkg/nuctl/command/run_test.go
pkg/nuctl/executor/function.go
pkg/playground/resource/function.go
pkg/processor/build/runtime/golang/eventhandlerparser/parse_test.go
pkg/processor/eventsource/generator/eventsource.go
pkg/processor/eventsource/http/factory.go
pkg/processor/eventsource/kinesis/shard.go
pkg/processor/eventsource/poller/types.go
pkg/processor/eventsource/poller/v3ioitempoller/eventsource.go
pkg/processor/eventsource/rabbitmq/test/event_recorder_golang/event_recorder.go
pkg/processor/eventsource/rabbitmq/test/rabbitmq_test.go
pkg/processor/eventsource/registry.go
pkg/processor/runtime/registry.go
pkg/processor/webadmin/resource/eventsources.go
pkg/processor/worker/worker.go
pkg/restful/resource_test.go
pkg/util/cmdrunner/cmdrunner.go
pkg/util/common/url_test.go
pkg/util/renderer/renderer.go

Use `impi` (github.com/pavius/impi) to verify correctness of import order.

Fix import order, verify import order on "lint" rule

---

pkg/common/helper.go
pkg/dockerclient/dockerclient.go
pkg/nuctl/test/build_test.go
pkg/nuctl/test/deploy_test.go
pkg/nuctl/test/env/env.py
pkg/platform/local/platform.go
pkg/processor/eventsource/http/eventsource.go
pkg/processor/runtime/python/runtime.go

1. Properly inject environment variables to docker containers spun up by the local platform
2. Fix Python runtime to inject all environment variables into the spawned wrapper process
3. Revert a change introduced in #243 that broke tests and behavior when a panic occurred in Go handlers

Local platform properly supports environment variables

---

cmd/controller/app/controller.go
cmd/controller/app/controller_test.go
cmd/playground/Dockerfile
pkg/platform/kube/functioncr/function.go
pkg/platform/kube/functioncr/function_test.go
pkg/playground/fixtures/source.go
pkg/playground/resource/function.go
pkg/processor/build/runtime/golang/docker/onbuild/Dockerfile
pkg/processor/build/runtime/golang/docker/onbuild/build-processor.sh
pkg/processor/build/runtime/python/docker/processor-py/Dockerfile
pkg/processor/runtime/python/wrapper.py

1. Playground fixtures changed (echo, encrypt and rabbitmq)
2. Playground image reduced from 150MB to 75MB by pulling just docker client rather than docker
3. Go on build image reduced from 700MB to 250MB by using an alpine based image
4. Processor-py now based on alpine3.6 - fixes an issue where user-driven apk installs would erroneously fail due to "no space left on device". This is due to an apk issue fixed in 3.6
5. Function names can now include hyphens (versioned functions end with three hyphens: `func---0`)

More playground fixtures, smaller images and some goodies

---

pkg/playground/resource/tunnel.go

If user runs playground from localhost, replace localhost with docker bridge IP address (currently hardcoded to 172.17.0.1).

Temporarily support playground from localhost

---

pkg/platform/local/platform.go

On some systems (actually, one) it was observed that "localhost" resolve to an actual IP address. To prevent this, the local platform uses 127.0.0.1 as the address to localhost - rather than assuming "localhost" resolves to "127.0.0.1".

Local platform uses "127.0.0.1" instead of "localhost"

---

cmd/playground/static/assets/app.js

`source_url` used to be absolute so it was used as-is when trying to load the source code of the function.
Now it is relative (starting with a `/` sign) so if index.html is opened locally, the http://host:port needs to be prepended to it.

Fix source loading (now source_url is relative)

---

cmd/playground/static/assets/app.js

The playground UI would ask the playground service to fetch sources from `browser_address/sources/<function-name>` - e.g. `192.168.64.4:32050/sources/echo.go`. The problem is that minikube (and probably Virtualbox) do not have the routes in place to allow a container to access that URL. 
This works fine in Kubernetes on AWS given that `browser_address` is the elastic IP and the container can reach this just fine.

Fix playground when running in minikube

---

README.md

The image link currently used in `README.md` doesn't specify a branch, which results in "build failing" images showing up if the latest build (even that of a development branch) failed.

Display Travis CI build status for master branch

---

README.md
pkg/nuctl/command/deploy.go
pkg/nuctl/command/get.go
pkg/nuctl/command/update.go
pkg/platform/abstract/platform.go
pkg/platform/function.go
pkg/platform/kube/deployer.go
pkg/platform/kube/function.go
pkg/platform/kube/functioncr/types.go
pkg/platform/kube/functiondep/client.go
pkg/platform/local/function.go
pkg/platform/local/platform.go
pkg/platform/types.go
pkg/processor/build/runtime/golang/test/incrementor-with-function-config/function.yaml

1. Fixes #293 
2. Fixes a bug where kuberentes based platform did not actually apply the function configuration
3. Fixes `-o wide` in `nuctl get`

Allow path based HTTP routing to functions

---

cmd/playground/static/assets/.eslintrc.json
cmd/playground/static/assets/app.css
cmd/playground/static/assets/app.js

Fixes this:
Also in this PR:
Changing function expressions to function statements and change some order of code and rename some variables to reduce shadowing (eslint "no-shadow" rule)

Ellipsis + tooltips on overflow of key-value pairs

---

cmd/playground/static/assets/app.js
pkg/playground/resource/function.go

After deploying a function, it was no longer available due to incorrect handling of the source URL

Fixed playground source load issue under Kubernetes

---

Makefile
pkg/processor/build/builder.go
pkg/processor/build/runtime/golang/docker/onbuild/Dockerfile
pkg/processor/build/runtime/golang/factory.go
pkg/processor/build/runtime/golang/runtime.go
pkg/processor/build/runtime/python/docker/processor-py/Dockerfile
pkg/processor/build/runtime/python/factory.go
pkg/processor/build/runtime/python/runtime.go
pkg/processor/build/runtime/python/runtime_test.go
pkg/processor/build/runtime/python/test/python2/printer.py
pkg/processor/build/runtime/python/test/python_test.go
pkg/processor/build/runtime/runtime.go

- Users can specify `python:2.7` or `python:3.6` runtimes (`python` falls back to `python:3.6`)
- Users can specify `baseImageName` as either `jesse` or `alpine` for Python. `baseImageName` for Golang remains unrestricted
- Go functions are now compiled with Go 1.9

Python: support different base images, support Python 2. Bump Go to 1.9

---

cmd/playground/app/playground.go
cmd/playground/main.go
pkg/playground/resource/function.go
pkg/playground/server.go

Fixes #291 (no need for nuclio URL given that Go plugin is now used).
Running the playground as:
`docker run -p 8070:8070 -v /var/run/docker.sock:/var/run/docker.sock -v /tmp:/tmp -e NUCLIO_PLAYGROUND_NO_PULL_BASE_IMAGES=true nuclio/playground:0.0.1-amd64`
will not pull images - will only uses local docker images.

conditionally pull base images in playground

---

.gitignore
Makefile
cmd/playground/Dockerfile
cmd/processor/Dockerfile
pkg/processor/build/runtime/golang/docker/onbuild/Dockerfile
pkg/processor/build/runtime/python/docker/processor-py/Dockerfile

Controller, playground and processor-py build appropriate binaries in multi-stage builds rather than via make.

All docker images rely on binaries built in docker, rather than locally

---

pkg/nuctl/command/get.go

@pavius After merging, we need to recreate **[nuctl_get.md](https://github.com/nuclio/nuclio/blob/development/docs/nuctl/nuctl_get.md)** and **[nuctl_get_function.md](https://github.com/nuclio/nuclio/blob/development/docs/nuctl/nuctl_get_function.md)**.

nuclio CLI: minor doc-review editing

---

README.md
docs/architecture.md
docs/k8s/function-ingress.md
docs/k8s/getting-started.md
vendor/k8s.io/apimachinery/README.md

@pavius Note that I place each sentence on a separate line (except for short sentences that can fit within 80 chars), to simplify future diffs (minimize the need for scrolling). I should have probably done this in a separate dedicated PR to simplify the current diffs.
Please verify specifically the editing that I did in relation to code and console snippets (mostly placeholder references and splitting output from commands).

[doc review] README, arch, and k8s getting-started & function-ingress + minor fixes in k8s.io/apimachinery README

---

cmd/playground/static/assets/app.css
cmd/playground/static/assets/app.js
cmd/playground/static/index.html

- Disable invoke pane on creating a new function
- Collapse/expand for panes in "Code" tab works properly
- Web-page title changed to: "playground | nuclio"
- Function list in switcher pop-up has more height now
- "Create" button renamed to "New", creation pop-up added
- Move "Save" next to functions list/switcher
- New "Data bindings" UI/UX
- Toggle ellipsis/wrap-around on click of key/value
- Condensed top bar with larger font size
- Bind configuration fields that were not bound on loading function
- Minor CSS cleanup & improvements

"New" button, collapse/expand

---

hack/examples/README.md
hack/examples/python/sentiments/sentiments.py
hack/examples/shell/img-convert/img-convert.sh
pkg/functionconfig/types.go
pkg/nuctl/command/deploy.go
pkg/playground/fixtures/source.go
pkg/playground/resource/function.go
pkg/processor/build/runtime/shell/test/reverser/reverser.sh
pkg/processor/build/runtime/shell/test/shell_test.go
pkg/processor/runtime/python/wrapper.py
pkg/processor/runtime/shell/runtime.go

1. Function configuration supports "RuntimeAttributes" for runtime specific attributes (nuctl receives this as `--runtime-attrs`)
2. Shell runtime can call any binary in the image
3. Added integration tests for shell, missing from previous PR
4. Added a shell example
5. Playground has most examples

Shell runtime can run binaries, added examples to playground

---

docs/k8s/install/linux.md

[Doc review] K8s kubaedm Linux install: remove TODO comment to add ref to conroller doc

---

Makefile
pkg/nuctl/test/deploy_test.go
pkg/processor/build/runtime/pypy/docker/Dockerfile.handler-pypy

1. PyPy assumed base image was tagged as "latest"
2. Deploy integration tests did not work on k8s, fixed

Fix pypy base image

---

pkg/common/helper.go
pkg/functionconfig/types.go
pkg/nuctl/command/build.go
pkg/processor/build/builder.go
pkg/processor/build/runtime/golang/eventhandlerparser/parse_test.go
pkg/processor/test/suite/suite.go

Fixes #405 
All staging directories created in builder are now under a single "temp directory", and cleaned up at the end of Build()

Build Temp Directory Cleanup

---

pkg/platform/local/platform.go
pkg/processor/build/runtime/test/suite/suite.go

If function configuration contains Spec.HttpPort, the local platform will use this port. If it's not set (or set to zero), the previous behavior will apply and a free port will be generated.

Local platform respects configured HTTP port

---

pkg/processor/runtime/python/test/python_test.go
pkg/processor/runtime/python/wrapper.py

Returning context.Response under Python 2.7 would result in an internal errior

Fix return response for Python 2.7

---

cmd/controller/app/controller.go
cmd/controller/main.go
cmd/processor/app/processor.go
cmd/processor/main.go
pkg/common/helper.go
pkg/common/map.go
pkg/common/map_test.go
pkg/functionconfig/types.go
pkg/platform/kube/functiondep/client.go
pkg/platform/local/platform.go
pkg/platformconfig/platformconfig.go
pkg/platformconfig/platformconfig_test.go
pkg/platformconfig/reader.go
pkg/platformconfig/types.go
pkg/processor/build/template.go
pkg/processor/runtime/shell/test/shell_test.go
pkg/processor/statistics/metricpusher.go

1. On deploy, the processor attempts to open /etc/nuclio/configs/platform/platform.yaml`. This has the following format:
```
webAdmin:
enabled: true
listenAddress: :8081
logger:
sinks:
stdout:
driver: stdout
staging-es:
driver: elasticsearch
url: http://10.0.0.1:9200
prod-es:
driver: elasticsearch
url: http://20.0.1:9200
attributes:
dontCrash: true
system:
- level: debug
sink: prod-es
- level: info
sink: stdout
functions:
- level: info
sink: stdout
metrics:
sinks:
mypush:
driver: prometheusPush
url: 10.0.0.1:30
attributes:
interval: 10s
system:
- mypush
functions:
- mypush
```
If the file doesn't exist, sane defaults are loaded (logs to stdout, metrics and webadmin disabled).
At the moment, only `metrics` is respected by the processor though the `platformconfig` module handles all aspects …

Functions receive platform config - respect only metrics

---

cmd/playground/app/playground.go
cmd/playground/main.go
pkg/dockercreds/dockercred.go
pkg/dockercreds/dockercreds.go
pkg/dockercreds/dockercreds_test.go
pkg/playground/server.go

Fixes #494.
1. Interval is by default 12 hours
2. If file contains "interval" (in the format of `<name>---<url>---<interval>.json`) it overrides default
3. Playground can receive the default refresh interval either in args (`--creds-refresh-interval`) or environment variable (`NUCLIO_PLAYGROUND_CREDS_REFRESH_INTERVAL`)

Playground refreshes docker credentials

---

cmd/playground/static/assets/app.js

Keyboard navigation with up/down arrow keys broke when filtering the function list

Playground: fix issue with keyboard nav on filtered function list

---

cmd/playground/static/assets/app.js

On function list, when entering a name in the filter box and it
already exists, it should not display the "Create new" option at the
bottom of the list.

Playground: fix suggesting to create new function with existing name

---

cmd/playground/static/assets/app.js
pkg/nuctl/command/invoke.go
pkg/platform/abstract/invoker.go
pkg/platform/abstract/platform.go
pkg/platform/kube/function.go
pkg/platform/platform.go
pkg/platform/types.go
pkg/playground/resource/invocation.go

Fixes #495.
1. Platform's `InvokeFunction` no longer outputs the result to an `io.Writer`, but returns a structured `InvokeResult`
2. Kubernetes platform supports invoke via domain name - this resolves the function cluster IP through `<function name>.<function namespace>.svc.cluster.local`
3. Playground uses a new resource, `/invocations`, to invoke functions. This resource expects the function name, namespace and path as headers (`x-nuclio-function-name`, `x-nuclio-function-namespace` and ``x-nuclio-function-path`) and utilizes the same mechanism as `nuctl` to invoke functions (implemented as part of the platform) - get them and then invoke them. Utilizes the new invocation mode introduced in (1)

Playground uses platform invoker, kube invoker uses DNS

---

cmd/playground/app/playground.go
cmd/processor/app/processor.go
pkg/platformconfig/platformconfig.go
pkg/platformconfig/reader.go
pkg/platformconfig/types.go
pkg/playground/server.go
pkg/processor/webadmin/resource/triggers.go
pkg/processor/webadmin/server.go
pkg/restful/server.go

- `platformconfig.Configuration.WebAdmin`'s struct type was renamed from `WebAdmin` to `WebServer` (field name left as-is), now fed to `restful.Server`'s constructor instead of just `webadmin.Server`'s
- The `WebServer` configuration struct is used for both the playground's and the processor's web interfaces
- The processor's web interface can be enabled from platform configuration and currently serves `GET /health` and `GET /triggers`
- Added log message if the web interface is disabled
- Completed rename of `eventsource.go` resource to `triggers.go`

Re-enable processor web interface

---

cmd/playground/main.go
pkg/dockercreds/dockercred.go
pkg/dockercreds/dockercreds.go
pkg/dockercreds/dockercreds_test.go
pkg/playground/server.go
pkg/processor/build/builder_test.go

Introduces two usability features:
1. Users can provide a secret in the form created by `kubectl create secret docker-registry` rather than the legacy format (which is still supported for backwards compatibility). Fixes #523
2. If users do not pass a docker registry URL (previously done via configmaps in k8s), the first URL from the secrets is used

Support docker registry secret

---

.travis.yml
pkg/processor/databinding/eventhub/databinding.go
pkg/processor/trigger/eventhubs/partition.go

1. Fail build on push failures (previously they were silently ignored)
2. Tag playground:stable when versions are released, push

Travis configuration improvements + deprecation fix

---

pkg/cmdrunner/shellrunner_test.go
pkg/dockerclient/shell_test.go
pkg/nuctl/command/build.go
pkg/nuctl/command/deploy.go
pkg/nuctl/test/build_test.go
pkg/platform/abstract/platform.go
pkg/processor/build/builder.go
pkg/processor/build/builder_test.go
pkg/processor/build/runtime/test/suite/suite.go
pkg/processor/test/suite/suite.go
test/_functions/common/json-parser-with-function-config/golang/function.yaml
test/_functions/common/json-parser-with-function-config/nodejs/function.yaml
test/_functions/common/json-parser-with-function-config/python/function.yaml
test/_functions/common/json-parser-with-function-config/shell/function.yaml
test/_functions/common/json-parser-with-inline-function-config/shell/parser.sh

1. Path (-p) must be passed in nuctl build
2. Function configuration path (-f) supported
3. Source directory (--nuclio-src-dir and --nuclio-src-url) removed. Have been unused for a while
Fixes #567 #566 #565

nuctl has better support for a few flags

---

pkg/processor/runtime/pypy/interface.go
pkg/processor/runtime/pypy/interface.h
pkg/processor/runtime/pypy/nuclio_interface.py

For some reason the API to pypy was exposing `eventVersion` which was always 1 and doesn't exist in the Go version of the API.

remove non existing eventVersion API

---

.travis.yml

Until the nuclio CI is in place, we can't have a 40 minute test running in travis per commit unfortunately.

Travis should only run unit tests

---

pkg/functionconfig/types.go
pkg/nuctl/command/build.go
pkg/processor/build/builder.go
pkg/processor/build/builder_test.go
pkg/processor/build/runtime/test/suite/suite.go
pkg/processor/build/test/build_test.go

FunctionSourceCode overrides the path to the handler file/directory, and instead holds the handler's code as a string
As part of the build process the function source code is written to <temp dir>/source/handler.<runtime-specific extension>
Fixes #562

Add FunctionSourceCode to function build config

---

cmd/controller/app/controller.go
cmd/controller/app/controller_test.go
pkg/dockerclient/shell.go
pkg/dockerclient/types.go
pkg/errors/errors.go
pkg/functionconfig/reader_test.go
pkg/functionconfig/types.go
pkg/nuctl/command/build.go
pkg/nuctl/command/deploy.go
pkg/platform/abstract/platform.go
pkg/platform/kube/deployer.go
pkg/platform/kube/functiondep/client.go
pkg/platform/local/platform.go
pkg/platform/types.go
pkg/playground/resource/function.go
pkg/processor/build/builder.go
pkg/processor/build/builder_test.go
pkg/processor/build/runtime/golang/runtime.go
pkg/processor/build/runtime/nodejs/runtime.go
pkg/processor/build/runtime/pypy/runtime.go
pkg/processor/build/runtime/python/runtime.go
pkg/processor/build/runtime/python/runtime_test.go
pkg/processor/build/runtime/runtime.go
pkg/processor/build/runtime/shell/runtime.go
pkg/processor/build/runtime/test/suite/suite.go
pkg/processor/build/template.go
pkg/processor/build/test/build_test.go
pkg/processor/test/suite/suite.go

Also:
1. Renamed `ImageName` to just `Image` in the code, to be canonical and consistent
2. Controller will write the full stack when it fails to deploy a function to the CRD message, making it available to the deployer

If --run-image is passed to deploy, don't prepend run-registry

---

pkg/platform/local/platform.go

Using the function name as container name in docker.

Naming container as namespace + function

---

cmd/dashboard/README.md
cmd/dashboard/app/dashboard.go
cmd/dashboard/main.go
hack/aks/resources/nuclio.yaml
hack/gke/resources/nuclio.yaml
hack/k8s/resources/nuclio-rbac.yaml
hack/k8s/resources/nuclio.yaml
pkg/dashboard/resource/externalipaddresses.go
pkg/dashboard/resource/function.go
pkg/dashboard/resource/project.go
pkg/dashboard/resource/version.go
pkg/dashboard/server.go
pkg/dashboard/test/server_test.go
pkg/platform/abstract/platform.go
pkg/platform/function.go
pkg/platform/kube/function.go
pkg/platform/kube/platform.go
pkg/platform/local/function.go
pkg/platform/local/platform.go
pkg/platform/platform.go
pkg/restful/server.go

1. Dashboard supports `/external_ip_addresses` - returns IP addresses that can be used to invoke functions
2. Dashboard supports `/versions` - returns versions of components (dashboard only for now)
3. Platform uses one of the supplied external IP addresses to invoke functions

Support setting external IP in dashboard

---

cmd/dashboard/README.md
pkg/dashboard/functiontemplates/filter.go
pkg/dashboard/functiontemplates/functiontemplates.go
pkg/dashboard/functiontemplates/repository.go
pkg/dashboard/functiontemplates/repository_test.go
pkg/dashboard/functiontemplates/types.go
pkg/dashboard/resource/function_template.go
pkg/dockerclient/shell.go
pkg/functionconfig/handler.go
pkg/processor/build/builder.go
pkg/processor/build/builder_test.go
pkg/processor/build/runtime/test/suite/suite.go
pkg/processor/build/test/build_test.go
pkg/processor/runtime/golang/handler.go
pkg/processor/runtime/nodejs/runtime.go
pkg/processor/runtime/shell/runtime.go

1. Dashboard supports function templates (only one for now)
2. FunctionSourceCode must be provided in base64 encoding
3. When FunctionSourceCode is provided, the generated file name is taken from the handler (e.g. if handler is `foo:my_handler` and the runtime is a `python` variant, the file name will be `foo.py`
4. Minor code cleanup around builder to reduce duplication in the face of adding runtimes

Support dashboard function templates

---

pkg/dockerclient/shell.go
pkg/dockerclient/types.go
pkg/platform/local/platform.go

Following a recent PR that set the container name to `namespace-name` in the local platform, if a function failed to deploy subsequent deploys would fail. This is because the local platform looked for existing functions via running containers with given labels. 
This PR changes the search for existing functions to be based on the container name.

Delete existing functions by name in local platform

---

cmd/playground/static/assets/app.js
docs/reference/triggers/http.md
pkg/dashboard/test/server_test.go
pkg/functionconfig/types.go
pkg/nuctl/command/deploy.go
pkg/nuctl/command/get.go
pkg/platform/function.go
pkg/platform/kube/controller/function.go
pkg/platform/kube/function.go
pkg/platform/kube/functionres/lazy.go
pkg/platform/kube/getter.go
pkg/platform/kube/platform.go
pkg/platform/local/function.go
pkg/platform/local/platform.go
pkg/playground/resource/function.go
pkg/processor/build/runtime/test/suite/suite.go
pkg/processor/test/suite/suite.go

This PR eliminates `spec.httpPort` in favor of `status.httpPort`. This is more than a field rename:
1. In Kubernetes, the function CRD will contain the deployed port - no need to look up the service. This makes the port gettable via the dashboard, which is what triggered this effort
2. Fixes `nuctl get` not displaying NodePort when running with Kubernetes
3. HTTP trigger contains a new `port` attribute
4. All port persistency behavior retained. If function is redeployed both in local and k8s platforms, the previous port is used except if the new function has an HTTP trigger configured with `port`

Change the way HTTP port is conveyed

---

Makefile

Remove duplication in lint target

---

docs/reference/triggers/http.md
pkg/functionconfig/types.go
pkg/platform/kube/functionres/lazy.go
pkg/platform/kube/functionres/lazy_test.go

This PR introduces the concept of `defaultIngressPattern`, configurable as part of the HTTP trigger. Prior to this change, a `/function-name/function-version` ingress rule would always be created. In some cases, users do not want to expose functions via ingresses or perhaps control this pattern. This is possible with this PR. The user can:
1. Do nothing, and behavior will be backwards compatible
2. Specify an empty string for `defaultIngressPattern` - in which case no ingress rule will be created
3. Specify a pattern for `defaultIngressPattern` to control the default ingress rule (more on this in the changed docs)
In addition, a few bugs were fixed in this area:
1. Ingress rules were incorrectly created since 0.2.8. They would be in the form of `/function-name/` rather than …

User can control the default ingress rule

---

Makefile

This allows running a single dockerized test.
Example:
```bash
make test NUCLIO_TEST_NAME='./pkg/processor/trigger/partitioned/kafka/test/...'
```

Use NUCLIO_TEST_NAME to pass tests to dockerized tests

---

Makefile

Revert "Use NUCLIO_TEST_NAME to pass tests to dockerized tests"

---

pkg/processor/build/runtime/shell/test/shell_test.go
pkg/processor/cloudevent/binary.go
pkg/processor/cloudevent/binary_test.go
pkg/processor/cloudevent/mockevent.go
pkg/processor/cloudevent/structured.go
pkg/processor/cloudevent/structured_test.go
pkg/processor/cloudevent/types.go
pkg/processor/cloudevent/wrappedevent.go
pkg/processor/runtime/dotnetcore/test/dotnetcore_test.go
pkg/processor/runtime/golang/builtin.go
pkg/processor/runtime/golang/test/golang_test.go
pkg/processor/runtime/java/test/java_test.go
pkg/processor/runtime/nodejs/test/nodejs_test.go
pkg/processor/runtime/pypy/interface.go
pkg/processor/runtime/pypy/test/pypy_test.go
pkg/processor/runtime/python/test/python_test.go
pkg/processor/runtime/rpc/encode.go
pkg/processor/runtime/rpc/encode_test.go
pkg/processor/runtime/shell/test/shell_test.go
pkg/processor/test/suite/suite.go
pkg/processor/trigger/cron/event.go
pkg/processor/trigger/http/event.go
pkg/processor/trigger/http/test/suite/suite.go
pkg/processor/trigger/trigger.go
pkg/processor/worker/worker.go
test/_functions/common/event-returner/golang/eventreturner.go

Logic is currently:
```
if event.headers["Content-Type"].startsWith("application/cloudevents"):
event = StructuredCloudEvent(event.body)
else if "CE-CloudEventsVersion" in event.headers:
event = BinaryCloudEvent(event)
else:
event = event
```
Allows posting CloudEvents (both structured and binary) such that the function will receive an `event` that returns the fields specified by the cloud event.

Support for CloudEvents 0.1 spec (structured and binary)

---

pkg/dashboard/ui/package.json
pkg/dockerclient/dockerclient.go
pkg/dockerclient/mock.go
pkg/dockerclient/shell.go
pkg/dockerclient/types.go
pkg/platform/local/platform.go
pkg/platform/local/store.go

1. Faster local platform storage access: Rather than run a new container each time in order to read resources like projects, function events, etc - the local platform will try to exec the command to read in a container with a known name. If this fails due to container not existing, it will run a container that pauses for 6 hours and re-run the exec. This means that subsequent reads are much faster (around 150ms vs 1200ms)
2. In the local platform, functions whose containers came up but failed to reach operational are now returned as part of get functions

Faster local platform storage access

---

pkg/cmdrunner/cmdrunner.go
pkg/dockerclient/shell.go
pkg/dockerclient/types.go
pkg/functionconfig/types.go
pkg/nuctl/test/function_test.go
pkg/nuctl/test/project_test.go
pkg/platform/kube/platform.go
pkg/platform/local/function.go
pkg/platform/local/platform.go
pkg/platform/local/store.go
pkg/processor/status/types.go

1. Rather than using information from docker containers to retreive which functions exist in the local platform, the store is used (identical to projects, function events, etc). This allows GETing functions which are currently being built and also allows communicating build errors
2. Store refactored
3. Store uses `exec` rather than run for all commands - faster deleting, writing
4. Store uses base64 encoded contents rather than string - can store pretty much anything without worrying about escaping and such

Local platform uses store for functions

---

.dockerignore
pkg/platform/test/platform_test.go
pkg/processor/build/runtime/golang/runtime.go
pkg/processor/build/runtime/java/docker/Dockerfile.handler-builder
pkg/processor/build/runtime/java/docker/Dockerfile.user-jar-builder

1. Golang build used a temporary image to build the handler whose name was not keyed by namespace/name. Concurrent builds would trip over each other
2. Replaced curl with wget in Java builds due to apt hell (broken packages)
3. Added .dockerignore so that building images ignores UI intermediates, if they exist
4. Added platform integration test, currently does nothing but will serve as a base for the integration test reorg

Fix Golang concurrent deploy + other minor fixes

---

docs/reference/triggers/http.md
pkg/platform/kube/functionres/lazy.go
pkg/platform/kube/functionres/lazy_test.go

1. Prior to this PR, by default ingresses were created for functions. This is a security concern as most people might not be aware that their functions get exposed
2. The concept of `defaultIngressPattern`, which was an attempt to allow some users to address (1) was not a clean enough interface and was removed
3. Paths in ingresses can now contain formatting

No ingresses by default, remove defaultIngress

---

pkg/nuctl/command/deploy.go
pkg/processor/build/test/build_test.go
pkg/processor/runtime/python/wrapper.py

1. Breaking change: `nuctl --env` is now a repetitive flag rather than command delimited (e.g. `nuctl --env a=b --env c=d` rather than `nuctl --env `a=b,c=d`). The reason is that it was quite difficult (impossible?) to receive values with `=` in them. This is quite common seeing how secrets can be base64 encoded
2. Python3 supports `context.platform.call_function` a small sign of things to come
3. If Python receives `application/json` in content type, it will try to `loads` the body
4. User can now pass dictionaries in `context.Response` for Python
5. If user implements `init_context`, it will be called like in Golang (missing tests)

Python runtime features

---

.travis.yml
Makefile
docs/reference/function-configuration/function-configuration-reference.md
hack/minikube/scripts/push_images.py
pkg/functionconfig/types.go
pkg/nuctl/command/build.go
pkg/processor/build/runtime/dotnetcore/docker/onbuild/Dockerfile
pkg/processor/build/runtime/dotnetcore/runtime.go
pkg/processor/build/runtime/golang/runtime.go
pkg/processor/build/runtime/java/docker/onbuild/Dockerfile
pkg/processor/build/runtime/java/runtime.go
pkg/processor/build/runtime/nodejs/docker/onbuild/Dockerfile
pkg/processor/build/runtime/nodejs/runtime.go
pkg/processor/build/runtime/python/docker/onbuild/Dockerfile
pkg/processor/build/runtime/python/runtime.go
pkg/processor/build/runtime/runtime.go
pkg/processor/build/runtime/runtime_test.go
pkg/processor/build/runtime/shell/runtime.go

It is now possible to specify which onbuild image the processor image will be built from. Left blank, it shall use the per runtime default (e.g. `nuclio/handler-builder-golang-onbuild:${NUCLIO_LABEL}-${NUCLIO_ARCH}`). 
This allows users to specify onbuilds which reside in private registries. It is possible to format with `{{ .Label }}` and `{{ .Arch }}`. For example:
`privateregistry.mydomain.com:20202/somerepo/handler-builder-golang-onbuild:{{ .Label }}-{{ .Arch }}`

Function configuration allows specifying onbuild image

---

docs/tasks/configuring-a-platform.md
pkg/functionconfig/types.go
pkg/nuctl/command/build.go
pkg/nuctl/command/deploy.go
pkg/processor/build/builder.go
pkg/processor/build/runtime/golang/docker/onbuild/Dockerfile
pkg/processor/build/runtime/golang/docker/onbuild/Dockerfile.alpine
pkg/processor/build/runtime/golang/docker/onbuild/build-handler.sh
pkg/processor/build/runtime/java/docker/onbuild/Dockerfile
pkg/processor/build/runtime/java/docker/onbuild/build-handler.sh
pkg/processor/build/runtime/java/runtime.go
pkg/processor/build/runtime/java/test/java_test.go
test/_functions/golang/slugger/slugger.go

1. Supported `spec.build.offline` to indicate that this build should not assume internet connectivity. Currently used by Golang (which skips `go get`) and Java (which runs `gradle --offline`)
2. Supported `spec.build.runtimeAttributes`, used by `Java` to specify `repositories`. This replaces the default `mavenCentral()` if passed
3. Fixed Java offline build by employing `--build-cache`
4. Java onbuild image size reduced

More offline support related features

---

pkg/dashboard/ui/package.json

- nuclio: Fixed visual bugs in breadcrumbs
- nuclio: Triggers: Port and host in ingresses are not mandatory
- nuclio: Refactor function export logic
- Number input: fix validation issues

Update dashboard-controls version to 0.0.53

---

pkg/dashboard/ui/package.json

- Use different font in "Build commands" field
- Fix error on exporting function on Mozilla Firefox

Update dashboard-controls version to 0.0.54

---

cmd/dashboard/app/dashboard.go
cmd/dashboard/main.go
pkg/dashboard/resource/function.go
pkg/dashboard/resource/functionevent.go
pkg/dashboard/resource/invocation.go
pkg/dashboard/resource/project.go
pkg/dashboard/resource/resource.go
pkg/dashboard/server.go
pkg/dashboard/test/server_test.go
pkg/dockercreds/dockercreds.go
pkg/dockercreds/dockercreds_test.go

1. If dashboard does not receive the namespace in the request, rather than returning 400 it will try to use the default namespace. Currently the default namespace is automatically detected at startup as the namespace the dashboard is in (k8s). In local platform, there is no default namespace
2. Removed a logged warning when loading registry credentials

Dashboard backend supports default namespace

---

.travis.yml
cmd/dashboard/app/dashboard.go
cmd/dashboard/main.go
pkg/dashboard/test/server_test.go
pkg/platform/abstract/platform.go
pkg/platform/kube/platform.go
pkg/platform/local/platform.go
pkg/platform/platform.go

1. Local platform explicitly uses "nuclio" as default namespace
2. Dashboard tagged as stable on release

Local platform sets default namespace

---

pkg/dashboard/ui/package.json

Enhancements:
- Dependencies in configuration tab should only be display for Java
- Runtime attributes should not display "Runtime" read-only field
- Revert to regular font in "Build Commands" and "Dependencies"
- Add "URL" label above the input to Archive / Jar
- Change "Image" to "URL" above the textbox of Image
- Make Image / Archive / Jar textbox field smaller
Issues fixed:
- Code editor is empty on selecting Archive
- Runtime Attributes improperly encoded (missing `repositories`)
- Deploy error not displayed when the initial POST request fails

Update dashboard-controls to version 0.0.56

---

pkg/dashboard/ui/package.json

- URL field for Jar/Archive/Image is larger (Code tab)
**Issued fixed**
- Code Entry Type not initializing according to `spec.build.codeEntryType` (Code Tab)

Update dashboard-controls to version 0.0.57

---

pkg/dashboard/ui/build.config.js
pkg/dashboard/ui/gulpfile.js
pkg/dashboard/ui/package.json
pkg/dashboard/ui/src/app/app.controller.js

- Make either "Interval" or "Schedule" required, not both (for cron triggers)
- "Namespace" field is not required anymore
- Capitalize "Nuclio" in web page's title (seen on the browser's tab)
- Better handle monaco dependency
- Can't vertically scroll Status tab (annoys when deploy panel is open)
- Split "URL" and "Container ID" by last slash of `spec.dataBinding.(name).url`

UI: Update dashboard-controls version to 0.0.60 + More

---

pkg/dashboard/ui/package.json

- Slashes stripped from URL of v3io data binding

UI: Update dashboard-controls version to 0.0.61

---

pkg/dashboard/ui/package.json
pkg/dashboard/ui/src/app/shared/services/nuclio-event-data.servie.js

- Preparation to integration of Nuclio dashboard in Iguazio dashboard.
- Path was not handled right for function events and invocations.

Update dashboard-controls version to 0.1.2 + Fix to Path

---

pkg/dashboard/ui/gulpfile.js
pkg/dashboard/ui/package.json

Depends on: https://github.com/iguazio/dashboard-controls/pull/197
Also avoids some warning during build.

UI: Update dashboard-controls version to 0.1.5

---

cmd/dashboard/README.md
pkg/dashboard/resource/function.go
pkg/dashboard/resource/functionevent.go
pkg/dashboard/resource/invocation.go
pkg/dashboard/resource/namespaces.go
pkg/dashboard/resource/project.go
pkg/dashboard/test/server_test.go
pkg/platform/errors.go
pkg/platform/kube/platform.go
pkg/platform/local/platform.go
pkg/platform/local/store.go
pkg/platform/platform.go
pkg/processor/build/builder.go
pkg/processor/runtime/ruby/test/ruby_test.go
pkg/restful/resource.go

1. Update function event / project returns 204 rather than 202
2. Error messages no longer indicate namespace is mandated
3. Dashboard supports /api/namespaces - returns a list of namespaces if dashboard is capable of retreiving this
4. Deleting project with functions returns 409 rather than 500
5. Performing actions that return error (e.g. updating a project without specifying name) sets content-type to application/json (rather than text/plain)
6. Deleting a non-existing resource (e.g. function / project) will return 404

Various dashboard HTTP REST API / doc fixes

---

pkg/dashboard/ui/package.json

- Remove "Num Container Workers" field from v3io-stream trigger
- Add "Num Workers" to v3io data binding
- Implement "Test" pane
- Change URL and page title from "trigger" to "triggers"
**Fixed issues**
- Broken screen on nav to non-existing project

Update dashboard-controls version to 0.1.6

---

pkg/dashboard/ui/package.json
pkg/dashboard/ui/src/app/shared/services/nuclio-event-data.service.js

Depends on https://github.com/iguazio/dashboard-controls/pull/207
**Improvements**
- Send `x-nuclio-log-level` header on function invocation to get `x-nuclio-logs` header on response.
- Specific error message when attempting to delete a non-empty project.
- Function deletion not working in functions list after one function is deleted.
- Can't create new functions.

UI: Update dashboard-controls version to 0.1.8 + more

---

docs/reference/function-configuration/function-configuration-reference.md
pkg/functionconfig/types.go
pkg/processor/test/workerwait/suite_test.go
pkg/processor/trigger/http/test/suite/suite.go
pkg/processor/trigger/http/trigger.go
pkg/processor/worker/allocator.go
test/_functions/common/sleeper/golang/sleeper.go

Before this PR, if an event arrived at a trigger and no worker was available to handle it - the trigger would receive and return an error (e.g. 503 in HTTP). This PR introduces a new trigger configuration with a snappy name: `workerAvailabilityTimeoutMilliseconds` that allows specifying a timeout.
If this value is left unset or set to 0 - the behavior of the trigger is unchanged (including no performance hit). If this value is set, the trigger will wait for a worker to become available for this duration of time (with a certain amount of performance hit - to be determined by benchmarking).

Allow triggers to wait for an available worker rather than return error immediately

---

pkg/processor/build/runtime/golang/docker/onbuild/Dockerfile
pkg/processor/build/runtime/golang/docker/onbuild/Dockerfile.alpine
pkg/processor/build/runtime/golang/docker/onbuild/build-handler.sh
pkg/processor/runtime/runtime.go

1. User should be able to configure what was previously "github.com/nuclio/handler" - otherwise local imports won't work
2. User should be able to know how the handler during runtime to route `InitContext` to the proper function

Allow for multiple golang functions in a single image

---

cmd/processor/app/processor.go
pkg/functionconfig/types.go
pkg/processor/runtime/runtime.go
pkg/processor/trigger/cron/factory.go
pkg/processor/trigger/factory.go
pkg/processor/trigger/http/factory.go
pkg/processor/trigger/kinesis/factory.go
pkg/processor/trigger/nats/factory.go
pkg/processor/trigger/partitioned/eventhub/factory.go
pkg/processor/trigger/partitioned/kafka/factory.go
pkg/processor/trigger/partitioned/v3io/factory.go
pkg/processor/trigger/poller/v3ioitempoller/factory.go
pkg/processor/trigger/rabbitmq/factory.go
pkg/processor/trigger/registry.go

Allows different triggers to share their worker pool. This allows re-using context state across different triggers (e.g. cron and http calling the same stateful function) and reducing the number of workers (e.g. two HTTP triggers for two different ports)
Currently only for cron and HTTP.

Experimental: Shared workers

---

pkg/platform/kube/platform.go

Update of projects and function events on k8s didn't worked since it expected a `metadata.resourceVersion` to be present.
Providing it the needed metadata by first doing Get on the requested function event or project

Fix update of projects and function events in k8s platform

---

pkg/platform/kube/functionres/lazy.go

Some triggers (e.g. RabbitMQ) use the runtime.Configuration metadata passed to the Start() method to generate unique names for things such as worker queues. Currently, this is not included in the ConfigMap used to provide the metadata to processors running on Kubernetes. This PR updates the ConfigMap generation code to include all relevant metadata.
Thanks to @pavius for basically all of this :-)

Fix: Include function metadata in the generated processor ConfigMap for k8s deployments

---

cmd/dashboard/app/dashboard.go
pkg/dashboard/test/server_test.go
pkg/platform/kube/platform.go
pkg/platform/local/platform.go
pkg/platform/platform.go
pkg/processor/test/readinesstimeout/suite_test.go

A feature in 0.5.8 (per function readinessTimeout) broke the deploy timeout for local platforms - unless the timeout was specified, the deploy would never fail. 
This fixes that regression (defaulting to the usual 30 seconds) and adds two integration tests to enforce it.

fix local deployment timeout

---

pkg/dashboard/resource/namespaces.go

The error returned was wrapped with standard error and returned 500 instead 403

Fix - for forbidden users, getting namespaces return 403

---

hack/k8s/helm/nuclio/README.md
pkg/dashboard/resource/invocation.go
pkg/dashboard/test/server_test.go
pkg/platform/abstract/invoker.go
pkg/platform/kube/function.go

Prior to this change, when a function invocation request was received at the dashboard it would resolve the function URL first through a configured external IP address and then through the node internal / external IP (queries k8s nodes).
This PR adds an additional step where if none of the above are configured, it will try to use the internal k8s DNS. 
In addition to the above, if there are errors in the process they will be logged.

Change the way invoke happens in dashboard (k8s)

---

cmd/dashboard/app/dashboard.go
cmd/dashboard/main.go
hack/aks/resources/nuclio.yaml
hack/gke/resources/nuclio.yaml
hack/k8s/helm/nuclio/Chart.yaml
hack/k8s/helm/nuclio/templates/deployment/controller.yaml
hack/k8s/helm/nuclio/templates/deployment/dashboard.yaml
hack/k8s/helm/nuclio/values.yaml
hack/k8s/resources/nuclio.yaml
pkg/dashboard/resource/function.go
pkg/dashboard/server.go
pkg/dashboard/test/server_test.go

1. If dashboard is run with `NUCLIO_DASHBOARD_OFFLINE` set to true, it will set the `Spec.Build.Offline` and `Spec.Build.NoPullBaseImages` for all builds it receives
2. `offline` stanza added to helm chart

Dashboard accepts "build.offline" parameter as environment variable

---

pkg/processor/trigger/test/eventrecorder.go

Before:
```
Error:      	Should be true
FAIL
```
After:
```
Error:      	Not equal: 
expected: []string{"myTopic-0", "myTopic-1", "myTopic-2"}
actual: []string{"myTopic-0", "myTopic-1", "myTopic-2", "this-shouldn't-be-here"}
Diff:
--- Expected
+++ Actual
@@ -1,5 +1,6 @@
-([]string) (len=3) {
+([]string) (len=4) {
(string) (len=9) "myTopic-0",
(string) (len=9) "myTopic-1",
- (string) (len=9) "myTopic-2"
+ (string) (len=9) "myTopic-2",
+ (string) (len=22) "this-shouldn't-be-here"
}
FAIL
```

Better test failure message.

---

cmd/processor/app/processor.go
hack/k8s/helm/nuclio/templates/_helpers.tpl
hack/k8s/helm/nuclio/templates/configmap/platform.yaml
hack/k8s/helm/nuclio/values.yaml
pkg/platform/kube/functionres/lazy.go
pkg/processor/metricsink/appinsights/factory.go
pkg/processor/metricsink/appinsights/metricsink.go
pkg/processor/metricsink/prometheus/pull/factory.go
pkg/processor/metricsink/prometheus/pull/metricsink.go
pkg/processor/metricsink/prometheus/pull/types.go
pkg/processor/metricsink/prometheus/push/factory.go
pkg/processor/metricsink/prometheus/push/metricsink.go
pkg/processor/metricsink/prometheus/trigger.go
pkg/processor/metricsink/prometheus/worker.go
pkg/processor/metricsink/registry.go

1. Prometheus pull expected job name and instance name which should not be a part of the configuration
2. Helm can receive platform configuration

Fix prometheus pull + platform support in helm

---

cmd/controller/app/controller.go
cmd/controller/main.go
cmd/dashboard/app/dashboard.go
cmd/dashboard/main.go
cmd/processor/app/processor.go
cmd/processor/main.go
docs/reference/runtimes/dotnetcore/dotnetcore-reference.md
docs/reference/runtimes/golang/golang-reference.md
docs/reference/runtimes/java/java-reference.md
docs/reference/runtimes/nodejs/nodejs-reference.md
docs/reference/runtimes/python/python-reference.md
docs/tasks/deploy-functions-from-dockerfile.md
hack/k8s/helm/nuclio/templates/deployment/controller.yaml
hack/k8s/helm/nuclio/templates/deployment/dashboard.yaml
hack/k8s/helm/nuclio/values.yaml
pkg/dashboard/server.go
pkg/dashboard/test/server_test.go
pkg/platform/kube/controller/controller.go
pkg/platform/kube/controller/function.go
pkg/platform/kube/deployer.go
pkg/platform/kube/functionres/lazy.go
pkg/platform/kube/functionres/lazy_test.go
pkg/platform/kube/functionres/types.go
pkg/platform/kube/updater.go
pkg/platformconfig/reader.go
pkg/processor/build/builder.go
pkg/processor/build/builder_test.go

1. Dashboard / controller now receive platform configuration
2. Processor defaults `--config` and `--platform-config` - removed from all Dockerfiles and such
3. Kubernetes deployer will look at function's status for HTTP port rather than looking for the service information
4. Controller will create metric port (in deployment / service) if `prometheusPull` is configured as a metric sink

Platform configuration added to controller / dashboard

---

docs/reference/function-configuration/function-configuration-reference.md
pkg/functionconfig/types.go
pkg/nuctl/command/build.go
pkg/nuctl/command/deploy.go
pkg/processor/build/builder.go
pkg/processor/build/runtime/test/suite/suite.go

Allows specifying github as a code entry type and introducing code entry attributes for both github code entry type and archive code entry type
Archive handling is left as is, adding optional workDir attribute
When specifying github code entry type, path should be the github repo url (e.g. https://github.com/nuclio/nuclio) and a branch is required to be set
- Github code entry attributes
- branch (specifying from what branch to download the archive)
- workDir (specifying the working directory where handler files located)
- Archive code entry attributes
- workDir (specifying the working directory where handler files located)

Adding github as code entry type

---

pkg/functionconfig/types.go
pkg/nuctl/command/build.go
pkg/nuctl/command/deploy.go
pkg/processor/build/builder.go
pkg/processor/build/runtime/dotnetcore/test/dotnetcore_test.go
pkg/processor/build/runtime/golang/test/golang_test.go
pkg/processor/build/runtime/java/test/java_test.go
pkg/processor/build/runtime/nodejs/test/nodejs_test.go
pkg/processor/build/runtime/pypy/_test/pypy_test.go
pkg/processor/build/runtime/python/test/python_test.go
pkg/processor/build/runtime/ruby/test/ruby_test.go
pkg/processor/build/runtime/shell/test/shell_test.go
pkg/processor/build/runtime/test/suite/suite.go

Allows specifying github as a code entry type and introducing code entry attributes for both github code entry type and archive code entry type
Archive handling is left as is, adding optional workDir attribute
When specifying github code entry type, path should be the github repo url (e.g. https://github.com/nuclio/nuclio) and a branch is required to be set
- Github code entry attributes
- branch (specifying from what branch to download the archive)
- workDir (specifying the working directory where handler files located)
- Archive code entry attributes
- workDir (specifying the working directory where handler files located)

GitHub entry type support

---

pkg/dashboard/resource/function.go
pkg/nuctl/test/function_test.go
pkg/platform/local/platform.go

1. If a panic occurs during dashboard deploy, it is logged
2. Removed unused code for update function
3. Local platform will ignore non hostPath volumes (caused panic)

Panics during dashboard deploy are now logged

---

pkg/dashboard/ui/package.json

- "Code" tab:
- "Test" pane:
- When reducing Test pane's width, the Headers, Body type drop-down and Log Level drop-down wrap around and move to the next line, instead of staying on the same lime.
- The contents of code editor in response part sometimes overflows to the right of the screen.
- "Status" tab:
- Invocation URL shows "N/A" even though the function is deployed and has a defined port number.

UI: Fix Test pane visual bugs; Status Invocation URL is N/A

---

docs/setup/minikube/getting-started-minikube.md

According to
https://github.com/kubernetes/minikube/blob/master/docs/drivers.md#hyperkit-driver
the "Hyperkit driver will eventually replace the existing xhyve driver".
It is a lot easier to get minikube up and running with hyperkit instead
of xhyve and it's more future-proof.

Use hyperkit instead of xhyve on OSX

---

pkg/functionconfig/types.go
pkg/platform/abstract/platform.go
pkg/processor/build/test/build_test.go

Source hash causes issues with backwards compatibility, simplify the logic for the client to decide when to build

Change source hash to build mode

---

pkg/platform/kube/functionres/lazy.go

Before this commit the behaviour was that if a user has not passed min and max replicas, it would have defaulted to zero and no pods were to be created.
This changes the behaviour to be at least 1 pod available and at max 10 as default for k8s based systems.

HPA defaults change

---

pkg/platform/kube/function.go
pkg/processor/trigger/http/trigger.go

On function invocation the logs are returned as part of the header, the size limit of default nginx config is 4096 bytes, so if the logs exceed the size don't set them in the header and skip

Fix 502 error when exceeding logs header limit 

---

pkg/dashboard/test/server_test.go
pkg/platform/abstract/invoker.go
pkg/platform/abstract/platform.go
pkg/platform/kube/dlx/handler.go
pkg/platform/kube/functionres/lazy.go
pkg/platform/kube/platform.go
pkg/platform/local/platform.go
pkg/platform/platform.go

When triggering function invocation set the proper headers and send the request to DLX service

Support scale from zero to one in function invocation

---

cmd/controller/app/controller.go
cmd/controller/main.go
cmd/dashboard/app/dashboard.go
cmd/dlx/app/dlx.go
cmd/dlx/main.go
cmd/processor/app/processor.go
cmd/scaler/app/scaler.go
cmd/scaler/main.go
pkg/dashboard/server.go
pkg/functionconfig/types.go
pkg/loggersink/loggersink.go
pkg/nuctl/command/deploy.go
pkg/platform/kube/controller/controller.go
pkg/platform/kube/functionres/lazy.go
pkg/platform/kube/functionres/lazy_test.go
pkg/platform/kube/functionres/types.go
pkg/platform/kube/scaler/scaler.go
pkg/platformconfig/platformconfig.go
pkg/platformconfig/platformconfig_test.go
pkg/platformconfig/reader.go
pkg/processor/types.go

1. Populating `spec.loggerSinks` will override the logger sinks from platform configuration 
2. Populating a single logger sink in `spec.loggerSinks` with only the level set will override all platform configuration logger sinks' levels
3. Used platform configuration to create loggers for dlx and scaler

Functions can override logger configuration

---

pkg/dashboard/ui/package.json
pkg/dashboard/ui/src/app/shared/services/nuclio-event-data.service.js

Also:
- Remove Pypy runtime entirely
- Fix: checkbox of project is not checked after failed deletion and actions panel is hidden
- Fix: on deleting an environment variable, always the last one on the list is actually removed

UI: Display proper error on function invocation error

---

hack/k8s/resources/nuclio.yaml
pkg/processor/build/builder.go

Older Docker versions will return an error if build args are not used:
https://github.com/moby/moby/issues/26249
This declares the build args in the Dockerfiles so that builds will work for Docker 1.12.

Support Docker 1.12

---

pkg/dashboard/resource/invocation.go

Before sending an error or any other response, set content type as json, if the function have a different content type to return, it will be overridden down the road

[Fix] Set appropriate content type on function invocation response

---

pkg/dashboard/resource/invocation.go

errors are returned properly now with `application/json` content type, any other message is for the caller to decide

Fix content type on invocation response

---

pkg/dashboard/test/server_test.go
pkg/platform/abstract/invoker.go
pkg/platform/abstract/platform.go
pkg/platform/kube/dlx/handler.go
pkg/platform/kube/functionres/lazy.go
pkg/platform/kube/platform.go
pkg/platform/local/platform.go
pkg/platform/platform.go
pkg/processor/trigger/partitioned/v3io/test/v3io_test.go

A selector for service is changed when a function is scaled to zero and on cold start, this allows cold start on inter-function communication.

Replace default-backend for dlx with service selector

---

pkg/dashboard/resource/function.go

artifacts are created unique to the cluster not needed to be returned to any client of nuclio REST API

Fix Import export between clusters

---

pkg/dashboard/ui/package.json

You can now use: `"kind": "string", "password": true` to render a password input field where entered characters are obscured on screen.

UI: Add ability to set password fields in template params

---

pkg/functionconfig/types.go
pkg/platform/kube/functionres/lazy.go
pkg/platformconfig/platformconfig.go
pkg/platformconfig/types.go

Allow either globally using function config's augmented function config or per function to choose the k8s service type for that function.
if node port chosen (default) then any logic remains as is
else, no auto assigning of ports is done and k8s service type is set to the type passed (e.g. clusterIP or LoadBalancer)

Allow to disable node port for functions

---

cmd/dashboard/README.md

Small typo in JSON example.
Use the following script to check, maybe it should be integrated in the tests/build cycle.
```python
import json
from glob import glob
def check_json(fname):
ok = True
in_json = False
json_lines = []
with open(fname) as fp:
for lnum, line in enumerate(fp, 1):
if '```json' in line:
in_json = True
continue
if '```' in line and '```json' not in line:
data = ''.join(json_lines)
if data:
try:
json.loads(data)
except ValueError as err:
ok = False
print(f'{fname}:{lnum}: json error: {err}')
json_lines = []
in_json = False
continue
if in_json:
json_lines.append(line)
return ok
for fname in glob('./**/README.md', recursive=True):
if 'vendor' in fname:
continue
ok = check_json(fname)
print(f'{fname}: {"OK" if ok else "ERROR"}')
```

Fix JSON in docs

---

pkg/dashboard/ui/package.json

Plus, placeholders were added to these fields.
Depends on: https://github.com/iguazio/dashboard-controls/pull/426

UI: Triggers: RabbitMQ: Queue Name and Topics can't be both empty

---

pkg/processor/trigger/rabbitmq/rabbitmq_test.go
pkg/processor/trigger/rabbitmq/test/rabbitmq_test.go
pkg/processor/trigger/rabbitmq/trigger.go

Don't force declaring of exchange or queue if no topics passed.
topics passed -> function should declare the exchange and queue, and bind the topics, then consume
topics not passed -> function only consumes, expects preconfigured queues and exchange

[Fix] RabbitMQ, allow to only consume queues

---

pkg/dashboard/ui/package.json

When the field is empty the model value should be an empty array: `[]`.
Instead, if was an array with a single item, an empty string: `['']`.
Depends on: https://github.com/iguazio/dashboard-controls/pull/428

UI: Triggers>RabbitMQ>Topics: wrong value when empty

---

pkg/platform/abstract/platform.go

This is to keep the image of the function when disabling a function
before removing image and runRegistry from spec returned from function resource handler, this was given by the client

Populate image of function on disable/enable

---

vendor/golang.org/x/net/trace/trace.go

Golang functions that vendor golang/x/net/trace explode on double init (for no good reason). This prevents this by not initializing trace in Nuclio processor

Disable golang/x/net/trace init

---

pkg/dashboard/ui/package.json
pkg/dashboard/ui/src/less/mixins.less

Bugfix: Should not allow to start function name with a digit
Depends on PR https://github.com/iguazio/dashboard-controls/pull/464

IG-2131 [General] Use common link style

---

pkg/dashboard/ui/package.json
pkg/dashboard/ui/src/less/mixins.less

- Bugfix: function "Code" tab is visually distorted on Safari web browser (https://github.com/nuclio/nuclio/issues/1140)
- General: do not hide placeholder on focus.
- Triggers:
- Do not crop the trigger list after 500 pixels
Depends on PR https://github.com/iguazio/dashboard-controls/pull/469

IG-2131 fixed placement of 'external link' icon

---

pkg/dashboard/ui/package.json

- Function:
- Configuration & Triggers:
- When a collapsible row is expanded and the "Create new" button is clicked, it will both collapse the expanded rows on that list and create a new row with a single click.
- Triggers:
- For `cron` only:
- Schedule: fix issue with different formats (`sec min hrs day mon yrs` vs `min hrs day mon yrs`, see https://github.com/nuclio/nuclio/issues/1146)
Closes https://github.com/nuclio/nuclio/issues/1146

UI: Cron schedule syntax issue fixed + minor UX improvement

---

pkg/dashboard/ui/src/app/shared/services/import.service.js

- Bugfix: YAML import/export of both projects and functions is corrupted when quote character (`'`) is used
- Projects screen:
- Bugfix: import a YAML file with multiple projects is not working
- "Code" tab:
- for "Archive" code-entry type: renamed "Session Key" to "Access key"
- for "GitHub" code-entry type: added "Token" field which populates `Authorization: token <user_token>` request-HTTP header
- "Configuration" tab:
- "Resources": "Request" field  is removed from "GPU" since only "Limit" is relevant according to [docs](https://kubernetes.io/docs/tasks/manage-gpus/scheduling-gpus/#v1-8-onwards)
Depends on PR https://github.com/iguazio/dashboard-controls/pull/514

IG-2174 [Nuclio] Import multiple-projects YAML not working

---

pkg/dashboard/ui/package.json

- Function » Code » Code-Entry Type: for "Archive in V3IO" only:
- Rename "Archive in V3IO" label to "Archive"
- Rename "Access key" label of field to "Access key (V3IO only)"
Depends on PR https://github.com/iguazio/dashboard-controls/pull/516

UI: Move "V3IO" text from Archive option to Access Key field

---

pkg/dashboard/ui/package.json

- Configuration tab: Volumes: Refactor V3IO type model & change field order
- Triggers tab: Move "Worker Allocator Name" to be last of the fields
Depends on PR https://github.com/iguazio/dashboard-controls/pull/519

UI: Refactor V3IO volumes & move Worker Allocator Name to be last

---

pkg/dashboard/ui/package.json

- Bugfix: when viewing/exporting function to YAML some unrelated `$$hashKey` properties were there. They are omitted now.
-  Bugfix: when selecting "Duplicate function" action from function list and clicking on "Cancel" in the dialog, the list of functions used to be unnecessarily reloaded. Now it does not get reloaded in this case.
Depends on PR https://github.com/iguazio/dashboard-controls/pull/525

UI: Remove unnecessary `$$hashKey` properties from YAML

---

pkg/dashboard/ui/package.json

- Function » Triggers » for Cron only » Schedule:
- Display entire 6-part value in collapsed row.
- Instead of prepending value with `*` for seconds, use `0` instead.
- Number input: bugfix – arrows mispositioned on Firefox browser.
Depends on PR https://github.com/iguazio/dashboard-controls/pull/533

UI: Cron trigger: use 0 instead of * for seconds in schedule

---

pkg/dashboard/ui/package.json

- Function screen » Configuration:
- Build:
- Add tooltips to "Disabled cache" and "No internet" checkboxes
- Resources:
- GPU: Add tooltip "per replica"
- Volumes:
- Remove "Host Path" volume type
Complements PR https://github.com/nuclio/nuclio/pull/1186
Depends on PR https://github.com/iguazio/dashboard-controls/pull/541

UI: Remove "Host Path" volume type; Add some tooltips

---

pkg/dashboard/ui/package.json

- Function screen » "Configuration" tab:
- Re-organization:
- Switched places of "Data Bindings" and "Volumes" panes
- Moved "Logger level" from "Logging" pane to "Basic Settings" pane
- Removed "Logging" pane
- Build » Timeout Readiness (seconds): changed minimum valid value from 0 to 1

UI: Re-organize Configuration panes; Readiness timeout min val 1

---

pkg/dashboard/ui/package.json

Text boxes debounce for typing was reduced from 1 second to 200 milli-seconds.
Depends on PR https://github.com/iguazio/dashboard-controls/pull/554

UI: Text boxes: reduce debounce for typing from 1s to 200ms

---

pkg/dashboard/ui/package.json
pkg/dashboard/ui/src/less/mixins.less

- Create function from scratch: These fields no longer have default values in UI so they don't override their corresponding values from remote configuration (from archive or GitHub): Min replicas, Max Replicas, Target CPU.
- Bugfix: single-quotes were doubled in request body on deploy (e.g. `"commands": ["echo: ''hello''"]` instead of `"commands": ["echo: 'hello'"]`).
- Align tone of placeholder text color of number inputs with that of text inputs.
- Multi-line text input fields are now scrollable.
- Bugfix: scrollbar of Monaco code editor was flickering on Firefox web browser.
Depends on PR https://github.com/iguazio/dashboard-controls/pull/562

UI: Remove some defaults from function creation; Fix quotes bug

---

pkg/platform/kube/functionres/lazy.go

Fixes 2 bugs that make deploy fail when subpath:
1. doesn't start with '/'
2. ends with '/'

Fix volume subpath structure when a wrong one is given

---

pkg/common/config.go
pkg/functionconfig/reader.go
pkg/functionconfig/reader_test.go

As requested, Loading configuration from code entry (Archive, Github) will *not* override UI specified fields
The only exception is that env vars will be merged - with priority to UI when there's conflict

Code entry values don't override base config values

---

cmd/dashboard/main.go
pkg/common/url.go
pkg/common/url_test.go
pkg/dashboard/functiontemplates/zipfunctiontemplatefetcher.go

Corresponding to #1204 
Changes:
- can read from local file when archive URL starts with "file://"
- added the option to pass "none"  in addition to "nil" when passing git repo and ref

Function templates load from local archive

---

pkg/dashboard/ui/gulpfile.js
pkg/dashboard/ui/package.json
pkg/dashboard/ui/resources/installRequire/app.js

- Function configuration: Build: Disable entire pane when the selected code entry type in "Code" tab is not "Edit Online".
- Make placeholders more consistent:
- "Enter" instead of "Type"
- Removed "a" or "an" articles
- Always end with "..." (and no space before it)
- Remove "sync-exec" dependency (due to vulnerability and it was no longer necessary)
Depends on PR https://github.com/iguazio/dashboard-controls/pull/565

UI: Configuration: Build: Disable pane for non-edit-online

---

pkg/platform/kube/functionres/lazy.go
pkg/platformconfig/platformconfig.go
pkg/platformconfig/types.go

Following #1201 
Enriches every function deployment with default values set inside platform config.
(platform config values will not override deployment's values)
structure example: (platform.yaml)
```
logger:
functions:
- level: debug
sink: myStdoutLoggerSink
sinks:
myStdoutLoggerSink:
attributes:
encoding: json
timeFieldEncoding: iso8601
timeFieldName: time
varGroupName: more
kind: stdout
system:
- level: debug
sink: myStdoutLoggerSink
kubernetes:
deployment: # a *v1beta1.Deployment struct
spec:
minReadySeconds: 2
```

Enrich deployments with platformConfig default values

---

hack/examples/README.md
hack/examples/golang/callfunction/fibonacci/fibonacci.go

- Doc review for the Go `callfunction` example added in PR #1174, commit 34c879a.
- Unify capitalization of the example names in **hack/examples/README.md**; as most of the names used title-case capitalization, I changed the few names that used sentence-case capitalization to title case.

[DOC] Edit CallFunction example description & log messages; unify capitalization in the examples README

---

pkg/dockerclient/shell.go

When running builds on Amazon EKS, containers do not have access to the network/routing so have no access to the internet, this is an issue when building dependencies with pip for example. This fixes the issue by exposing and env variable that can be applied to the deployment of the nuclio dashboard.
```
env:
- name: BUILD_USE_HOST_NET
value: "true"
```
This will add the `--network host` argument to the build command.
If the variable is set to false, or not specified, it will default to `--network default`.

Allow Nuclio build on EKS

---

pkg/dashboard/resource/resource.go
pkg/platform/kube/consumer.go
pkg/platform/types.go

Fixes #1205
Uses Header Authorization to authenticate against kubernetes apiserver
```
Authorization: Bearer [TOKEN_VALUE]
```

Change AuthConfig to use BearerToken rather than OIDC Auth Provider

---

pkg/functionconfig/reader.go
pkg/functionconfig/reader_test.go
pkg/functionconfig/types.go

Bug Description:
When setting code entry type to be `archive` for example, with `targetCpu: <some-value>` 
and passing from the UI another targetCpu - then the targetCPU is taken from the codeEntry instead from the UI as expected.
Cause and Solution:
This happened because the targetCpu was passed in the codeEntry configuration as `targetCpu` while in the backend it is saved as `targetCPU`, a thing that makes the `targetCpu` value get priority after the merge of the configurations.
solution - Normalize the given code entry configuration values to the matching JSON name declared in the FunctionConfiguration Go struct

[Bug fix] targetCPU gets overridden by code entry configuration

---

pkg/dashboard/ui/package.json

Function » Configuration » Resources » Memory: change value of unit option "K" from `'K'` to `'k'` (according to https://github.com/kubernetes/apimachinery/blob/master/pkg/api/resource/suffix.go#L127)
Depends on PR https://github.com/iguazio/dashboard-controls/pull/593

UI: Resource memory units: change 'K' to 'k'

---

pkg/nuctl/command/deploy.go
pkg/platform/kube/controller/nucliofunction.go
pkg/platform/kube/functionres/lazy.go
pkg/platform/local/platform.go

Instead of only ignoring HostPath volumes - remove them from the functionConfig so it won't be kept inside the nucliofunction resource
* Also updated function default readiness timeout to 60

Remove HostPath from function resource (and default readiness timeout update)

---

pkg/dashboard/ui/package.json

- Function:
- Code:
- Added "S3" code entry type
- Configuration:
- Added "more info" icons with explanatory tooltips on click
- Build: Removed default value of "Readiness Timeout (seconds)"
- Triggers:
- bugfix: trigger got collapsed on clicking/dragging the scrollbar thumb
- bugfix: some console errors when deploying HTTP trigger with ingresses
Depends on PR https://github.com/iguazio/dashboard-controls/pull/609
Corresponds to PR https://github.com/nuclio/nuclio/pull/1242

UI: Add S3 code entry type

---

pkg/processor/build/builder.go

Bug description:
When passing `path` to a function that is not of type archive - build fails with `Downloaded file type is not supported. (expected an archive)`
(for example when passing a path to `.go` file that describes only the source code of a function)
Solution:
Specified the restriction to add only archive files - only to the relevant code entry types - `archive`, `s3` and `github`

Expect archive file type only on external code entry types

---

pkg/common/aws.go
pkg/dashboard/resource/frontendspec.go
pkg/platform/kube/functionres/lazy.go
pkg/platform/kube/platform.go

The problem happened because the function `spec.selector.matchLabels` didn't update on function update to the new labels (the deployment's `spec.selector.matchLabels` must be a subset of `spec.template.labels`)
- added also some other small fixes

Fix function labels as re-deploy fails

---

docs/setup/gke/getting-started-gke.md
docs/setup/k8s/getting-started-k8s.md
hack/k8s/helm/nuclio/README.md
pkg/processor/build/builder_test.go

Since the document is kind of out of date, I have updated the URL of Docker Hub in this document so as to deploy functions successfully.

registry.hub.docker.com -> docker.io

---

pkg/platform/abstract/platform.go

Fixes #1283
Skips populating existing function image to the requested function image
in case of codetype image or when the user specified the image to run with.

Don't populate create function image if run image is specified

---

pkg/dashboard/ui/package.json

Function » Configuration » Annotations, Labels & Environment Variables: [Bugfix] "Deploy" button does not turn disabled on entering an invalid value to "Name"/"Key" field of an existing item.

UI: Deploy not disabled on invalid key/name when editing

---

pkg/dashboard/ui/package.json

- Projects: [bugfix] Some error appearing in browser console in welcome screen.
- Function » Configuration » Build: Remove default value from "Readiness Timeout (seconds)" field
Depends on PR https://github.com/iguazio/dashboard-controls/pull/635

UI: Remove default value from "Readiness Timeout (seconds)"

---

pkg/processor/build/builder.go
pkg/processor/build/runtime/test/suite/suite.go

Providing a URL to a non-Go function (e.g. http://www.foo.com/my-function.py) failed. This is because a recent change was made to rename the function after download. In addition, the integration test to verify downloading files from URLs was not proper.
This PR fixes downloading files from remote URLs (doesn't rename them, yet maintains the behavior of renaming archivees) and fixes the integration test. It also refactors a long function (`resolveFunctionPath`) to be easier to read.

Fix build from URL

---

pkg/dashboard/ui/package.json

- Function » Triggers: [bugfix] When creating a new trigger and collapsing it, its info is not displayed on the trigger's row.
Depends on PR https://github.com/iguazio/dashboard-controls/pull/637

UI: Fix bug where trigger info is not displayed after creation

---

pkg/dashboard/ui/package.json

- Projects » Functions list » Actions:
- Duplicate function redirects to function screen of the new duplicated function, and does not automatically initiates its deployment
- Function:
- Actions: Duplicate function redirects to function screen of the new duplicated function, and does not automatically initiates its deployment
- "Code" tab » "Test" pane » "Test" button:
- For a function that is not in "Running" status, the "Test" button is disabled with a tooltip “Only running functions can be tested”
- "Configuration" tab:
- Several text additions and changes in description tooltips
- Build » "Readiness Timeout (seconds)" field: Removed default value
- General:
- More-info tooltip: for those tooltips which are opened on a click event rather than on hover, they are now closing when …

UI: Duplicate function redirects to new function before deploy

---

pkg/dashboard/ui/package.json

This is to address a UI regression in roundtrip re-deployment where the default max-replicas=0 would prevent a redeployment if auto-filled by previous deployment
Depends on PR https://github.com/iguazio/dashboard-controls/pull/644

Bumping dashboard controls and freezing to 0.8.22

---

pkg/processor/runtime/dotnetcore/UnixSocketHandler.cs
pkg/processor/runtime/dotnetcore/test/_outputter/outputter.cs
pkg/processor/runtime/dotnetcore/test/dotnetcore_test.go

If you're passing a message body with more than ~370 Characters you get the errors described in #1001.
Problems in current code:
Searching for '\n' only works, if the whole message (including linebreak) fits into the buffer. If you need to read the buffer a second time, there won't be a linebreak in the first part of the buffer. 
Then, IndexOf returns -1 and substring will fail with the exception (which is also in #1001):
```
Socket Error: Length cannot be less than zero.,
Parameter name: length,
```
The exception breaks the while loop and every next request will be answered with 500.
I fixed it by reading the input message until the linebreak is recognized.

dotnet-runtime: Fixed handling of large function-input

---

docs/devel/contributing.md

... otherwise `make lint` will fail.

Added missing dependency in how-to-contribute guide

---

docs/reference/runtimes/dotnetcore/dotnetcore-reference.md
pkg/processor/build/runtime/dotnetcore/docker/onbuild/Dockerfile
pkg/processor/runtime/dotnetcore/AssemblyLoader.cs
pkg/processor/runtime/dotnetcore/Wrapper.cs
pkg/processor/runtime/dotnetcore/test/_outputter/handler.csproj
pkg/processor/runtime/dotnetcore/test/_outputter/outputter.cs
pkg/processor/runtime/dotnetcore/test/dotnetcore_test.go

Currently the wrapper loads the handler.dll, but without the dependency-dlls of handler. 
I used a custom AssemblyLoader taken from a dotnet-core github issue (referenced in code).
With this AssemblyLoader all necessary dependencies will be loaded.
You can now use your own nuget-packages by creating a handler.csproj (Use the [handler.csproj from nuclio repo](https://github.com/nuclio/nuclio/blob/master/pkg/processor/build/runtime/dotnetcore/docker/onbuild/handler.csproj) as base and extend it with your own packages) file in your project, which will be copied by the Dockerfile in ONBUILD RUN section and its packages will be restored. 
This should fix #1281 and #1078. Until this is merged and shipped I will write a short how-to in #1078 how to build the function with a custom dockerfile.

dotnet: Fix loading of handler in Wrapper to allow custom nuget packages

---

pkg/processor/runtime/dotnetcore/UnixSocketHandler.cs

This is a fix on top of #1288 .
I did a few tests under higher load and encountered not reproducible problems that a Function throws InternalServerError with a large JSON-input. After calling the function again with the same input it usually worked. 
In the logs I saw 
> The input is not a valid Base-64 string as it contains a non-base 64 character, more than two padding characters, or an illegal character among the padding.
which seems to be an error message of `Encoding.UTF8.GetString(buffer);`
I had a look at a few examples of c#-sockets and considered to include the number of received bytes.
With this fix, the problem did not appear again.

dotnet: Fixed byte length for buffer in Wrapper to avoid Base-64 errors

---

pkg/dashboard/ui/src/app/shared/services/nuclio-projects-data.service.js

https://trello.com/c/Bwk8VBti/58-nuclio-use-project-name-instead-of-display-name

[Nuclio] Use project name instead of display name

---

docs/reference/function-configuration/code-entry-types.md

@omesser please merge. (The GitHub output looks good both with the previous and new list-item source-code indentation variations, but in the Nuclio doc site only the second variation results in the desired indentation.)

[PR #3111 completion] Code-entry types function configuration: fix list-item indentation

---

pkg/dashboard/resource/function.go
pkg/dashboard/resource/project.go
pkg/dashboard/test/server_test.go
pkg/dashboard/ui/package.json
pkg/nuctl/command/create.go
pkg/nuctl/command/get.go
pkg/nuctl/test/project_test.go
pkg/platform/types.go

Project ID (name) will be the one that is displayed. (instead of receiving `displayName` and generating uuid as project ID).
This change is made to make project identification easier.
This also means that project name cannot be updated anymore.
- Also increased `creationStateUpdatedTimeout` to 45 to prevent early timeout that may happen for example when the download of the function's code/configuration files takes longer than expected
**Note: this PR needs to be merged alongside matching UI branch**

Deprecate project display name

---

hack/k8s/helm/nuclio/templates/ingress/dashboard.yaml
hack/k8s/helm/nuclio/values.yaml

A small PR to enable users to add an ingress for the dashboard.
I've used the "best practice" way for creating the ingress resource, that is the way the ingress is created when you do a `helm create mychart`.
I've also tried to copy the practices used in the nuclio helm chart for the labels and the directory structure.

Add an ingress for the dashboard in the Helm chart

---

pkg/processor/build/builder.go
pkg/processor/build/runtime/python/runtime.go
pkg/processor/build/util/decompress.go

Changes:
- Updated `isArchive` boolean to be set to `false` whenever it is "archive" code entry and a jar file is given as its path, to make it possible to load java functions as jar file this way using the UI.
- Changed python3.6 default base image to be "python:3.6" instead of "python:3.6-alpine"

Fix loading jar from archive code entry, and set "python:3.6" as default python3.6 base image

---

docs/reference/function-configuration/function-configuration-reference.md
pkg/platform/kube/deployer.go
pkg/platform/kube/functionres/lazy.go
pkg/processor/runtime/golang/test/timeout_test.go
pkg/processor/test/suite/suite.go

It seems that on k8s v1 (we're using v1beta1) label selector became immutable.
It was done because updating label selector caused unexpected behavior that wasn't properly handled.
In this PR we make function's  `Meta.Labels` immutable - it will always stay the same as it was set on the first deployment

Make function labels immutable

---

pkg/dashboard/resource/function.go
pkg/restful/resource.go
pkg/restful/resource_test.go

- Increasing creation state update timeout to 45 to prevent wrong function deployment timeout, that may be caused as a result of a longer download of function files from external code entry type for example
- adding errorCause to the error response payload to provide the UI with a human-readable information to show to the user when an error happens

Add error cause and increase creation state update timeout

---

cmd/dashboard/app/dashboard.go
cmd/playground/app/playground.go
pkg/dashboard/resource/function.go
pkg/dashboard/resource/project.go
pkg/nuctl/command/nuctl.go
pkg/platform/abstract/platform.go
pkg/platform/factory/factory.go
pkg/platform/kube/controller/controller.go
pkg/platform/kube/platform.go
pkg/platform/local/platform.go
pkg/platform/test/platform_test.go
pkg/processor/build/test/build_test.go
pkg/processor/test/suite/suite.go
pkg/processor/util/v3io/v3ioutil_test.go

Changes:
1. Added `default` project.
- ensure its existence (Create if doesn't exist whenever nuclio starts)
- make `default` project not deletable
2. Validate project name on function creation
- when no project name was given assign the function automatically to `default` project
3. Return `Conflict 409` when project creation fails on name already exists

Add default project and validate project existence on function creation

---

pkg/platform/kube/functionres/lazy.go

The condition was looking on the function spec (which if the user leaves empty default to 0)
instead of looking on the closure generated values (which takes the values from the function spec, unless they are zero, than they are default to 1 (min) and 10 (max))

Fix HPA deletion condition

---

pkg/dashboard/functiontemplates/render_test.go
pkg/dashboard/test/server_test.go
pkg/functionconfig/types.go
pkg/nuctl/command/deploy.go
pkg/platform/kube/apis/nuclio.io/v1beta1/types.go
pkg/platform/kube/functionres/lazy.go
pkg/platform/kube/resourcescaler/resourcescaler.go
pkg/playground/resource/function.go

Changes:
* Function spec replicas fields (`Replicas`, `MinReplicas`, `MaxReplicas`) changed to be `*int` instead of `int` to enable the `nil` value, which is there to mark "Not given"
* `Replicas` takes precedence over `MinReplicas/MaxReplicas`, e.g. if the given spec is:
```
Replicas: 3,
MinReplicas: 1,
MaxReplicas: 5
```
than in practice `MinReplicas` and `MaxReplicas` will be 3 (meaning no scale up/down will be active)
* if neither `Replicas` nor `MinReplicas` nor `MaxReplicas` is given, these defaults will be applied:
```
Replicas: nil,
MinReplicas: 1,
MaxReplicas: 1
```
* (Bugfix) The nuclio function crd operator changed to patch the deployment on update instead of updating it. 
Updating the deployment caused to override the deployment's replicas on every update, which in case of a …

Changing function spec replicas fields + fixing scale up bug

---

docs/reference/function-configuration/code-entry-types.md

@omesser / @liranbg please merge.

[DOC] Code-entry types reference: Fix S3 session-token dashboard label ("Token" > "Session token")

---

pkg/dashboard/ui/package.json

- Function screen: [bugfix] status icon hides on small resolution
- Functions list: [bugfix] "invocation #" column always shows 0, and is displayed in demo-mode only
Depends on PR https://github.com/iguazio/dashboard-controls/pull/725

UI: Show "Invocations #" column in production

---

pkg/platform/kube/functionres/lazy.go
pkg/processor/build/test/build_test.go

Occurs when function is firstly created with non-gpu resources
This happen because of the patch strategy is being used for updating deployment resource.
While marshaling the deployment resource, the deployment strategy `rollingUpdate` field is being omitted and thus, its configuration on the server is not being deleted but preserved. that interfere with changing the deployment strategy type to `Recreate`

Fix gpu allocation on redeploy

---

pkg/processor/trigger/kinesis/shard.go

Not before each call to GetRecords.

Kinesis trigger: only wait in case of an error.

---

hack/k8s/resources/nuclio.yaml

the apps/v1beta1 has been deprecated, Deployment is no longer valid under this version.
This PR is to fix the broken deployment configuration due to the above.
Further details:
https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.16.md#deprecations-and-removals

fix the deployment configuration for the deprecated apiVersion

---

pkg/platform/kube/consumer.go
vendor/k8s.io/client-go/rest/request.go

In order for the Nuclio command line to communicate with a Nuclio deployment on EKS, it needs to pass a bearer token with every request.
Instead of changing all call sites to `consumer.clientSet`, `consumer.getClientSet` etc to each individually pass an `AuthConfig`, instead we set this globally when the consumer is instantiated using an environment variable.
This will have minimal changes to existing logic and behaviour. However, with this change in place, we are now able to communicate with our EKS cluster by setting the environment variable.

Add support for defining Bearer Token globally using environment variable

---

pkg/processor/metricsink/prometheus/trigger.go
pkg/processor/runtime/golang/builtin.go
pkg/processor/timeout/timeout.go
pkg/processor/trigger/trigger.go
pkg/processor/trigger/types.go
pkg/processor/worker/allocator.go
pkg/processor/worker/types.go

1. Add worker metrics that measure worker allocation things like wait time, availability, etc
2. Minor worker allocation performance hit when a worker allocation timeout is specified now happens only when there are no workers available and a timeout is specified

Add worker metrics

---

pkg/containerimagebuilderpusher/containerimagebuilder.go
pkg/containerimagebuilderpusher/docker.go
pkg/containerimagebuilderpusher/kaniko.go
pkg/dashboard/test/server_test.go
pkg/platform/abstract/platform.go
pkg/platform/platform.go
pkg/processor/build/builder.go
pkg/processor/build/runtime/dotnetcore/runtime.go
pkg/processor/build/runtime/golang/runtime.go
pkg/processor/build/runtime/java/runtime.go
pkg/processor/build/runtime/nodejs/runtime.go
pkg/processor/build/runtime/python/runtime.go
pkg/processor/build/runtime/ruby/runtime.go
pkg/processor/build/runtime/runtime.go
pkg/processor/build/runtime/shell/runtime.go

Use dedicated base images registry (pull registry) if defined
If base registry is not defined will use the following:
- for docker builder: quay.io
- for kaniko builder: push registry

IG-13850: Base registry fix

---

hack/aks/resources/nuclio.yaml
hack/gke/resources/nuclio.yaml
hack/k8s/helm/nuclio/Chart.yaml
hack/k8s/helm/nuclio/values.yaml
hack/k8s/resources/nuclio.yaml

The version bump patch 345497633660dd0499ff460b3820fd8d7f6c9173
provided version 1.2.1 although it doesn't look it exist in quay.io
$ docker pull quay.io/nuclio/controller:1.2.1-amd6
Error response from daemon: manifest for quay.io/nuclio/controller:1.2.1-amd6 not found
$ docker pull quay.io/nuclio/dashboard:1.2.1-amd64
Error response from daemon: unknown: Tag 1.2.1-amd64 was deleted or has expired. To pull, revive via time machine
Proper latest version seems to be 1.2.2 based on Github tags.
Signed-off-by: Alexis de Talhouët <adetalhouet89@gmail.com>

Bump to 1.2.2

---

README.md

Doc-review edits for **README.md** changes done by Yaron H. in PR #1402

[DOC-REVIEW] README update (PR #1402)

---

pkg/dashboard/ui/package.json

- [bugfix] Port 0 is displayed instead of N/A invocation URL or “Not yet deployed” message
- [bugfix] When exiting “Edit Project” dialog by pressing the ESC key an unrelated error occurs
Depends on PR https://github.com/iguazio/dashboard-controls/pull/810

UI: Consider `httpPort: 0` as invocation URL N/A or not deployed

---

README.md
docs/reference/runtimes/dotnetcore/dotnetcore-reference.md
docs/reference/runtimes/dotnetcore/writing-a-dotnetcore-function.md
hack/examples/README.md
pkg/processor/build/runtime/dotnetcore/docker/onbuild/Dockerfile
pkg/processor/build/runtime/dotnetcore/docker/onbuild/handler.csproj
pkg/processor/build/runtime/dotnetcore/runtime.go
pkg/processor/runtime/dotnetcore/test/_outputter/handler.csproj
pkg/processor/runtime/dotnetcore/wrapper.csproj

Upgrading due to a bug on 2.x & deprecation of `netstandardapp`
Bug logs:
```
Error loading function: Could not load file or assembly 'Microsoft.CSharp, Version=4.0.5.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'., Path: /opt/nuclio/handler/handler.dll, Type: nuclio, Function: parser
Unhandled Exception: System.Exception: Error loading function: Could not load file or assembly 'Microsoft.CSharp, Version=4.0.5.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'., Path: /opt/nuclio/handler/handler.dll, Type: nuclio, Function: parser
at processor.Wrapper.CreateTypeAndFunction(String dllPath, String typeName, String methodName) in /home/nuclio/src/wrapper/Wrapper.cs:line 59
at processor.Program.Main(String[] args) in /home/nuclio/src/wrapper/Program.cs:line 26
at …
```

bump dotnet 2.0 to 3.1

---

hack/k8s/helm/nuclio/Chart.yaml
hack/k8s/helm/nuclio/templates/role/function-deployer.yaml
pkg/platform/kube/deployer.go
pkg/processor/runtime/python/py/_nuclio_wrapper.py

Some deployment errors can be found only in k8s events. (like failed to perform volume mount, insufficient memory etc..)
When deployment fails and pod fails to start - show k8s events (warnings only)

Show k8s events on deployment failure

---

pkg/dashboard/ui/package.json
pkg/dashboard/ui/src/less/mixins.less

- Function:
- Configuration: added validation rules to many text fields
- on deploy, when the deploy log is displayed in a collapsible block of yellow, and deploy fails – the entire deploy log is replaced by the error message only (the same content as in the “Error” pane in the “Status” tab).
- General: fixed styling of disabled buttons
Depends on PRs https://github.com/iguazio/dashboard-controls/pull/812 https://github.com/iguazio/dashboard-controls/pull/813

UI: Add validation rule to configuration; Show build error

---

pkg/dashboard/ui/package.json

- Function » Status: [bugfix] invocation URL was “Not yet deployed” when function was in scaled-to-zero state, even though it had a properly working invocation URL (which was displayed correctly in function list screen)
Depends on PR https://github.com/iguazio/dashboard-controls/pull/830

UI: Fix invocation URL "Not yet deployed" for scaled-to-zero func

---

pkg/processor/trigger/http/types.go

We want to pass JWT tokens to the function through the request headers.
Tried with a basic JWT coming from Dex and it exploded on too big header

Increasing fasthttp server read buffer size from 4KB to 16KB

---

pkg/platform/kube/apis/nuclio.io/v1beta1/types.go

`GetComputedMaxReplicas` flow is now:
1. if `Replicas` given, use it
2. if `MaxReplicas` given, use it
3. if `MinReplicas` given, use it
4. default to 1
Before this PR step 3 didn't exist which would have broken if `MinReplicas > 1` since `MaxReplicas` would default to 1 and HPA can't have `MinReplicas > MaxReplicas`
Decided to leave `GetComputedMinReplicas` flow as is:
1. if `Replicas` given, use it
2. if `MinReplicas` given, use it
3. default to 1

Default MaxReplicas to MinReplicas before default value

---

pkg/dashboard/ui/package.json

Function » Configuration » Labels & Annotations » Key: [bugfix] wrong validation rules disallowed entering uppercase letters to the name part of the key
Depends on PR https://github.com/iguazio/dashboard-controls/pull/852

UI: Fix wrong validation rules for label and annotation keys

---

pkg/processor/runtime/python/py/_nuclio_wrapper.py

To avoid a bug in user code crashing the wrapper.

IG-14589: Catch GeneratorExit in Python wrapper.

---

cmd/dashboard/app/dashboard.go
cmd/dashboard/main.go
hack/k8s/helm/nuclio/Chart.yaml
hack/k8s/helm/nuclio/templates/deployment/dashboard.yaml
hack/k8s/helm/nuclio/values.yaml
pkg/common/helper.go
pkg/dashboard/resource/frontendspec.go
pkg/dashboard/server.go
pkg/dashboard/test/server_test.go
pkg/platform/abstract/platform.go
pkg/platform/factory/factory.go
pkg/platform/kube/platform.go
pkg/platform/local/platform.go
pkg/platform/platform.go
pkg/platform/test/mock.go
pkg/platform/types.go
pkg/processor/build/builder.go
pkg/processor/build/builder_test.go

**Bug description:**
* Create nuclio function that prints "Hello"
* In "Configuration" set image name to "test1"
* Deploy function
* Create another nuclio function that prints "Goodbye"
* In "Configuration" set image name also to "test1"
* Deploy second function
* Delete pod for the first function
The result is that the first function outputs "Goodbye" instead of "Hello"
**Solution:**
Added an option to configure image name prefix template.
any prefix that includes the project and function name should fix the problem.
the template will be used in 2 points:
* default function image name - so far was `processor-{{ functionName }}` now will be 
`{{ imageNamePrefix }}processor` (if template is provided)
* enforcement on custom image names provided by the user - if the user specify a custom …

Add option to configure a template for image name prefix

---

pkg/dashboard/ui/package.json

- Navigation tabs: fix wrong coloring
- Configuration tab › Volumes section: [bugfix] when two (or more) volume entries are expanded and there is uniqueness violation in some field among the expanded volume entries (so the same field in each entry is marked as invalid) — if then an entry is modified to be valid and is applied successfully, the rest of the expanded entries will be re-evaluated for their validity status, because they now may become valid.
- Triggers tab:
- Max Workers field:
- Turned into a *number* input field instead of regular *text* input field
- Added upper limit of 100000
- for Cron trigger kind: added Max Workers and Worker Availability Timeout Millis fields
- for Kafka trigger kind: added Max Workers field
Depends on PR …

UI: Triggers: Add Max Workers to Kafka trigger & more (see desc)

---

cmd/processor/app/processor.go
pkg/common/helper.go
pkg/common/map.go
pkg/common/map_test.go
pkg/containerimagebuilderpusher/kaniko.go
pkg/platform/abstract/platform.go

Changes:
- Remove ANSI colors from kaniko logs - it makes it non human readable, and doesn't compile with colors when printed on the UI
- Attach kwargs of logs when formatting and prettifying them (used to not show them before)
- Fixed kaniko truncation bug (string index out of bound)

Improve logs and format kaniko logs

---

cmd/controller/app/controller.go

This is to handle better heavier load of nuclio functions (meaning higher number of nucliofunction crd records).
It is also possible to up the worker concurrency on the queue, but let's start with this

Upping controller's resync interval to 10min

---

pkg/dashboard/ui/package.json
pkg/dashboard/ui/src/app/components/data-wrappers/create-function-data-wrapper/create-function-data-wrapper.component.js
pkg/dashboard/ui/src/app/components/data-wrappers/create-function-data-wrapper/create-function-data-wrapper.tpl.html

- On creating a new function or duplicating an existing one, a function name uniqueness violation test is performed to early prevent the user from using a name that is already in use (until today the error would occur only on deploy after all fields of the function were filled)
- Triggers: the Password field now has concealed characters
- Volumes:
- [bugfix] when naming a volume with a name that is already in use by other volume, and then deleting one of the volumes that share the same name — all volumes were deleted
- [bugfix] when using the same mount path to a volume which is already in use and expanding another volume and focusing on its mount path field — the field got set invalid, and when fixing the collision, the field remained invalid even though the collision was resolved
- When …

[Nuclio] Add name uniqueness validation to functions

---

pkg/dashboard/resource/functionevent.go
pkg/dashboard/resource/project.go

To align with the healthy behaviour (see https://github.com/nuclio/nuclio/pull/1483)
Aligning `GET` on `/api/projects/:id` and `/api/functionevent/:id`

Detail endpoints to return 404 on missing resources

---

pkg/dashboard/ui/package.json

- Function list: [bugfix] sorting by “Status” column was broken.
- Function:
- Test pane: when selecting a saved function event, its request body type now defaults to “Text” instead of “File”.
- Configuration:
- Build › Image: added template prefix if exists, and what the default would be if the field is left empty. 
- Labels: added a tooltip when labels are disabled on already-deployed functions. 
- Triggers: [bugfix] after a function is deployed and the success ribbon appears, if a trigger was deleted it caused the action bar (where the deploy button is) to be hidden. 
Depends on PR https://github.com/iguazio/dashboard-controls/pull/897

UI: Default function event request body type to Text + more

---

docs/reference/triggers/kafka.md

@liranbg / @pavius please merge. I'll do a thorough doc review and submit a separate; this is just a first-aid spell-check fixes PR.

[DOC REVIEW for PR #1496] Kafka trigger reference: Fix typos

---

pkg/common/helper.go
pkg/processor/build/builder.go
pkg/processor/build/runtime/java/docker/onbuild/Dockerfile
pkg/processor/build/runtime/java/runtime.go

```
Reminder:
Standard java project directory structure is - `src/main/java`
```
This fix prevents double creation of standard directory structure, an example for this:
if a given nuclio Java function is already in the structure `src/main/java` a double structure will be `/src/main/java/src/main/java/...`

Fix - Java project structure double creation

---

hack/k8s/helm/nuclio/templates/NOTES.txt
hack/k8s/helm/nuclio/values.yaml

Commenting that out forces the user to provide with a `secretName`
instead, use defaults 
fixes a regression made by #1495

Fix missing secretName value

---

cmd/processor/app/processor.go

Introduced to prevent the case where the health-check servers starts, and the function is marked as healthy and ready, but there's a failure after a moment when starting other processor components (such as triggers)

Start health-check server after processor started successfully

---

README.md
docs/setup/k8s/getting-started-k8s.md
docs/setup/k8s/running-in-production-k8s.md
hack/k8s/helm/nuclio/templates/deployment/dashboard.yaml
hack/k8s/helm/nuclio/values.yaml
pkg/containerimagebuilderpusher/kaniko.go
pkg/containerimagebuilderpusher/types.go
pkg/platform/factory/factory.go

- Added a new `running-in-production-k8s.md` doc to help orient users towards using nuclio in production
- Properly passing `kaniko` executor image details to dashboard from helm values

Docs - Running nuclio in production over k8s

---

cmd/processor/app/processor.go

1. Immediately respond to /ready and /live
2. /live will always return 200
3. /ready will return 503 unless processor's Start() completed and all workers indicate they are ready

Respond immediately to /ready and /live

---

docs/setup/k8s/running-in-production-k8s.md
hack/k8s/helm/nuclio/Chart.yaml
hack/k8s/helm/nuclio/templates/deployment/dashboard.yaml
hack/k8s/helm/nuclio/values.yaml

Needed to override base image (whether default or given) - for true kaniko darksite

Allow control of dependant registry URL override in helm chart

---

pkg/containerimagebuilderpusher/kaniko.go

Truncating function name may result in '-' being the last character which is invalid for k8s job name

Fixed kaniko job naming

---

pkg/common/consts.go
pkg/common/map.go
pkg/platform/abstract/platform.go
pkg/platform/abstract/platform_test.go
pkg/platform/abstract/test/logs_examples/go_with_call_stack/brief_errors_message.txt
pkg/platform/abstract/test/logs_examples/go_with_call_stack/formatted_function_logs.txt
pkg/platform/abstract/test/logs_examples/go_with_call_stack/function_logs.txt
pkg/platform/abstract/test/logs_examples/multi_worker/brief_errors_message.txt
pkg/platform/abstract/test/logs_examples/multi_worker/formatted_function_logs.txt
pkg/platform/abstract/test/logs_examples/multi_worker/function_logs.txt
pkg/platform/abstract/test/logs_examples/panic/brief_errors_message.txt
pkg/platform/abstract/test/logs_examples/panic/formatted_function_logs.txt
pkg/platform/abstract/test/logs_examples/panic/function_logs.txt
pkg/platform/abstract/test/logs_examples/special_substrings/brief_errors_message.txt
pkg/platform/abstract/test/logs_examples/special_substrings/formatted_function_logs.txt
pkg/platform/abstract/test/logs_examples/special_substrings/function_logs.txt
pkg/processor/runtime/python/py/_nuclio_wrapper.py
pkg/processor/runtime/python/py/requirements.txt
pkg/processor/runtime/rpc/abstract.go

Improving and fixing **brief errors log** on several deployment failure cases.
Changes:
---
- On multiple workers trigger - show only the errors of the first worker
- Remove redundant Call Stack log lines
- Remove redundant lines after a Worker fails with panic
_(all those lines can still be found in the full log)_

Brief logging fixes

---

pkg/processor/trigger/http/trigger.go

Disabling as fasthttp implementation contains string comparison which will reduce performance

Disable fasthttp log all errors feature

---

pkg/processor/runtime/python/py/_nuclio_wrapper.py
pkg/processor/runtime/rpc/abstract.go

added the minimum supported float64 number if duration is zero

Fix metric response returns with zero due to blazing fast function

---

hack/k8s/helm/nuclio/templates/deployment/dashboard.yaml
hack/k8s/helm/nuclio/values.yaml
pkg/containerimagebuilderpusher/containerimagebuilder.go
pkg/containerimagebuilderpusher/docker.go
pkg/containerimagebuilderpusher/kaniko.go
pkg/containerimagebuilderpusher/types.go
pkg/platform/abstract/platform.go
pkg/platform/factory/factory.go
pkg/platform/mock/platform.go
pkg/platform/platform.go
pkg/processor/build/builder.go
pkg/processor/build/runtime/dotnetcore/runtime.go
pkg/processor/build/runtime/golang/runtime.go
pkg/processor/build/runtime/java/runtime.go
pkg/processor/build/runtime/nodejs/runtime.go
pkg/processor/build/runtime/pypy/runtime.go
pkg/processor/build/runtime/python/runtime.go
pkg/processor/build/runtime/ruby/runtime.go
pkg/processor/build/runtime/runtime.go
pkg/processor/build/runtime/shell/runtime.go

The motivation for this change is the need to have different behavior for the *default* base images, and custom, *user supplied* (upon function config) base images in air-gapped systems for *kaniko* container builder kind.
- Onbuild images default to `quay.io` registry, but should be point-able to any user given accessible registry in an air-gapped system (dark site).
- Base images don't have a single default registry across runtimes; Each runtime pulls a different default base image from the web (`docker.io` or `mcr` for example). Still, for *air-gapped* systems, this behavior should be overridable, such that all default base images  will be taken from a single accessible, user-provided registry. While the above remains, *user-provided base images*, would not be automatically pulled from …

Onbuild and base image registries to be controlled separately

---

pkg/processor/runtime/golang/test/_outputter/outputter.go
pkg/processor/runtime/golang/test/golang_test.go
pkg/processor/trigger/http/trigger.go

* handling the case where the user return pointer to `nuclio.ErrorWithStatusCode`
* writing the error message in the response body

Fixing returned error handling in http trigger

---

pkg/platform/abstract/platform.go
pkg/platform/kube/platform.go
pkg/platform/local/platform.go

When creating many functions in parallel while trying to get functions it panics as `DeployLogStreams` is not yet safe concurrency read/write
Using `sync.Map` we achieve a locking mechanism to make `DeployLogStreams` concurrency safe (aka thread-safe)
Dev logs:
```
fatal error: concurrent map writes
goroutine 602 [running]:
runtime.throw(0x17964b4, 0x15)
/usr/local/go/src/runtime/panic.go:616 +0x81 fp=0xc42073de18 sp=0xc42073ddf8 pc=0x42add1
runtime.mapassign_faststr(0x156a2a0, 0xc42024bc50, 0xc420d41b80, 0x19, 0x1)
/usr/local/go/src/runtime/hashmap_fast.go:779 +0x3ce fp=0xc42073de88 sp=0xc42073de18 pc=0x40b8fe
github.com/nuclio/nuclio/pkg/platform/kube.(*Platform).CreateFunction(0xc4204951c0, 0xc42046fc00, 0x239b828, 0xc420a43440, 0x4) …
```

Use sync.Map for DeployLogStreams locking mechanism

---

pkg/processor/runtime/nodejs/wrapper.js

Some runtimes are missing metric output in runtime handler. #1248 
I added Nodejs metrics, and minimum duration seconds to dodge returning value to zero.
Prometheus metrics:

Add Nodejs metrics

---

pkg/processor/runtime/shell/runtime.go

Some runtimes are missing metric output in runtime handler. #1248
I added shell runtime metrics.
Prometheus is here:

Add shell metrics

---

pkg/nuctl/test/function_test.go
pkg/processor/build/builder.go

Set it to `Image` CET so it will be redeploy-able via the UI

Nuctl update local directory path function as image CET

---

pkg/platform/kube/deployer.go
pkg/platform/kube/function.go
pkg/platform/kube/functionres/lazy.go

Far from air tight, but simple and will cover 99% of cases
This needs to be reopened when we have a strategy to avoid function name collision between same-namespace projects (in which case we might prefix everything or some other crazy notion)

Reduce chance of k8s resource name conflicts with external resources

---

cmd/dashboard/docker/runner.sh

using `--jobs 0` to unlimit # of jobslots

Fix parallel not running all jobs on single-core machines

---

pkg/containerimagebuilderpusher/docker.go

Due to a bug on initializing docker platform, it is not getting the default values correctly (unlike in kube platform)
This is a hotfix for `:unstable` images until a complete fix will be done.

Docker build fix - not getting default onbuild registry correctly

---

pkg/dashboard/ui/src/app/shared/services/import.service.js
pkg/dashboard/ui/src/less/mixins.less
pkg/dashboard/ui/src/less/palette.less

- Import/export projects: improve UX flow by allowing the users to choose between skipping or replacing conflicted function names within the same project, and allowing to take the same action for all subsequent conflicted functions in the same imported project, or in all subsequent projects as well.
Depends on PR https://github.com/iguazio/dashboard-controls/pull/968

[Nuclio] Import: skip/override functions with same name

---

cmd/dashboard/docker/runner.sh

Fix nuclio dashboard image stuck on citing when running interactively (`docker run -ti`)

Fix citation

---

pkg/processor/build/builder.go

Bug: If image name is given, and contains a tag (e.g.: `v1.2`), it will defaults to `imageName:v1.2:latest`

Fix appending latest

---

pkg/processor/runtime/python/runtime.go

Bug: If a function base image contain PYTHONPATH, processor image will override its previous content.

Fix: preserve PYTHONPATH if provided

---

cmd/processor/Dockerfile
pkg/containerimagebuilderpusher/docker.go
pkg/dockerclient/shell.go
pkg/nuctl/command/nuctl.go
pkg/processor/runtime/python/runtime.go

- Reduced processor image from 850mb to 30mb
- Tweak build logs (allowing better readability when using `nuctl`)
- Allow user to use different python exe path (by providing `NUCLIO_PYTHON_EXE_PATH` as environment variable)

Some tweaks and improvements

---

pkg/dashboard/ui/package.json
pkg/dashboard/ui/src/app/components/projects/edit-project-dialog/edit-project-dialog.component.js
pkg/dashboard/ui/src/app/components/projects/new-project-dialog/new-project-dialog.component.js

- Function › Code › Test pane › Request › Path: do not hide border of field when idle
- Before:
- After:
- Function › Configuration › Resources: move "Inactivity window" filed to production 
- Function › Triggers:
- All kinds: add a red asterisk to mark mandatory fields.
- HTTP › annotations: [bugfix] Key field was not mandatory, now it is.
- Cron › Event handlers:  [bugfix] Key field was not mandatory, now it is.
Depends on PR https://github.com/iguazio/dashboard-controls/pull/975

UI: Handle forms better; Add mandatory fields

---

pkg/platform/kube/platform.go

When function deployments fails on `build` stage - we want to present the _call stack_ inside the `Error` pane (as shown on the image below) - because this is where the relevant information to debug this problem is at 
(Before this fix the only thing that was shown inside the error pane was the exit status code)

Show call stack on build function failures (on brief errors message - a.k.a the 'Error' pane)

---

pkg/nuctl/command/get.go
pkg/nuctl/command/nuctl.go
pkg/nuctl/test/function_test.go

- Added test to ensure `nuctl get function --output json|yaml` returns with a valid `json|yaml`
- Info level logging -> debug level to avoid unneeded loggings  upon `nuctl get <resource>`

Fixed nuctl get resource as yaml/json returned with info level logs

---

pkg/dockerclient/shell.go

Bug: `NUCLIO_DOCKER_BUILD_NETWORK` env may be initialized with `none`, in that case, `common.GetEnvOrDefaultString` will default it to an empty string ("").
`NUCLIO_BUILD_USE_HOST_NET` is default in case no `NUCLIO_DOCKER_BUILD_NETWORK` is given.

Fix: docker build network env is overridden in case of `none`

---

pkg/dashboard/resource/function.go
pkg/dashboard/resource/functionevent.go
pkg/dashboard/resource/project.go
pkg/dashboard/resource/resource.go
pkg/dashboard/test/server_test.go
pkg/functionconfig/types.go
pkg/functionconfig/types_test.go
pkg/platform/abstract/platform.go
pkg/platform/kube/apis/nuclio.io/v1beta1/types.go
pkg/platform/kube/controller/nucliofunction.go
pkg/platform/kube/functionres/lazy.go
pkg/platform/kube/platform.go
pkg/platform/local/platform.go
pkg/platform/local/platform_test.go
pkg/restful/resource.go

Added the following functionalities for a Import/Export system:
Export:
- On `GET /api/functions[:/id]?export=true`: Scrub parts of the function data(like status) which is irrelevant to the export and add 2 annotations(`skip-build`, and `skip-deploy`) for the later import.
- On `GET /api/projects[:/id]?export=true`: Exports the project with all its function(in their exported format) and their function events.
Import:
- On `POST /api/functions`: If the function is posted with the above annotations, during this POST, the function will not be built or deployed, and the annotations are removed so on the next update, the function will be built and deployed.
- On `POST /api/projects?import=true`: This deals with the output of `GET /api/projects[:/id]?export=true` so it imports the project with …

Import and Export Functions & Projects in backend

---

docs/reference/triggers/http.md
pkg/common/helper.go
pkg/processor/test/suite/suite.go
pkg/processor/trigger/http/cors/cors.go
pkg/processor/trigger/http/http_test.go
pkg/processor/trigger/http/test/suite/http_test.go
pkg/processor/trigger/http/test/suite/suite.go
pkg/processor/trigger/http/trigger.go
pkg/processor/trigger/http/types.go
pkg/processor/trigger/trigger.go

tl;dr: Implemented https://github.com/nuclio/nuclio/issues/640
with some additional stuff (such as max-age, credentials)
To support CORS by the [following guideline](https://www.w3.org/TR/cors/#access-control-allow-methods-response-header), we required to ensure the function respond to a preflight requests (default on method `OPTIONS`), that have a price for the processor not delegating the request to the function (meaning, function will not be able to answer to `OPTIONS` when CORS is enabled)
A CORS is valid when returned code is 200, and invalid otherwise (currently, it will return 400 to any bad preflight request)

Added CORS support

---

pkg/platform/kube/functionres/lazy.go

**Bug:**
When more than 1 nuclio-controller is running (happens during rolling-upgrade) and a function is deployed - deployment will fail with "configmaps _function-name_ already exists" (configmap is just the first resource to be created on function deployment flow)
This happens because the second controller will try to create the function's configmap after the first already has - and it will change the function's state to _error_.
**Solution:**
Solves this problem by just retrying to create/update the resource whenever this happens - so on the second iteration it will just update the resource (because it already exists) instead of creating.

Fix function deployment failure when deploying with more than 1 controller pod

---

hack/k8s/helm/nuclio/templates/deployment/autoscaler.yaml
hack/k8s/helm/nuclio/templates/deployment/controller.yaml
hack/k8s/helm/nuclio/templates/deployment/dashboard.yaml
hack/k8s/helm/nuclio/templates/deployment/dlx.yaml

This will ensure a pod restart upon changes of registry credentials / url and other spec changes which require restarts
- Adding docker url configmap/secret as checksums to dashboard pod template

K8s helm charts - Adding configmaps/secrets to pod spec annotations to invoke pod restarts

---

pkg/dockerclient/shell.go

Bug description:
Upon function build burst, there's a race condition between a built function that removes its cached layers to a new function being built that try to reused that very cached layer.
Since we use `--force-rm` to eliminate both successful & failed builds containers, we strike with an error `No such image: sha256:....\n` in which tells us that the cached layer we are trying to retrieve is gone. (we distinguish between existing image and cached layer when using `sha256:` as a prefix to the cached layer name)
To tackle this we are left with 2 options
1. Use the default `--rm=true` in which eliminate successful builds only, but that means we would need to handle removal of failed build leftovers (containers and etc)
2. Retry when such an error happened
option (2) is implemented …

Retry on function build failed due to missing cached layer

---

docs/reference/triggers/http.md
docs/reference/triggers/kafka.md

@liranbg in addition to the PR #1640 HTTP trigger CORS review, I also fixed a typo in the Kafka trigger reference ("authenticatio" > "authentication") — see commit 05b9ffb. Please merge this fix also to `1.3.x` and any other active branches.

[DOC REVIEW for PR #1640] HTTP trigger: add CORS attributes; Kafka trigger reference: fix typo

---

docs/reference/triggers/v3iostream.md

@pavius NOTE: As I wrote you on Slack, the value of the function trigger's `URL` configuration field — `http://v3io-webapi:8081/users/test-stream-0@cg0` seems wrong to me.
(a) The `@cg0` at the end seems wrong.
(b) I'm not sure whether it should be `http://v3io-webapi:8081` or the API URL of the user platform's web-APIs service.
UPDATE: Eran confirmed that the URL is correct and explained that `@cg0` at the end is the consumer group, as described earlier in the same document (when we explain how to set the **URL** dashboard field). => @pavius I've now slightly edited the description of the **URL** UI field in the example to clarify this — commit 9339c4c:
> **URL** - `http://v3io-webapi:8081/users/test-stream-0@cg0` (where `/users/test-stream-0` is the stream path and `cg0` is the name of …

[DOC REVIEW for PR #1648] v3ioStream trigger reference: new example using v3ctl

---

.github/workflows/ci.yaml
Makefile
docs/devel/contributing.md
docs/reference/runtimes/nodejs/nodejs-reference.md
pkg/common/helper.go
pkg/common/helper_test.go
pkg/dockerclient/shell.go
pkg/nuctl/test/suite.go
pkg/platform/abstract/platform_test.go
pkg/platform/local/platform_test.go
pkg/processor/build/runtime/nodejs/runtime.go
pkg/processor/runtime/dotnetcore/test/dotnetcore_test.go
pkg/processor/test/suite/suite.go
pkg/processor/trigger/cron/test/cron_test.go
pkg/processor/trigger/http/test/suite/suite.go
pkg/version/version.go

This PR introduce some fixes, update and mainly prepare the ground to auto integration tests to run
- Build fix
- Added a retry on `failed to get digest sha256:` that happened when the overlay image is gone from disk (just like `No such image: sha256:`) that simply indicate the image is gone from cache.
- Test fixes (integ mainly)
- Fixed transient error on cron triggers
- Added `version.SetFromEnv()` for tests purposes to inject version during tests
- `blastHTTP` tests - wait for function to be healthy and answer a dummy call before blasting it.
- Base image update
- Updated base image for node to`node:10.20-alpine` due to a bug on npm
- CI updates
- Updated packages and versions for github workflow
- Added `nuctl docker test` that will give `nuctl` integration test against docker …

Build fix, alpine-base update, and test fixes

---

pkg/nuctl/command/nuctl.go
pkg/nuctl/test/function_test.go
pkg/platform/kube/deleter.go
pkg/platform/local/platform.go

Bug: When deleting (`DELETE /api/<resource>/<resource-id>`) a non-existing resource, an error is returned as `Internal Server Error (500)`
To solve that, we ensure _delete_ action on resources are idempotent

Make delete resource idempotent

---

pkg/nuctl/command/nuctl.go
pkg/nuctl/test/function_test.go
pkg/platform/kube/deleter.go
pkg/platform/local/platform.go

backports https://github.com/nuclio/nuclio/pull/1662 to 1.3.x

Make resource deletion idempotent [1.3.x backport]

---

pkg/dockerclient/dockerclient.go
pkg/dockerclient/mock.go
pkg/dockerclient/shell.go
pkg/platform/local/platform.go
pkg/platform/local/platform_test.go

This pr will allow nuclio dashboard to monitor unhealthy function containers to validate whether its containers are healthy so the function state would be set to `ready` again.
That will complete issue #1668 in terms of monitoring function states when function container healthiness changes.
In order to ensure the monitor is on, it is required to provide nuclio-dashboard with env `NUCLIO_CHECK_FUNCTION_CONTAINERS_HEALTHINESS` with value of `true`
The monitor will work on two modes
- check healthy function against its container health, if container isn't healthy, set function as unhealthy as well
- check unhealthy function, that its state was previously changed by nuclio, against its container health, if container is healthy, set function as healthy as well

Improve docker platform function containers healthiness

---

cmd/autoscaler/Dockerfile
cmd/dlx/Dockerfile
hack/docker/build/base-alpine/Dockerfile
hack/docker/build/base/Dockerfile
hack/docker/build/builder/Dockerfile
pkg/functionconfig/reader_test.go
pkg/nuctl/command/build.go
pkg/playground/fixtures/source.go
pkg/processor/build/runtime/golang/docker/onbuild/Dockerfile
pkg/processor/build/runtime/golang/docker/onbuild/Dockerfile.alpine

Follow up with https://github.com/v3io/scaler/pull/39
Locking go version on 1.14.3 so clients will no panic on `plugin was built with a different version of package internal/cpu` when CGO runtime version is different

Lock go version (1.14.3)

---

pkg/dashboard/ui/src/app/app.run.js

Originated in PR https://github.com/nuclio/nuclio/pull/1676
Shame on me, shame on me, shame on me!

UI: Fix `namespace` instead of `platformKind` (erann's fault)

---

.dockerignore

- Avoid shoving .git into built docker images (🤦 )
- Ignore changes made on `Dockerfiles` forcing the entire layers to be rebuilt

Backport .dockerignore improvements

---

pkg/platform/kube/function.go

Typo fix
Function ingress address is currently being used only for invoking function via `loadbalancer`

Function ingressAddress is always empty

---

docs/reference/triggers/http.md
pkg/processor/trigger/http/test/suite/http_test.go
pkg/processor/trigger/http/trigger.go
pkg/processor/trigger/http/types.go

Making fast http max request body size configurable allowing us to tweak & modify allowed request body size in essense of
1. Limiting the request body buffer to a smaller than default (4mb)
2. Increasing the allowed body size (for those of you sending large request body)
Note:
Since this change is only on the processor size, the limitation on runtimes such as python will not accept (2) yet. This will followed by another pr to make it configurable on the runtime side.

Allow configuring http max body size

---

Makefile
pkg/dashboard/test/server_test.go
pkg/dockerclient/shell.go
pkg/dockerclient/types.go
pkg/nuctl/test/function_test.go
pkg/platform/local/platform.go
pkg/platform/local/test/platform_test.go
pkg/processor/test/readinesstimeout/suite_test.go
pkg/processor/timeout/timeout_test.go
test/_functions/common/event-returner/golang/eventreturner.go
test/_functions/common/long-initialization/golang/sleepy.go
test/compare/compare_test.go

When waiting for container healthy, if container exited, no need to wait until it becomes healthy as when running on local platform, nothing will restart / resolve its issue so fail-fast, that would save some valuable time waiting for doomed functions

Local platform fail fast when container exited

---

pkg/dashboard/ui/package.json

Function › Triggers:
- Name field:
- Added validation rules 
- Assign input value to the `name` property of the trigger
- Changed generic error message "The input you provided is invalid or incorrect" to a more specific "Name is required"
- Kafka cluster:
- Renamed:
- "Consumer Group" to "Consumer group name"
- Removed:
- "SASL Enable"
- Added:
- "Worker allocation mode"
- "Session timeout"
- "Heartbeat interval"
- "Bytes to fetch (default)"
- "Rebalance timeout"
- "Rebalancing grace period"
- V3IO Stream:
- Modified:
- "URL":
- Renamed to "Remote URL"
- Mandatory only as long as "Container name" is empty
- "Polling Interval Ms": renamed to "Polling Interval"
- "Seek to": renamed to "Initial offset"
- "Read batch size": added "Bytes" suffix
- Removed:
- "Username"
- "Password"
- …

UI: Triggers Kafka & V3IO stream refactor

---

hack/k8s/resources/nuclio-rbac.yaml

This file contains nuclio rbac rules and being used when installing nuclio directly via `kubectl` (from tuturials)

Add missing rules to nuclio rbac

---

.github/workflows/ci.yaml
Makefile
pkg/processor/runtime/python/py/_nuclio_wrapper.py
pkg/processor/runtime/python/py/requirements/dev.txt
pkg/processor/runtime/python/py/test_wrapper.py
pkg/processor/runtime/python/test/Dockerfile
pkg/processor/runtime/python/test/test.sh

Motivation is #1696 and now it is possible after #1689 is merged.
Since the processor handle the max body size limit before reaching out to the python wrapper.
Bonus 👉 : removal of the preallocated buffer (on python wrapper side) of 4mb cause to reduction of `4mb * workers`
CI Bonus: running python wrapper tests to ensure no breakage is made.
Attached are logs of a deployed nuclio [function](https://raw.githubusercontent.com/nuclio/nuclio/development/hack/examples/python/empty/empty.py) running on 20 cores machine
Executed with `./hey -n 20 -c 20 -z 2m`
Pre change:
```
PID %MEM %CPU   RSS    SZ    VSZ
142936  0.0 12.1 18552 19882  79528
142943  0.0  9.5 18320 19856  79424
142949  0.0  9.4 18320 19856  79424
142950  0.0  9.3 18316 19851  79404
142951  0.0 12.6 18556 19882  79528
142952 …
```

Removed python body size limitation

---

pkg/processor/trigger/http/cors/cors.go
pkg/processor/trigger/http/http_test.go
pkg/processor/trigger/http/trigger.go
pkg/processor/trigger/http/types.go

The previous CORS flow did not handle simple cross requests. That means that GET request we're never treated when cors was enabled.
Following the [chart](https://en.wikipedia.org/wiki/Cross-origin_resource_sharing#/media/File:Flowchart_showing_Simple_and_Preflight_XHR.svg)
The current CORS flow cover simple cross request

Fixed CORS for browsers

---

pkg/nuctl/test/function_test.go
pkg/platform/kube/platform.go
pkg/processor/build/builder.go
pkg/registry/registry.go

Bug:
1. create a function
2. redeploy while function build phase failed (e.g.: failed to find handler / runtime)
3. process failed with "Report creation failed" instead of "Failed to find handler"
The reason it failed is because the `existingFunctionInstance` was not populated when build failed.
Solution, resolve both existingFunctionConfig and existingFunctionInstance at the same time.

Fix function creation report error failed on existing function

---

pkg/platform/abstract/platform.go
pkg/processor/build/builder.go

Python is just a reference to 3.6.
To unmask what is running, enrichment should dereference between python to its actuall running runtime version.

Populate version when runtime is python 

---

pkg/nuctl/command/invoke.go
pkg/nuctl/test/function_test.go
pkg/platform/abstract/invoker.go

- Populate from `--content-type` flag, then from given headers (`--headers content-type=<X>`)
- If population return with no content type, default to `http.DetectContentType` value
- Allow populating content type from both `--content-type` flag and `--header content-type=<X>`)

Fix resolving content type

---

pkg/processor/runtime/python/py/_nuclio_wrapper.py
pkg/processor/runtime/python/test/python_test.go
pkg/processor/test/suite/suite.go
pkg/processor/trigger/http/test/suite/suite.go
test/_functions/common/empty/python/empty.py

Msgpack by default limit the max buffer to 1MB to avoid denial of service.
Since the msgpack is part of python runtime wrapper, it is not required to ensure/validate the max buffer as the [processor](https://github.com/nuclio/nuclio#processor) will take of it by ensuring the body size is less than the allowed max body configuration.

Increase msgpack for python

---

pkg/containerimagebuilderpusher/docker.go
pkg/dockerclient/shell.go

Docker might not find a local image althought it was just recently created due to high load.
Using `RetryUntilSuccessfulOnErrorPatterns ` for error caused by such case (`unable to find image 'x' locally`).

Retry function build if docker failed to find its produced image

---

pkg/dashboard/ui/package.json

See https://github.com/gulpjs/gulp/issues/2246
This dependency could be removed if Gulp v3 will no longer be used in this codebase (for example, migrate to Gulp v4, or Webpack).
Relates to PR https://github.com/iguazio/dashboard-controls/pull/1030

UI: Build: Fix Gulp v3 failure on newer NodeJs versions

---

.github/workflows/periodic.yaml
Makefile
README.md
pkg/processor/test/suite/suite.go
pkg/processor/trigger/kafka/test/kafka_test.go
pkg/processor/trigger/test/broker.go

- Adding periodic (12h intervals) tests to run on the default branch (`development` today)
- This runs `make test-periodic` (~2h runtime) - which is the full test suite, *without* kafka trigger tests which I could not get to work in the GH actions VM (hostname resolution sarama <-> kafka) - This needs to be fixed and added asap
- Leaving in some minor fixes and changes I've made to `Makefile`, introducing `test-build` reuse, allowing to run the `test-periodic` targets easily, and also `test-kafka` specifically which should ease future testing.
- Minor logging changes in test suites

GH Actions - Adding periodic tests

---

pkg/nuctl/command/import.go

On `nuctl import projects <projectManifestFile>` it is possible to add the flag `--skip <projectName>[,<projectName>,...]` to skip importing specific projects from the given project manifest.

Add skip flag to nuctl import projects

---

cmd/dashboard/README.md
pkg/dashboard/resource/project.go

Some bug fixes
1. `x-nuclio-project-namespace` header is optional, as it fallback to default namespace given by the dashboard
2. Project `displayName` field is deprecated, no need that any more.
3. Enrich project create request with `spec` if not given, to prevent panic

Minor doc update + bug fixes

---

pkg/processor/runtime/python/py/_nuclio_wrapper.py
pkg/processor/runtime/python/py/test_wrapper.py

Current behavior: In case client disconnect from wrapper (processor), the wrapper terminate gracefully. this lead to unexpected behavior where the processor did not handle wrapper exiting gracefully.
Fix: in case of _fatal error_ (such as client disconnect), wrapper will _try_ log and exit with status code 1.
This should trigger the processor to handle the wrapper termination (such as restarting wrapper process)
- Added a python nuclio wrapper test to ensure failing function (due to runtime error, or so) return with response
- Slight refactor (mainly moving functionality parts from _ serve_requests_ to functions (readability reasons)

Nuclio python wrapper termination fix

---

pkg/processor/build/builder.go

Python is just an _alias_ to python:3.6

Fix resolving runtime name for python

---

cmd/controller/main.go
docs/reference/triggers/cron.md
pkg/platform/kube/controller/cronjobmonitoring.go
pkg/platform/kube/deployer.go
pkg/platform/kube/functionres/lazy.go

Cron job fixes.
Changes:
- Changed "cronJobStalePodsDeletionInterval" to be 1min instead of 10min (prevent many stale pods running on the system)
- Limit job history to 1 (makes kube jobs api clearer)
- Added `jobBackoffLimit` to cron trigger spec. Limiting the number of retries before failing a job (defaults to 2, to reduce stress on the system - relevant especially for triggers with low cron interval)
- Fix - prevent functionPods List from selecting cron-job pods

Cron job fixes

---

pkg/platform/kube/deployer.go

**Bug:**
"NuclioFunction pod (nuclio-somefunc-56bcc67685-z6q9p) container exited with an error" error is shown when replicas is increased on function re-deploy.
This happened as a result of the orchestration mechanism of k8s, that lifts more pods then it should, and then makes one of them exit to reach the wanted number of replicas.
In the same moment the redundant new pod was marked as 'Exited' with an error, we caught it, and failed-fast the function because of it.
**Solution:**
Removing the part where we fail-fast when the container is in "Exited" state.
This will prevent this bug, and will not harm the fail-fast mechanism, because when the function deploy should _really_ fail fast it will change it state to "crashLoopBackoff"

Fix - function "fails-fast" when redeploying with a higher number of replicas

---

cmd/dashboard/app/dashboard.go
hack/k8s/helm/nuclio/README.md
hack/k8s/helm/nuclio/templates/deployment/dashboard.yaml
pkg/containerimagebuilderpusher/containerimagebuilder.go
pkg/containerimagebuilderpusher/docker.go
pkg/containerimagebuilderpusher/kaniko.go
pkg/dashboard/server.go
pkg/dashboard/test/server_test.go
pkg/dockercreds/dockercred.go
pkg/platform/abstract/platform.go
pkg/platform/kube/platform.go
pkg/platform/mock/platform.go
pkg/platform/platform.go
pkg/processor/build/builder.go
pkg/processor/build/runtime/dotnetcore/factory.go
pkg/processor/build/runtime/golang/factory.go
pkg/processor/build/runtime/java/factory.go
pkg/processor/build/runtime/nodejs/factory.go
pkg/processor/build/runtime/pypy/factory.go
pkg/processor/build/runtime/pypy/runtime.go
pkg/processor/build/runtime/python/factory.go
pkg/processor/build/runtime/ruby/factory.go
pkg/processor/build/runtime/runtime.go
pkg/processor/build/runtime/shell/factory.go

- This removes the hostpath & volume for the host dockerd socket from the dashboard deployment.
- Hence, no usage of docker can or should be made when kaniko is used
Not requiring docker bind mount was the main drive behind integrating kaniko, because mounting the docker socket embodies several security issues (hospath, host IPC, escalation via docker) puts restriction on running user vs host fs permissions (observed in openshift default scc) etc

Remove dashboard bind-mount to docker socket when using Kaniko container builder

---

.github/workflows/ci.yaml
.github/workflows/periodic.yaml
.github/workflows/release.yaml

It's wasteful to spam all forker's repos with periodic, changing GH action's periodic workflow to only run on main repo
Adding missing github context dumps for debugability

Periodic test - run only for upstream repo

---

hack/k8s/helm/nuclio/templates/role/crd-admin.yaml
hack/k8s/helm/nuclio/templates/role/function-deployer.yaml
hack/k8s/helm/nuclio/templates/rolebinding/function-deployer.yaml
hack/k8s/helm/nuclio/values.yaml
hack/k8s/resources/nuclio-rbac.yaml

- Function deployer can be a cluster role (and need cluster role binding) if in multi-namepace mode. Other wise:
1. Broken for all but the same namespace of controller / release (if helm)
2. cronJob stale pod monitor will fail Listing pods in cluster scope
- Missing namespaces in cluster role

RBAC fix for multi-namespaced nuclio installation

---

cmd/controller/app/controller.go
cmd/controller/main.go
docs/reference/triggers/cron.md
pkg/platform/kube/controller/controller.go
pkg/platform/kube/controller/cronjobmonitoring.go
pkg/platform/kube/functionres/lazy.go

1. In order to reduce stress on the system that may be caused by having multiple cron jobs with low interval, we decided to set the default concurrencyPolicy to 'Forbid'
2. In order to decrease the failure rate of cron jobs, we're now retrying to perform the Curl operation for 10 seconds
3. Added `deleteStaleJobs()` task to the `cronJobStaleResourcesCleanup` cycle - as there're failed jobs that stay forever up on a specific bug (when jobFailures > jobBackoffLimit)

Cron job robustness enhancements

---

.run/(kube) nuctl test.run.xml
pkg/functionconfig/types.go
pkg/nuctl/command/get.go
pkg/nuctl/test/function_test.go
pkg/nuctl/test/suite.go
pkg/platform/abstract/platform.go
pkg/platform/kube/functionres/lazy.go

Bug:
1. Create function without http trigger
2. Function deployed successfully, a random port number X was allocated
3. Redeploy function with http trigger with a specific port Y
4. Function still listen on port X
Expected:
Function listen on port Y
RCA:
When giving an HTTP trigger, the port is unmarshaled from the `attributes` block (each trigger has an attributes block for additional trigger attributes)
Since the unmarshaling return with int of type 64, which was not expected for the type assertion, the port was not converted and returned with 0
Solution:
Adding type assertion for int64 as well
Bonus:
- Test to cover function port changing between first and second deployments
-  `nuctl get function [function-name]` returns with status

Fix http trigger port type assertion

---

pkg/processor/build/runtime/golang/docker/onbuild/Dockerfile

When system is in a heavy load, sometimes building a go function would fail with this message:
```
Error - exit status 126
.../nuclio/nuclio/pkg/cmdrunner/cmdrunner.go:131
Call stack:
stdout:
Sending build context to Docker daemon  3.964MB
Step 1/3 : FROM quay.io/nuclio/handler-builder-golang-onbuild:unstable-amd64-alpine
---> Running in fba76b7cd32c
Removing intermediate container fba76b7cd32c
---> Running in 65b11a397eda
Removing intermediate container 65b11a397eda
---> Running in 9b2fbdb35383
/bin/sh: ./moduler.sh: Text file busy
Removing intermediate container 9b2fbdb35383
stderr:
The command '/bin/sh -c mv /moduler.sh . && chmod +x moduler.sh && ./moduler.sh' returned a non-zero code: 126
.../nuclio/nuclio/pkg/cmdrunner/cmdrunner.go:131
Failed to build onbuild image …
```

BugFix - Made Dockerfile for golang wait for chmod to complete fully on disk before running script

---

pkg/dashboard/resource/function.go

Bug:
When updating a function on a namespace different that what nuclio installed on, it fails with function not exists
The reasons for that
1. UI does not include the `x-nuclio-function-namespace` header
2. BE does not try to read the namespace from the function body as well (as fallback in case header does not exists)
Note: this bug occur on nuclio installed with helm value of `rbac.crdAccessMode=cluster`
closes #1761

Fix resolving namespace

---

pkg/processor/build/inlineparser/jarparser_test.go
pkg/processor/build/inlineparser/parser_test.go
pkg/processor/build/runtime/golang/test/golang_test.go
pkg/processor/build/runtime/java/test/java_test.go
pkg/processor/build/runtime/test/suite/suite.go
pkg/processor/runtime/golang/test/golang_test.go
pkg/processor/runtime/golang/test/timeout_test.go
pkg/processor/runtime/java/test/java_test.go
pkg/processor/runtime/python/test/python_test.go
pkg/processor/runtime/python/test/timeout_test.go
pkg/processor/test/callfunction/golang/suite.go
pkg/processor/test/callfunction/python/suite.go
pkg/processor/test/cloudevents/suite.go
pkg/processor/test/offline/suite_test.go
pkg/processor/test/suite/suite.go
pkg/processor/trigger/http/test/suite/suite.go
test/_functions/python/timeout/timeout.py

When functions with python runtime hit a worker timeout it restarts automatically, sometimes the second request comes a bit before the actual restart and cause the test to fail
Migrated all `suite.DeployFunction` calls to `suite.DeployFunctionAndRequest` for those implementing `SendRequestAndVerify` within the _postDeployRequestVerifications_
Added `RetryUntilSuccessfulStatusCode` fields (along with `RetryUntilSuccessfulDuration`, `RetryUntilSuccessfulInterval`) so that upon verifying request (on `suite.DeployFunctionAndRequest`), it will retry upon failures

Fix timeout test suites

---

pkg/processor/trigger/http/cors/cors.go
pkg/processor/trigger/http/cors/cors_test.go
pkg/processor/trigger/http/http_test.go
pkg/processor/trigger/http/test/suite/http_test.go
pkg/processor/trigger/http/types.go

Aligning with https://fetch.spec.whatwg.org/#http-responses

Cors fix: preflight request max age cache should be 5 seconds by default

---

pkg/dashboard/ui/src/app/app.route.js

https://trello.com/c/YJsl2kNB/505-nuclio-triggers-are-not-saved-while-switching-tabs

[Nuclio] Triggers are not saved while switching tabs

---

pkg/processor/trigger/kinesis/test/kinesis_test.go
pkg/processor/trigger/kinesis/trigger.go
pkg/processor/trigger/test/broker.go

An integration test suite for kinesis trigger. Its configuration can be changed in case user would want to test against a production-like kinesis stream. by default it uses `instructure/kinesalite` image to get a kinesis playground env.
Bonus point: added the option to provide an custom URL for kinesis trigger to connect to. (used in the added test suite)

Added integration test for kinesis trigger

---

pkg/dockerclient/dockerclient.go
pkg/dockerclient/mock.go
pkg/dockerclient/shell.go
pkg/dockerclient/types.go
pkg/platform/abstract/platform.go
pkg/platform/kube/functionres/lazy.go
pkg/platform/kube/functionres/lazy_test.go
pkg/platform/local/platform.go

The current behavior is that nuclio build process allocates a "free" port and uses it to run the function container.
The issue is that the mechanism of "allocating" a port, releasing it, and using it to run a function container, does not ensure us it would be usable if allocated.
e.g. when system is under high load, the OS would still respond that the port is in use. (Happens mostly on our CI)
The solution is to let docker pick a random port, and build process will resolve it once container is running
Note: all explained above is for a case where user did *not* specify a port for his function http trigger.

Fix port allocation for functions running under docker platform

---

pkg/platform/abstract/platform_test.go

As per go 1.15 you can't do `string(i)` for `i` an `int` - it now has to go through a `rune`
See: https://github.com/golang/go/issues/3939
See also: https://github.com/golang/go/issues/32479
Now this issues a warning in go vet.
While in nuclio we use go1.14.2, the CI (GH actions) cache picked up go 1.15:
https://github.com/nuclio/nuclio/runs/1003538254?check_suite_focus=true
Notice: 
Because we pick up latest with ^1.14.0 which will pick up 1.15.x if available.

Fix CI tests - go 1.15 compatibility

---

hack/k8s/helm/nuclio/values.yaml
pkg/dashboard/resource/frontendspec.go
pkg/dashboard/test/server_test.go
pkg/functionconfig/types.go
pkg/platform/kube/functionres/lazy.go
pkg/platform/kube/test/platform_test.go
pkg/platformconfig/platformconfig.go
pkg/platformconfig/reader.go

- Added `kubeDefaultServiceType` to `platformConfig` and helm values
- Added `serviceType ` to `functionconfig.Trigger.Attributes`
- Exposed the default in `frontedSpec`
- For each function, its service's ServiceType is now chosen in this order:
- If the default/regular HTTP Trigger has a `serviceType` attribute - take that
- If the function spec has a `ServiceType` - take that (for backwards compatibility)
- Otherwise, take the default from `platformConfig`
- For backwards compatibility, the default is still `NodePort` but for security reasons it is recommended to change the default to `ClusterIP`
- Platform config was granted a new "kube" sub config, currently containing only `defaultServiceType`

Configurable ServiceType for functions

---

pkg/platform/abstract/platform_test.go

Backports #1799 to ensure ci tests passes for prs open against `1.4.x` branch

Fix CI tests - go 1.15 compatibility [backport 1.4.x]

---

hack/k8s/helm/nuclio/Chart.yaml

bumping minor to 0.7.x, as 0.6.x is here to track any nuclio 1.4.x changes/releases

Bump chart version to 0.7.0

---

.github/workflows/pr_label.yaml

Now that `pull_request_target` can be used, this PR can provide a better way to use the label-er action (as oppose to a cron that ran every 30 minutes)

Labeler - use pull_request_target instead of cron

---

docs/reference/function-configuration/function-configuration-reference.md
pkg/dockerclient/dockerclient.go
pkg/dockerclient/mock.go
pkg/dockerclient/shell.go
pkg/dockerclient/types.go
pkg/platform/local/platform.go
pkg/platform/local/test/platform_test.go
pkg/platform/local/types.go

Nuclio deploy a function while dumping its processor configuration to host `/tmp`, this allow us to share configuration between containers  (dashboard & deployed function) and nuctl (running from host).
Since `tmp` might get wiped every now and then, it result with errors when 
1. docker daemon tries to restart function
2. tmp dir is getting wiped during deploy
3. file permission changes
To use this feature, you would require to edit your function spec and set the platform attributes as follow
```
meta:
name: no-mount-binding-function
spec:
..my other spec fields..
platform:
attributes:
processorMountMode: volume
```
This should resolve 
- https://github.com/nuclio/nuclio/issues/1806
- https://github.com/nuclio/nuclio/issues/1812
- https://github.com/nuclio/nuclio/issues/1782
- …

Use docker volume to mount the processor config to function container

---

pkg/common/helper.go
pkg/functionconfig/types.go
pkg/nuctl/command/deploy.go
pkg/platform/kube/functionres/lazy.go
pkg/platform/kube/test/platform_test.go

Security context is the Kubernetes way to define the access control to the running pod
Adding `SecurityContext` field to the function spec allowing us to ensure the running function has the correct privileges.
TODO:

Allow passing security context via function config

---

docs/reference/function-configuration/function-configuration-reference.md
pkg/nuctl/test/function_test.go

Part 1 - https://github.com/nuclio/nuclio/pull/1819
- Added nuctl test for security context
- Added docs for security context in function spec

Allow passing security context via function config - Part 2

---

pkg/common/errors.go
pkg/dashboard/resource/apigateway.go
pkg/dashboard/resource/function.go
pkg/dashboard/resource/functionevent.go
pkg/dashboard/resource/project.go
pkg/platform/abstract/platform.go
pkg/restful/resource.go

To avoid cases where the root cause, containing the desired error status code get ignored when trying to resolve the status from the top level error.
This pr ensure that errors hidden on the root cause would be populated (unless the user intentionally override it on the top level error)

Resolve error status code from top level error or root cause

---

pkg/platform/kube/apigatewayres/lazy.go
pkg/platform/kube/ingress/ingress.go
pkg/platform/kube/ingress/types.go

More familiar and generic as a "mode" name, even though the implementation is dex specific today

Apigateways - renaming authentication mode (dex -> oauth2)

---

.github/workflows/ci.yaml

Upgrade `manusa/actions-setup-minikube` to the latest version.
Removes the following warnings caused by [CVE-2020-15228](https://github.com/actions/toolkit/security/advisories/GHSA-mfwh-5m23-j46w):
```
Warning: The `set-env` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
Warning: The `add-path` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
```
Relates to:
- https://github.com/manusa/actions-setup-minikube/issues/22
- …

chore: Upgrade actions-setup-minikube to v2.0.1

---

pkg/processor/build/runtime/java/docker/onbuild/Dockerfile

To resolve the issue of 
```
E: Could not configure 'libc6:amd64'.
E: Could not perform immediate configuration on 'libnss-nis:amd64'. Please see man 5 apt.conf under APT::Immediate-Configure for details. (2)
```
Note that curl is being used during image creation, nothing else afterwards is using it

Fix building java onbuild image

---

.github/workflows/ci.yaml
.github/workflows/release.yaml

reason: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

Fix github action set-env deprecation warning

---

pkg/platformconfig/platformconfig.go
pkg/platformconfig/reader.go
pkg/platformconfig/types.go

If platform config was given, the default service type wasn't included.
Fixed the enrichment, so it happens after reading the file, adding the DefaultServiceType if it wasn't given.

[BugFix]: DefaultServiceType enrichment

---

pkg/dockerclient/shell.go
pkg/dockerclient/types.go
pkg/nuctl/test/function_test.go
pkg/platform/kube/functionres/lazy.go
pkg/platform/local/platform.go

Added SecurityContext feature for local platform using the `--user` and `--group-add` flags for `docker run`.
And fixed a bug where security context wasn't updated in kube platform if the function already existed.

SecurityContext for local platform and bugfix

---

pkg/nuctl/test/function_test.go
pkg/platform/kube/functionres/lazy.go
pkg/processor/runtime/shell/runtime.go

Shell runtime would need to `chmod` the run script to give it execute permissions.
If a security context is given, this fails.
Added a check to see if the handler is a script in the current working directory or a command from the PATH.
If it is a command, it is run with `sh -c`
If not, it is run with `sh` (without `-c`) which results in `sh` reading the file as a script and running it, so there's no need to `chmod` the file.
Benchmarked the changes in the event processing function to ensure no large loss of performance happens because of the string manipulations. The performance change is negligible.

[Bugfix]: Shell runtime execution with security context

---

pkg/platform/kube/ingress/ingress.go
pkg/platform/kube/platform.go

Removed api gateway authentication mode validation on api gateway creation/update.
Done to allow nuctl create/update api gateways (couldn't before, because its platform config wasn't configured accordingly)

Remove api gateways authentication mode validation

---

.github/workflows/ci.yaml
Makefile
pkg/nuctl/test/apigagteway_test.go

Updated minikube version to 1.14.0 that allows us to:
1. use docker driver
2. enable ingress addon
3. enable api gateway nuctl tests

Update CI minikube version

---

pkg/platform/kube/controller/controller.go
pkg/platform/kube/controller/nucliofunction.go
pkg/platform/kube/test/platform_test.go
pkg/platform/kube/test/suite.go
pkg/processor/test/suite/suite.go

There are scenarios where function is marked as failed when node become unschedulable and pod is being evicted from node A to node B.
The reason for that might is related to the fact that is that the function deployment is not available for period of time until the a node is being able to schedule and run the pod again.
This pr suggest to check function in error state where its deployments are available, meaning, the function deployment has recovered and now the function can be set as ready again (while removing its error message).
Added a test for the following scenario:
- deploy a function
- ensure function state is ready
- set cluster node as unscheduable
- delete pod (aka evict)
- ensure function state is error
- set clsuter node as schedulable
- ensure function pod is running
- …

Function recovery from error state when deployment is available again

---

pkg/dashboard/ui/package-lock.json
pkg/dashboard/ui/package.json

`protractor`: from `^5.4.4` to `git:angular/protractor#release-5.4` to remedy `yargs-parser` vulnerability.

UI: Upgrade dependency packages to remedy vulnerabilities

---

pkg/dashboard/ui/package-lock.json
pkg/dashboard/ui/package.json
pkg/dashboard/ui/src/app/components/data-wrappers/function-events-data-wrapper/function-events-data-wrapper.component.js
pkg/dashboard/ui/src/app/components/data-wrappers/function-events-data-wrapper/function-events-data-wrapper.tpl.html
pkg/dashboard/ui/src/app/shared/services/nuclio-event-data.service.js

After fix:
- On K8s platform with `ClusterIP` service type:
- Invocation URL: always "URL not exposed"
- Test button: always enabled (unless function is not running, etc.)
- `x-nuclio-invoke-via` request header: `domain-name`
- On K8s platform with `NodePort` service type and on non-K8s platform:
- Invocation URL:
- comprises of external IP address and port number in case they are valid
- "URL not exposed" otherwise
- Test button:
- enabled in case external IP address and port number are valid
- disabled otherwise (and when function is not running, etc.)
- `x-nuclio-invoke-via` request header: `external-ip`

UI: Wrong conditions for Invocation URL, Test button, invoke-via

---

pkg/nuctl/test/apigagteway_test.go
pkg/nuctl/test/function_test.go
pkg/platform/abstract/platform.go
pkg/platform/kube/platform.go

Following up with #1884 to fix typo of *preserved* -> *reserved* 
and added validation on api gateway as well

Followup - reserved resource name

---

pkg/platform/kube/apigatewayres/lazy.go
pkg/platform/kube/ingress/ingress.go
pkg/platform/kube/ingress/types.go
pkg/platform/types.go

Added new `RedirectUnauthorizedToSignIn` bool to `DexAuth` inside `APIGatewayAuthenticationSpec`
When this is true, the `"nginx.ingress.kubernetes.io/auth-signin"` annotation is added to the underlying ingress.
The effect - when the ingress gets a request it tries to authorize it by sending request to the `"nginx.ingress.kubernetes.io/auth-url"`, if it fail, if the `auth-signin` is defined it returns a redirect to it, if it's not defined it returns 401.
The bad side of defining the `auth-signin` is that it will mostly be some UI login screen, so a script sending request to the ingress and being redirected to the login screen might mistakenly think the request passed successfully, while it just got a 200 response with html body (the login screen).
Bottomline, setting the `auth-signin` is …

[API Gateway] Condition sign in annotation

---

pkg/platformconfig/types.go

From now on,
Functions will be created with ClusterIP ServiceType by default.
This means functions will not be exposed outside the k8s cluster, unless:
- Either an ingress is created to expose the http trigger
- Or the ServiceType of the http trigger is specified as NodePort

Switch ServiceType Default to ClusterIP

---

pkg/platform/kube/apigatewayres/lazy.go
pkg/platform/kube/types.go

Prefixed apigateway to start with `nuclio` to aligned with all nuclio kubernetes managed resources
Shorthanded apigateway to `agw` to avoid name too long and kept it in to relate ingress name to apigateway feature

Renamed apigateway ingress resources to prefixed with nuclio

---

cmd/dashboard/docker/Dockerfile

We've been using this version lately for our dashboard image. after discussion with @eran-nussbaum we considered this bump safe.

Bump dashboard image node version

---

pkg/processor/build/builder.go
pkg/processor/build/builder_test.go

Fix - Function processor image tag is concatenated twice when passed on build.image

---

pkg/dashboard/ui/package-lock.json
pkg/dashboard/ui/package.json

- Function › Triggers › HTTP:
- Reword message when no HTTP trigger exists
- Fix: HTTP trigger name's more-info tooltip missing on init and appears only after trigger item is expanded then collapsed.
- When using the link in the above message to add a new HTTP trigger:
- Set its name `http` instead of value from backend (`default-http`).
- Start in edit mode of trigger (expanded with input fields).
- Disable the Deploy button (until trigger item is applied validly).
- Function › Configuration › Labels: added 'nuclio.io' as an invalid prefix:
- API gateways › Wizard › Authentication › OAuth2: added “Redirect unauthorized requests” checkbox field
- Disallow naming functions and API gateways after the following reserved words: `dashboard`, `controller`, `dlx`, `scaler`
- Create new function: …

UI: HTTP trigger tweaks; Disallow naming after reserved words

---

pkg/dashboard/ui/package-lock.json
pkg/dashboard/ui/package.json

The issue originated in the wrong assumption that triggers on backend model are a list (array), while actually they are a dictionary (object).
Depends on PR https://github.com/iguazio/dashboard-controls/pull/1118

UI: No invocation URL when HTTP trigger has ingresses

---

pkg/dashboard/ui/package-lock.json
pkg/dashboard/ui/package.json
pkg/dashboard/ui/src/app/app.route.js
pkg/dashboard/ui/src/app/shared/services/nuclio-api-gateways-data.service.js

- Project screen: hide API gateways tab when running on non-K8s platform
- On K8s:
- On non-K8s:
Depends on PR https://github.com/iguazio/dashboard-controls/pull/1122

[API gateways] Hide when on non-K8s platform

---

pkg/processor/trigger/http/test/suite/http_test.go

`Access-Control-Expose-Headers` is not part of CORS preflight response

Fix integration test

---

Makefile
pkg/processor/runtime/python/py/_nuclio_wrapper.py
pkg/processor/runtime/python/py/test_wrapper.py
pkg/processor/runtime/python/test/Dockerfile
pkg/processor/runtime/python/test/python_test.go
pkg/processor/runtime/python/test/test.sh

_msgpack_, our json binary encoder/decoder, use `utf8` to decode incoming events. When an incoming event contains, for an instance, a non `utf8` header value, it raises a decode exception and its internal buffer never get cleaned. This immediately put the function in bad shape as it is being able to respond to any consecutive incoming events.
In this PR:
1. reset unpacker upon decoding failures
2. avoid sending server exception traceback in response (unless raised within function handler)
3. Enhanced python wrapper tests (test on 2.7 and 3.6 to 3.9)
4. Fix python runtime integration test to be run from IDE

Python runtime to recover from msgpack decoding exceptions

---

pkg/dashboard/ui/package-lock.json
pkg/dashboard/ui/package.json

- Project › API gateways › wizard › Basic Settings: when on non-K8s platform, when there is no default HTTP host-ingress template from backend, added a new “Host” field, which, together with “Path” field, constructs “Endpoint” (when “Host” is empty “Enter host to see endpoint” message appears and the copy-to-clipboard icon button is hidden):
- Function › Configuration › Labels: disabled on edit only for K8s platform
- On K8s platform:
- On non-K8s platform:
Depends on PR https://github.com/iguazio/dashboard-controls/pull/1125

UI: Add host field to API gateway wizard when no template

---

pkg/dashboard/ui/package-lock.json
pkg/dashboard/ui/package.json

- Introduced new `unhealthy` state:
- Project › Functions › Status column:
- Function › Status tab header:
- Project › API gateways › Wizard › Primary/secondary functions:
Depends on PR https://github.com/iguazio/dashboard-controls/pull/1127

UI: Functions: introduce Unhealthy state

---

pkg/containerimagebuilderpusher/nop.go
pkg/platform/abstract/platform.go
pkg/platform/abstract/platform_test.go
pkg/platform/kube/platform.go
pkg/platform/kube/platform_test.go
pkg/platform/mock/platform.go
pkg/platform/platform.go
pkg/platformconfig/platformconfig_test.go

- Max workers is set to 1 for http / v3ioStream
- Do not allow empty name triggers
- Added kube platform unit test (+ test to ensure serviceType is added for http triggers)
Fixes:
- Do not create docker clients and etc for short platform (abstract / kube) tests

Enhanced create function enrichment + validation

---

hack/k8s/helm/nuclio/Chart.yaml
hack/k8s/helm/nuclio/values.yaml
pkg/platform/abstract/platform.go
pkg/platform/mock/platform.go
pkg/platform/platform.go
pkg/platformconfig/platformconfig.go
pkg/platformconfig/types.go
pkg/processor/build/builder.go
pkg/processor/build/runtime/runtime.go

A new section in platform config can receive per-runtime registry override for base and onbuild images for finer grained control over dark-site compatibility

Configurable base/onbuild images by runtime

---

pkg/platform/abstract/platform.go

```
suite.go:63: test panicked: runtime error: invalid memory address or nil pointer dereference
goroutine 24 [running]:
runtime/debug.Stack(0xc00044ae48, 0x227b380, 0x33cc5c0)
/usr/local/Cellar/go@1.14/1.14.9/libexec/go1.14.9/src/runtime/debug/stack.go:24 +0x9d
github.com/stretchr/testify/suite.failOnPanic(0xc000187680)
/Users/liranbg/go/pkg/mod/github.com/stretchr/testify@v1.6.1/suite/suite.go:63 +0x57
panic(0x227b380, 0x33cc5c0)
/usr/local/Cellar/go@1.14/1.14.9/libexec/go1.14.9/src/runtime/panic.go:969 +0x166
github.com/nuclio/nuclio/pkg/platform/abstract.(*Platform).getBaseImagesOverrides(0xc000230120, 0xb1deb0784f84352, 0xc00044b080, 0x100fc9d)
/Users/liranbg/iguazio/nuclio/nuclio/pkg/platform/abstract/platform.go:1037 +0xf1 …
```

Bugfix - nil pointer dereference when running in local/docker platform

---

pkg/processor/test/suite/suite.go

Due to uninitialized platform config, long ci / periodic were failing with panic.

CI test fix

---

pkg/processor/runtime/shell/runtime.go
pkg/processor/runtime/shell/runtime_test.go
pkg/processor/runtime/shell/test/outputter/outputter.sh
pkg/processor/runtime/shell/test/shell_test.go
pkg/processor/runtime/shell/test/timeout_test.go
pkg/processor/runtime/shell/types.go
test/_functions/shell/timeout/timeout.sh

When an execution fail, the response body is empty. To fix that, I added both _error_, _stderr_  and  _stdout_ to response output.
In addition to that, I made the execution timeout configurable on the runtime attributes level.
if your shell runtime execution should last more than a minute, override its `runtimeAttributes` with
`DefaultTimeout: 10m`.

Shell: return stderr upon execution error 

---

pkg/platform/abstract/platform.go
pkg/platform/abstract/platform_test.go

To avoid weird behavior in UI where trigger name is empty while its key is filled.

Enrich trigger name from its map key

---

docs/reference/function-configuration/function-configuration-reference.md
docs/tasks/benchmarking.md
docs/tasks/deploying-functions.md
pkg/processor/build/runtime/python/runtime.go
pkg/processor/build/runtime/python/test/python_test.go
pkg/processor/build/test/build_test.go
pkg/processor/runtime/python/py/_nuclio_wrapper.py
pkg/processor/runtime/python/py/test_wrapper.py

Python 2.7 has gone deprecated and unmaintained a while ago.
To allow ourselves add great features, fix encoding decoding bugs and improve python performance, it is require for us to deprecate python 2.7 to allow using 3rd party packages which drop support for python 2.7.
This change would happen incrementally, while all versions up until today will continue deploying python 2.7.
Starting next minor release, we will drop support for python 2.7 functions.
To update your functions, you simply update your `function.yaml` runtime from `python:2.7` to `python` (which would be resolve to the default python runtime, which is currently 3.6).

Add deprecation warnings when deploying a function with python 2.7

---

pkg/dashboard/ui/package-lock.json
pkg/dashboard/ui/package.json
pkg/dashboard/ui/src/app/app.run.js

- Function:
- Use the same orange color for “Building” state in the “Status” tab header as the orange color used in the project‘s “Functions” screen in “Status” list
Before:
After:
- Configuration › Basic Settings:
1. Put “Run as user” first, “Run as group” second, and “FS Group” last.
2. Made “Run as user” mandatory when “Run as group” is not empty.
3. Set the maximum value for all three fields to 2147483647.
- Create function: reworded the text messages in the pop-up dialogs when attempting to create a function with a name that is already in use by an existing function
- Project › Functions: add text color to status cells
**Before:**
**After:**
Depends on PR https://github.com/iguazio/dashboard-controls/pull/1134

UI: Function list: color function status text (+ more)

---

pkg/restful/server.go

Considering the fact the resource can be called w/out a suffix of `/`, the check should trim it and ensure it correspondingly

Fix dashboard logging for GET /api/functions requests

---

pkg/dashboard/resource/function.go
pkg/platform/abstract/platform.go
pkg/platform/abstract/platform_test.go
pkg/platform/function.go
pkg/platform/kube/platform.go
pkg/platform/kube/platform_test.go
pkg/platform/kube/test/platform_test.go
pkg/platform/local/platform.go

Following https://github.com/nuclio/nuclio/pull/1697,
Enforce resourceVersion for `DELETE /api/function/:id` as well

Enforce function resource version validation upon deletion

---

pkg/dashboard/ui/package-lock.json
pkg/dashboard/ui/package.json

- Function › Code › Code Entry Type: when any option is selected other than “Source code (edit online)” a message is displayed to inform the user that the configuration in UI has precedence over the configuration in the external code source.
- Create function: reworded the text messages in the pop-up dialogs when attempting to create a function with a name that is already in use by an existing function
- For a function on the same project, or on another project when running on a non-K8s platform:
- For a function on another project when running on a K8s platform
Depends on PR https://github.com/iguazio/dashboard-controls/pull/1137

UI: Function: Inform about UI precedence over external + reword

---

.github/workflows/ci.yaml

Following https://github.com/manusa/actions-setup-minikube/issues/24, Updating Cuclio CI to use newer version of minikube and its installation action

Update minikube CI installation

---

pkg/platform/abstract/platform.go
pkg/platform/abstract/platform_test.go
pkg/processor/runtime/python/test/python_test.go

To avoid inconsistency between trigger key and name, a validation upon function creation will take place to enforce such scenario would fail.

Enforce trigger key and name equality

---

pkg/common/errors.go
pkg/common/errors_test.go
pkg/dashboard/resource/apigateway.go

Whenever there's an error, `ResolveErrorStatusCodeOrDefault` will iterate top-down on the error stack and return the first status code it finds

Resolve top-down status code on error

---

pkg/dashboard/ui/gulpfile.js
pkg/dashboard/ui/package-lock.json
pkg/dashboard/ui/package.json
pkg/dashboard/ui/src/app/components/projects/edit-project-dialog/edit-project-dialog.tpl.html
pkg/dashboard/ui/src/app/components/projects/new-project-dialog/new-project-dialog.tpl.html

- Create new function › From Template: [bugfix] when filtering templates the pagination was not working.
- Function:
- On deploying a function, in case there is already a newer version deployed, show a pop-up explaining the situation and suggest to overwrite the newer version with the current stale one (“Cancel” button is focused by default):
- [bugfix] Refresh and Actions remained disabled after the “Deploy” button was click and deploy was canceled or failed
- Build: The HTML minifier used to collapsed sequences of whitespace characters between HTML elements and remove them altogether. Now they would be collapsed into a single space character instead. For example, the source code
```html
<foo>   
<bar>
```
would turn to
```html
<foo> <bar>
```
instead of
```html
<foo><bar>
```

UI: Allow to overwrite newer function version with stale (+ more)

---

pkg/cmdrunner/mock.go
pkg/cmdrunner/shellrunner.go
pkg/cmdrunner/types.go
pkg/containerimagebuilderpusher/docker.go
pkg/dockerclient/shell.go
pkg/dockerclient/shell_test.go

Fix a scenario when multiple concurrent deployments cause docker to reuse a specific function onbuild image as a layer cache. that is risky since once build is done, the cached layer would be saved while causing the artifact to be missing from another build in process.
A fix is simply to retry running the build command, allowing docker regenerate required docker cache layers while understanding the missing layer is not there to be used.
Add:
- Updated shell / mock unit test to use _real_ mocked cmd runner
- shorten `err if err` - proper err handling

Updated retry on build errors

---

pkg/dashboard/resource/apigateway.go
pkg/nuctl/command/create.go
pkg/nuctl/command/import.go
pkg/platform/kube/platform.go
pkg/platform/kube/test/suite.go
pkg/platform/types.go

Since the previous structure that holds the apigateway configuration was passed by value, it caused the enrichment function within the `.CreateAPIGateway` not to enrich the callee object that is later being respond to the user.
Changing the `CreateAPIGatewayOptions` and `UpdateAPIGatewayOptions` to hold a point to the config resolves this issue, as it would passed by reference and hence enrichment would ensure the response body is enriched as well.

Return created apigateway resource upon create request

---

pkg/dashboard/ui/src/app/app.run.js

https://trello.com/c/tf8RTj9r/616-api-gateways-get-authentication-type-options-from-backend

[API gateways] Get authentication type options from backend

---

pkg/dashboard/ui/package-lock.json
pkg/dashboard/ui/package.json

- Function › Configuration › Build › Image name: [bugfix] the read-only prefix that precedes the image name field disappeared after deploying the function.
Depends on PR https://github.com/iguazio/dashboard-controls/pull/1151

UI: Config>Build: Fix missing image name prefix after deploy

---

.run/(test_kube) nuctl.run.xml
pkg/common/k8s.go
pkg/containerimagebuilderpusher/types.go
pkg/dashboard/resource/frontendspec.go
pkg/dashboard/test/server_test.go
pkg/nuctl/command/deploy.go
pkg/nuctl/command/nuctl.go
pkg/platform/abstract/platform.go
pkg/platform/config/types.go
pkg/platform/factory/factory.go
pkg/platform/kube/platform.go
pkg/platform/local/platform.go
pkg/platform/mock/platform.go
pkg/platform/platform.go
pkg/platformconfig/platformconfig.go
pkg/platformconfig/types.go
pkg/processor/build/test/build_test.go

Currently, nuctl holds a degraded version of platform config, unlike dashboard, which is lack of many functionality that cannot be introduced without adding many hacks and workarounds - this make both code maintaining hard
In this PR, I removed `platform/config` internal pkg (so called nuctl platform config) and ensure nuctl uses `platformconfig.Config` - which is the object being used by dashboard.
That brings unity between both components while reducing noise of code duplication / less workarounds and much more clarity.
Future note: it would allow us to pass a command arg of platform config path, that can be used during deployment.

Remove nuctl redundant platform config

---

pkg/processor/runtime/rpc/abstract.go

CI logs:
```
20.12.14 06:51:37.456 [0;37m  rpc-runtime-test.logger[0m [0;32m(D)[0m Creating listener socket {"path": "/tmp/nuclio-rpc-bvbgmu8a53hfknchbhu0.sock"}
20.12.14 06:51:37.456 [0;37m  rpc-runtime-test.logger[0m [0;34m(I)[0m Wrapper connected {"wid": 0}
20.12.14 06:51:37.456 [0;37m  rpc-runtime-test.logger[0m [0;32m(D)[0m Started
20.12.14 06:51:38.457 [0;37m  rpc-runtime-test.logger[0m [0;33m(W)[0m Nothing waiting on result channel during restart. Continuing
20.12.14 06:51:38.457 [0;37m  rpc-runtime-test.logger[0m [0;32m(D)[0m Creating listener socket {"path": "/tmp/nuclio-rpc-bvbgmuga53hfknchbhug.sock"}
20.12.14 06:51:38.457 [0;37m  rpc-runtime-test.logger[0m [0;34m(I)[0m Wrapper connected {"wid": 0}
20.12.14 06:51:38.457 [0;37m …
```

Fix transient error on restarting process

---

pkg/dashboard/ui/package-lock.json
pkg/dashboard/ui/package.json

- Invocation URL: Both in function list of a project and in Status tab of a function, when the function is not running display “N/A” as invocation URL. When the function is running and it is in `ClusterIP` service type, and there is no ingress for its HTTP trigger — show “N/A” plus a more-info icon explaining that an ingress can be added, with a link to Triggers tab.
- Function › Triggers › HTTP › Ingresses › Host: limit the length between two periods of a DNS-1123 sub-domain to 63 maximum
- General: prevent tooltip from being obstructed by different UI elements (as a result of CSS rule `overflow: hidden`).
Before:
After:
Depends on PR https://github.com/iguazio/dashboard-controls/pull/1161

UI: Invocation URL is N/A when function is not running

---

pkg/functionconfig/reader_test.go

Added a test to the external code entry type merger to ensure the HTTP trigger merge behaviour is as described:
```
--|-----------------------|-----------------------|----------------------
1 | default-http          | default-http          | Merge; UI prevails
2 | default-http          | <custom name>         | <custom name> (UI)
3 | <custom name>         | default-http          | <custom name> (ECS)
4 | <custom name>         | <custom name = ECS>   | Merge; UI prevails
5 | <custom name>         | <custom name != ECS>  | Deployment ERROR
```
_ECS_: External Code Source

Added external code entry type merger test for http trigger serviceType

---

pkg/platform/kube/controller/functionevent.go
pkg/platform/kube/controller/project.go

When having multiple projects/function events, controller become too spammy as it logs the entire object - tho it doesnt do anything with it.

Reduce spammy log lines on controller

---

pkg/common/helper.go
pkg/common/helper_test.go
pkg/nuctl/command/import.go
pkg/nuctl/test/project_test.go

To provide a [Kubernetes-like](https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/) way to skip importing projects by a label selector - Ive added a `--skip-selectors` flag to `nuctl import` command, to ensure projects matched by the given label selectors, would be skipped during import process.
E.g.:
For exported projects
```
project-a:
meta:
name: project-a
labels:
some-key: some-value
...
```
when invoking 
> cat exportedProjects.yaml |  nuctl import project --skip-selectors some-key=some-value
Project `project-a` would be skipped.

Add skip importing projects by label selectors

---

docs/tasks/exporting-and-importing.md

DOC PR #1974 completion — edit the ***exporting-and-importing.md** task doc title to place "Exporting first", to match the file name and the doc order, which matches the typical flow (first export then import), Also fixed the heading level of the function-deployment section and a typo in the last sentence.

[DOC REVIEW] Minor exporting-and-importing.md fixes & improvements

---

docs/reference/triggers/cron.md
docs/reference/triggers/nats.md
docs/tasks/configuring-a-platform.md

Doc review for PR 1628, PR 1735, PR 1748, and PR 1755 (Cron trigger reference & platform-configuration task) + minor rephrasing in the NATS-trigger attributes doc for cross-triggers doc consistency
@liranbg / @omesser please merge.

[DOC REVIEW] K8s cron-triggers config; NATS trigger unify doc format

---

pkg/dashboard/ui/src/app/app.route.js

https://trello.com/c/z04oF2MI/638-nuclio-breaks-on-projects

[Nuclio] Breaks on /projects/

---

pkg/dashboard/ui/build.config.js
pkg/dashboard/ui/package.json

https://trello.com/c/s4qGK3k0/640-nuclio-layout-breaks-on-window-resize-with-closed-test-pane
- Function › Code: [bugfix] layout breaks on window resize while the test pane is closed
Depends on PR https://github.com/iguazio/dashboard-controls/pull/1169

[Nuclio] Layout breaks on window resize with closed test pane

---

pkg/dashboard/ui/package-lock.json
pkg/dashboard/ui/package.json

- Function › Configuration › Build › Image: When the build image name (`spec.build.image`) includes the system's image-name prefix, split it so the prefix is only readonly to the left of the input field, and only the name itself is editable in the input field.
Before:
After:
Depends on PR https://github.com/iguazio/dashboard-controls/pull/1172

UI: Function > Build: Do not repeat image name prefix in field

---

pkg/common/map.go
pkg/nuctl/test/project_test.go
pkg/platform/abstract/platform.go
pkg/platform/abstract/platform_test.go
pkg/platform/errors.go
pkg/platform/kube/platform.go
pkg/platform/kube/test/platform_test.go
pkg/platform/local/platform.go
pkg/platform/types.go

- if `restricted`, it gets functions and api gateways for the given project name, thought it might be a non-existing project.
> Added get on project, to ensure it exists before proceeding with more excessive API calls
-  When getting project related resources, it fetches both functions and api gateways sequently and not concurrently
> changed to use error group to allow concurrency
- When getting project resources, functions are being enriched with api gateways
> this is not needed. projects fetches api gateways anyway

Optimize delete projects endpoint

---

pkg/dashboard/ui/package-lock.json
pkg/dashboard/ui/package.json

- Function › Configuration › Annotations: Hide from the list the annotations with key prefix of `nuclio.io`. You can still see them via “View YAML” action.
- Function: [bugfix] breadcrumbs are incorrect
Before:
After:
Depends on PR https://github.com/iguazio/dashboard-controls/pull/1175

UI: Hide annotations with key prefix of `nuclio.io`

---

pkg/dashboard/resource/function.go
pkg/platform/abstract/platform.go
pkg/platform/abstract/platform_test.go
pkg/platform/kube/platform.go
pkg/platform/kube/test/suite.go
pkg/platform/local/test/platform_test.go
pkg/platform/types.go
pkg/processor/test/suite/suite.go

Enriching get functions with api gateways makes UI life's better, but that is too excessive while making needlessly enrichments that cost many IO/s.
+ eliminated code dup on local/kube test suite.

Enrich get functions requests with API Gateways only when needed

---

pkg/platform/kube/platform.go
pkg/platform/kube/test/platform_test.go
pkg/platform/kube/test/suite.go

Bug description:
Following [PR](https://github.com/nuclio/nuclio/pull/1997), When creating a function it validates whether there is an ingress existing with the same one desired by the function to be created. if there is one, it returns with a conflicting error saying an ingress is already existing. The issue is that, it **should** not fail if the ingress was created for that specific function.

Fix function ingress host and path validations

---

pkg/dashboard/ui/src/app/components/projects/projects.component.js

- Projects: When multiple projects are selected and a single action is taken upon all of them it makes sense to have each project's name before its corresponding error message so the user knows which error message is relevant to which project.
When an action is taken on a single project the project name is superfluous.
Multiple:
Single — before:
Single — after:

UI: Omit project name from error message on single project action

---

pkg/platform/abstract/platform.go
pkg/platform/errors.go
pkg/platform/kube/platform.go

To allow better error handling on the client side, it is required to differentiate between _conflict_ and _validation_ error. and hence we group them the following way
Conflict:
- upon resource create (e.g. POST): means another resource exists
- upon resource update (e.g. PUT): means resource version requested is stale (`resourceVersion` applied to k8s only)
PreCondition:
- upon resource create/update: request does not adhere to a specific rule, validation failed

Update status code errors returned on validation failure

---

pkg/dashboard/resource/function.go

Enrich functions with apigateway when explicitly indicated by `x-nuclio-function-enrich-apigateways` header.

Explicitly enrich functions with apigateway

---

pkg/dashboard/ui/package-lock.json
pkg/dashboard/ui/package.json
pkg/dashboard/ui/src/app/components/projects/edit-project-dialog/edit-project-dialog.component.js
pkg/dashboard/ui/src/app/components/projects/new-project-dialog/new-project-dialog.component.js

- Changed restrictions for function and API gateway names from DNS-1035 label to DNS-1123 label. The only difference between a DNS-1123 label and a DNS-1035 label is that DNS-123 label can being with a digit while DNS-1035 cannot.
- Function:
- Code › Test pane: enable the Test button when the function is scaled-to-zero and update its tooltip text accordingly
- Configuration › Volumes:
- Removed the uniqueness restriction on the volume name
- Turned “Container name” field of V3IO volume type optional

UI: Use DNS-1123 instead of DNS-1035 for resource name

---

pkg/platform/kube/functionres/lazy.go
pkg/platform/kube/test/platform_test.go

Bug description:
User wants to volume once, and volume mount twice. meaning, allow to "volumize" the same input to multiple locations.
Since the current function.spec requires you having tuple of volume and its volume mount, it is impossible to given partial list of `[volume, volumeMount, volumeMount] ` but requiring the user to provide a list of `[(volume, volumeMount), (volume, volumeMount)]`.
Since `volume` is unique per its name, using its "tuple" presentation forcing us to create the volume instance twice, which is not possible by Kubernetes.
Solution:
To resolve it, without changing the function spec or create a mutant of partially filled tuple (e.g.: `[(volume,), (,volumeMount), (,volumeMount)]`) - while resolving the volume / volumeMount instances to be created, I use map to …

Allow volume mount to reuse volume

---

docs/tasks/exporting-and-importing.md

Fix for PR #1999 (doc review for PR #1971)

[DOC] import project: fix spec.displayName field-name typo

---

pkg/dashboard/ui/src/app/components/projects/new-project-dialog/new-project-dialog.component.js
pkg/dashboard/ui/src/app/shared/services/import.service.js
pkg/dashboard/ui/src/app/shared/services/nuclio-functions-data.service.js
pkg/dashboard/ui/src/app/shared/services/nuclio-projects-data.service.js

https://trello.com/c/7pD5pfgG/661-projects-import-do-not-omit-specdisplayname-during-import
Also add `import=true` on `POST` requests as part of import process.
Reverts PR https://github.com/nuclio/nuclio/pull/1990

[Projects] Do not omit `spec.displayName` on create

---

pkg/platform/kube/platform.go
pkg/platform/local/platform.go

Since log lines are added to export/import, it screws the produced artifact.
Reducing log level for now, on next version a better logger mechanism would be introduced.

Reducing log level for create project

---

pkg/dockerclient/shell.go

Adding two more error messages to build phase, as these error might occur during COPY directives.
related ticket:
https://github.com/moby/moby/issues/36573

Update build function retry errors

---

pkg/platform/kube/monitoring/test/function_test.go

Caused because recently deployed functions grace period was too short causing the monitoring service to mark function as unhealthy mistakenly

Fix CI transient failures on function monitoring

---

.github/workflows/ci.yaml

Upgrade `manusa/actions-setup-minikube` to use the latest version.
GitHub is rolling out Ubuntu 20.04 as the default environment. GitHub actions workflows using `ubuntu-latest` will [soon ](https://github.com/actions/virtual-environments/issues/1816) start an Ubuntu 20,04 instance instead of 18.04.
Prior versions of `manusa/actions-setup-minikube` have a check which won't allow the workflow job to run. Starting on `2.2.0`, Ubuntu 20.04 is supported too (https://github.com/manusa/actions-setup-minikube/issues/26).

chore: Upgrade actions-setup-minikube to v2.3.0

---

pkg/common/strings.go
pkg/platform/kube/deployer.go
pkg/platform/kube/test/platform_test.go

Added integration tests to make sure `function.status.message` is filled with the expected brief error message on different function deployment failures.
- Made sure no same warning event is printed to brief error message
- Used https://github.com/fernandoporazzi/sorensen-dice-coefficient `CompareTwoStrings` to compare how close the function.status.message and the expected one are (in percent). 
Done  to allow flexibility so tests won't break when small changes happen (like different stack trace code line references)

Add integration test for function brief error message

---

pkg/platform/kube/monitoring/function.go
pkg/platform/kube/monitoring/test/function_test.go

This change came after noticing many CI failures, caused by a race condition between the function monitoring and the resync process.
Disclaimer:
- the post deployment block call is _up_ to 60 seconds, once deployment is ready it might check it immediately.
- while function is deployed, is has a "minimum available replicas" which allow the function to become "ready".
- during second deploy of a function, there is a transient state in which a deployment has replicas set for old function + new function rollout. e.g.: for function with 1 replica, during deployment, a deployment would have 2 replicas set.
CI Failure logs
```
21.01.06 17:21:06.211                      test (I) Function deploy complete {"functionName": "function-deploy-fail", "httpPort": 32053}
21.01.06 17:21:06.277 …
```

Function monitoring: enhancing the way deployment is detected as available

---

pkg/platform/kube/functionres/lazy.go
pkg/platform/kube/functionres/lazy_test.go
pkg/platform/kube/monitoring/test/function_test.go

Function were re-deployed transiently due to deployment spec change on the list of volume / volume mounts, causing the pod to restart each X controller intervals.

Fix unordered list of volumes causing deployment spec to be reconfigured

---

pkg/dashboard/ui/package-lock.json
pkg/dashboard/ui/package.json

- Function: [bugfix] Refresh and Actions remained disabled after the “Deploy” button was click and deploy was canceled or failed
- Function › Configuration › Build › Readiness Timeout (seconds): when emptying the field — omit it entirely from the `POST`/`PUT` request’s JSON body (`spec.readinessTimeoutSeconds`) instead of setting it to an empty string.
Depends on PR https://github.com/iguazio/dashboard-controls/pull/1188

UI: Omit readiness timeout from request on empty field

---

cmd/dashboard/app/dashboard.go
cmd/dashboard/app/dashboard_test.go
cmd/dashboard/app/types.go
cmd/dashboard/docker/Dockerfile
cmd/dashboard/docker/runner.sh
cmd/dashboard/main.go
cmd/processor/app/processor.go
hack/k8s/helm/nuclio/templates/deployment/dashboard.yaml
hack/k8s/helm/nuclio/values.yaml
pkg/cmdrunner/shellrunner.go
pkg/cmdrunner/types.go
pkg/common/healthcheck/server.go
pkg/common/status/status.go
pkg/common/statusprovider/status.go
pkg/dashboard/healthcheck/server.go
pkg/dockerclient/dockerclient.go
pkg/dockerclient/mock.go
pkg/dockerclient/shell.go
pkg/dockerclient/shell_test.go
pkg/processor/healthcheck/server.go
pkg/processor/runtime/golang/runtime.go
pkg/processor/runtime/pypy/runtime.go
pkg/processor/runtime/rpc/abstract.go
pkg/processor/runtime/runtime.go
pkg/processor/runtime/shell/runtime.go
pkg/processor/trigger/http/http_test.go
pkg/processor/trigger/http/trigger.go
pkg/processor/worker/worker.go
pkg/processor/worker/worker_test.go
pkg/restful/server.go

Docker daemon may be restarted during dashboard lifetime, that will lead to an orphaned socket being volumized to dashboard (for docker container builder).
In this PR I added healthcheck server to nuclio-dashboard, for both kubernetes & docker platforms.
This allow us to declare process healthiness while monitoring docker deamon connectivity by running `docker version` periodically.
Since most of the code was written and built for the functions / processor, I moved some code around to common to make it reusable.

Introducing dashboard healthcheck server

---

docs/reference/function-configuration/function-configuration-reference.md
pkg/common/consts.go
pkg/dockerclient/shell.go
pkg/platform/local/platform.go
pkg/platform/local/test/platform_test.go
pkg/platform/local/types.go

To allow deploying function with configuration being volume mounted (and not bind mounted) for all functions being deployed, I aded `NUCLIO_DASHBOARD_DEFAULT_FUNCTION_MOUNT_MODE` env to local platform. that will ensure function mount mode on all functions without an explicit mount mode. 
continuing #1820 which introduced the option.
Deprecation note: `processorMountMode` in favor of `mountMode` for naming correctness as not only the processor is being mounted.
That being said, the value is still accepted and if `mountMode` isn't set, the deprecated value is being shoved onto `mountMode`.

Add function mount mode on local platform

---

docs/reference/function-configuration/function-configuration-reference.md
pkg/platform/local/types.go

On <=1.5.x versions, `processorMountMode` was used for functions running with local platform to allow them override the way the (processor) configuration was shoved into the function container.
Since its name has changed to `mountMode` and `processorMountMode`  and was deprecated on 1.5.16 - it is now safe to simply remove this field completely.

Deprecate local platform functions attribute processorMountMode in favor of mountMode

---

pkg/common/consts.go
pkg/platform/kube/monitoring/function.go
pkg/platform/local/platform.go

Aligned behavior with kube platform on 1.5.x and now status message has been deprecated. 
Remove its appearance for good.

Deprecated local platform old function unhealthy status message

---

.github/workflows/release.yaml
.gitignore

Adding `arm64` to the release artifacts (nuctl + Nuclio docker images).
Images:
- amd64: all
- arm64: all
nuctl:
- amd64: linux, windows, macOS
- arm64: linux
armhf (arm32) - In a followup PR

Support releasing images and nuctl against multi architectures (arm64 / amd64)

---

pkg/platform/kube/test/suite.go

Nuclio latest tag are used for local development only. fixing a glitch were latest tags were used on CI.

Fix test relaying on latest tag existence

---

hack/examples/ruby/empty/empty.rb
hack/examples/shell/empty/empty.sh
pkg/common/helper.go
pkg/functionconfig/types.go
pkg/nuctl/test/function_test.go
pkg/nuctl/test/suite.go
pkg/processor/build/runtime/runtime.go

Each function would be built, deployed and invoked to provide more confidence for cross runtime changes.
- Added "empty" example for both shell / ruby to align with other runtimes.
- Moved `GetRuntimeNameAndVersion` to common, as it is being used by various places around (code-dup).
- Remove `rootCommandeer` as suite property, to allow test parallelism (doing so locally for now, not CI)

Added CI build + deploy for all runtimes

---

.github/workflows/benchmark.yaml
.gitignore
Makefile
hack/scripts/benchmark/benchmark.py

Its been a while since our [benchmarking.md](/nuclio/nuclio/blob/development/docs/tasks/benchmarking.md) document has been updated with some of our latest improvements.
In this PR I added a worfklow in which can be triggered to start a benchmarking test against a PR (or development if not PR number has provided).
To run it on a remote machine, simply use `wget -qO- https://raw.githubusercontent.com/nuclio/nuclio/development/hack/scripts/benchmark/benchmark.py \
| python3 /dev/stdin --help`
and checkout its usage help.
By running with its defaults, the script will then
- deploy a function per runtime (e.g.: golang) on a local platform
- run vegeta to benchmark it
- repeat for all given runtimes
For each benchmarked runtime, the output would be
- A vegeta report, such as:
```
Requests …
```

Added HTTP load benchmarking test script

---

hack/scripts/benchmark/benchmark.py
pkg/nuctl/test/function_test.go

Update / enable ci tests for python 3.7 and 3.8:
- Deploy "sanity" function (using examples/empty) for both python 3.7 and 3.8 as part of CI integration tests
- Add both python 3.7 and 3.8 runtimes to benchmarking (e.g.: `python benchmark.py --runtimes golang,python:3.7,python:3.8`)

Enable python 3.7 & 3.8 CI tests + add to benchmarking script

---

pkg/platform/kube/test/suite.go

backports [this](https://github.com/nuclio/nuclio/pull/2073)

Fix test relaying on latest tag existence [1.5.x backport]

---

pkg/dashboard/ui/package-lock.json
pkg/dashboard/ui/package.json

-  API Gateways: [bugfixed] Transient states were sometimes shown on “Status” column instead of the (existing) loader.
Before:
After:
- API Gateways › Wizard › Function list:
Instead of merely capitalizing the `status.state` of the function, such as:
be consistent with the same set of values that is used throughout Nuclio for function status:

UI: Fix falsely showing transient states of functions and API GWs

---

pkg/dashboard/ui/package-lock.json
pkg/dashboard/ui/package.json

Backports PR https://github.com/nuclio/nuclio/pull/2081 from branch **development** into branch **1.5.x**.
-  API Gateways: [bugfixed] Transient states were sometimes shown on “Status” column instead of the (existing) loader.
Before:
After:
- API Gateways › Wizard › Function list:
Instead of merely capitalizing the `status.state` of the function, such as:
be consistent with the same set of values that is used throughout Nuclio for function status:
Depends on PR https://github.com/iguazio/dashboard-controls/pull/1204

UI: Fix falsely showing transient states of functions and API GWs [1.5.x backport]

---

hack/scripts/benchmark/benchmark.py

Usage example:
`wget -qO- \
https://raw.githubusercontent.com/nuclio/nuclio/development/hack/scripts/benchmark/benchmark.py \
| python3 /dev/stdin --runtimes golang,python:3.8 --body-sizes 0KB,128KB,1MB,4MB --nuctl-path <somewhere>`
That will start a benchmarking against golang and python 3.8 runtimes while using different body sizes while using vegeta attack.

Benchmarking script support different body sizes requests

---

pkg/processor/runtime/python/test/python_test.go

Test was made in purpose to be run manually to ensure runtime throughput against two different python SDK versions.
Disabled because CI has excessive CPU tests that drain throughput  to a level this test would transiently fail.

Skip python throughput test
