nuclio/nuclio

pkg/dashboard/ui/package-lock.json
pkg/dashboard/ui/package.json

- Remove runtime “Python 2.7” and add runtimes “Python 3.7” and “Python 3.8”:
- Create function › From template › Runtime filter
- Create function › From scratch › Runtime field
- Function › Code › Runtime field
- Project › Functions (list) › Runtime (column)
Depends on PR https://github.com/iguazio/dashboard-controls/pull/1206

UI: Remove "Python 2.7" and add "Python 3.7" and "Python 3.8"

---

Makefile
go.mod
go.sum
pkg/processor/build/runtime/python/test/python_test.go
pkg/processor/runtime/python/py/_nuclio_wrapper.py
pkg/processor/runtime/python/py/requirements/common.txt
pkg/processor/runtime/python/py/requirements/dev.txt
pkg/processor/runtime/python/py/requirements/python3_6.txt
pkg/processor/runtime/python/py/requirements/python3_7.txt
pkg/processor/runtime/python/py/requirements/python3_8.txt
pkg/processor/runtime/python/py/test_wrapper.py
pkg/processor/runtime/python/runtime.go
pkg/processor/runtime/python/test/python_test.go
pkg/processor/runtime/python/test/test.sh
pkg/processor/runtime/rpc/encode_msgpack.go
test/_functions/common/event-recorder/python/event_recorder.py
test/_functions/common/event-returner/python/eventreturner.py
test/_functions/common/json-parser-with-function-config/python/parser.py
test/_functions/common/json-parser-with-inline-function-config/python/parser.py

Event fields type would be byte strings and not encoded to strings.
e.g.:
> $> type(event.path)
> <class 'bytes'>
- by default, do not encode event strings to utf8 for runtimes 3.7, 3.8
- bumped msgpack on python wrapper / sdk to 1.0.2 for runtimes > 3.6, python 3.6 remains in its current constellation
- bumped `nuclio-sdk-py` version [related pr](https://github.com/nuclio/nuclio-sdk-py/pull/24) to 0.3.0
- bumped processor msgpack to latest v4 to include all bug fixes
- Allow explicitly decoding events to utf8 if running any python runtime with env `NUCLIO_PYTHON_DECODE_EVENT_STRINGS` set to true.
- setting it to false would would force the opposite. empty for default behavior.
- Fixed Makefile python test command to fail fast
- Updated few python test functions to work against decoded …

Python 3.7, 3.8: Do not decode event strings to utf8 by default

---

pkg/processor/runtime/python/py/_nuclio_wrapper.py

First set logger handler and then then `init_context` to allow logger instance send log lines back to the processor.

Nuclio wrapper - set logger before init context

---

Makefile
pkg/processor/build/runtime/python/docker/onbuild/Dockerfile
pkg/processor/runtime/python/py/requirements/python3_6.txt
pkg/processor/runtime/python/py/requirements/python3_7.txt
pkg/processor/runtime/python/py/requirements/python3_8.txt

Python onbuild images download artifacts and store them for future nuclio functions to be built with.
since some of those artifacts might require a specific platform (e.g.: msgpack), it is require to prebuilt those onbuild images with a specific platform.
In addition - install common.txt requirement from each runtime.

Prefix onbuild python images

---

.github/workflows/release.yaml
Makefile
pkg/processor/build/runtime/python/docker/onbuild/Dockerfile

- [reverted, somehow](https://github.com/nuclio/nuclio/pull/2100) python onbuild image name prefix (for now, as anyway onbuild currently holds "binary" presentation of msgpack)
- marked fail-fast to false, to allow either platform to finish its release if goes OK. (that being said, if one of them has failed, once all is done, exit code would be > 0)

Fix release and python onbuild - Phase 2

---

hack/k8s/helm/nuclio/Chart.yaml
hack/k8s/helm/nuclio/templates/_helpers.tpl
hack/k8s/helm/nuclio/templates/service/dashboard.yaml
hack/k8s/helm/nuclio/values.yaml

To allow removing duplication in mlrun-kit umbrella chart

Helm chart - support dashboard nodePort from global for mlrun-kit

---

pkg/dashboard/ui/package-lock.json
pkg/dashboard/ui/package.json
pkg/dashboard/ui/src/app/app.route.js

- **Breadcrumbs**:
- Widened dropdown menu to allow about 10 more characters and add a tooltip with the value in full
Before:
After:
- Clicking on the project-name breadcrumb will now go to “Project” screen (URL path: `/projects/{project}`) instead of directly to “Functions” tab in “Projects” screen (URL path `/projects/{project}/functions`):
- In Nuclio open-source it will enter the default nested tab, which is currently “Functions”, so there is no impact.
- It allows other consumers of Nuclio UI to redirect to an external project screen.
- Function › Configuration › Volumes: brought back “Host Path” volume kind
- Added read-only checkbox to host-path volumes.
- For local platform: host path is the only kind available.
- For K8s platform: all kinds besides host path are available. …

UI: Bring back Host Path volume kind for local platform

---

pkg/dashboard/ui/package-lock.json
pkg/dashboard/ui/package.json

- Function › Configuration › Volumes: Removed the red asterisk from the “Read only” checkbox field of the “Host Path” kind
Depends on PR https://github.com/iguazio/dashboard-controls/pull/1213

UI: Function volumes: remove red asterisk from Read Only field

---

pkg/nuctl/command/nuctl.go
pkg/platform/local/platform.go
pkg/platformconfig/platformconfig.go
pkg/platformconfig/reader.go
pkg/platformconfig/types.go

It has been asked a lot by the open-source community and there is no good reason why not to allow it by default.
The result of this change would help reflecting whether a function is healthy or not.

Enable function container healthiness check by default for local platform

---

docs/tasks/configuring-a-platform.md
hack/k8s/helm/nuclio/values.yaml
pkg/functionconfig/types.go
pkg/platform/abstract/platform.go
pkg/platform/mock/platform.go
pkg/platform/platform.go
pkg/platformconfig/platformconfig.go
pkg/processor/build/builder.go
pkg/processor/build/runtime/python/runtime.go
pkg/processor/build/runtime/python/test/python_test.go
pkg/processor/build/runtime/runtime.go
pkg/processor/build/test/build_test.go
pkg/processor/trigger/http/test/suite/suite.go
pkg/runtimeconfig/runtimeconfig.go

Forward porting #2109  to development (, >=1.6.x)
Allowing us to add per-runtime platform configuration which sets build arguments during function image creations.
E.g.: to ensure all python functions are using pre-defined pypi server, simply pass the following platform configuration
```
platformConfiguration:
...
runtime:
python:
buildArgs:
PIP_INDEX_URL: "https://my-pypi-server.com"
```

Support runtime specific build arguments

---

hack/k8s/helm/nuclio/Chart.yaml
hack/k8s/helm/nuclio/templates/_helpers.tpl
hack/k8s/helm/nuclio/templates/service/dashboard.yaml
hack/k8s/helm/nuclio/values.yaml

Backporting https://github.com/nuclio/nuclio/pull/2103 to 1.5.x (part of 0.7.19 chart)
This Change will be followed by re-releasing 0.7.20 chart (current 0.7.20 missing contents from 0.7.19)

Helm chart - support dashboard nodePort from global for mlrun-kit [1.5.x backport]

---

.github/workflows/ci.yaml
.github/workflows/release.yaml

Lock is done due to performance regression on Nuclio unit test `TestStaticAllocatorStress ` for go 1.16.
from UT and testings, it seems like it takes *more* than 30 seconds to consume messages while on 1.14 it takes ~7 seconds.

Lock CI to go version 1.14

---

docs/reference/function-configuration/code-entry-types.md
docs/reference/function-configuration/function-configuration-reference.md
pkg/processor/build/builder.go
pkg/processor/build/builder_test.go

This PR introduces GitEntryType ("git") to be used as a new Code Entry Type.
New CET structure:
```
- `spec.build`
- path - (Required) the URL of the Git repository that contains the function code
- codeEntryAttributes
// must use one of the following as git reference
- gitBranch -  the Git repository branch from which to download the function code.
- gitTag - the Git repository tag from which to download the function code.
- gitReference - the Git repository reference from which to download the function code.
- gitUsername - (Optional) Git username
- gitPassword - (Optional) Git password
- workDir - the relative path to the function-code directory within the configured repository.
The default work directory is the root directory of the git repository (`"/"`).
```
Replacing #2104 …

Add git code entry type (not including Azure Devops)

---

docs/reference/runtimes/python/python-reference.md

Changes:
- EOL for python 2.7
- Introducing 3.7 and 3.8

Python runtime doc update

---

docs/concepts/k8s/function-ingress.md
docs/devel/coding-conventions.md
docs/reference/nuctl/nuctl.md
docs/reference/triggers/cron.md
docs/reference/triggers/http.md
docs/reference/triggers/kafka.md
docs/setup/gke/getting-started-gke.md
docs/setup/k8s/getting-started-k8s.md
docs/setup/minikube/getting-started-minikube.md
docs/tasks/deploying-functions.md

- New section `Exposing a function` section added to `/docs/tasks/deploying-functions.md`
- References and clarifications in various nuctl notes
- Various other small fixes

nuctl docs updates - Explaining function exposure and nodePorts

---

.golangci.yml
hack/scripts/generate-crds/update-codegen.sh
pkg/platform/kube/controller/controller.go
pkg/platform/kube/controller/nucliofunction_test.go
pkg/platform/kube/controller/test/controller_test.go
pkg/platform/kube/test/suite.go

- Added an integration test to ensure restarted controller syncs function during start up (while resync interval is disabled)
that means, if function CRD was created while controller is being restarted due to a reason, the controller would then start and pick up that function waiting for resources creation.
- Updated controller unit test with new fake clientset

Added controller integration test suite

---

pkg/cmdrunner/mock.go
pkg/cmdrunner/shellrunner.go
pkg/common/git.go
pkg/common/git/git.go
pkg/common/git/types.go
pkg/common/helper.go
pkg/dockerclient/shell.go
pkg/processor/build/builder.go
pkg/processor/build/builder_test.go

Changes:
- Support Azure Devops repositories (use git cli, as it is not supported by go-git) + tests on `builder_tests`
- Print current commit SHA when cloning from git repos
- Refactored builder's git logic into common/git.go
- Moved `common.Redact()` function to `cmdRunner.Redact()` (to prevent circular dependencies when using cmdRunner on git client)

Support Azure-Devops repositories on Git code entry type

---

hack/k8s/resources/nuclio-rbac.yaml
pkg/dashboard/resource/frontendspec.go
pkg/restful/resource.go

Fixing: https://github.com/nuclio/nuclio/issues/2135
- Missing ability/permisions (k8s, via RBAC) to list nodes and thus to get external addresses caused `GET /frontend_spec` to fail
- Failure in `/frontend_spec` because of the above caused a panic in dashboard, and the UI to not show the option to pick `serviceType` in the advanced section of the HTTP trigger configuration, which should always be there in k8s
- This failure and panic in dashboard probably happened when using the resource yamls for a while, but since we didn't have the `serviceType` conditioned on the response, it went unnoticed
- Added missing rule to `clusterrole` in rbac yaml
- Added error handling in `resource.go:callCustomRouteFunc` to log the error correctly and avoid a panic
- Smoother handling of inability to get …

Fix - Missing ClusterRole rule in nuclio-rbac.yaml

---

Makefile
docs/reference/function-configuration/function-configuration-reference.md
docs/reference/runtimes/python/python-reference.md
hack/scripts/benchmark/benchmark.py
pkg/dashboard/functiontemplates/generated.go
pkg/dashboard/functiontemplates/generator/generator.go
pkg/nuctl/test/function_test.go
pkg/processor/build/builder.go
pkg/processor/build/runtime/python/docker/onbuild/Dockerfile
pkg/processor/build/runtime/python/runtime.go
pkg/processor/build/runtime/python/test/python_test.go
pkg/processor/runtime/python/py/requirements/python3_9.txt
pkg/processor/runtime/python/test/python_test.go

Introducing python 3.9 as officially OOB runtime.
Continuing the work effort made on https://github.com/nuclio/nuclio/pull/2072

Introducing Python 3.9

---

pkg/platform/local/platform.go

It seems that for latest docker client, the container host port is `0` and not `""` (empty string) when user _did not_ assign a port.
Possible fixes https://github.com/nuclio/nuclio/issues/2158

Fix resolved function container port

---

Makefile
hack/k8s/helm/nuclio/Chart.yaml
hack/k8s/helm/nuclio/templates/deployment/autoscaler.yaml
hack/k8s/helm/nuclio/templates/deployment/controller.yaml
hack/k8s/helm/nuclio/templates/deployment/dashboard.yaml
hack/k8s/helm/nuclio/templates/deployment/dlx.yaml
hack/k8s/helm/nuclio/values.yaml

- Backporting #2168, #2168
- Bump chart to 0.7.21 (will be released manually)

Helm chart - node selector, affinity and tolerations support [1.5.x backport]

---

hack/k8s/helm/nuclio/templates/deployment/autoscaler.yaml
hack/k8s/helm/nuclio/templates/deployment/controller.yaml
hack/k8s/helm/nuclio/templates/deployment/dashboard.yaml
hack/k8s/helm/nuclio/templates/deployment/dlx.yaml

Backporting #2170
No need to bump chart, re-releasing 0.7.21

Helm chart - fix indentation on new nodeSelect,tolerations,affinity [1.5.x backport]

---

pkg/platform/kube/controller/nucliofunction.go
pkg/platform/kube/monitoring/test/function_test.go
pkg/platform/kube/platform.go

Scenario:
1. Kubernetes being slow on reporting function pods readiness
2. Deploy function(s)
3. Nuclio-controller gives up on waiting for function readiness, marking function state as `unhealthy`
4. While that happened, the context used to create/update the function gets timedout (deadline due to readiness timeout)
5. The Worker (Kubernets workers) gets the function, see its context got timeout and re-queue it
6. Nuclio-controller being triggered again, this time function has "unhealthy" state but does nothing
7. In the meantime, Nuclio-dashboard is waiting for the function deployment to finish
8. Nuclio-dashboard identify the deployment has finished with state != ready and report error by setting function state back to error.
9. Function pods are up and serving while function being left …

Preserve function unhealthiness when deployment failed

---

.github/workflows/ci.yaml
.github/workflows/long_ci.yaml
.github/workflows/periodic.yaml
.github/workflows/release.yaml
Makefile
hack/scripts/ci/free-space.sh

Updates - 
1. Free more disk space (from 2gb cleanup to more than 40GB!)
2. Use makefile `save-docker-images` and `load-docker-images`
3. Update minikube installation script
w.r.t (1):
Free disk space before cleanup:
```
Filesystem      Size  Used Avail Use% Mounted on
/dev/root        84G   64G   20G  77% /
devtmpfs        3.4G     0  3.4G   0% /dev
tmpfs           3.4G   12K  3.4G   1% /dev/shm
tmpfs           696M  1.1M  695M   1% /run
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           3.4G     0  3.4G   0% /sys/fs/cgroup
/dev/loop0       33M   33M     0 100% /snap/snapd/11588
/dev/loop1       71M   71M     0 100% /snap/lxd/19647
/dev/loop2       56M   56M     0 100% /snap/core18/1997
/dev/sdb15      105M  7.8M   97M   8% /boot/efi
/dev/sda1        14G  4.1G  9.0G  32% …
```

CI - tweaks and updates

---

pkg/common/helper.go
pkg/errgroup/errgroup.go
pkg/platform/kube/monitoring/function.go
pkg/platform/kube/monitoring/function_test.go

1. Fix max concurrent write (🤕 ) panic when bulkly update many functions using `sync.Map`
2. Added errgrup with panic recovery
3. Added unit test
Error logs
```
...controller logs...
fatal error: concurrent map read and map write
fatal error: concurrent map read and map write
goroutine 10039 [running]:
runtime.throw(0x16dce6f, 0x21)
/usr/local/go/src/runtime/panic.go:1116 +0x72 fp=0xc0008cecb8 sp=0xc0008cec88 pc=0x433a42
runtime.mapaccess2_faststr(0x14fd6e0, 0xc00062bb00, 0xc000013670, 0xa, 0x5, 0x1)
/usr/local/go/src/runtime/map_faststr.go:116 +0x47c fp=0xc0008ced28 sp=0xc0008cecb8 pc=0x412eec
github.com/nuclio/nuclio/pkg/platform/kube/monitoring.(*FunctionMonitor).resolveFunctionProvisionedOrRecentlyDeployed(0xc0001521e0, 0xc0006c0900, 0x4) …
```

Fix function monitoring concurrent map writes

---

pkg/platform/abstract/platform.go
pkg/platform/kube/client/deployer.go
pkg/platform/local/platform.go
pkg/platform/types.go

Currently, once a function has been deployed with clusterIP, the troublesome log line includes `httpPort: 0` only without explaining how to invoke the function
This PR, continuing the effort made on https://github.com/nuclio/nuclio/pull/2163 by includes the internal/external invocations urls
Exampels:
NodePort + Ingress
With a clusterIP
```
[11:23:44.883]  (I)  Function deploy complete   [externalInvocationURLs: [], functionName: "helloworld", httpPort: 0, internalInvocationURLs: ["nuclio-helloworld.default.svc.cluster.local:8080"]] 
```
With a nodePort
```
[11:21:44.949]  (I)  Function deploy complete   [externalInvocationURLs: ["192.168.65.4:32366"], functionName: "helloworld", httpPort: 32366, internalInvocationURLs: ["nuclio-helloworld.default.svc.cluster.local:8080"]] 
```
With an …

Log internal/external invocation urls upon successfull deployment

---

cmd/dashboard/README.md
pkg/dashboard/resource/invocation.go
pkg/dashboard/server.go
pkg/dashboard/test/server_test.go
pkg/nuctl/command/invoke.go
pkg/nuctl/test/function_test.go
pkg/platform/abstract/invoker.go
pkg/platform/types.go

Golang HTTP Client timeout is not set by default. That may _potentially_ lead to function invocations waiting forever for a response.
To avoid such scenarios, the invocation timeout default is set to `1m`. to override it, and set an unlimited timeout, the user may provide `--timeout 0s`  from nuctl or set `x-nuclio-invoke-timeout: 0s` using the RESTful resource `/api/function_invocations`

Added function invocation timeout

---

pkg/restful/resource.go

Dashboard log an error when removing a function
```
21.05.03 12:42:06.481 oard.server.api/functions (E) Response writer failed writing empty resources {"err": "http: request method or response status code does not allow body", "routeFuncError": "json: unsupported type: restful.CustomRouteFunc", "requestError": "json: unsupported type: func() (io.ReadCloser, error)"}
```
This does not interfere with the response, but hurting the logs

Dashboard - avoid writing body on NoContent code

---

hack/k8s/helm/nuclio/values.yaml
pkg/dashboard/resource/frontendspec.go
pkg/nuctl/command/deploy.go
pkg/platform/abstract/platform.go
pkg/platform/kube/controller/nucliofunction.go
pkg/platform/local/platform.go
pkg/platformconfig/platformconfig.go
pkg/platformconfig/platformconfig_test.go
pkg/platformconfig/types.go

It is desired to have the readiness timeout configurable via the platform config.
Readiness timeout is a timeout used by nuclio-controller to wait until function pods are ready. if the timeout expires, the function then become "unhealthy".
The readinessTimeout is first populated from the function config spec. if that is zero (aka not set), then it checks for the platform config readiness timeout, which is default to 60 seconds.
This PR allowing us to change the default timeout.
Note: if readinessTimeout is set to `0` on the platform config (only), e.g.: `functionReadinessTimeout: 0s` it is then considered as nuclio-controller won't wait for function pods and would mark the function as ready immediately. This is not a best practice as for now, but optional.

Configurable default function readiness timeout

---

pkg/common/helper.go
pkg/common/map.go
pkg/common/url.go
pkg/nuctl/test/project_test.go
pkg/platform/abstract/platform.go
pkg/platform/abstract/project/external/client.go
pkg/platform/abstract/project/external/client_test.go
pkg/platform/abstract/project/external/leader/iguazio/client.go
pkg/platform/abstract/project/external/leader/iguazio/helper.go
pkg/platform/abstract/project/external/leader/iguazio/synchronizer.go
pkg/platform/abstract/project/external/leader/iguazio/synchronizer_test.go
pkg/platform/abstract/project/external/leader/iguazio/types.go
pkg/platform/abstract/project/external/leader/mlrun/client.go
pkg/platform/abstract/project/external/leader/mock/client.go
pkg/platform/abstract/project/external/leader/types.go
pkg/platform/abstract/project/mock/client.go
pkg/platform/errors.go
pkg/platform/factory/factory.go
pkg/platform/kube/platform.go
pkg/platform/kube/project/client.go
pkg/platform/kube/project/safecache.go
pkg/platform/kube/project/safecache_test.go
pkg/platform/kube/test/platform_test.go
pkg/platform/local/platform.go
pkg/platform/local/project/client.go
pkg/platform/types.go
pkg/platform/types_test.go
pkg/platformconfig/platformconfig.go
pkg/platformconfig/types.go

Added a synchronizer component to align projects with leader projects
- Configurable interval `platformConfig.ProjectsLeader.SynchronizationInterval` (0 means no sync)
- Every loop gets only updated projects (filter by `project.updated_at` field) - except for the first interval
- Only creates and update functions (no mechanism for deletion - this can be done by invoking delete again by the leader)
- Added `platformConfig.ManagedNamespaces` (k8s namespaces)
WIP (Adding tests)

Project Sync - Add leader polling/synchronization loop

---

pkg/processor/runtime/python/py/_nuclio_wrapper.py
pkg/processor/runtime/python/py/test_wrapper.py

As discussed, this adds support for `async def handle` and `async def init_context`, by running the wrapper in an asyncio event loop, awaiting where appropriate, and using an async recv call when `handle` is a coroutine.

Support async def init_context and handle

---

pkg/dashboard/resource/frontendspec.go
pkg/platformconfig/platformconfig_test.go
pkg/platformconfig/types.go

Using default function node selector allowing us to set an initial set of selectors for each created functions

Add default function node selector to platform config

---

hack/k8s/helm/nuclio/Chart.yaml
hack/k8s/helm/nuclio/templates/crd/api-gateway.yaml
hack/k8s/helm/nuclio/templates/crd/function-event.yaml
hack/k8s/helm/nuclio/templates/crd/function.yaml
hack/k8s/helm/nuclio/templates/crd/project.yaml

Instead of https://github.com/nuclio/nuclio/pull/1947

k8s 1.19 compatibility - helm chart - Bumping CRD apiVesion to v1 + fixing schema validation

---

pkg/dashboard/ui/package-lock.json
pkg/dashboard/ui/package.json

- “Project” screen › “Functions” tab:
- Removed “Invocation URL” column.
Before:
After:
- Added an “Owner” column, sortable
- “Function” screen:
- “Configuration” tab: Added ”Node Selectors”
- “Status” tab: list internal invocation URLs and external invocation URLs with a copy button for each.
Before:
After:
Depends on PR https://github.com/iguazio/dashboard-controls/pull/1234

UI: Node selectors, internal & external invocation URLs, owner

---

pkg/dashboard/ui/package-lock.json
pkg/dashboard/ui/package.json

Backports part of PR https://github.com/nuclio/nuclio/pull/2219 from branch **development** to branch **1.5.x**
- Function › Configuration: added ”Node Selectors”
Depends on PR https://github.com/iguazio/dashboard-controls/pull/1243

UI: Add Node Selector to Configuration tab of Function screen

---

pkg/dashboard/ui/package-lock.json
pkg/dashboard/ui/package.json
pkg/dashboard/ui/src/app/components/data-wrappers/function-events-data-wrapper/function-events-data-wrapper.component.js
pkg/dashboard/ui/src/app/components/data-wrappers/function-events-data-wrapper/function-events-data-wrapper.tpl.html
pkg/dashboard/ui/src/app/shared/services/nuclio-event-data.service.js

- “Function” screen › “Code” tab › “Test” pane: Added a select field of all internal and external invocation URLs, and replaced use of `x-nuclio-invoke-via` HTTP request header with `x-nuclio-invoke-url` that uses the selected URL.
- “Project” screen › “Functions“ tab: [bugfix] table was overflowing the viewport on the right edge
Before:
After:

UI: Test pane: add selection of invocation URL

---

pkg/dashboard/ui/package-lock.json
pkg/dashboard/ui/package.json

- “Function” screen › “Code” tab › “Test” pane: added `nuclio.io/project-name` label on saving (create/update) a function event.
Depends on PR https://github.com/iguazio/dashboard-controls/pull/1254

UI: Set `nuclio.io/project-name` label on saving function events

---

docs/reference/triggers/http.md

Making it clear that the port has no effect unless node port is used

Docs - HTTP trigger port update

---

pkg/dashboard/resource/function.go
pkg/dashboard/resource/functionevent.go
pkg/dashboard/resource/project.go
pkg/opa/factory.go
pkg/opa/http.go
pkg/opa/mock.go
pkg/opa/nop.go
pkg/opa/opa.go
pkg/opa/types.go
pkg/platform/abstract/platform.go
pkg/platform/kube/client/updater.go
pkg/platform/kube/platform.go
pkg/platform/kube/platform_test.go
pkg/platform/local/platform.go
pkg/platform/mock/platform.go
pkg/platform/platform.go
pkg/platform/types.go

For the Iguazio leader functionality, added a configurable header in the Platform Config so that if a request comes with the `x-projects-role` header and the header value matches the configured override header value, the OPA is bypassed and allows the action automatically.

Support OPA override header

---

docs/reference/triggers/kafka.md

This makes the parameters consistent with the multiple topics and example yaml section.

Docs - update Kafka trigger for multi-topic support

---

go.mod
go.sum
pkg/loggersink/stdout/factory.go
pkg/loggersink/stdout/types.go

For a log record of `loggerInstance.DebugWith("some-message", "a", "c")` you will get
`{"level":"debug","time":1624547045572.538,"name":"something","message":"some-message","extra":{"a":"c"}}`
instead of
`{"level":"debug","time":1624547025451.832,"name":"something","message":"some-message","extra":"a=c"}`
note the "extra" is structured.

Logger - support JSON compliant extra vars

---

.github/workflows/ci.yaml
Makefile

Fix CI
- it seems that the `ubuntu-latest` image (20.04) that is shipped with the github action runner has kernel issues that cause the minikube network driver not to work and hit on `dial tcp 10.96.0.1:443: i/o timeout error` error (reference - https://github.com/kubernetes-sigs/kind/issues/2240)
- we want to use the `kubectl` that `minikube` is shipped with to allow perfect version matching.
otherwise, we might hit `kubectl` at version >> minikube, which brings feature incompatibility

CI - fix latest issues

---

hack/k8s/helm/nuclio/Chart.yaml
hack/k8s/helm/nuclio/templates/crd/api-gateway.yaml
hack/k8s/helm/nuclio/templates/crd/function-event.yaml
hack/k8s/helm/nuclio/templates/crd/function.yaml
hack/k8s/helm/nuclio/templates/crd/project.yaml

Backporting https://github.com/nuclio/nuclio/pull/2218

k8s 1.19 compatibility - helm chart - Bumping CRD apiVesion to v1 + fixing schema validation [1.5.x]

---

cmd/autoscaler/app/autoscaler.go
cmd/dlx/app/dlx.go
go.mod
go.sum
pkg/functionconfig/types.go
pkg/loggersink/loggersink.go
pkg/platform/kube/controller/nucliofunction.go
pkg/platform/kube/functionres/lazy.go
pkg/platform/kube/resourcescaler/resourcescaler.go
pkg/platform/kube/resourcescaler/test/resourcescaler_test.go
pkg/platform/kube/test/suite.go
pkg/processor/cloudevent/mockevent.go
pkg/processor/test/suite/suite.go
pkg/restful/resource.go

Bump `v3io/scaler` pkg version to 0.5.0
Changes
1. better integration with `v3io/scaler` for further desired features
2. first integration of scale to/from zero (using fake metric client)
3. accomodate scaler loggers to nuclio's loggersinks

Scale to zero update

---

.golangci.yml
Makefile
pkg/common/strings.go
pkg/dashboard/resource/frontendspec.go
pkg/platform/kube/platform.go

`golint` and `interfacer` are no longer supported.
added `revive` as a replacement  for `golint`

CI - update lint

---

pkg/common/k8s.go
pkg/dashboard/test/server_test.go
pkg/nuctl/command/common/renderers.go
pkg/nuctl/command/create.go
pkg/nuctl/test/project_test.go
pkg/nuctl/test/suite.go
pkg/platform/kube/apigatewayres/lazy.go
pkg/platform/kube/apigatewayres/lazy_test.go
pkg/platform/kube/ingress/ingress.go
pkg/platform/kube/platform.go
pkg/platform/kube/platform_test.go
pkg/platform/kube/test/platform_test.go
pkg/platform/kube/test/suite.go
pkg/platform/types.go

For scale to zero to work, we need to annotate created ingresses with custom header indicating which function should be woken up upon an HTTP request. for that case, upon creating API Gateway record, annotate its primary ingress with `X-Nuclio-Target`.
This does not cover cases with canary deployment just yet, a follow-up PR would come to resolve cases where apigateway have a canary which needs to be woken up as well (or instead).

API Gateway - add needed header to allow STZ mechanism to work

---

.github/workflows/ci.yaml
Makefile
pkg/platform/abstract/project/external/client.go
pkg/platform/abstract/project/external/client_test.go
pkg/platform/abstract/project/external/leader/iguazio/client.go
pkg/platform/abstract/project/external/leader/iguazio/synchronizer.go
pkg/platform/abstract/project/external/leader/iguazio/synchronizer_test.go
pkg/platform/abstract/project/external/leader/iguazio/types.go
pkg/platform/abstract/project/internalc/kube/kube.go
pkg/platform/kube/platform.go
pkg/platform/types_test.go

Use explicit list of namespaces to use when syncing projects to avoid
```
User \"system:serviceaccount:default-tenant:default-tenant-nuclio\" cannot list resource \"nuclioprojects\" in API group \"nuclio.io\" at the cluster scope
```
kind of errors

Opa - fix syncing leader projects

---

pkg/dashboard/ui/package-lock.json
pkg/dashboard/ui/package.json

- “Function“ screen › “Triggers” tab: [bugfix] For triggers of type Cron, the “Schedule” field (bound to attributes.schedule) was unexpectedly changed from 6 fields (for example 0 0 5 * * *) to 5 fields (for example 0 5 * * *) — which totally changed the scheduling of the trigger.
Depends on https://github.com/iguazio/dashboard-controls/pull/1256

UI: Cron Trigger: fix unexpected change of schedule fields

---

pkg/platform/kube/controller/nucliofunction.go
pkg/platform/kube/controller/nucliofunction_test.go
pkg/platform/kube/platform.go
pkg/platform/local/platform.go

Changes
1. if validation has failed, do not empty-out previous build logs
2. if function become unhealthy (or any error occured during k8s resource creation), preserve build logs while updating function status

Preserve build logs

---

pkg/containerimagebuilderpusher/docker.go
pkg/containerimagebuilderpusher/types.go
pkg/dockerclient/shell.go
pkg/dockerclient/shell_test.go
pkg/dockerclient/types.go
pkg/processor/build/builder.go

When building a function w/o docker caching layers `--no-cache`, it does not pull base images if they have changed on upstream.
Associating `NoCache` with `Pull` for function building will ensure that base images would be pulled upon function build with `No Cache`.

Fix - Pull base images upon building a function without cache

---

pkg/containerimagebuilderpusher/docker.go
pkg/containerimagebuilderpusher/types.go
pkg/dockerclient/shell.go
pkg/dockerclient/shell_test.go
pkg/dockerclient/types.go
pkg/processor/build/builder.go

backports  #2263 onto 1.5.x branch

Fix - Pull base images upon building a function without cache [1.5.x backport]

---

.github/workflows/ci.yaml

Ubuntu 18 runner has been upgraded while minikube is old and fails to use  conntrack due to file permission. 
This pr hotfixes the issue that has been resolved by new minikube versions (>= 1.21.0).

Fix Kubernetes CI [1.5.x]

---

cmd/dlx/app/dlx.go
cmd/dlx/main.go
hack/k8s/helm/nuclio/templates/deployment/dlx.yaml
hack/k8s/helm/nuclio/values.yaml
pkg/platform/kube/resourcescaler/resourcescaler.go
pkg/processor/trigger/http/http_test.go
pkg/processor/trigger/http/trigger.go
pkg/processor/trigger/http/types.go

On some env it is noticed that function that scale from zero become ready while its http trigger is not ready to take in requests.
In this PR I added an internal endpoint that serves healthiness checkup requests, and while the function scale from zero, the DLX component will verify that the function is ready AND can take in requests by checking on that added endpoint. (that mode is disabled by default, by can be easily turned on by setting `NUCLIO_RESOURCESCALER_FUNCTION_READINESS_VERIFICATION_ENABLED` envvar  to `"true"`.
The drawback is that, if you only take in this fix without _redeploying_ your functions, then DLX readiness verification flow would get to the user code and add incoming requests to statistics thought those requests are just for checkups.
To ensure that readiness …

Scale to zero - verify function readiness [1.5.x]

---

pkg/dashboard/resource/version.go

Reverts nuclio/nuclio#2268
The reason is that some clients would want to know nuclio version to understand how to interact with its backend

Revert "Auth - protect /version endpoint"

---

cmd/processor/app/processor.go
cmd/processor/app/processor_test.go
pkg/processor/trigger/cron/factory.go
pkg/processor/trigger/cron/trigger.go
pkg/processor/trigger/factory.go
pkg/processor/trigger/http/factory.go
pkg/processor/trigger/kafka/factory.go
pkg/processor/trigger/kickstart/factory.go
pkg/processor/trigger/kinesis/factory.go
pkg/processor/trigger/mqtt/basic/factory.go
pkg/processor/trigger/mqtt/iotcore/factory.go
pkg/processor/trigger/nats/factory.go
pkg/processor/trigger/partitioned/eventhub/factory.go
pkg/processor/trigger/poller/v3ioitempoller/factory.go
pkg/processor/trigger/pubsub/factory.go
pkg/processor/trigger/rabbitmq/factory.go
pkg/processor/trigger/registry.go
pkg/processor/trigger/v3iostream/factory.go
pkg/processor/worker/factory.go
pkg/processor/worker/sync.go

This PR fixes triggers not sharing allocated workers due to race condition on map read/write
Added `AllocatorSyncMap` to administrate all allocation with mutex protection while (sort of) complying to `sync.Map` interface, for conveniency.
Internal ticket: `IG-18888`

Fix shared worker allocation

---

hack/k8s/helm/nuclio/values.yaml
pkg/platform/kube/functionres/lazy.go
pkg/platform/kube/functionres/lazy_test.go
pkg/platformconfig/types.go

Allowing to customize default ingress annotation that would be added upon each function deployment.
These default are enriched as long as the user did not specify otherwise.

Default ingress annotations

---

pkg/processor/trigger/v3iostream/event.go

Like other triggers, if `GetPath` is not _supported_ it should return empty string.

Update V3IO trigger event path

---

pkg/platform/abstract/project/external/leader/iguazio/client.go
pkg/platform/abstract/project/external/leader/iguazio/types.go

leader will now enrich namespace upon get projects while querying for its tenancy relationship

Projects - enrich with namespace

---

go.mod
go.sum
pkg/platform/kube/apigatewayres/lazy.go
pkg/platform/kube/apigatewayres/lazy_test.go
pkg/platform/kube/test/platform_test.go

backports both #2247 and #2267 onto 1.5.x to make sure both primary and canary are registered on the `X-Nuclio-Target` header.
Note: need to backport the relevant part on `v3io/scaler` as well, to support multiple targets

API Gateway - add needed header to allow STZ mechanism to work [1.5.x]

---

pkg/common/testutils/http.go
pkg/common/url.go
pkg/dashboard/resource/function.go
pkg/dashboard/resource/project.go
pkg/dashboard/test/server_test.go
pkg/nuctl/command/common/renderers.go
pkg/nuctl/command/create.go
pkg/opa/http.go
pkg/platform/abstract/platform.go
pkg/platform/abstract/project/external/leader/iguazio/client.go
pkg/platform/abstract/project/external/leader/iguazio/client_test.go
pkg/platform/abstract/project/external/leader/iguazio/synchronizer.go
pkg/platform/abstract/project/external/leader/iguazio/types.go
pkg/platform/kube/resourcescaler/test/resourcescaler_test.go
pkg/platform/types.go

PR include - 
1. upon create project - wait for job completion
2. fix un-reused http clients (http clients are thread-safe and highly suggested to be re-used)
3. added project `owner` field
4. added project status to response

Projects - update and fixes

---

pkg/dashboard/ui/package-lock.json
pkg/dashboard/ui/package.json

- “Function” screen › “Code” tab › “Git” code-entry type: Enforce filling only one of “Branch”, ”Tag” or “Reference” fields. When one is filled the others are disabled (and on hovering them when disabled a tooltip shows to explain this)
Depends on PR https://github.com/iguazio/dashboard-controls/pull/1263

UI: Git code entry: Enforce only one of Branch, Tag, Reference

---

pkg/dashboard/ui/package-lock.json
pkg/dashboard/ui/package.json

- “Function” screen › “Configuration” tab › “Node Selector” section:
- Pre-populates with default node-selector entries coming from `GET /api/frontend_spec` endpoint.
- Added “Revert to defaults” action to restore these defaults if they were changed.
Depends on PR https://github.com/iguazio/dashboard-controls/pull/1265

UI: Pre-populate default node-selector entries and allow revert

---

pkg/common/consts.go
pkg/dashboard/auth/iguazio/auth.go
pkg/dashboard/resource/apigateway.go
pkg/dashboard/resource/function.go
pkg/dashboard/resource/project.go
pkg/nuctl/command/common/renderers.go
pkg/nuctl/command/create.go
pkg/nuctl/command/deploy.go
pkg/nuctl/command/export.go
pkg/nuctl/command/import.go
pkg/platform/abstract/platform.go
pkg/platform/abstract/platform_test.go
pkg/platform/abstract/project/external/client.go
pkg/platform/abstract/project/external/client_test.go
pkg/platform/kube/apigatewayres/lazy.go
pkg/platform/kube/client/updater.go
pkg/platform/kube/controller/apigateway.go
pkg/platform/kube/controller/project.go
pkg/platform/kube/ingress/ingress.go
pkg/platform/kube/platform.go
pkg/platform/kube/test/suite.go
pkg/platform/local/client/store.go
pkg/platform/local/platform.go
pkg/processor/build/builder.go

Some updates and refining:
- reused `nuclio.io/project-name` using `common` var
- filter projects using OPA (except from when request is made by leader)
- list projects from CRD instead of leader

Projects: code updates

---

pkg/dashboard/ui/package-lock.json
pkg/dashboard/ui/package.json

- “Function” screen › “Configuration” tab › “Node Selector” section: Added validation rules to “Value” field
Depends on PR https://github.com/iguazio/dashboard-controls/pull/1267
Jira ticket IG-18765

UI: Node Selector: Add validation rules to value

---

pkg/dashboard/ui/package-lock.json
pkg/dashboard/ui/package.json

- Function › Configuration › Node Selector: When deploying a new function with node-selector entries, on deploy completion the node-selector entries cleared from the view. Refreshing the web-browser tab made them re-appear.
Jira ticket IG-19302
Depends on PR https://github.com/iguazio/dashboard-controls/pull/1272

UI: Node Selector: empty after new function deploy

---

hack/k8s/helm/nuclio/values.yaml

Set explicit limit / request resources on Opa container to avoid cases where opa consumes much resources when under high load.
To figure Opa server needs I first created ~30 projects and few functions on each project.
Then I performed 2 benchmark testings, 1 with cpu/limit and one without and here are the findings
The test is blasting with 200 parallel connections sending as much requests as possible within 60s, each request is a POST with an empty body.
I used [bombardier](https://github.com/codesenberg/bombardier) to simulate high load
results:
w requests/limits: (10Mi 100m CPU /  3 CPU 200Mi)
```
Bombarding http://localhost:8181/v1/data/iguazio/authz/allow for 1m0s using 200 connection(s)
[================================================================================================== …
```

Add default requests and limits to Opa server

---

pkg/platform/abstract/platform.go
pkg/platform/abstract/platform_test.go

Ensure all volumes sharing the same volume mount have the same configuration to avoid invalid volume configuration.
For an instance: 2 different volumes sharing the same volume mount would cause none-determinism of which volume would be mounted on path X.

Volumes and volume mounts validation

---

pkg/platform/abstract/platform.go
pkg/platform/abstract/platform_test.go

Ensure the function service type is valid for Nuclio (as not all Kubernetes service types are supported yet)

Validate service type

---

pkg/platform/abstract/platform.go
pkg/platform/abstract/platform_test.go

Follow-up #2321 - it introduced a non BC change for local platform where it required volume mount name to be filled.
This pr introduces name enrichment and a validation for volume name and volume mount name matching (as each function volume is compiled by a coupled volume and volume mount).

Volume enrichment and validation updates

---

pkg/dashboard/ui/package-lock.json
pkg/dashboard/ui/package.json
pkg/dashboard/ui/src/app/components/projects/edit-project-dialog/edit-project-dialog.tpl.html
pkg/dashboard/ui/src/app/components/projects/new-project-dialog/new-project-dialog.tpl.html

- Projects screen › Create/edit project pop-up: Changed label "Project Name" (capitalized) to "Project name" (uncapitalized) for consistency with the rest of the field labels in the app.
Before:
After:
Jira ticket IG-19348
Depends on PR https://github.com/iguazio/dashboard-controls/pull/1274

UI: Reword "Project Name" to "Project name" for consistency

---

pkg/dashboard/resource/function.go
pkg/dashboard/server.go
pkg/platform/abstract/platform.go
pkg/platform/abstract/platform_test.go
pkg/platform/kube/client/deleter.go
pkg/platform/kube/platform_test.go
pkg/platform/types.go

To avoid cases where user A deploy function while user B deletes it - added a validation to disallow deleting function being provisioned
To ignore such validation, a request to backend should include header `x-nuclio-delete-function-state-validation: true`

Do not allow deleting functions that are being provisioned

---

pkg/dashboard/ui/package-lock.json
pkg/dashboard/ui/package.json

- “Function” screen › “Code” tab › “Git” code-entry type:
- Added tooltip to “Git” option  
- Changed tooltip of “URL” and “Branch” from “GitHub” to “Git”
- Added tooltip to “Username”
Depends on PR https://github.com/iguazio/dashboard-controls/pull/1277
Jira ticket IG-19432

UI: Code: Add tooltips to Git code-entry type

---

pkg/dashboard/ui/package-lock.json
pkg/dashboard/ui/package.json
pkg/dashboard/ui/src/app/components/data-wrappers/functions-data-wrapper/functions-data-wrapper.component.js
pkg/dashboard/ui/src/app/components/data-wrappers/functions-data-wrapper/functions-data-wrapper.tpl.html
pkg/dashboard/ui/src/app/components/data-wrappers/version-data-wrapper/version-data-wrapper.component.js
pkg/dashboard/ui/src/app/components/data-wrappers/version-data-wrapper/version-data-wrapper.tpl.html
pkg/dashboard/ui/src/app/shared/services/nuclio-functions-data.service.js

- Function: An attempt to delete a function while it is deploying will now result in a confirmation dialog that would allow to forcibly delete it (before it just resulted in an error)
Before:
After:
- “Function” screen: if a function was deleted while deploying, a new pop-up dialog would indicate that to the user and suggest to either go to the Functions screen, or deploy the function to recreate it.
Depends in PR https://github.com/iguazio/dashboard-controls/pull/1279
Jira ticket IG-17690

[Nuclio] Delete a function while it is deploying

---

pkg/processor/build/runtime/java/docker/onbuild/Dockerfile

mirrored and fixed apt public key issues on `gcr.io/iguazio`

Fix java onbuild image [1.5.x]

---

pkg/dashboard/ui/package-lock.json
pkg/dashboard/ui/package.json

- “Function” screen: When deployment was finished in “unhealthy” state, the deploy result had incorrect colors and text.
Before:
After:
Depends on PR https://github.com/iguazio/dashboard-controls/pull/1282
Jira ticket IG-19030

UI: Deploy result: Wrong text and colors when unhealthy

---

pkg/dashboard/ui/package-lock.json
pkg/dashboard/ui/package.json

- On starting to create a new function it was unexpectedly recognized as deploying then the new “another user delete this function” confirmation dialog showed.
Bug originates in https://github.com/nuclio/nuclio/pull/2346 [1.6.20](https://github.com/nuclio/nuclio/releases/tag/1.6.20) IG-19030
Jira ticket IG-19456

UI: Unexpected confirmation on function creation

---

hack/k8s/helm/nuclio/templates/deployment/dashboard.yaml
hack/k8s/helm/nuclio/values.yaml
pkg/platform/abstract/platform.go
pkg/platform/mock/platform.go
pkg/platform/platform.go
pkg/platformconfig/platformconfig.go
pkg/processor/build/builder.go
pkg/processor/build/runtime/dotnetcore/runtime.go
pkg/processor/build/runtime/golang/runtime.go
pkg/processor/build/runtime/java/runtime.go
pkg/processor/build/runtime/nodejs/runtime.go
pkg/processor/build/runtime/python/runtime.go
pkg/processor/build/runtime/python/test/python_test.go
pkg/processor/build/runtime/ruby/runtime.go
pkg/processor/build/runtime/runtime.go
pkg/processor/build/runtime/shell/runtime.go
pkg/processor/build/runtimeconfig/runtimeconfig.go

It is up to the user to create a secret with the ca contents. e.g.:
```
kubectl create secret generic my-ca-secret --from-file=pip-ca-certificates.crt=file.cert
```
and when installing nuclio (using helm) - 
```
helm install nuclio --set dashboard.pipCACertSecretName=my-ca-secret nuclio
```
When user would then build a Python function, the ca cert would be copied (with file permission 0400) onto the function image while `pip` env `PIP_CERT` would point to its location. any following `pip` command would use such certificate automatically.

Python - support injecting custom ssl ca for pip commands

---

hack/k8s/helm/nuclio/templates/deployment/dashboard.yaml
hack/k8s/helm/nuclio/values.yaml
pkg/containerimagebuilderpusher/kaniko.go
pkg/containerimagebuilderpusher/types.go

Added `--push-retry` flag to kaniko job spec.
Tested manually by deleting docker registry ingress during nuclio function deployment.
Logs showed 3 retries before failing.

Kaniko - Retry pushing images to registry

---

pkg/dashboard/resource/function.go

it has been noticed that on some flaky k8s envs we would need to wait a little bit longer while creating functions

Increase waiting for function creation timeout

---

pkg/processor/trigger/v3iostream/trigger.go
pkg/processor/trigger/v3iostream/types.go

We can set an `ackWindowSize` in a v3io-stream trigger's attributes, which will make the stream consumer commit the sequence number of the event only after another `ackWindowSize` events have been consumed.

V3io stream trigger - allowing predefined ack window offset

---

pkg/platform/local/platform.go

Instead of using the hosts's `/tmp` directory, default function mount to docker's volume.

Local platform - Change default function mount to docker volume

---

pkg/platform/kube/client/deployer.go
pkg/platform/kube/client/updater.go
pkg/platform/kube/controller/nucliofunction.go
pkg/platform/kube/functionres/lazy.go
pkg/platform/kube/functionres/types.go
pkg/platform/kube/test/suite.go

There was a race condition between the dashboard and the controller since the fast failure logic was located in the dashboard.
Moving it to the controller makes the controller the only source of truth regarding the function deployment state, and removing the race condition.
Tested manually on several failing functions, where the logs show the controller fails immediately in `waitAvailable`.

Move fast failure logic from dashboard to controller

---

pkg/cmdrunner/shellrunner_test.go

Fix a race condition between reading from buffer and finding out if it was filled. using channel and timeouts to fulfil both stream test cases (stream was cancelled / stream was finished)

Fix stream unit test

---

pkg/platform/kube/controller/controller_test.go
pkg/platform/kube/controller/nucliofunction.go
pkg/platform/kube/controller/test/controller_test.go

When a deployment fails, unset invocation URLs even if previous deployment has succeeded.
Tested on a live system:
After successful deployment:
After redeployment failure:
internal ticket: IG-19662

Unset function invocation urls in case function deployment fails

---

hack/k8s/helm/nuclio/Chart.yaml
hack/k8s/helm/nuclio/templates/role/crd-admin.yaml
hack/k8s/helm/nuclio/templates/role/function-deployer.yaml
hack/k8s/helm/nuclio/templates/rolebinding/crd-admin.yaml
hack/k8s/helm/nuclio/templates/rolebinding/function-deployer.yaml
hack/k8s/resources/nuclio-rbac.yaml

Resolving: https://github.com/nuclio/nuclio/issues/2402
- Changing k8s resources and chart to use `rbac.authorization.k8s.io/v1` and not `rbac.authorization.k8s.io/v1beta1`. No spec changes needed
- Bumping chart minor (resource api change)

K8s resources (helm/yamls) - Deprecate rbac.authorization.k8s.io/v1beta1, fix k8s 1.22 compatibility

---

pkg/platform/kube/functionres/lazy.go
pkg/platform/kube/functionres/lazy_test.go

Change event reason according to: https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md#what-events-are-emitted-by-ca

Fix autoscale event typo

---

pkg/nuctl/command/import.go
pkg/platform/local/client/store.go
pkg/processor/timeout/timeout.go
pkg/processor/worker/factory.go

Replace all usage of sync/errgroup with nuclio/errgroup for a more unified code base.

Use nuclio/errgroup instead of sync/errgroup

---

cmd/autoscaler/Dockerfile
cmd/controller/Dockerfile
cmd/dlx/Dockerfile
pkg/platform/local/client/store.go
pkg/platform/local/platform.go
pkg/processor/build/runtime/golang/runtime.go
pkg/processor/build/runtime/shell/runtime.go

Addressing some security scan concerns in older 3.11 alpine image and picking up newest 3.15

Use newer alpine images

---

pkg/platform/kube/client/deployer.go
pkg/platform/kube/platform.go
pkg/platform/kube/platform_test.go
pkg/platform/kube/resourcescaler/test/resourcescaler_test.go
pkg/platform/kube/test/platform_test.go
pkg/platform/kube/test/suite.go
pkg/platform/types.go

resource version is verified on pre create/update validations but that should be enforced on the api call as well.

Populate resource version for create/update scenarios

---

pkg/dashboard/resource/function.go
pkg/dashboard/resource/project.go
pkg/dashboard/resource/resource.go

Create a new context from the request context with its request id, so that the context won't expire during concurrent operations.
Currently implemented in Create and Update for functions and projects.

Create resource context form request

---

pkg/context/detached.go
pkg/context/detached_test.go
pkg/dashboard/resource/function.go
pkg/dashboard/resource/project.go
pkg/dashboard/resource/resource.go

The Detached struct enables creating a copy of a context with all of its values, but cancelling the parent context will not cancel the detached.
It is used when forwarding a request context to a goroutine, thus when the request context is cancelled - the goroutine can continue its operation properly.
Added unit tests and tested by creating a deploying and editing functions on a live system.

Add Detached context struct

---

pkg/containerimagebuilderpusher/containerimagebuilder.go
pkg/containerimagebuilderpusher/docker.go
pkg/containerimagebuilderpusher/kaniko.go
pkg/containerimagebuilderpusher/nop.go
pkg/nuctl/command/common/renderers.go
pkg/nuctl/command/create.go
pkg/nuctl/command/delete.go
pkg/nuctl/command/export.go
pkg/nuctl/command/get.go
pkg/nuctl/command/import.go
pkg/nuctl/command/invoke.go
pkg/nuctl/command/nuctl.go
pkg/nuctl/command/update.go
pkg/nuctl/test/suite.go
pkg/platform/abstract/platform.go
pkg/platform/mock/platform.go
pkg/platform/platform.go
pkg/processor/build/builder.go

As a follow-up to the k8s bump (#2428), we inject the same context in nuctl from the root commandeer to all command's commandeers.

Nuctl - Inject context to commands from root commandeer

---

pkg/dashboard/functiontemplates/generator/generator.go
pkg/dockercreds/dockercreds.go
pkg/processor/build/builder.go
pkg/processor/build/runtime/test/suite/suite.go
pkg/processor/build/util/copy.go

`os.ReadDir` was added in Go 1.16 as part of the deprecation of `ioutil` package. It is a more efficient implementation than `ioutil.ReadDir` as stated here https://pkg.go.dev/io/ioutil#ReadDir. 
The full proposal can be read here: https://github.com/golang/go/issues/41467

refactor: use `os.ReadDir` for lightweight directory reading

---

hack/k8s/helm/nuclio/values.yaml
pkg/dashboard/resource/project.go
pkg/processor/runtime/nodejs/js/wrapper.js
pkg/processor/runtime/nodejs/js/wrapper.test.js

Fix a leak raised by issue #2460 
Emitting using `on` creates an event listener without deleting it once finished as oppose to `once` where it create & delete the listener.

Fix nodejs event leak

---

.golangci.yml
cmd/autoscaler/app/autoscaler.go
cmd/controller/app/controller.go
cmd/dashboard/app/run.go
cmd/dlx/app/dlx.go
pkg/common/k8s.go
pkg/platform/kube/monitoring/test/function_test.go
pkg/platform/kube/test/suite.go

Instead of letting klog logging to stdout/stderr - use nuclio's logger facility

Log Kubernetes server warnings nicely

---

pkg/functionconfig/types.go
pkg/platform/kube/platform.go
pkg/platformconfig/types.go

This PR introduce a mode whereas function with specific preemption mode (aka `allow`) will be enriched with given configurations to make sure its pods toleration / node selectors are assigned with values that allows them to run on preemptible nodes (aka `Spot`).
Since each cloud provider has its own configuration to indicate whether a pod is runnable on a spot node - it is up to the user to provide such configuration via the platform config.
e.g.:
```
kube:
preemptibleNodes:
tolerations:
- key: a
operator: "Equal"
value: "value1"
effect: "NoSchedule"
```
once function is deployed and has `preemptionMode: allow`, then its `tolerations` configuration would be enriched automatically with the given configuration.

Allow support for functions to run on preemptible nodes

---

pkg/functionconfig/types.go
pkg/platform/kube/platform.go
pkg/platformconfig/types.go

This PR adds a constraint mode which attach function pods to preemptible nodes

Allow support for function pods to run on preemptible nodes part 2

---

pkg/platform/kube/test/platform_test.go
pkg/processor/build/runtime/python/runtime.go
pkg/processor/runtime/python/runtime.go

A part of an effort to drop python 3.6 support form Nuclio altogether.
Added a deprecation warning in the function logs and in the UI build logs. 
Requirement: https://jira.iguazeng.com/browse/IG-20142

Add deprecation warnings when deploying a function with python 3.6

---

hack/k8s/helm/nuclio/Chart.yaml
hack/k8s/helm/nuclio/templates/_helpers.tpl
hack/k8s/helm/nuclio/templates/deployment/controller.yaml
hack/k8s/helm/nuclio/templates/deployment/dashboard.yaml
pkg/platform/kube/platform.go

Allowing setting the external ip address via ".global" which was ignored for the past few versions.
This PR making sure that the external ip address being injected to dashboard/controller is taking from (the first non empty)
- `global.externalHostAddress`
- `dashboard.externalIPAddresses`
- empty string
NOTE: we try to resolve the external ip address programmatically, if not explicitly given, by:
- checking on the k8s nodes
- using the k8s host

Fix helm chart external ip address resolution

---

pkg/opa/http.go

Some requests that require permissions fail due to unstable OPA behavior.
Retrying on HTTP requests to OPA should fix this issue.
Related JIRA: https://jira.iguazeng.com/browse/IG-19671

Add retries to OPA permission queries

---

cmd/dashboard/README.md
pkg/dashboard/resource/apigateway.go
pkg/dashboard/test/server_test.go

Enable updating apigateways using a specific endpoint:
```
PUT <dashboard-url>/api/apigateways/<apigateway-name>
```
And deprecate updating apigateways via a general and point:
```
PUT <dashboard-url>/api/apigateways/
```
w.r.t https://jira.iguazeng.com/browse/IG-20264

Support updating apigateways via specific route

---

docs/reference/runtimes/python/python-reference.md
pkg/processor/build/runtime/python/docker/onbuild/Dockerfile
pkg/processor/runtime/python/runtime.go

Following #2087 and its breaking change it introduced by not decoding utf8, we have decided to perform a breaking change by aligning python 3.7+ with python 3.6 behavior to allow seamless upgrade between runtimes.

Python - decode utf8 characters by default

---

pkg/dashboard/resource/function.go
pkg/dashboard/test/server_test.go
pkg/platform/mock/platform.go

Continuing https://github.com/nuclio/nuclio/pull/2195 with a small twist. return the entire err stack instead of wrapping to avoid err with status code being ignored
Thanks to @omesser ❤️

Bugfix - silent failure on function deployment - continue

---

cmd/dashboard/README.md
pkg/dashboard/resource/project.go
pkg/dashboard/test/server_test.go

Enable updating projects using a specific endpoint:
`PUT <dashboard-url>/api/projects/<project-name>
`
And deprecate updating projects via a general and point:
`PUT <dashboard-url>/api/projects/
`
https://jira.iguazeng.com/browse/IG-20345

IG-20345 - add support for project update by id

---

pkg/dashboard/resource/frontendspec.go
pkg/functionconfig/types.go
pkg/platform/kube/functionres/lazy.go
pkg/platform/kube/platform.go
pkg/platform/kube/platform_test.go
pkg/platformconfig/platformconfig.go
pkg/platformconfig/types.go

Enriches function pod with the below described spec. if no platformConfiguration related configuration is given, do nothing.
`Allow` 	- Adds Tolerations / GPU Tolerations if taints were given. otherwise, assume pods can be scheduled on preemptible nodes.
- Purges any `affinity` / `anti-affinity` preemption related configuration
`Constrain` - Uses node-affinity to make sure pods are assigned using OR on the given node label selectors.
- Uses `Allow` configuration as well.
- Purges any `anti-affinity` preemption related configuration
`Prevent`	- Prevention is done either using taints (if Tolerations were given) or anti-affinity.
- Purges any `tolerations` / `gpuTolerations` preemption related configuration
- Purges any `affinity` preemption related configuration
- Adds anti-affinity IF no …

Preemption modes - Add prevent

---

pkg/common/v3io/v3io.go
pkg/restful/middleware/middleware.go
pkg/restful/resource.go

- Resolve status code on v3io errors (instead of 500).
- Remove spammy response body from dashboard logs for v3io streams resources.
- Pretty-print `routeFunc` name on custom route failure.

Refactor v3io streams resource logging and errors

---

pkg/auth/iguazio/auth.go
pkg/containerimagebuilderpusher/kaniko.go
pkg/restful/middleware/middleware.go

It is observed that when url is changed between authentication, we need to invalidate cache to ensure it enriches with data plane.
In addition, few fixes to some duration logs

Auth - fix cache key to include url

---

pkg/platform/kube/platform.go

In case function had a preset of node selector, function would have conflicting spec by having an anti affinity to that selector and label selector.
Fix by pruning the label selector first.

Preemption - fix potential bug when setting mode to prevent

---

pkg/platform/kube/client/updater.go
pkg/platform/kube/controller/nucliofunction.go
pkg/platform/kube/controller/nucliofunction_test.go
pkg/platform/kube/functionres/lazy.go
pkg/platform/kube/monitoring/function.go
pkg/platform/kube/platform.go
pkg/platform/kube/test/platform_test.go

Nuclio function CRD control pattern reacts to each function status update, this lead to many needlessly `createOrUpdate` executions.
In this PR I picked some of the flows that are finite in term of not-needing the entire create or update flow to be executed, and skip it.
In addition, do not monitor scaled to zero functions.

Enhance function lazy create or update

---

pkg/platform/kube/controller/nucliofunction.go
pkg/platform/kube/functionres/lazy.go
pkg/platform/kube/functionres/types.go

According to https://jira.iguazeng.com/browse/IG-20501, the fail-fast logic doesn't "catch" the cluster auto-scaler events and fails the deployment before they arrive.
To mitigate that, we increase autoscale waiting time from 10s to 60s. 
Also add functionality to `WaitReadinessTimeoutBeforeFailure` flag - if true, skip the fail-fast logic when waiting for function to be available.

Increase cluster autoscale wait time 

---

pkg/platform/kube/controller/nucliofunction.go
pkg/platform/kube/functionres/lazy.go
pkg/platform/kube/functionres/lazy_test.go
pkg/platform/kube/functionres/types.go

Instead of hard-coded waiting of 5 seconds for ingress to be populated, wait for the ingress status block to be populated by ingress-controller with its ip. 
A small twist here is that function deployment ready + ingress not ready => function unhealthy. which means, if it takes longer for the function ingress, eventually the function would become ready. this is done to avoid marking function deployment as error and cause some regressions.

Ingress - improve resource creation waiting

---

pkg/platform/kube/functionres/lazy.go

Fix an edge case of `WaitAvailable`:
Currently, after checking the ingress there is a `sleep` period, and a context check that verifies weather `readinessTimeout` has passed.
If the function ingress is ready after a period of _almost_ `readinessTimeout`, after sleeping the context is canceled and the function state is set to `Unhealthy`, although both deployment and ingress are ready.
Checking the `ingressReady` and `deploymentReady` flags before sleeping will fix this issue.

Check deployment and ingress readiness before readiness timeout

---

pkg/dashboard/test/server_test.go
pkg/platformconfig/types.go

Some bugs occurred in where a function ingress was ready long after the deployment was ready, causing it to fail on readiness timeout exceeded.
In this PR we raise the default function readiness timeout to 2 minutes to mitigate these errors.

Increase default function readiness timeout

---

pkg/platform/kube/functionres/lazy.go
pkg/platform/kube/monitoring/function.go
pkg/platform/kube/monitoring/test/function_test.go
pkg/platform/kube/test/suite.go

Following https://github.com/nuclio/nuclio/pull/2553 and great catch by @TomerShor  - This PR tweaks a bit the wait for function availability by using for/select to omit the coupling between "sleep" and the function availability check.
In addition, reduce some noisy logs and removed some needlessly logs.
Note: resources availability verification functionality remained untouched.

Kubernetes - tweak function availability wait

---

pkg/containerimagebuilderpusher/kaniko.go

Don't fail Kaniko job polling on first error, but rather wait the build timeout duration.
Related bug: https://jira.iguazeng.com/browse/IG-20629

Kaniko - Improve job status polling

---

pkg/dashboard/resource/frontendspec.go
pkg/dashboard/test/server_test.go

For UI purposes.
Add a `defaultFunctionPodResources` field, that looks as such:
```
{
...
"defaultFunctionPodResources": {
"Requests": {
"CPU": "25m",
"Memory": "1Mi"
},
"Limits": {
"CPU": "2",
"Memory": "20Gi"
}
},
...
}
```

Add default function pod resources to frontend spec

---

docs/reference/runtimes/java/java-reference.md
pkg/processor/build/runtime/java/docker/onbuild/Dockerfile
pkg/processor/build/runtime/java/runtime.go
pkg/processor/runtime/java/build.gradle
test/_functions/java/custom-gradle-script/build.gradle

PR includes
- Bump SDK to `1.1.0` which is compatible with java11
- Use Java-11 for its LTS

Bump Java SDK - 11

---

docs/setup/k8s/running-in-production-k8s.md
hack/k8s/helm/nuclio/Chart.yaml
hack/k8s/helm/nuclio/templates/deployment/dashboard.yaml
hack/k8s/helm/nuclio/values.yaml
pkg/containerimagebuilderpusher/kaniko.go
pkg/containerimagebuilderpusher/types.go
pkg/processor/build/builder.go

- Volume aws secret generated from `.aws/credentials` file to communicate with ECR.
- Use init container with aws cli to create the ECR repository if it does not exist.
- If aws secret was not given - assume instance role

Support ECR with kaniko

---

pkg/functionconfig/types.go
pkg/platform/abstract/platform.go
pkg/platform/abstract/platform_test.go
pkg/processor/trigger/kafka/types.go

As part of the explicit ack requirement, introduce `ExplicitAckMode` for stream triggers which has three options:
- 'enable': Allows for explicit and implicit acks
- 'disable': Allows only implicit acks (default)
- 'explicitOnly': Allows only explicit acks and ignores implicit acks
Will be used in follow-up PRs.
Requirement: https://jira.iguazeng.com/browse/IG-18655

Add ExplicitAckMode to Trigger config

---

pkg/processor/runtime/python/py/_nuclio_wrapper.py

Support both sync and async sockets in Nuclio python wrapper.
Async usage is determined according to `_is_entrypoint_coroutine` property.
Also, generalize socket connection and sending, as a set up for addition of another socket.
Tested with `test_wrapper.py`.

Python wrapper - support async socket communication

---

cmd/processor/app/processor.go

The entire platform config which contains sensitive information is logged when the processor is initialized, and is printed to the dashboard which is visible to users.
This can cause security issues hence removed from the logs.

Remove platform config from processor logs

---

pkg/common/helper.go
pkg/platform/kube/operator/multiworker.go
pkg/processor/runtime/python/test/timeout_test.go
pkg/processor/runtime/rpc/abstract.go
pkg/processor/trigger/http/test/suite/suite.go
pkg/restful/resource.go

It appears that the helper function `CatchAndLogPanic` (which provided syntactic sugar for using `CatchAndLogPanicWithOptions` with `nil` options) did not recover properly from panics as it should.
The reason being that when a panic occurs, the `recover` builtin function should be called from a deferred function inside the panicking goroutine.
Calling `recover` from a nested deferred function fails to catch and handle the panic.
References:
https://stackoverflow.com/questions/49344478/why-recover-does-not-work-in-a-nested-deferred-function
https://go.dev/play/p/g2LpMKD5RMA

Remove CatchAndLogPanic wrapper function

---

pkg/platform/abstract/platform.go

check if env var exists in slice

Fix bug in enrich env vars

---

pkg/processor/runtime/python/test/timeout_test.go

`TestTimeout` for python runtime sometime fails transiently during CI.
Increasing timeouts and sleep times to make the test a bit more lenient.

TestTimeout - increase timeout and sleep time

---

pkg/processor/trigger/kafka/types.go

Worker termination timeout is configured in the Trigger's spec, and used in the runtime's `Terminate` function (currently relevant only for Kafka during rebalance).
When creating a new kafka configuration, enrich the runtime's configuration with the worker termination timeout duration.

Kafka - Enrich runtime configuration with worker termination timeout

---

pkg/containerimagebuilderpusher/kaniko.go

An edge case of deploying 2 functions one after the other can result in a 2 kaniko jobs with the same name.
The reason is the job suffix is `time().Now().Unix()` which is the number seconds from epoch. This is not unique enough, in case two functions are deployed within the same second.
Changing the suffix to a random string fixes this issue.
JIRA: https://jira.iguazeng.com/browse/IG-21088

Kaniko - Create job name with random suffix

---

pkg/nuctl/test/function_test.go
pkg/processor/build/runtime/shell/runtime.go

On `20.10.17+azure-1` the response for `id` command is `uid=1000 gid=2000 groups=2000,3000` whereas on older version it was `uid=1000 gid=2000 groups=3000`.
This ofcourse should not fail the test as the point of security context test is to make sure the running container populates the user / group /fsgroup ids correctly.

Fix security context test failure on docker platform

---

pkg/platform/kube/controller/cronjobmonitoring.go

Surpress messages
```
{"level":"warn","time":"2022-08-31T07:35:56.673Z","name":"controller.kube_warnings","message":"child pods are preserved by default when jobs are deleted; set propagationPolicy=Background to remove them or set propagationPolicy=Orphan to suppress this warning","more":{"agent":"-"}}
{"level":"warn","time":"2022-08-31T07:36:56.708Z","name":"controller.kube_warnings","message":"child pods are preserved by default when jobs are deleted; set propagationPolicy=Background to remove them or set propagationPolicy=Orphan to suppress this warning","more":{"agent":"-"}}
{"level":"warn","time":"2022-08-31T07:36:56.711Z","name":"controller.kube_warnings","message":"child pods are preserved by default when jobs are deleted; set propagationPolicy=Background to remove them or set …
```

Fix cron job deletion

---

hack/k8s/helm/nuclio/Chart.yaml
hack/k8s/helm/nuclio/templates/secret/dashboard-opa.yml

The trailing `#` signs caused iguazio system to fail installing nuclio, with the following error:
```
Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: apiVersion not set
error validating "": error validating data: apiVersion not set
```

Minor chart templates fixes

---

hack/k8s/helm/nuclio/values.yaml
pkg/containerimagebuilderpusher/kaniko.go
pkg/containerimagebuilderpusher/types.go
pkg/dashboard/server.go
pkg/processor/build/builder.go
pkg/restful/middleware/middleware.go

Preparing the ground for kaniko to work with security context. (it does not work yet, as it requires to all container images being used during buildtime to be working rootless and it is something we cannot guarantee yet.
In this PR
1. bumped kaniko to 1.9.0
2. reduce spammy logs in case job pod was not created
3. kaniko to use `/kaniko` as a working dir during function builds
4. dashboard to serve kaniko artifacts (function .tar.gz) via http server, useful for when running dashboard locally.
Set of envvar I used during my testings to make sure dashboard is running as a process (and not as a pod / container)
```
NUCLIO_CONTAINER_BUILDER_KIND=kaniko
NUCLIO_DASHBOARD_DEPLOYMENT_NAME=45.0.0.106
NUCLIO_DASHBOARD_SERVE_KANIKO_ARTIFACTS_MODE=local
NUCLIO_KANIKO_INSECURE_PULL_REGISTRY=true …
```

Kaniko - use workdir /kaniko

---

pkg/processor/runtime/python/py/_nuclio_wrapper.py
pkg/processor/runtime/python/py/test_wrapper.py

It takes too much time for a daemon thread to run in python unit test

Fix Python unit test timings

---

pkg/common/consts.go
pkg/logprocessing/logprocessing.go
pkg/processor/runtime/rpc/abstract.go
pkg/processor/runtime/rpc/controlmessagebroker.go
pkg/processor/trigger/kafka/trigger.go

If explicit ack mode is `disable`, the Kafka workers won't get signaled for termination.
This causes the `workerTerminationCompleteChan` channel to never get sent on, and eventually be closed without any traffic.
However - If a channel is blocking some code flow, and then closed, it unblocks code and it executes whats after it.
In the case of a disabled explicit ack mode, when all the relevant channels are closed, the following code section is executed, causing a `panic: send on closed channel` on the `readyForRebalanceChan` channel:
https://github.com/nuclio/nuclio/blob/development/pkg/processor/trigger/kafka/trigger.go#L288-L295
```
go func() {
<-workerTerminationCompleteChan
k.Logger.DebugWith("Workers terminated", "partition", claim.Partition())
wg.Done()
}()
wg.Wait() …
```

Kafka - Decouple worker termination signal from explicit ack

---

.github/workflows/release.yaml

some xargs f@#$ up. will tackle in a different approach using buildkit caching.

CI - Fix release fails on pushing cache images

---

pkg/platform/kube/functionres/lazy.go

Since the Nginx ingress controller's Sync cycle is 1 minute, waiting only 1 minute for the ingress to be ready can miss a cycle by a matter of minutes and cause the deployment to fail fast.
In this PR we increase the ingress readiness wait time to 2.5 minutes - this way we can ensure we have at least 2 sync cycles in the ingress controller.
If function readiness timeout is shorter than 2.5 minutes and the ingress is not ready, the context will be canceled and the the deployment will fail fast as expected.
Related bug: https://jira.iguazeng.com/browse/IG-21127

Increase ingress readiness wait time to 2.5 minutes

---

.github/ISSUE_TEMPLATE/bug_report.yaml
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/documentation_improvement.yaml
.github/ISSUE_TEMPLATE/feature_request.yaml
.github/ISSUE_TEMPLATE/setup_issue.yaml

Added templates for submitting GitHub issues. 
This should improve the whole issue process, with all the needed information upfront.
Includes Setup Issue, Bug Report, Documentation Improvement, Feature Request, and Question/Help/Support (Links to the Nuclio slack community)

Add Github issue templates

---

pkg/processor/runtime/rpc/abstract.go
pkg/processor/trigger/kafka/test/kafka_test.go
pkg/processor/trigger/kafka/trigger.go
pkg/processor/trigger/kafka/types.go
pkg/processor/worker/worker.go

It appears that sending a SIGTERM to the wrapper process terminates the process if not handled otherwise.
This causes workers to exit prematurely when a rebalance occurs.
In this PR we comment out the worker signaling as an intermediate fix until we find a better way to signal the runtime process on an imminent rebalance.
Related bug: https://jira.iguazeng.com/browse/IG-21152

Kafka - Disable worker signaling before rebalance

---

Makefile
cmd/controller/app/controller.go
cmd/dashboard/app/dashboard.go
cmd/dashboard/app/dashboard_test.go
cmd/dashboard/app/run.go
pkg/cmdrunner/cmdrunner_test.go
pkg/cmdrunner/shellrunner_test.go
pkg/dashboard/test/server_test.go
pkg/errgroup/errgroup_test.go
pkg/platform/abstract/platform.go
pkg/platform/abstract/platform_test.go
pkg/platform/kube/apigatewayres/lazy_test.go
pkg/platform/kube/ingress/ingress.go
pkg/platform/kube/platform.go
pkg/platform/kube/test/suite.go
pkg/platform/mock/platform.go
pkg/processor/runtime/rpc/abstract_test.go
pkg/processor/runtime/rpc/rpc_test.go
pkg/processor/runtime/shell/runtime_test.go
pkg/processor/trigger/cron/cron_test.go
pkg/processor/trigger/http/http_test.go
pkg/processor/trigger/mqtt/iotcore/iotcore_test.go
pkg/processor/trigger/rabbitmq/rabbitmq_test.go

Detect race-condition during unit-testings
- moved some unit-tests that used `shell` to `integration`
- fixed some race conditions, mainly on test-specific cases

CI - Run unit test with race-condition detection

---

.github/workflows/benchmark.yaml
.github/workflows/ci.yaml
.github/workflows/long_ci.yaml
.github/workflows/periodic.yaml
.github/workflows/pr_label.yaml
.github/workflows/release.yaml

1. update to use latest packages
2. fix released from branched out causes nuclio stable to use older versions

Update github workflows

---

pkg/dashboard/resource/frontendspec.go
pkg/dashboard/test/server_test.go
pkg/functionconfig/types.go
pkg/platform/kube/functionres/lazy.go
pkg/platform/kube/functionres/lazy_test.go
pkg/platformconfig/platformconfig.go

To support autoscaling function based on different metrics than cpu usage, this PR adds a list of autoscale metrics to the function config, which will be used to create HPAs in future PRs.
The auto scale metric object contains the following fields:
```
Name - metric name to be used
Kind - Metrics spec kind (Resource / Pods / External)
Type - Tells the UI how to show the metrics value (int / percentage)
TargetValue - the threshold value, above which scaling will occur 
```
In the controller - generate `v2beta1.MetricSpec` for each of the given auto scale metrics, and merge them with the explicitly given metrics in `CustomScalingMetricSpecs`.
In the fronted spec - respond with `supportedAutoScaleMetrics` to be shown in the UI. 
This list is configurable from the platform config under the …

Add Autoscale metrics to function and frontend spec 

---

pkg/dashboard/test/server_test.go
pkg/nuctl/command/create.go
pkg/platform/kube/apigatewayres/lazy.go
pkg/platform/kube/ingress/ingress.go
pkg/platform/kube/ingress/types.go
pkg/platform/types.go

Add the ability to add custom labels to api gateways' upstreams, so they will be populated as Ingress labels.
Usage: In the api gateway spec, add `spec.upstreams[<index>].extraLabels` as key-value object with the extra labels, as such:
```
{
"spec": {
"name": "<apigateway-name>",
"description": "some description",
"path": "/some/path", 
"authenticationMode": "none",
"upstreams": [
{
"kind": "nucliofunction",
"nucliofunction": {
"name": "function-name-to-invoke"
},
"percentage": 0,
"extraLabels": {
"my-custom-label": "some-label-value"
}
}
],
"host": "<apigateway-name>-<project-name>.<nuclio-host-name>"
},
"metadata": {
"labels": {
"nuclio.io/project-name": "default"
},
"name": "<apigateway-name>"
}
}
``` 
If using `nuctl`, add the extra labels in a  JSON-encoded string and pass it to the …

API Gateways - Support extra labels

---

cmd/controller/app/controller.go
cmd/controller/main.go
hack/k8s/helm/nuclio/templates/deployment/controller.yaml
hack/k8s/helm/nuclio/values.yaml
pkg/common/helper.go
pkg/common/k8s.go
pkg/platform/kube/controller/controller.go
pkg/platform/kube/controller/controller_test.go
pkg/platform/kube/controller/cronjobmonitoring.go
pkg/platform/kube/controller/evictedpodsmonitoring.go
pkg/platform/kube/controller/nucliofunction_test.go
pkg/platform/kube/test/suite.go

Kubernetes sometimes evicts pods if they are too resource-heavy and reclaims the used resources.
Evicted the pods stay in the cluster in `Evicted` state.
In this PR, the nuclio controller spins up a goroutine that looks for evicted pods periodically according to the configurable `evictedPodsCleanupInterval`. 
If the pod is evicted for more than the interval period, it is deleted.
JIRA: https://jira.iguazeng.com/browse/IG-21377

Cleanup evicted function pods

---

.github/workflows/ci.yaml
pkg/platformconfig/platformconfig.go

Also, CI fails `build_nuctl` task because `actions/setup-go@v3` creates `/home/runner/go` as root, thus the runner doesn't have permissions for it. 
In this PR we comment out `nuctl-bin` task in CI until a fix is found.

Fix sensitive fields typo in platform config

---

pkg/platform/kube/platform.go
pkg/platform/kube/platform_test.go
pkg/platform/kube/test/platform_test.go

Currently it is impossible to create an api gateway for a function that already has an ingress, and vice-versa.
However, the nginx ingress controller allows multiple ingresses to forward to a single service, as long as the endpoint path is different (which is already validated).
Multiple canary ingresses will not work ([as per this nginx issue](https://github.com/kubernetes/ingress-nginx/issues/5848)), but this is not the case with the nuclio api gateway which only creates one canary ingress.
This PR removes validation of existing api gateways when adding an ingress to a function's http trigger, and removes validation of existing ingresses when creating an api gateway for a funcition.

Remove existing ingress and api gateway validation

---

hack/k8s/helm/nuclio/templates/deployment/dashboard.yaml
hack/k8s/helm/nuclio/values.yaml
pkg/containerimagebuilderpusher/kaniko.go
pkg/containerimagebuilderpusher/types.go

Kaniko sometimes fails to get filesystem from image:
```
INFO[0002] Unpacking rootfs as cmd COPY --from=python-onbuild /home/nuclio/bin/processor /usr/local/bin/processor requires it. 
error building image: error building stage: failed to get filesystem from image: read tcp 10.200.254.29:58626->65.9.112.124:443: read: connection timed out
/nuclio/pkg/processor/build/builder.go:263
```
This is an issue that still hasn't been addressed by Kaniko - https://github.com/GoogleContainerTools/kaniko/issues/1717 
A current workaround is to best-effort retry extracting the image filesystem (default currently set to 3 retries).
JIRA: https://jira.iguazeng.com/browse/IG-21355

Kaniko - Retry extracting image filesystem

---

cmd/processor/app/processor.go
pkg/dashboard/resource/function.go
pkg/functionconfig/mask.go
pkg/functionconfig/types.go
pkg/platform/kube/client/deployer.go
pkg/platform/kube/functionres/lazy.go

Some fixes following the new function config masking functionality:
- Skip creating flex volume secrets if they do not contain an access key - fixes https://jira.iguazeng.com/browse/IG-21407
- Skip creation of function secret if secret content is empty.
- Remove "has-secret" annotation on GET /functions, as the dashboard adds/removes this annotation depending on actual secrets existence - fixes https://jira.iguazeng.com/browse/IG-21409

Function config secret fixes

---

pkg/functionconfig/mask_test.go
pkg/platformconfig/types.go

Missing `$` at the end of the regex custom caused the `Scrub` functions to mask and reference unwanted fields in the function configuration.
Relates to https://jira.iguazeng.com/browse/IG-21408

Mark sensitive fields regex with end of string

---

pkg/platform/kube/platform.go
pkg/platform/kube/test/platform_test.go

When an http's trigger was set to `nil / null` it was only enriched to the default service type in the controller.
This caused the function config scrubbing (done beforehand in the dashboard) to fail on a zero type.
This PR enriches nil service types in `EnrichFunctionConfig`, right when the Create Function process starts.
https://jira.iguazeng.com/browse/IG-21413

Enrich nil service type in http trigger

---

cmd/processor/app/processor.go
pkg/dashboard/resource/function.go
pkg/functionconfig/types.go
pkg/platform/kube/client/deployer.go
pkg/platform/kube/functionres/lazy.go

Instead of annotating the function with `has-secret = true` for signaling the controller and processor that a secret was created, the controller will always volume the function secret as `optional`, and the processor will just check the existence of the secret in the pre-determined path.

Remove "has-secret" annotation

---

cmd/processor/app/processor.go
pkg/functionconfig/mask.go
pkg/functionconfig/mask_test.go
pkg/platform/kube/client/deployer.go
pkg/platform/kube/test/platform_test.go

When the secret map keys are encoded without the `$ref:` prefix, the processor doesn't restore the scrubbed function config properly. 
Related bug: https://jira.iguazeng.com/browse/IG-21414

Don't remove reference prefix when encoding secret map

---

pkg/functionconfig/mask_test.go
pkg/platform/abstract/platform.go
pkg/platform/kube/client/deployer.go
pkg/platform/kube/platform.go
pkg/platform/kube/test/platform_test.go
pkg/platform/local/platform.go
pkg/platform/mock/platform.go
pkg/platform/platform.go
pkg/platformconfig/types.go

When using function code from Github, S3 and Archive there is sensitive information in the function spec, so we'll scrub it too.
Since the image builder requires that information, and when updating a function these field will have the `$ref:..` reference, the function config is restored before building the image.
This causes some refactoring to allow some better code re-use.
fixes https://jira.iguazeng.com/browse/IG-21430

Refactor platform secret handling and add attributes to sensitive fields

---

pkg/cmdrunner/shellrunner.go
pkg/cmdrunner/types.go
pkg/dashboard/resource/functiontemplate.go
pkg/dockerclient/shell.go
pkg/functionconfig/types.go
pkg/nuctl/test/apigagteway_test.go
pkg/platform/local/client/store.go

most of logs are due to nuclio local store tries to do "get and create" whereas the get fails because some resource does not exist and thus spamming the log with spammy log lines that has nothing meaninful.

Local - reduce misleading error log lines

---

pkg/dashboard/resource/frontendspec.go
pkg/dashboard/test/server_test.go
pkg/functionconfig/types.go
pkg/platform/abstract/platform.go
pkg/platform/abstract/platform_test.go
pkg/platform/kube/functionres/lazy.go
pkg/platform/kube/functionres/lazy_test.go
pkg/platformconfig/platformconfig.go

Metrics are saved in the k8s metric server with a window size (1m, 2m, etc.).
Hence, this should be reflected in the auto scale metrics in the function spec.
In this PR I refactored the `AutoScaleMetric` struct to include the window size, as well as some renaming for the fields so it makes more sense.
This is also reflected in the `frontendSpec`, so the UI will need to handle it accordingly.
Some guidelines for the future UI PR:
Frontend spec - will return `autoScaleMetrics` of the following structure:
```
"autoScaleMetrics": {
"metricPresets": [
{
"metricName": "cpu",
"sourceType": "Resource",
"displayType": "percentage"
},
...
]
"windowSizePresets": [
"1m",
"2m"
]
}
```
The window size presets will be displayed as a dropdown next to the metric selection dropdown, and added to the spec …

Refactor autoscale metric spec

---

pkg/functionconfig/mask.go
pkg/platform/kube/client/deployer.go
pkg/platform/kube/test/platform_test.go

When an already masked value is changed, the new value should be in the secret.
Due to the functionality of `labels.Merge`, the new map got overridden by the old one.
Fixes https://jira.iguazeng.com/browse/IG-21440

Override existing secret map with the new one

---

pkg/functionconfig/mask.go
pkg/platform/kube/client/deployer.go
pkg/platform/kube/functionres/lazy.go
pkg/platform/kube/functionres/lazy_test.go
pkg/platform/kube/platform.go
pkg/platform/kube/test/platform_test.go

This PR addresses several bugs found regarding flex volume secrets:
- Remove trailing non-alphanumeric characters from flex volume secret names (fixes https://jira.iguazeng.com/browse/IG-21443)
- When getting function secrets, copy reference to a new variable so they won't get overridden (fixes https://jira.iguazeng.com/browse/IG-21438)
- Deep copy volumes config in the lazy controller, so manipulating them won't affect the volumes in the function config (fixes https://jira.iguazeng.com/browse/IG-21438)
- Delete stale volume secrets by secret name instead of by volume name label
- Improve logging a bit

Fix flex volume secrets issues

---

pkg/functionconfig/mask_test.go
pkg/platformconfig/types.go

`X-V3io-Session-Key` is a part of the code entry attributes `header` attributes, so the sensitive path is changed accordingly.
Fixes https://jira.iguazeng.com/browse/IG-21430

Set v3io session key header as sensitive field

---

pkg/platform/abstract/platform.go
pkg/platform/kube/functionres/lazy.go
pkg/platform/kube/test/platform_test.go

Following https://github.com/nuclio/nuclio/pull/2762, the controller is doing validation and enrichment on a copy of each function volume, resulting with the actual function spec staying the same.
Moving the subpath validation and enrichment to the dashboard solves this by cleaning the subpath first, before creating the CRD.
Fixes https://jira.iguazeng.com/browse/IG-21463

Move flex volume sub path enrichment to dashboard

---

pkg/dashboard/resource/frontendspec.go
pkg/platformconfig/platformconfig.go

When working in an open-source setup, the scale to zero window size presets are not populated (null).
Since metrics also use window size presets, we add default presets in case the scale to zero presets are not present.
Current defaults are for 1,2,5,10,30 minutes.

Add default window size presets

---

cmd/dashboard/app/run.go
cmd/processor/app/processor.go
cmd/processor/app/processor_test.go
pkg/common/consts.go
pkg/dashboard/resource/function.go
pkg/dashboard/resource/project.go
pkg/dashboard/server.go
pkg/dashboard/test/server_test.go
pkg/functionconfig/mask.go
pkg/functionconfig/mask_test.go
pkg/nuctl/command/export.go
pkg/nuctl/command/import.go
pkg/nuctl/test/apigagteway_test.go
pkg/nuctl/test/function_test.go
pkg/nuctl/test/project_test.go
pkg/nuctl/test/suite.go
pkg/platform/abstract/platform.go
pkg/platform/factory/factory.go
pkg/platform/kube/platform.go
pkg/platform/kube/test/suite.go
pkg/platform/local/platform.go
pkg/platform/mock/platform.go
pkg/platform/platform.go
pkg/platformconfig/platformconfig.go
pkg/processor/test/suite/suite.go

When a function is exported using nuctl or the dashboards api, we do not want scrubbed fields to still contain references.
So, before exporting the function we restore the scrubbed data in the function config.
This PR also replaces `"kube"` and `"local"` magic string with constants, for better reuse of strings.

Restore function config when exporting function

---

cmd/processor/app/processor.go
pkg/dashboard/resource/function.go
pkg/functionconfig/scrubber.go
pkg/functionconfig/scrubber_test.go
pkg/nuctl/command/export.go
pkg/platform/abstract/platform.go
pkg/platform/kube/client/deployer.go
pkg/platform/kube/functionres/lazy.go
pkg/platform/kube/test/platform_test.go

If the function has a flex volume and is then duplicated, the access key field in the function config contains a `$ref`.
We validate that a secret already exists for the same volume name, and not fail due to missing existing secret.
Followup of this PR will be how to resolve all other secrets when duplicating a function, since they're all in the original function's secret.
Also, in this PR I did a bit of a refactor to the mask module -
- Renamed `mask.go` to `scrubber.go`
- Added the `Scrubber` object, that is responsible for all of the scrubbing/restoring/encoding/decoding
Fixes https://jira.iguazeng.com/browse/IG-21490

Validate volume secret exists if access key is already scrubbed

---

pkg/dashboard/resource/function.go
pkg/dashboard/resource/project.go
pkg/dashboard/test/server_test.go

Restoring function config on export using `GET /functions?export=true"` is susceptible to security issues as anyone calling this endpoint can see the actual values.

Don't restore function config when exporting via api

---

pkg/nuctl/command/export.go
pkg/platform/abstract/project/external/leader/iguazio/synchronizer.go

Allow to export both functions and projects without scrubbing sensitive unnecessary data, using `--no-scrub` flag.

Nuctl - move no-scrub flag to export comandeer

---

pkg/platform/kube/controller/evictedpodsmonitoring.go

anyway, when an evicted pod is being deleted, it will be logged

Controller - less spammy

---

pkg/functionconfig/scrubber.go
pkg/functionconfig/scrubber_test.go
pkg/platform/kube/client/deployer.go
pkg/platform/kube/functionres/lazy.go
pkg/platform/kube/test/platform_test.go

Using `XID` to generate random id for the volume secret name and then trimming it according to the k8s guidelines proved to be error-prone, as after the trimming the volume names weren't unique enough, and multiple volumes caused volume secrets to be overridden.
In this PR I improved the secret name generation as follows:
- For function secrets: the format is `nuclio-secret-<project-name>-<function-name>-<unique-id>`. 
If the name > 63 characters, it is trimmed from the right, keeping the unique id.
- For flex volume secrets: the format is `nuclio-flexvolume-<project-name>-<function-name>-<volume-name>-<unique-id>`. 
If the name > 63 characters, the pair `<project-name>-<function-name>` is removed.
If after the removal the name is still too long, trim it from the right, keeping the unique …

Improve secret name generation

---

pkg/platform/abstract/project/external/leader/iguazio/synchronizer.go
pkg/platform/abstract/project/external/leader/iguazio/synchronizer_test.go

When syncing projects from leader, filter out labels that are not allowed in kubernetes so project creation won't fail.
From k8s docs:
> a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.',
and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345',
regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')
Also fixed some unit test mocks following https://github.com/nuclio/nuclio/pull/2792

Project Sync - Filter invalid project labels

---

pkg/dashboard/resource/invocation.go
pkg/platform/abstract/invoker.go
pkg/platform/types.go

Following up https://github.com/nuclio/nuclio/pull/2796 which eliminated the invokeVia from most places we observed that a non backwards compatibility solution was provided, thus this pr provides a fallback for function invocation where, for older api clients, invoking the function will use an invocation url from functions status, as long as none was explicitly provided.

API - backwards compatbility fix

---

Makefile
pkg/dashboard/resource/invocation.go
pkg/platform/abstract/invoker.go
pkg/platform/types.go

cover cases where deprecated `invoke-via` was not given at all along without providing `url`

[Invoke] Default to internal address for better backwards compatibility

---

pkg/functionconfig/types.go

When exporting a function with `no-scrub==true`, the resource version persists and makes it impossible to import the function back.
Since this value is autogenerated by k8s, we can always remove it when exporting.
Fixes https://jira.iguazeng.com/browse/IG-21567

[FunctionConfig] Always scrub function resource version

---

pkg/dashboard/resource/frontendspec.go
pkg/dashboard/test/server_test.go
pkg/platform/kube/functionres/lazy.go
pkg/platformconfig/platformconfig.go
pkg/platformconfig/types.go

Add `AutoScaleMetricsMode` to the platform config, which supports 2 options:
- `legacy` - scale functions according to CPU usage only.
- `custom` - scale function according to user selected metrics.
Also, add a feature flag to the frontend spec specifying whether to show the custom scaling selection fields, or the previous `Target CPU` slider. 
Feature flag is `frontendSpec.autoScaleMetrics.customMetricsEnabled == true/false`.

[PlatformConfig + FrontendSpec] Add auto scale metrics mode

---

cmd/processor/app/processor.go
pkg/functionconfig/scrubber.go
pkg/functionconfig/scrubber_test.go
pkg/platform/kube/client/deployer.go
pkg/platform/kube/controller/nucliofunction.go
pkg/platform/kube/functionres/lazy.go
pkg/platform/kube/functionres/lazy_test.go
pkg/platform/kube/test/platform_test.go

A few fixes regarding function secrets:
- Re-use the function's existing secret when updating a function - Instead of creating a new secret for every redeployment, and possibly deleting secrets that are currently volumed to the running function, the existing secret will be updated on redeploy.
- Remove project name from secret name - a function name is unique in a namespace, and the project is specified in the annotations. 
- Do not delete stale secrets in dashboard - secrets will be deleted by the controller on function deletion.
- When the controller is volumizing the function / volume secret, use the most recently created secret.
- On processor startup - log function config before restoring.
This PR also fixes https://jira.iguazeng.com/browse/IG-21557

[Secrets] Reuse secret names, delete secrets only on function deletion

---

pkg/containerimagebuilderpusher/kaniko.go

Before, every kaniko job failed to get logs.
Now it succeeds:
```
{"level":"debug","time":"2023-02-02T09:15:07.642Z","name":"dashboard.platform.kaniko","message":"Getting job pods","requestID":"83d5c9914a3651b3ba04bba20393805c","more":{"jobName":"nuclio-kanikojob.nucliodefaultabcdefghijklmnopproces.713kbpui5e"}}
{"level":"debug","time":"2023-02-02T09:15:07.649Z","name":"dashboard.platform.kaniko","message":"Fetching pod logs","requestID":"83d5c9914a3651b3ba04bba20393805c","more":{"name":"nuclio-kanikojob.nucliodefaultabcdefghijklmnopproces.713kbzjwnp","namespace":"default-tenan
t"}}
{"level":"debug","time":"2023-02-02T09:15:07.662Z","name":"dashboard.platform.kaniko","message":"Job was completed successfully","requestID":"83d5c9914a3651b3ba04bba20393805c","more":{"jobLogs":"INFO[0000] …
```

[Kaniko] Fix get job pod logs

---

pkg/platform/kube/apigatewayres/lazy.go
pkg/platform/kube/test/platform_test.go

Api gateways annotations were only populated in the api gateway CRD, and not in the created ingress resource.

[API Gateway] Populate ingress with api gateway annotations

---

hack/k8s/helm/nuclio/values.yaml
pkg/dashboard/resource/invocation.go
pkg/dashboard/test/server_test.go
pkg/nuctl/command/invoke.go
pkg/nuctl/test/function_test.go
pkg/platformconfig/platformconfig.go
pkg/platformconfig/types.go

When nuclio is used via third party application (e.g. CVAT), invoking functions does not always support adding custom headers such as `X-Nuclio-Invoke-Timeout`.
In this PR we enable changing the default function invocation timeout via the platform configuration, which can be set in the helm chart at `platform.functionInvocationTimeout` as a string, e.g `180s`.
Resolves #2814

[Platform] Support configurable default function invocation timeout

---

.github/workflows/benchmark.yaml
.github/workflows/ci.yaml
.github/workflows/long_ci.yaml
.github/workflows/periodic.yaml
.github/workflows/release.yaml

Cleanup script was updated and removed `go` binary that was installed prior to that.
Update some of the CI steps and ensure running cleanup script *prior* to go installation so that it wont remove it.

CI - fix workflow breakage

---

go.mod
go.sum
pkg/platform/abstract/platform.go
pkg/platform/abstract/platform_test.go

V3io stream trigger doesn't support autoscaling.
If the function spec has `minReplicas != maxReplicas`, and a v3io-stream trigger - fail validation.
Fixes https://jira.iguazeng.com/browse/IG-21633

[FunctionConfig] Validate autoscaling is supported by trigger

---

pkg/platform/abstract/platform.go

When validating min/max replicas in v3io stream trigger, check the values instead of pointer addresses.
Fixes https://jira.iguazeng.com/browse/IG-21639

[FunctionConfig] Fix checking replica values instead of pointers

---

pkg/platform/kube/functionres/lazy.go

It is observed that function readiness might take a while on slower systems.

[Kube] Tweak function readiness probes

---

cmd/processor/app/processor.go
pkg/processor/trigger/trigger.go

Triggers are created in parallel, initializing the labels within each go routine would end up in a race condition. Fixed by moving the map initialization before go routine starts.

[Trigger] Fix trigger initialization race condition

---

pkg/nuctl/test/function_test.go
pkg/platform/kube/functionres/lazy.go
pkg/platform/kube/functionres/lazy_test.go
pkg/platformconfig/platformconfig.go
pkg/platformconfig/types.go
pkg/processor/build/runtime/shell/runtime.go

In iguazio systems, the communication goes through secure connections, and each ingress has a tls secret.
In this PR, we enrich function ingresses with the iguazio system's tls secret, and enable nginx ssl redirection by default.

[Ingress] Set default TLS secret in iguazio systems [1.9.x]

---

pkg/platform/kube/functionres/lazy.go
pkg/platform/kube/functionres/lazy_test.go
pkg/platformconfig/platformconfig.go
pkg/platformconfig/types.go

In iguazio systems, the communication goes through secure connections, and each ingress has a tls secret.
In this PR, we enrich function ingresses with the iguazio system's tls secret, and enable nginx ssl redirection by default.

[Ingress] Set default TLS secret in iguazio systems [1.10.x]

---

.github/workflows/release.yaml

On forks some credentials might be missing and releases constantly fail.
Anyways, no need to release from forks at all.

[Release] Only run release job on main fork

---

cmd/dashboard/README.md
pkg/dashboard/resource/invocation.go
pkg/nuctl/command/invoke.go
pkg/platform/abstract/invoker.go
pkg/platform/types.go

Support skipping tls verification when invoking a function via:
1. `/function_invocations` endpoint - send a request with the following header:
```
X-nuclio-skip-tls-verification: true
```
2. nuctl - add the `--skip-tls` flag to the `invoke` command.
followup to #2839

[Invoke] Add option to skip tls verification

---

docs/reference/function-configuration/function-configuration-reference.md
pkg/dockerclient/shell.go
pkg/dockerclient/types.go
pkg/platform/local/platform.go
pkg/platform/local/platform_test.go

Idea is to support local platform functions memory and cpu resource management.  We do support that for kubernetes, using kubernetes sdk, we will use it and translate the "kubernetes" resource unit sizes and provide it as docker-compatible unit sizes for both cpu and memory.

[Local] Support providing function cpu and memory

---

.github/workflows/ci.yaml
pkg/dashboard/resource/frontendspec.go
pkg/platform/abstract/platform.go
pkg/platform/kube/controller/test/controller_test.go
pkg/platform/kube/platform.go
pkg/platform/local/platform.go
pkg/platform/mock/platform.go
pkg/platform/platform.go

In a kube platform, the container builder is only needed when creating a new function.
Initializing it only when needed allows other operations to run with a platform without it.
This resolves issues that occur when nuctl, for example, wants to perform operations without docker being installed on the system.
In docker platform it is still initialized when creating a new platform, as docker is needed anyways to perform all operations.
Resolves https://github.com/nuclio/nuclio/issues/2854

[Kube] Initialize container image builder pusher only when needed

---

docs/reference/triggers/rabbitmq.md
pkg/processor/trigger/rabbitmq/trigger.go
pkg/processor/trigger/rabbitmq/types.go

When configuring the rabbit broker channel a value called prefetch is determined which selects how many events will be fetched even before it's time to ingest them. When the `prefetch` value isn't configured correctly (for example takes all) it can mess with the scaling of the Nuclio since the new pods will not have any messages to ingest (already found in another pod).
Added the ability to configure the prefetch using attributes from the rabbit trigger, if not configured (or 0) will act as before (rabbit default). example:
```yaml
rabbit-example:
class: ""
kind: rabbit-mq
name: rabbit-example
url: "amqp://rmq-host:5672"
attributes:
prefetchCount: 1
exchangeName: exchangeName
topics:
- someKey
```
Tested manually on a Nuclio cluster using MLRun community edition …

[RabbitMQ] Use prefetch from configuration

---

.github/ISSUE_TEMPLATE/config.yml

The old link no longer exists, use the new one: https://go.iguazio.com/nuclio/joincommunity

[Issues] Update slack invite link

---

go.mod
go.sum
pkg/dashboard/functiontemplates/basefunctiontemplatefetcher.go
pkg/dashboard/functiontemplates/generated.go
pkg/dashboard/functiontemplates/generatedfunctiontemplatefetcher.go
pkg/dashboard/functiontemplates/generator/generator.go
pkg/dashboard/functiontemplates/render.go
pkg/functionconfig/reader.go
pkg/functionconfig/reader_test.go
pkg/nuctl/command/common/helpers.go
pkg/nuctl/test/function_test.go
pkg/nuctl/test/project_test.go
pkg/nuctl/test/suite.go
pkg/platform/kube/functionres/lazy.go
pkg/platform/kube/test/suite.go
pkg/platform/local/platform.go
pkg/platformconfig/reader.go
pkg/processor/build/runtime/java/types.go
pkg/processor/config/reader.go
pkg/processor/config/writer.go

The package `github.com/ghodss/yaml` is no longer actively maintained. [`sigs.k8s.io/yaml`](https://github.com/kubernetes-sigs/yaml) is a permanent fork of `github.com/ghodss/yaml`. It is actively maintained by Kubernetes SIG, and also widely used in K8s projects.
The notable change is that `github.com/ghodss/yaml` uses `gopkg.in/yaml.v2 v2.2.2`, but `sigs.k8s.io/yaml` uses `gopkg.in/yaml.v2 v2.4.0`. Changes can be seen here [v2.2.2...v2.4.0](https://github.com/go-yaml/yaml/compare/v2.2.2...v2.4.0), mostly bug fixes.

Replace `github.com/ghodss/yaml` with `sigs.k8s.io/yaml`

---

pkg/functionconfig/scrubber.go
pkg/functionconfig/scrubber_test.go
pkg/platform/kube/platform.go
pkg/platform/kube/test/platform_test.go
pkg/platformconfig/platformconfig.go

Gosecretive's restore sometimes altars complex objects inside the function config.
To avoid it, we convert the config to map before restoring, and convert back to function config object afterwards, same as we do when scrubbing it.
Fixes https://jira.iguazeng.com/browse/IG-21726

[Scrubber] Convert function config to map when restoring

---

pkg/processor/trigger/kafka/types.go
pkg/processor/trigger/types.go
pkg/processor/trigger/v3iostream/types.go

To add an option to enable the explicit ack feature via UI, allow setting explicit ack mode in annotations for kafka and v3io stream triggers.
Supported modes: `enable`, `disable`, `explicitOnly`.
**Usage example:** add the following annotations:
kafka:
```
"nuclio.io/kafka-explicit-ack-mode": "enable"
```
v3io stream:
```
"nuclio.io/v3iostream-explicit-ack-mode": "enable"
```

[Kafka/V3ioStream] Allow setting explicit ack mode via annotations

---

pkg/dashboard/resource/function.go

Allow redeploying a function regardless of its current state.
Relates to https://github.com/nuclio/nuclio/issues/2685

[Function] Ignore current function state when patching a function

---

pkg/common/headers/headers.go
pkg/dashboard/resource/function.go
pkg/dashboard/test/server_test.go
pkg/nuctl/command/deploy.go

When redeploying functions, support redeploying only imported functions by passing the following header:
```
"X-Nuclio-Imported-Function-Only": "true"
```
To do it in nuctl, pass the `--imported-only` flag to the `nuctl beta deploy --no-build` command.

[Function / Nuctl] Support patching imported functions only

---

test/k8s/ci_assets/install_nginx_ingress_controller.sh

Replace the nginx ingress controller installation script from `kubectl apply` to `helm upgrade` to be aligned with the latest nginx versions and being able to upgrade easily.

[Assets] Install nginx ingress controller using helm

---

Makefile
pkg/processor/build/runtime/golang/docker/onbuild/Dockerfile.alpine
pkg/processor/build/runtime/java/docker/onbuild/Dockerfile

compiling go on alpine failed due to missing `ld` - added `binutils-gold` os package
compiling java failed due to usage of non-arm image - injected suitable arm image for java sdk

[Build] Fix building java & go runtimes for arm

---

.github/workflows/release.yaml

export `DOCKER_DEFAULT_PLATFORM ` to ensure all docker builds command passes are targeted to right architecture
in addition, use docker qemu install script, for simplicitness

[Release] Fix building images for arm

---

.github/workflows/release.yaml

Building arm64 images takes a very long time (~2.5h) and causes the release to be "dangling" for too long.
To decrease release time, we add the docker images to be built to the workflow's matrix, and build them in parallel.

[Release] Build and push images in parallel

---

.github/workflows/release.yaml

Golang runtime's handler onbuild doesn't require the processor image when building.

[Release] Don't add processor image to golang runtime onbuilds

---

.dockerignore
.github/workflows/ci.yaml
.github/workflows/release.yaml
.github/workflows/security_scan.yaml
.gitignore
Makefile
cmd/processor/Dockerfile

When compiling processor under different architecture than host, the emulation layer of qemu/docker makes build process takes forever.
In order to reduce it, we will compile processor binary on host while injecting the "architecture" to go, allowing it to compile it natively to its desired arch and the processor image will simply load it. that way, we reduce the compilation of processor on image from ~30m to ~3m for arm64

[Release] Faster processor build

---

.github/workflows/release.yaml
Makefile

When making onbuild golang  it builds alpine image as well as go function defaultto alpine images. for development it is handy, for release it runs the build twice while not needed. this PR ensure when building alpine / regular onbuild go, it builds them only

[CI] Refine release

---

Makefile
cmd/autoscaler/Dockerfile
cmd/controller/Dockerfile
cmd/dashboard/docker/Dockerfile
cmd/dlx/Dockerfile
pkg/platform/factory/factory.go
pkg/platform/local/client/store.go
pkg/platform/local/platform.go
pkg/processor/build/runtime/golang/docker/onbuild/Dockerfile
pkg/processor/build/runtime/golang/docker/onbuild/Dockerfile.alpine

1. no need `-a --installsuffix cgo` when `CGO_ENABLED=0`
2. fix building processor on mac (missing target os)
3. print nuclio version upon platform initialization
4. pick store image according to go arch (runtime)
5. pick node image according to go arch (buildtime)

[Build] Update go build commands

---

docs/reference/triggers/kafka.md
docs/reference/triggers/v3iostream.md

V3io stream doc referenced kafka.
Fixes https://jira.iguazeng.com/browse/IG-21814

[Docs] Fix explicit ack notes in kafka and v3iostream

---

pkg/processor/build/runtime/golang/docker/onbuild/Dockerfile.alpine

Building docker images for the `handler-builder-golang-onbuild` target intermittently fails the following step in the Dockerfile:
```sh
RUN apk upgrade --no-cache     && apk add --no-cache git gcc musl-dev file binutils-gold
```
With the following errors:
```
ERROR: libstdc++-12.2.1_git20220924-r4: remote server returned error (try 'apk update')
ERROR: binutils-gold-2.39-r2: remote server returned error (try 'apk update')
...
```
So adding apk update before the RUN command.

[Build] `apk update` before adding alpine packages in Go runtime

---

pkg/processor/trigger/kafka/test/kafka_test.go
pkg/processor/trigger/kafka/trigger.go
pkg/processor/trigger/v3iostream/trigger.go

When explicit ack mode is set to `explicitOnly`, after submitting the event and handling the `processErr` the error was ignored and not passed back to the `subnmittedEvent.done` channel.
This caused the handler in `ConsumeClaim` to be starved waiting for the event handling to be done, and block it from iterating to the next record batch.
To fix it, in `explicitOnly` mode the event submitter should always return a non-nil error, so the record won't be committed, as they should only be committed in the explicit ack handler.
This is relevant both for kafka and v3io stream triggers.
Fixes https://jira.iguazeng.com/browse/IG-21816

[Stream] Fix submitted event handling for explicit ack only mode

---

pkg/processor/trigger/kafka/kafka_test.go
pkg/processor/trigger/kafka/types.go
pkg/processor/trigger/v3iostream/types.go
pkg/processor/trigger/v3iostream/v3iostream_test.go

Validate the new configuration's explicit ack mode against the worker allocation mode after it is populated from annotations, instead of validating against the trigger configuration.
Fixes https://jira.iguazeng.com/browse/IG-21815

[Stream] Fix validation of explicit ack mode with worker pool mode

---

docs/reference/triggers/v3iostream.md

V3IO stream trigger doesn't support rebalace, this `on_signal` is irrelevent for it.
Resolves https://jira.iguazeng.com/browse/IG-21820

[Docs] Remove rebalance section from v3iostream trigger

---

pkg/platform/abstract/platform.go
pkg/processor/trigger/kafka/kafka_test.go
pkg/processor/trigger/kafka/test/kafka_test.go
pkg/processor/trigger/kafka/types.go
pkg/processor/trigger/types.go
pkg/processor/trigger/v3iostream/types.go
pkg/processor/trigger/v3iostream/v3iostream_test.go

In stream triggers (kafka/v3io) setting worker allocation mode via annotations is supported, however in most cases it is set in the trigger attributes (e.g. in the UI).
Unorganized code caused the annotation value to always override the attribute, and populate the default in case no annotation was given.
In this PR I added a common function to resolve the worker allocation mode, where the attribute has priority over the annotation, as annotations are mostly used for tech-previewing functionalities.
Fixes https://jira.iguazeng.com/browse/IG-21823

[Trigger] Fix resolving worker allocation mode

---

.github/workflows/long_ci.yaml

[CI] Allow running `long_ci` on development

---

pkg/platform/kube/controller/controller.go
pkg/processor/runtime/rpc/encode.go
pkg/processor/runtime/rpc/encode_msgpack.go

For some reason, the `offset` event field was ignored by the event encoder while transforming the event to a map.
This caused issues with explicit acks, as the offset value was always set to zero.
Resolves https://jira.iguazeng.com/browse/IG-21839 along with https://github.com/nuclio/nuclio-sdk-py/pull/47

[Event Encoder] Add `offset` filed when encoding events

---

pkg/nuctl/command/version.go

Resolves https://github.com/nuclio/nuclio/issues/2931

[Nuctl] Add trailing new line to version command output

---

pkg/common/helper.go
pkg/nuctl/command/deploy.go
pkg/nuctl/test/function_test.go

When deploying a function with nuctl and passing a function yaml file, the function name was overridden with an different value and caused some issues, such as the updater updating the wrong function.
In this PR I did some organization regarding overrides:
1. Validate that a function name is indeed given.
3. If flag args are given as well as a function config file, give precedence to the flag arguments and override them.
Fixes https://github.com/nuclio/nuclio/issues/2934

[Nuctl] Deploy - Fix config enrichment

---

pkg/platform/abstract/project/external/leader/iguazio/client.go

When a communication error occur the response object is nil, thus a panic occur

[Platform] Fix iguazio client

---

pkg/nuctl/client/api.go
pkg/nuctl/command/beta.go
pkg/nuctl/command/deploy.go

For making requests to the nuclio api, nuctl uses a basic authentication header.
This authentication method only works with a username and an access key, an not password.
Thus, to use the `beta` deploy command, pass the `--access-key` flag.
Also, removed username requirement.
Resolves https://jira.iguazeng.com/browse/IG-21894

[Nuctl] Rename beta's `password` flag to `access-key`

---

pkg/processor/runtime/python/py/requirements/common.txt
pkg/processor/runtime/rpc/abstract.go
pkg/processor/trigger/http/test/suite/http_test.go

When an error occurs during event processing, the the rpc runtime just ignores it, and a successful empty response is returned.
In this PR we return the error, resulting with a 500 response with the error message in the body.
Plus, bump nuclio-sdk-py to v0.5.5, which contains a fix on handler return values - https://github.com/nuclio/nuclio-sdk-py/pull/52 
Resolves https://jira.iguazeng.com/browse/IG-21912

[RPC Runtime] Return event process error to trigger

---

pkg/nuctl/command/deploy.go

The build commands were mistakenly ignored in the deploy refactor https://github.com/nuclio/nuclio/pull/2935.
Brought back in this PR.

[Nuctl] Deploy - fix build commands support

---

pkg/nuctl/client/api.go

Increase default timeout to 5 minutes, as 1 minute is too short for some of the actions.
Resolves https://jira.iguazeng.com/browse/IG-21931

[Nuctl] Increase http client's default timeout

---

pkg/platform/kube/functionres/lazy.go
pkg/platform/kube/test/platform_test.go

The `AutoScaleMetricsMode` was introduced as a prep for supporting different auto scale metrics.
However, this mode is still not exposed to the users properly, and we still want to let the user set explicit kubernetes-y custom auto scale metrics.
So in this PR we don't ignore the given custom scaling metrics, regardless of the `AutoScaleMetricsMode` value.

[Scaling] Don't ignore explicit custom scaling metrics in "legacy" AutoScaleMetricsMode

---

.github/workflows/periodic.yaml

Periodic CI fails lately with the following errors:
```
The operation was canceled.
```
```
The runner has received a shutdown signal. This can happen when the runner service is stopped, or a manually started runner is canceled.
```
This is an issue with the github runners, and as suggested in https://github.com/actions/runner-images/discussions/7188 - downgrading the runners to `ubuntu-20.04` should fix the issue.

[CI] Downgrade periodic runner to ubuntu-20.04

---

pkg/dashboard/resource/function.go
pkg/dashboard/test/server_test.go
pkg/nuctl/client/api.go
pkg/nuctl/client/types.go
pkg/nuctl/command/common/helpers.go
pkg/nuctl/command/deploy.go

When redeploying functions with the `--wait` flag, poll the function status to make sure function is redeployed instead of letting the server (dashboard) wait for the deployment to complete.
Added a flag `--wait-timeout` to modify the timeout when waiting for the function redeployment to complete. Defaults to 15 minutes.
Also, PATCH function will return status 202 (Accepted) as the redeployment is async.
Resolves https://jira.iguazeng.com/browse/IG-21931

[Nuctl] Poll function status when waiting for function redeployment

---

.github/workflows/ci.yaml
hack/scripts/ci/free-space.sh

Test K8s Nuctl job fails intermittently in CI with `Error: No space left on device` from docker.
To fix this, we run the `free_space.sh` step in the job as well.
Also - I removed some more stuff in the free space script to hopefully free more space.

[CI] Free space in Test K8s Nuctl job

---

pkg/dashboard/resource/function.go
pkg/dashboard/test/server_test.go
pkg/nuctl/command/deploy.go
pkg/platform/kube/client/updater.go
pkg/platform/kube/platform.go
pkg/platform/local/platform.go
pkg/platform/local/test/platform_test.go
pkg/platform/mock/platform.go
pkg/platform/platform.go
pkg/platform/types.go

When redeploy functions, instead of recreating the function (enriching, building etc) we change the function CRD status to "waitingForResourceConfiguration", and add an annotation.
This triggers the controller to update all related resources, and bring the function to a ready state.
Related jira ticket: https://jira.iguazeng.com/browse/IG-21931

[Function] Redeploy using crd state update

---

.github/workflows/release.yaml

Currently, we release the nuctl binary in the following OS/Architecture matrix:
linux / amd64 + arm64
darwin (macOS) / amd64
windows / amd64
We need to add  darwin / arm64 to the binary releases.

[CI] Added release of nuctl darwin arm64 binary

---

pkg/processor/runtime/rpc/abstract_test.go

In the abstract runtime tests we use the runtime's `Stop` function, this in turn signals the runtime to drain using `SIGUSR1`.
Since the test runtime doesn't register to this signal, it causes tests to fail.
We should skip the signaling by default by setting `isDrained` to true.

[RPC] Fix testRuntime drain failures

---

pkg/processor/trigger/kafka/trigger.go

It has been seen that when a rebalance occurs, the last event before the rebalance is handled twice, regardless of the timeout configurations described in https://github.com/nuclio/nuclio/blob/development/docs/reference/triggers/kafka.md#rebalancing-config-choice .
We noticed that while the kafka trigger does wait for the worker to finish handling the last event, when it is done the event offset is not committed on the stream, and thus at least a single event will be handled twice.
In this PR we commit event in such cases. 
JIRA: https://jira.iguazeng.com/browse/IG-22040

[Kafka] Commit the offset when handler is done on rebalance

---

hack/k8s/helm/nuclio/templates/rolebinding/crd-admin.yaml
pkg/processor/runtime/rpc/abstract_test.go

Jira: `IG-22043`
In the Nuclio helm chart, we define the value of `rbac.crdAccessMode` to be either "cluster" or "namespaced".
If set to "namespaced" - all RBAC resources are created in the given namespace (e.g Roles, Rolebindings)
If set to "cluster" - all RBAC resources are created cluster-wide (e.g ClusterRoles, ClusterRolebindings)
It has been seen that for RoleBindings, a ClusterRoleBinding is created regardless of the 
crdAccessMode value. This can cause issues when installing Nuclio without cluster admin permissions, and when the relevant ClusterRole doesn't exist.

[Helm] Fix creation of ClusterRoleBinding for namespace access mode

---

cmd/processor/app/processor.go
cmd/processor/app/processor_test.go
pkg/platform/kube/test/platform_test.go
pkg/platform/kube/test/suite.go
pkg/processor/runtime/rpc/abstract.go
pkg/processor/trigger/cron/types.go
pkg/processor/trigger/http/types.go
pkg/processor/trigger/kafka/kafka_test.go
pkg/processor/trigger/kafka/trigger.go
pkg/processor/trigger/kafka/types.go
pkg/processor/trigger/kickstart/types.go
pkg/processor/trigger/kinesis/types.go
pkg/processor/trigger/mqtt/types.go
pkg/processor/trigger/nats/types.go
pkg/processor/trigger/partitioned/eventhub/types.go
pkg/processor/trigger/partitioned/types.go
pkg/processor/trigger/poller/types.go
pkg/processor/trigger/pubsub/types.go
pkg/processor/trigger/rabbitmq/types.go
pkg/processor/trigger/trigger.go
pkg/processor/trigger/types.go
pkg/processor/trigger/v3iostream/types.go

Jira: `IG-22036`
When a pod is deleted, k8s signals the main process with a SIGTERM, and after a certain grace period (30 seconds) it kills the process with SIGKILL. (https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#pod-termination)
We want to use this grace period to drain the workers properly, and allow them to execute their termination callback (if it exists).

[Processor] Add workers draining on processor termination

---

pkg/common/headers/headers.go
pkg/dashboard/resource/function.go
pkg/dashboard/resource/project.go
pkg/dashboard/resource/resource.go
pkg/functionconfig/types.go
pkg/nuctl/command/common/renderers.go
pkg/nuctl/command/deploy.go
pkg/nuctl/command/export.go
pkg/nuctl/command/get.go

Jira:`IG-22067`
When redeploying an imported function, the dashboard updates the CRD status and the controller creates the relevant resources.
However - when exporting the function in the first place, the image in `spec.image` is cleared. This results with the controller creating a deployment with an empty image name, although it might already exist in the registry.
To overcome this, we should add an option to keep the image name in the spec, so when the deployment is created it will use the same image.
If the image won't exist in the registry - the redeployment will still fail, and a regular deployment will be required.

[Nuctl] Add flag to leave image info in function config 

---

hack/k8s/helm/nuclio/templates/rolebinding/crd-admin.yaml
pkg/processor/runtime/rpc/abstract_test.go

Reverts nuclio/nuclio#2986, since it caused other issues reverting https://github.com/nuclio/nuclio/pull/2987

Revert "[Helm] Fix creation of ClusterRoleBinding for namespace access mode"

---

pkg/processor/trigger/kafka/trigger.go

Jira: `IG-22062`
We got a panic:
```
panic: send on closed channel
goroutine 1530 [running]:
github.com/nuclio/nuclio/pkg/processor/trigger/kafka.(*kafka).ConsumeClaim.func1()
/home/runner/work/nuclio/nuclio/pkg/processor/trigger/kafka/trigger.go:302 +0x22a
created by github.com/nuclio/nuclio/pkg/processor/trigger/kafka.(*kafka).ConsumeClaim
/home/runner/work/nuclio/nuclio/pkg/processor/trigger/kafka/trigger.go:277 +0xaa5
```
The reason for this panic was an attempt to record in an already closed channel. We closed this channel due to the timeout waiting for the completion of two goroutines, so we just exited. After discussing with @TomerShor various options for solving the problem of synchronizing the closing of the channel and writing to it, it was decided to simply add panic recover to …

[Processor] Fix panic on try to write to closed channel 

---

pkg/dashboard/resource/function.go
pkg/dashboard/test/server_test.go
pkg/functionconfig/types.go
pkg/nuctl/command/export.go

Jira: `IG-22051`
When exporting a function, add its current state as an annotation "nuclio.io/previous-state".
The state should be taken from the function status, and should be one of the available options of "FunctionState".
This will later be used when importing and redeploying function to determine the desired state.

[Nuctl] Add previous state annotation when export function

---

pkg/opa/opa.go
pkg/platform/abstract/platform.go
pkg/platform/kube/platform.go
pkg/platform/local/platform.go

Add opa permissions check when patching a function for redeployment.
The check is for the `create` action, for the following resource:
```
/projects/<project-name>/functions/<function-name>/redeploy
```
Resolves https://jira.iguazeng.com/browse/IG-22061
Related to https://github.com/iguazio/zebo/pull/6309

[OPA] Add redeploy function permission check

---

pkg/functionconfig/types.go
pkg/platform/kube/client/updater.go
pkg/platform/kube/controller/nucliofunction.go

Jira: `IG-22050`
There are some annotations added to the Nuclio function CRD that are being used only to communicate some details from the dashboard to the controller.These annotations are then put on the function deployment itself, although they are not needed there and can confuse and distract the users. The controller should clean the irrelevant annotations from the CRD before adding them the the resources it creates (only if they exist).

[Controller] Remove internal annotations from function deployment

---

pkg/common/version.go
pkg/processor/runtime/rpc/abstract.go
pkg/processor/test/suite/suite.go
pkg/processor/timeout/timeout.go
pkg/processor/trigger/http/test/suite/suite.go
pkg/processor/trigger/kafka/trigger.go
pkg/processor/worker/allocator.go

Various of changes were made, all of them together are part of my investigation and fixing of the "Timeout" integ test that has raised a regression on how python handles event timeout
Processor:
- Moved trigger timeout before restart to ensure 408 is returned (for http trigger specifically) prior to (hard / soft) restart.
- Added some logs to when workers / triggers are being stopped
- Removed the draining call from `Stop()` to force explicit call to `Drain()` prior to `Stop()`. The reason of it is to speed up the `stop` flow when it is required. if there is any need to `Drain()`, then it is up to the callee to invoke it first.
- Drain single worker as well
Tests:
- Log container logs upon request failure
- Added `common.SetVersionFromEnv()` to suite to allow using envvars (such as …

[Processor] Fix event timing out

---

pkg/processor/trigger/kafka/trigger.go
pkg/processor/worker/allocator.go
pkg/processor/worker/worker.go

Jira: `IG-22088`
Recently nuclio function with explicitAck kafka trigger stopped consumption on certain partition for some reason.
The thing is that `ConsumeClaim` is a go routine spawned by sarama for each partition, so basically, the `SignalWorkerDraining` is invoked N times (as the amount of the partitions we get, so each worker drains itself over and over again while crashing and left in zombie state. The solution is to synchronise workers draining with blocking each worker state during draining process.

[Processor] Fix unexpected consumption stop 

---

cmd/processor/app/processor.go
cmd/processor/app/processor_test.go
pkg/common/status/status.go
pkg/nuctl/command/export.go
pkg/processor/trigger/kafka/trigger.go
pkg/processor/trigger/trigger.go
pkg/processor/util/partitionworker/allocator.go
pkg/processor/worker/allocator.go
pkg/processor/worker/worker.go

Reduce spammy log lines
Fixed potential race condition where a drained-worker would be reset while another partition will now try to drain it again
Improve some log lines with relevant kwargs

[Kafka] Explicit ack enhancements

---

pkg/common/headers/headers.go
pkg/dashboard/resource/function.go
pkg/nuctl/command/deploy.go

Jira: `IG-22044`, `IG-22084`
When redeploying function post-upgrade, the redeployment will work only if Nuclio uses an external registry and the function images are persisted.
If Nuclio uses the internal app node registry, the images will be deleted during the cluster re-installation as the app-node registry is volatile.
This can be configured using a header to the PATCH request:
`x-nuclio-verify-external-registry` - Only redeploy functions if the registry is external.
If the header is given and the registry is internal, return 412 status code (PreconditionFailed).

[Nuctl][Dashboard] Add flag to ensure external registry when redeploying functions

---

pkg/containerimagebuilderpusher/docker.go
pkg/containerimagebuilderpusher/kaniko.go
pkg/containerimagebuilderpusher/types.go
pkg/dockerclient/shell.go
pkg/nuctl/command/deploy.go
pkg/processor/build/builder.go

Added skip-external-registry-verify option to nuctl beta deploy and fixed typo in BuildFlags

[Nuctl] Add skip-external-registry-verify option to nuctl beta deploy

---

pkg/nuctl/command/beta.go
pkg/nuctl/command/deploy.go
pkg/nuctl/command/nuctl.go
pkg/nuctl/command/redeploy.go

Jira: `IG-22145`
As part of this task, we are transferring part of the functionality of the `deploy` command to a separate `redeploy` command. That part of the functionality in the `deploy` that worked in beta mode with the flag `--no-build` will now be in `redeploy`. 
Beta Commander will only contain `redeploy` command for now, because following our concept that everything that uses the api is beta, this is the only command that uses the api. That is, the `redeploy` command will be available only in beta mode. 
In turn, the `deploy` command will contain only that part of the functionality that was in the main mode.
In other words, `deploy=build+deploy from scratch` and `redeploy=deploy without build`

[Nuctl] Move redeploying functionality to a new command

---

pkg/nuctl/command/common/patchmanifest.go
pkg/nuctl/command/common/patchmanifest_test.go
pkg/nuctl/command/import.go
pkg/nuctl/command/redeploy.go

While using the new `redeploy` nuctl command I noticed several thing that are fixed in this PR: 
- Replace Info and Debug logs so that the default logs will be more informative
- Expand and fix help messages for `redeploy` and `import`, and for some flags
- Allow redeploying from file and passing function names as arguments (merge them)
- Use `RetryUntilSuccessful` when waiting for function deployment
Example usage of command:
```bash
nuctl --namespace <namespace> beta redeploy --api-url <api-url> --access-key <access-key> --save-report --report-file-path temp/nuctl-redeploy-report.json --skip-tls-verify --wait --wait-timeout 10m --verbose
```

[Nuctl] Improve `redeploy` user experience

---

.github/workflows/security_scan.yaml

The current security scan publishes the results to github actions by default when running on `development` branch, and it is not easy to identify the vulnerabilities.
In this PR I improved the workflow by:
1. Replace Trivy scan with Grype scan
2. Print report by default instead of publish report to Github
3. Add workflow options

[CI] Security Scan - use grype instead of trivy and print results

---

pkg/functionconfig/types.go
pkg/platform/kube/client/deployer.go
pkg/platform/kube/controller/nucliofunction.go
pkg/platform/kube/test/platform_test.go

https://jira.iguazeng.com/browse/NUC-31
When redploying functions post-upgrade, there is a risk of trying to create many pods at once and failing to get all resources.
Furthermore, if a function was scaled-to-zero before upgrading, it should remain scaled-to-zero post upgrade as well. To deploy it - the user should just invoke it. Within this PR the ability of redeploying function right to the status which function had before being imported is added.

[Controller] Allow redeploying function as Scaled To Zero

---

pkg/common/headers/headers.go
pkg/common/types.go
pkg/dashboard/resource/function.go
pkg/dashboard/resource/resource.go
pkg/dashboard/test/server_test.go
pkg/functionconfig/types.go
pkg/nuctl/command/export.go

Reverts part of https://github.com/nuclio/nuclio/pull/3028 , while keeping the `ExportFunctionOptions` struct.
After some discussion it was decided to revert the default behavior, so older clients that run export without the newly added nuctl flag `--with-previous-status` will still export functions with it, and the redeployment will consider the previous state.

[Nuctl] Export with previous status annotations by default

---

.github/workflows/release.yaml

There are some issues with building dotnet on qemu for arm64

[CI] Skip building dotnet for arm64

---

pkg/dashboard/resource/function.go
pkg/dashboard/test/server_test.go
pkg/nuctl/command/redeploy.go
pkg/platform/kube/apis/nuclio.io/v1beta1/types.go
pkg/platform/kube/platform.go
pkg/platform/types.go

Jira: [NUC-67](https://jira.iguazeng.com/browse/NUC-67)
Since we currently support function deployment not only as `ready`, but also as `scaledToZero`, we decided to allow the user to specify the `desired-state` parameter in the redeploy command. We currently only support `scaledToZero` and `ready` states. Default desired state is `ready`

[Dashboard][Controller][Nuctl] Redeploy to desired state

---

pkg/nuctl/command/common/patchmanifest.go
pkg/nuctl/command/redeploy.go

When some function fail to redeploy and the redeployment report is saved, log that it is possible to redeploy retryable functions from the report.

[Nuctl] Log how to redeploy from report if functions failed redeployment

---

pkg/common/types.go
pkg/dashboard/resource/function.go
pkg/dashboard/resource/resource.go
pkg/functionconfig/types.go
pkg/nuctl/command/export.go

It was decided to keep the image spec by default when we export function

[Nuctl] Keep image in spec by default when exporting

---

pkg/processor/trigger/types.go

When populating explicit ack mode on the trigger configuration, the value from `spec.trigger[<name>].explicitAckMode` was ignored and the default `disable` mode was used, unless given in the annotations.

[Trigger] Fix explicit ack mode population

---

.github/workflows/periodic.yaml
Makefile
pkg/platform/local/test/platform_test.go
pkg/processor/build/builder.go
pkg/processor/test/suite/suite.go

Jira - [NUC-34](https://jira.iguazeng.com/browse/NUC-34)
Within this PR:
* split periodic CI into 7 parallel jobs using matrix
* removed python3.6 usage from builder
* fixed platform test so they can be run independently from other tests
Here is run example: https://github.com/nuclio/nuclio/actions/runs/6637257969
Instead of ~2h30min execution, whole tests run takes ~1hour

[CI] Run tests with long execution time in parallel with the fast ones

---

go.mod
go.sum

Includes security and bugfixes.
https://github.com/grpc/grpc-go/releases/tag/v1.57.1
https://github.com/grpc/grpc-go/releases/tag/v1.57.2

[Dependencies] Bump google.golang.org/grpc from 1.57.0 to 1.57.2

---

pkg/processor/trigger/nats/test/nats_test.go
pkg/processor/trigger/nats/trigger.go
pkg/processor/trigger/test/eventrecorder.go

In the current implementation of the NATS trigger, even when multiple workers are configured, the event is submitted to the event, and the next event will only be submitted once the previous event is done processing.
Since we do not do anything after an event is processed, we can better utilize the multiple workers by processing the events concurrently.
Resolves #2955

[NATS] Submit events to workers concurrently

---

pkg/platform/kube/test/platform_test.go

I noticed that TestDeployFunctionWithSidecarSanity fails frequently, so we need to restart CI. So, I added the use of the RetryUntilSuccessful method so that we can wait some time for the expected log.
For instance, https://github.com/nuclio/nuclio/actions/runs/6734461758, https://github.com/nuclio/nuclio/actions/runs/6733740643

[Tests] Add RetryUntilSuccessful to TestDeployFunctionWithSidecarSanity

---

pkg/platform/kube/platform.go

Jira - https://jira.iguazeng.com/browse/NUC-78
The idea of this PR is to make it possible to run nuctl in the pod without kubeconfig propagation. We need this to unblock cluster backup/restore feature so it could backup and restore all nuclio staff

[Nuctl] Make it possible to run nuctl in the pod without kubeconfig propagation

---

pkg/processor/runtime/python/py/requirements/common.txt
pkg/processor/runtime/python/py/requirements/python3_10.txt
pkg/processor/runtime/python/py/requirements/python3_11.txt
pkg/processor/runtime/python/py/requirements/python3_7.txt
pkg/processor/runtime/python/py/requirements/python3_8.txt
pkg/processor/runtime/python/py/requirements/python3_9.txt

Bump pip to the latest version for all python version, following some security threats: https://github.com/nuclio/nuclio/security/dependabot

[Python] Bump pip for all python versions

---

pkg/platform/kube/functionres/lazy.go

When a pod has multiple containers, getting logs require specifying the container name.
When sidecars are set for a function, this can cause error when a deployment fails and the dashboard tries getting the pod logs, resulting with the following output:
```
Failed to read logs: a container name must be specified for pod <pod-name>, choose one of: [nuclio sidecar-container]
```
In this PR we set the default logs container to the nuclio function container when sidecars are set.
see https://text.superbrothers.dev/en/201123-allow-to-preselect-interesting-container-in-logs/

[Controller] Set default logs container when sidecars are set

---

cmd/controller/app/controller.go
cmd/controller/main.go
pkg/platform/kube/controller/controller.go
pkg/platform/kube/controller/controller_test.go
pkg/platform/kube/controller/nucliofunction_test.go
pkg/platform/kube/monitoring/function.go
pkg/platform/kube/monitoring/function_test.go
pkg/platform/kube/monitoring/test/function_test.go
pkg/platform/kube/test/platform_test.go
pkg/platform/kube/test/suite.go

We have seen some cases where a function with minReplicas != maxReplicas is set as `Unhealthy` state while it's being scaled up.
This is because the way the function monitor decides wether a function is available or not is based on the function deployment's `Available` condition. However - this condition can be set to `False` while scaling up, due to `MinimumReplicasUnavailable`.
In this PR, I have added another check if the function deployment is unavailable, where we check if the function's HPA is actively scaling the function. If so - we give it a "grace period" (configurable, and defaults to 3m), in which if it is still scaling the function we do not set its state to `Unhealthy`.
If the grace period passed and the HPA is still working - set it to `Unhealthy` anyways.
It is important …

[Controller] Consider scaling when monitoring function state

---

pkg/functionconfig/types.go
pkg/platform/abstract/platform.go
pkg/platform/abstract/platform_test.go
pkg/platform/kube/platform_test.go

In this pull request, existence validation for triggers has been added. This validation is performed within the validateTriggers method, which is part of the function validation flow occurring after the enrichment flow. This is crucial because the default HTTP trigger is added during the enrichment phase. Therefore, we aim to raise an error only if there is no trigger (either default or custom).

[Dashboard] Add trigger existence validation

---

docs/index.md

update the meta title of the new website from "Nuclio Overview" to "Nuclio Documentation" to be the same as the old website -

[Docs] Fix title for SEO

---

cmd/processor/app/processor.go
cmd/processor/app/processor_test.go
docs/reference/runtimes/python/python-reference.md
docs/reference/triggers/kafka.md
pkg/processor/runtime/python/py/_nuclio_wrapper.py
pkg/processor/runtime/python/py/requirements/common.txt
pkg/processor/runtime/rpc/abstract.go
pkg/processor/runtime/runtime.go
pkg/processor/trigger/kafka/test/kafka_test.go
pkg/processor/trigger/trigger.go
pkg/processor/worker/allocator.go
pkg/processor/worker/worker.go
pkg/processor/worker/worker_test.go
test/_functions/python/drain-hook/drain-hook.py

Jira - [NUC-107](https://jira.iguazeng.com/browse/NUC-107)
In this PR, we have separated the drain and termination flows to enhance flexibility for users. Here's a breakdown of each flow:
**Drain**:
* applicable for functions with stream triggers only
* being called on rebalance by sending the `SIGUSR2` signal to runtime
**Termination**:
* applicable for functions with all trigger types
* being called when the processor terminates by sending the `SIGUSR1` signal to runtime

[Processor] [Python runtime][Docs] Split drain and termination flows

---

pkg/nuctl/command/export.go
pkg/platform/kube/test/platform_test.go
pkg/processor/build/builder.go

When building a function from a file path, the file contents are copied to the `functionSourceCode` attribute so it can be used when building an image.
In cases where the `codeEntryType` is not `sourceCode` , e.g when deploying a function from git, the source code is not needed in the function spec for the image to be built properly, and it is better for security and privacy to not expose the source code in such cases.
Resolves https://github.com/nuclio/nuclio/issues/3084

[Build] Don't populate function source code for all code entry types

---

pkg/processor/build/test/build_test.go

Following #3088 , source code is populated only if `codeEntryType` is set to `sourceCode`.

[Build] Fix source code population test

---

pkg/processor/trigger/kafka/trigger.go
pkg/processor/trigger/trigger.go
pkg/processor/util/partitionworker/allocator.go
pkg/processor/worker/allocator.go

Followup to https://github.com/nuclio/nuclio/pull/3092 , where we are blocking worker allocation if a the workers are terminated:
- Add termination check to the static worker allocator mode. It was missing from https://github.com/nuclio/nuclio/pull/3092 because the static allocator allocates all workers on startup, instead of per event.
- Rename termination state related methods to "drain state".
- In Kafka's `drainOnRebalance` - close the `readyForRebalanceChan` after sending a value on it. This will help cases where the `maxWaitHandlerDuringRebalance` times out before the drain handler finishes, and then the channel is closed before the drain invoking goroutine passes a value on it.

[Worker] Check if worker allocator is terminated in static allocation mode

---

pkg/common/helper.go
pkg/common/helper_test.go

Check that the field is empty before populating it with the given value, so we won't override the existing value.

[Helpers] Populate fields from values only if they're empty

---

pkg/nuctl/command/beta.go
pkg/nuctl/command/import.go
pkg/nuctl/command/nuctl.go
pkg/nuctl/command/redeploy.go

Jira - https://jira.iguazeng.com/browse/NUC-118
It's just a first iteration of upcoming changes in nuctl import logic. 
In this PR, we introduce error logging for each function import process.
We are moving away from using errgroup to enable the tracking of errors for each import individually. This change will enable us to generate a finely-grained report (in following PR) for each failed import, complete with a detailed description and recommendations.

[Nuctl] Change error handling logic for function import

---

pkg/common/consts.go
pkg/common/k8s.go
pkg/dashboard/resource/functionevent.go
pkg/dashboard/resource/project.go
pkg/dashboard/test/server_test.go
pkg/nuctl/command/common/renderers.go
pkg/nuctl/command/create.go
pkg/nuctl/command/export.go
pkg/nuctl/command/get.go
pkg/nuctl/test/project_test.go
pkg/platform/abstract/platform_test.go
pkg/platform/kube/client/function.go
pkg/platform/kube/controller/cronjobmonitoring.go
pkg/platform/kube/controller/evictedpodsmonitoring.go
pkg/platform/kube/functionres/lazy.go
pkg/platform/kube/functionres/lazy_test.go
pkg/platform/kube/ingress/ingress.go
pkg/platform/kube/platform_test.go
pkg/platform/kube/test/platform_test.go
pkg/platform/kube/test/suite.go
pkg/platform/local/client/store.go
pkg/platformconfig/platformconfig_test.go

For better reusability and locating usages, replace all explicit strings labels with constants.

[*] Replace all labels with constants

---

pkg/processor/build/builder.go

When passing a custom base image in the function spec, this overrides the base image of the specified runtime, meaning that the value in `spec.runtime` is ignored.
This means that if the function is set to use a specific programming language and it is not pre-installed in the given base image, the function will fail.
Relates to #3095

[Builder] Log runtime is ignored when custom base image is set

---

.golangci.yml

No replacements as of https://golangci-lint.run/usage/linters

[Lint] Remove deprecated linters

---

.golangci.yml
cmd/processor/app/processor.go
hack/scripts/releaser/releaser.go
pkg/dashboard/resource/resource.go
pkg/dashboard/test/server_test.go
pkg/functionconfig/scrubber.go
pkg/platform/kube/platform.go
pkg/platform/kube/test/functional/platform_test.go
pkg/processor/build/builder.go
pkg/processor/build/runtime/java/test/java_test.go
pkg/processor/runtime/golang/test/timeout_test.go
pkg/processor/runtime/rpc/abstract.go
pkg/processor/runtime/rpc/rpc_test.go
pkg/processor/trigger/kafka/test/kafka_test.go
pkg/processor/trigger/poller/trigger.go
pkg/processor/trigger/poller/v3ioitempoller/trigger.go
pkg/restful/resource_test.go

Removed all unused functions except for 2:
- `resolveReceivedEventBodies` in kafka suite - it is being called from a currently commented out test. 
In a followup PR it will be removed if the test is stale.
- `executeMinikube` in platform test - I can see benefits for it in the future.

[Lint] Add `unused` linter

---

pkg/nuctl/command/import.go
pkg/nuctl/test/function_test.go
test/_imports/autofixable_function.yaml

This PR is a part of https://jira.iguazeng.com/browse/NUC-118
It enables the ability to automatically fix known issues on the nuctl side if any occur.

[Nuctl] Autofix function import failure

---

.golangci.yml
Makefile
cmd/autoscaler/app/autoscaler.go
cmd/controller/app/controller.go
cmd/dashboard/app/run.go
cmd/dashboard/main.go
cmd/dlx/app/dlx.go
cmd/processor/app/processor.go
cmd/processor/app/processor_test.go
cmd/processor/main.go
pkg/dashboard/test/server_test.go
pkg/nuctl/command/nuctl.go
pkg/platform/kube/apis/nuclio.io/v1beta1/register.go
pkg/platform/kube/client/consumer.go
pkg/platform/kube/client/deleter.go
pkg/platform/kube/client/getter.go
pkg/processor/build/builder.go

Introduce the [gci](https://golangci-lint.run/usage/linters/#gci) import linter which is a part of the golangci linters.
It is able to validate **and fix** the imports according to the set rules.
The import order is as follows:
- Standard go libraries
- Nuclio in-house packages (`github.com/nuclio/nuclio/`)
- External packages
- Black imports (`_`)
- Relatice (dot) imports
See more at https://github.com/daixiang0/gci

[Lint] Replace impi with gci import linter

---

pkg/processor/runtime/rpc/abstract.go
pkg/processor/runtime/rpc/abstract_test.go

[No ticket]
Deleted `isDrained` flag from runtime. It caused a bug when we drain only on 1st happened rebalance.

[Processor] Delete isDrained flag from runtime

---

pkg/processor/trigger/http/trigger.go

Kubernetes health check requests do not have any headers (specifically - no `Origin` header), and are very frequent.
When CORS is enabled, these checks fail CORS origin validation and keep the trigger constantly busy so every request gets redirected.
Fixes https://jira.iguazeng.com/projects/NUC/issues/NUC-5

[HTTP] Handle internal healthcheck before request validation

---

pkg/processor/runtime/python/py/_nuclio_wrapper.py

[NUC-119](https://jira.iguazeng.com/browse/NUC-119)
Also:
* Exit python wrapper following a termination signal.
* Await a coroutine if returned by drain or termination callback (relates to https://github.com/nuclio/nuclio-sdk-py/pull/60). This unblocks [ML-4421](https://jira.iguazeng.com/browse/ML-4421), because it allows for drain/termination callbacks to call `explicit_ack()` without having to start a separate thread. E.g.:
```python
async def drain_callback():
for qualified_offset in context.qualified_offsets.values():
await context.platform.explicit_ack(qualified_offset)
```
instead of
```python
def drain_callback():
for qualified_offset in context.qualified_offsets.values():
def commit():
asyncio.run(context.platform.explicit_ack(qualified_offset))
thread = …
```

[Python] Fix duplicate event on drain callback

---

pkg/common/helper.go
pkg/nuctl/command/delete.go
pkg/nuctl/test/function_test.go
pkg/nuctl/test/suite.go
pkg/platformconfig/platformconfig.go

Allow deleting functions that are in a provisioning state, and projects with resources by using the `--force` flag.
This is already possible from the API, adding support in `nuctl` as well. 
Resolves #3059

[Nuctl] Allow force-deleting resources

---

pkg/nuctl/command/common/importreport.go
pkg/nuctl/command/import.go
pkg/nuctl/test/function_test.go
test/_imports/project_with_wrong_conf.yaml

[No ticket]
This PR provides following `nuctl import` improvements:
* Save import report with fields in lowercase
* Print error cause instead of wrapped error
* Save report for functions as well

[Nuctl] Lowercase report fields and report error cause

---

cmd/processor/app/processor.go
cmd/processor/app/processor_test.go
pkg/processor/runtime/python/py/_nuclio_wrapper.py
pkg/processor/runtime/rpc/abstract.go
pkg/processor/runtime/runtime.go
pkg/processor/trigger/kafka/trigger.go
pkg/processor/trigger/trigger.go
pkg/processor/worker/allocator.go
pkg/processor/worker/worker.go
pkg/processor/worker/worker_test.go

Jira - https://jira.iguazeng.com/browse/NUC-119
This pull request addresses an issue where the processor sent events to the runtime after draining and before reconnection. Now, the wrapper will skip all events received after draining and wait for the `SIGCONT` signal to resume event processing.
These changes also allow us to get rid of `isDrained` checks on processor side.

[Processor] Stop processing events on draining and send signal to continue processing

---

pkg/dashboard/resource/function.go
pkg/dashboard/test/server_test.go
pkg/nuctl/test/function_test.go
pkg/platform/abstract/platform.go
pkg/platform/abstract/platform_test.go

Function name validation was happening only on the `resource` side, when parsing the function information on `Create` / `Update` / `Delete` requests.
This allowed deploying functions with invalid names via Nuctl - The deployment would eventually fail, but the error message was not as clear as it should be.
This also caused errors when trying to delete the already erroneous function because delete request failed function validation.
Thus, we move the function name validation to the platform, so it will be appplied both when deploying via the dashboard and via nuctl.
Resolves #3045

[Platform] Move function name validation from resource to platform

---

pkg/dashboard/resource/function.go
pkg/dashboard/test/server_test.go
pkg/nuctl/test/function_test.go
pkg/platform/abstract/platform.go
pkg/platform/abstract/platform_test.go

Reverts nuclio/nuclio#3130
This failed the CI on several tests, and the reason being that if a function is deployed from a function configuration file (or URL), the config is read in the `Build` part of the deployment which happens after the enrichment/validation.
Until we move the configuration reading earlier, I'm reverting this change.

Revert "[Platform] Move function name validation from resource to platform"

---

.github/workflows/periodic.yaml

Send slack notification using a webhook when the periodic CI fails.
Using https://github.com/marketplace/actions/notify-slack-action

[CI] Add slack notification for periodic failures

---

.github/workflows/periodic.yaml

According to [notify-slack-action docs](https://github.com/marketplace/actions/notify-slack-action#:~:text=In%20order%20to%20use%20%7Bworkflow_url%7D%2C%20specify%20the%20token%20input%20as%20token%3A%20%24%7B%7B%20secrets.GITHUB_TOKEN%20%7D%7D.) - add the github token to allow using the {workflow_url} link.

[CI] Add token to slack notification step

---

pkg/processor/runtime/python/py/_nuclio_wrapper.py

To avoid blocking the asyncio event loop. Fixes `TestDrainHook`.

[Python] Always use nonblocking socket calls

---

.github/workflows/periodic.yaml

`workflow_url` link to the [workflow yaml](https://github.com/nuclio/nuclio/blob/development/.github/workflows/periodic.yaml) which is less interesting then the url to the actual run that failed.

[CI] Periodic slack notification - Replace workflow url with run url

---

pkg/nuctl/test/function_test.go
pkg/nuctl/test/project_test.go

In order to avoid using the same file in two tests at the same time, suffix was added to report file path.

[Nuctl] Fix report path in nuctl tests

---

pkg/processor/runtime/python/py/_nuclio_wrapper.py

Currently, it's retained until the next event arrives, preventing the event from being garbage collected before then.
Needed to resolve [ML-4421](https://jira.iguazeng.com/browse/ML-4421).

[Python] Delete reference to event as soon as possible

---

pkg/dashboard/functiontemplates/generated.go

In Nuclio, we have two options to define templates:
1. Define them locally in the nuclio/hack directory and generate a templates file (in a format understandable by the dashboard) with generate.go.
2. Define templates in the nuclio-templates repository.
I've noticed that the local templates (point 1) haven't been updated for a while. Therefore, we would like to have them updated.
Jira - https://jira.iguazeng.com/browse/NUC-132
To generate - run the file `generator.go`

[Templates] Update local templates from `hack` directory to the latest version

---

pkg/nuctl/command/common/helpers.go
pkg/nuctl/test/function_test.go
pkg/nuctl/test/project_test.go
pkg/nuctl/test/suite.go
pkg/platform/abstract/platform.go

Also:
- Comment out `TestParseReport` until a fix is found
- Some minor improvements

[Test] Add logs to Nuctl test suite teardown

---

cmd/dashboard/app/run.go
pkg/auth/iguazio/auth.go
pkg/platform/abstract/platform.go
pkg/platform/kube/platform_test.go

When creating a Nuclio function in Iguazio, a function label is created:
`iguazio.com/username: <username> `
Following the SSO effort, we need to allow usernames that looks like an email, e.g:`name@nuclio.com `
The issue is that the `@` sign is an invalid character in a kubernetes label.
To resolve this issue, in case we encounter an email-like username, we will split it into 2 labels, e.g.:
```
iguazio.com/username: name
iguazio.com/domain: nuclio.com 
```
Jira - https://jira.iguazeng.com/browse/NUC-133

[Dashboard] Support email in username label

---

docs/tasks/configuring-a-platform.md

Document how to enable and set up sensitive fields masking in the platform configuration.

[Docs] Add sensitive fields reference to platform configuration

---

pkg/common/config.go
pkg/common/config_test.go
pkg/platform/kube/platform.go

Recently, the bug was discovered where the sidecar's environment variables were being updated with the function's environment variables during each function deployment, resulting in numerous duplications of the same key in the sidecar's spec. This PR addresses the issue by implementing merging functionality.
Jira - https://jira.iguazeng.com/browse/NUC-134

[Dashboard] Merge sidecar's and container's environmental variables

---

pkg/nuctl/command/beta.go
pkg/nuctl/command/build.go
pkg/nuctl/command/create.go
pkg/nuctl/command/delete.go
pkg/nuctl/command/deploy.go
pkg/nuctl/command/export.go
pkg/nuctl/command/get.go
pkg/nuctl/command/import.go
pkg/nuctl/command/invoke.go
pkg/nuctl/command/nuctl.go
pkg/nuctl/command/parse.go
pkg/nuctl/command/redeploy.go
pkg/nuctl/command/update.go

This PR introduces the ability to configure the initialization of the platform during the initialization of the nuctl root command. Previously, platform initialization was required in every command before the addition of nuctl parse. However, when using nuctl parse, users do not expect to specify any namespace (or other) parameters. That's why there was a need for this functionality to be implemented.
Jira - https://jira.iguazeng.com/browse/NUC-136

[Nuctl] Do not init platform in nuctl parse

---

pkg/common/helper.go
pkg/nuctl/command/common/helpers.go
pkg/nuctl/test/function_test.go

This PR resolves the issue where an error occurred if a user attempted to create a report file directory that did not exist.
Jira - https://jira.iguazeng.com/browse/NUC-137

[Nuctl] Ensure that report path exists

---

pkg/processor/trigger/kafka/trigger.go

This PR addresses a bug where some messages were processed twice after a function restart. The issue arose because, after sending a termination signal, all workers were marked as terminated. Subsequently, when the `ConsumeClaim` function attempted to allocate a worker, it encountered an error, causing the consumption loop to break and, consequently, halting the `explicitAckHandler`. As a result, the processor side could no longer respond to control messages from the runtime side, as evidenced in the log with the message: `"Failed to read control message","more":{"errRootCause":"EOF"}}`.
This PR modifies this behavior so that the consumption loop does not break upon receiving the `ErrAllWorkersAreTerminated` error.
Jira - https://jira.iguazeng.com/browse/NUC-139

[Processor] Do not close kafka connection if workers are terminated

---

pkg/nuctl/command/parse.go

Simply print the generated report instead of logging it.
[No ticket]

[Nuctl] Print nuctl parse report without logging

---

pkg/nuctl/command/common/patchmanifest.go
pkg/nuctl/command/redeploy.go
pkg/nuctl/test/function_test.go
test/_imports/redeploy-test-function.yaml

This PR adds a test for `nuctl redeploy`, and also during writing tests, I noticed that we exit with a zero-code even if some redeployments fail. I've changed this so that we analyse the report and, based on it, raise an error or do not raise one.
Jira - https://jira.iguazeng.com/browse/NUC-52

[Nuctl] Add test for redeploy command and make it exit with error if failed

---

pkg/processor/runtime/python/py/_nuclio_wrapper.py

This PR aligns wrapper's behaviour for termination with the drain's one. So, we won't break a serving loop after termination, but will discard all events which come afterwards. The reason for this is the conditions when we want to stop waiting for full termination. One of those conditions should be met: runtime is stopped OR waiting timeout is passed. If the runtime exits right after sending an `ExplicitAck` control message, then the processor might not have enough time to process control messages which leads to processing same messages twice.

[Processor] Do not break wrapper loop on termination

---

pkg/processor/controlcommunication/types.go
pkg/processor/runtime/python/py/_nuclio_wrapper.py
pkg/processor/runtime/rpc/abstract.go
pkg/processor/trigger/kafka/test/kafka_test.go
pkg/processor/trigger/kafka/trigger.go

Reverts nuclio/nuclio#3153.
We have seen that this new functionality causes issues and is unstable regarding the different handling of the 2 control message kinds:
- stream ack message is received once by each partition, who always listens for these messages.
- drain done messages are sent from each partition to every worker, meaning that for N partition and M workers - we will have NxM messages. This requires a much more complex logic to handle, which is risky at this point of the development.
Reverting back to only waiting on timeout until we have a better solution to that.
Resolves https://jira.iguazeng.com/browse/NUC-141

Revert "[Processor] Add a control message to inform the processor that draining is done"

---

pkg/common/k8s.go
pkg/common/k8s_test.go
pkg/platform/abstract/platform.go
pkg/platform/abstract/platform_test.go
pkg/platform/abstract/project/external/leader/iguazio/client.go
pkg/platform/abstract/project/external/leader/iguazio/synchronizer.go
pkg/platform/abstract/project/external/leader/iguazio/synchronizer_test.go
pkg/platform/kube/test/platform_test.go

When a new project is created in the leader, it sends a POST request to Nuclio to create the project, instead of relying on Nuclio's synchronization mechanism.
Since currently the leaders allow for project labels that are invalid in k8s, we want to just ignore those labels when we receive a create project request from the leader.
**Note:** these labels are already filtered in the synchronization mechanism (see #2794).
In addition, some more improvements regarding this flow:
- Move label filtering to the common k8s module.
- Validate project labels to get a better traceback and failing early, instead of failing on the actual CRD creation.
- Differentiate the `Creating projects` logs a bit for a better debugging experience.

[Project] Filter invalid labels if creating project from leader request

---

docs/reference/function-configuration/function-configuration-reference.md
pkg/platform/kube/functionres/lazy.go
pkg/platform/kube/functionres/lazy_test.go
pkg/platform/kube/monitoring/test/function_test.go
pkg/platform/kube/platform.go
pkg/platform/local/platform.go

This PR addresses pretty old bug where we set function to error state within the fast-fail controller's mechanism because of either CrashLoop or scheduling issues. So, we could end up with working and healthy function stacked in error state forever, because our approach to Nuclio states assumes that `error` state is a permanent state which can not be changed per time. While `unhealthy` state is a state that we monitor with FunctionMonitor component, so it is changeable. In light of this, we decided to set function to `unhealthy` state in case of any of above described errors occurred. 
Also, `resolveFailFast` function returns not only error, but also a status to which controller should set the function in case of error. For now, we only set function to `unhealthy` state here, but we plan …

[Controller] Set function status to `unhealthy` instead of `error` during fast-fail check

---

docs/reference/triggers/mqtt.md
pkg/processor/trigger/kinesis/event.go
pkg/processor/trigger/mqtt/event.go
pkg/processor/trigger/mqtt/trigger.go
pkg/processor/trigger/nats/event.go
pkg/processor/trigger/partitioned/eventhub/event.go

The MQTT topic was previously populated in the URL field of the event, and was confused with the recently added (empty) `topic` property.
In this PR I added some fields to the MQTT event, as suggested in #3170 :
-  `URL`: The URL of the MQTT broker
- `topic`: The topic of the message
- `path`: The topic of the message (alias for `topic`)
- `body`: The message payload
- `id`: The message id
Resolves #3170

[MQTT] Add properties to the mqtt event

---

docs/conf.py
docs/requirements.txt

Remove the `sphinx-markdown-tables` package that uses the less-permissive LGPL license.

[Docs] Remove usage of `sphinx_markdown_tables` library

---

docs/conf.py
docs/requirements.txt

[Docs] Remove usage of `sphinx_markdown_tables` library [1.12.x]

---

docs/requirements.txt

[Docs] Add `markdown` library to requirements

---

pkg/processor/build/runtime/test/suite/suite.go

When creating a compressed archive, we need to specify the compressions format, otherwise it returns an undefined file that is not recognized as an archive.

[Test] Fix runtime archive tests

---

pkg/processor/trigger/kafka/trigger.go

TLS 1.0 and 1.1 are out-of-date protocols and they contain security vulnerabilities that may be exploited by attackers.
Version >= 1.2 should be used instead.
Deprecation: https://datatracker.ietf.org/doc/html/rfc8996

[Kafka] Remove support for TLS version 1.0 and 1.1

---

pkg/common/consts.go
pkg/platform/kube/functionres/lazy_test.go
pkg/platform/kube/platform.go
pkg/platform/kube/platform_test.go

Currently, we don't allow passing an empty host for the API gateway. Typically, it's generated on the UI side, which hasn't been a significant issue until now. However, with the implementation of API Gateways on the MLRun side, where MLRun will create API gateways via the Nuclio API, we want to enable MLRun to not set the host explicitly and leave this task to Nuclio.
https://iguazio.atlassian.net/browse/NUC-116

[Dashboard] Allow passing empty API gateway host

---

cmd/processor/app/processor.go

jira - https://iguazio.atlassian.net/browse/NUC-163
This PR fixes a bug where we see `json: unsupported value: encountered a cycle via` in the log. The culprit is this line: `p.logger.DebugWith("Starting triggers", "triggers", p.triggers)`. Here, `p.triggers` is of type `[]Trigger`, where Trigger is an interface. Each trigger in the list is a child of an `AbstractTrigger`. Each `AbstractTrigger` maintains a pointer to the original child trigger.So here is a loop. Hence, this log line itself is the reason we encounter this error. The logger was unable to encode the object into JSON.

[Misc] Fix the error `json: unsupported value: encountered a cycle via`

---

pkg/nuctl/command/common/patchmanifest.go
pkg/nuctl/command/common/patchmanifest_test.go

Here is an example of the error we got:
```
cmex020008l4lvyj0igny3-extract  
error   "Failed to patch function"
retryable   false
```
That's not meaningful enough, because it's a wrapped error, not the error cause, so we need to print the error cause.

[Nuctl] Add more detailed fail description for patch manifest

---

pkg/platform/kube/functionres/lazy.go
pkg/platform/kube/test/platform_test.go

When updating a deployment, do not ignore the init and sidecar containers as they might change as well.
For init containers - recreate the containers list from scratch.
For sidecars - keep the first container (the main nuclio function container) and recreate the sidecar containers.
Resolves https://iguazio.atlassian.net/browse/NUC-172

[Controller] Populate init and sidecar containers when updating a function

---

cmd/processor/app/processor.go
pkg/common/scrubber.go
pkg/functionconfig/scrubber.go
pkg/functionconfig/scrubber_test.go
pkg/functionconfig/types.go
pkg/platform/apigateway.go
pkg/platform/apigateway_test.go
pkg/platform/kube/client/deployer.go
pkg/platform/types.go

This PR is the first iteration of implementing a masking functionality for API gateways. 
Within this PR scrubber was defined as an interface in `common` pkg. All the abstract functionality was moved to AbstractScrubber entity. Two structs inherit `AbstractScrubber` - `functionconfig.Scrubber` and `APIGatewayScrubber`. 
Also, `ReferencePrefix` is a configurable field now.
1st part of https://iguazio.atlassian.net/browse/NUC-114 - https://iguazio.atlassian.net/browse/NUC-169

[Scrubber] API Gateway Scrubber

---

pkg/platform/kube/platform.go
pkg/platform/kube/platform_test.go
pkg/platformconfig/types.go

The default behavior has been modified to consider the platform's NodeSelectors only if the project's NodeSelectors are not set. This adjustment aims to synchronize MLRun's logic with Nuclio's. Despite altering the default behavior, this pull request aims to provide users with the option to re-enable the merging logic.
Jira - https://iguazio.atlassian.net/browse/NUC-171

[Platform] Add platform configuration to merge platform's default node selectors with project's node selectors

---

pkg/platform/abstract/platform.go
pkg/platform/abstract/platform_test.go

This PR fixes the enrichment of `disableDefaultHTTPTrigger` configuration. The original PR which implemented this functionality had some parts left only for platform configuration enrichment and as a result there are some code parts left misaligned with function configuration.

[Platform] Fix default http trigger enrichment

---

pkg/dashboard/resource/function.go
pkg/dashboard/test/server_test.go

Nuctl expects dashboard to return Accepted status, otherwise it fails function redeploy. It makes sense to return `Accepted` if function is ready on condition that user want to redeploy only `imported` functions.

[Dashboard] Return nuclio.ErrAccepted instead of nil when we don't redeploy function because it is not imported 

---

pkg/processor/trigger/v3iostream/event.go

Revert a small part of #3125 , since the event path is not supposed to be the stream path (which is basically the topic), but an internal path in the function.
This causes some issues for functions that handle different paths.
Resolves https://iguazio.atlassian.net/browse/NUC-177

[v3iostream] Remove `GetPath` implementation from v3iostream event

---

pkg/processor/trigger/v3iostream/event.go

[v3iostream] Remove `GetPath` implementation from v3iostream event [1.12.x]

---

.github/workflows/ci.yaml
docs/reference/api/README.md
pkg/dashboard/resource/function.go
pkg/platform/kube/platform.go
pkg/platform/local/platform.go
pkg/platform/mock/platform.go
pkg/platform/platform.go
pkg/platform/types.go

With the addition of sidecars, a function pod can have multiple containers.
We want to provide an API to stream logs from a specific given container.
This PR extends the log streaming API by adding support for the `containerName` query param.
Example usage:
```
GET /api/functions/<function name>/logs/<replica-name>`?containerName=sidecar
```

[Function] Support getting log stream from a specific container

---

pkg/common/consts.go
pkg/platform/kube/client/deployer.go
pkg/platform/kube/controller/nucliofunction.go
pkg/platform/kube/functionres/lazy.go
pkg/platform/kube/functionres/types.go

This PR fixes a bug where on all request except the 1st one to scaledToZero function we returned 503 error without waiting for the function start.
Jira - https://iguazio.atlassian.net/browse/NUC-1 (solution is explained in the task)

[Controller] Replace selector only when function is ready

---

pkg/platform/abstract/platform.go
pkg/platform/kube/controller/nucliofunction.go
pkg/platform/kube/functionres/lazy.go
pkg/platform/kube/functionres/lazy_test.go
pkg/platform/kube/platform.go
pkg/platform/kube/platform_test.go
pkg/platform/kube/test/platform_test.go

To allow accessing the sidecar containers directly, we first need to expose them to the internal cluster by adding the sidecar ports to the function service.
Since the function service already populates some other reserved internal ports, added validation to the sidecars' ports so they won't override anything.
https://iguazio.atlassian.net/browse/NUC-185

[Sidecars] Populate function service with sidecar container ports

---

pkg/platform/abstract/platform.go

Jira - https://iguazio.atlassian.net/browse/NUC-189
This PR addresses the bug which happened during upgrade. 
The function that failed importing had the following in its spec:
* V3io Stream trigger
* MinReplicas = 0
* MaxReplicas = 4
In Nuclio, we autofix functions with v3io stream triggers and `MinReplicas != MaxReplicas` to `MinReplicas == MaxReplicas`, so what happened is that the resulting spec was `MinReplicas = MaxReplicas = 0` - which is not allowed. So, the new logic is to check `minReplicas` value and if it's equal to `0` , set it to `1`.

[Nuctl] Fix autofixing of v3io trigger configuration

---

pkg/platform/abstract/platform.go

[Nuctl] Fix autofixing of v3io trigger configuration [1.12.x]

---

pkg/processor/trigger/kafka/test/kafka_test.go

The `wurstmeister` project is no longer maintained, and its images have been deleted from docker hub (see [this issue](https://github.com/wurstmeister/kafka-docker/issues/744).
Replacing the absent images with the same images on iguazio gcr.

[Kafka] Replace Kafka images in integration test suite

---

pkg/processor/runtime/python/py/_nuclio_wrapper.py
pkg/processor/runtime/python/py/test_wrapper.py

Jira - https://iguazio.atlassian.net/browse/NUC-180, part of https://iguazio.atlassian.net/browse/NUC-146
This PR is a crucial part of a upcoming event batching feature. It is here more for review purpose, there is no need to merge it for now. 
This part implements an ability to encode a batched response from `entrypoint_output` to json, so processor able to read it correctly. It doesn't change anything in current flow, just preparation for the future.

[Wrapper] Support a batched response as entrypoint_output in python wrapper

---

pkg/common/strings.go
pkg/platform/kube/platform.go
pkg/platform/kube/platform_test.go

We don't have any name validation for api gateway, so this PR addresses this issue and adds a validation. 
I decided to implement it by adding the common method which checks if name follows k8s common naming rules because from the api_gateway name we create an ingress object.
Jira - https://iguazio.atlassian.net/browse/ML-6487

[Dashboard] Add name validation for api gateway

---

pkg/containerimagebuilderpusher/kaniko.go

I was running github actions to run linter [makezero](https://github.com/ashanbrown/makezero) for top github golang repos.
see issues https://github.com/alingse/go-linter-runner/issues/1
and the github actions output https://github.com/alingse/go-linter-runner/actions/runs/9242646334/job/25425727611 
```
====================================================================================================
append to slice `onbuildStages` with non-zero initialized length at https://github.com/nuclio/nuclio/blob/development/pkg/containerimagebuilderpusher/kaniko.go#L155:19
====================================================================================================
```

[Kaniko] Fix non-zero slice initialization

---

hack/scripts/benchmark/bench.go

Usage example:
`go run benchmark/bench.go  -url=<url> -totalRequests=1000 -maxParallel=100`

[Script] Add script for local benchmarking

---

pkg/common/headers/headers.go
pkg/dashboard/resource/function.go
pkg/nuctl/command/delete.go
pkg/platform/kube/platform.go
pkg/platform/kube/test/platform_test.go
pkg/platform/kube/test/suite.go
pkg/platform/types.go

Jira - https://iguazio.atlassian.net/browse/ML-6561
This PR provides the ability to define via handler whether API gateways associated with a function should be deleted when deleting the function. The default behavior remains the same, meaning the API gateway will not be deleted, and the user will need to delete it manually.

[Dashboard] Allow deleting a function along with its api gateways

---

pkg/dashboard/resource/apigateway.go
pkg/nuctl/command/get.go
pkg/nuctl/test/apigagteway_test.go
pkg/platform/kube/platform.go
pkg/platform/types.go

This change allows to get list of api gateways attached to specific function. 
* In nuctl, the function name can be specified by `--function-name <function-name>`. 
* When sending a request to the Dashboard to get API gateways attached to a specific function, the function name should be included in the request header as "X-Nuclio-Function-Name".
Jira: https://iguazio.atlassian.net/issues/NUC-205

[API Gateways] Add option to list API gateways associated with a specific function

---

pkg/dockerclient/dockerclient.go
pkg/dockerclient/mock.go
pkg/dockerclient/shell.go
pkg/platform/local/client/store.go
pkg/platform/local/platform_test.go
pkg/platform/local/test/platform_test.go

This PR addresses #3261 issue, where user faced a `docker exec` error, because argument was too long (> 131072, see restrictions [here](https://man7.org/linux/man-pages/man2/execve.2.html) for argument `MAX_ARG_STRLEN`)
To address this issue, I've updated the approach for writing files. Instead of using docker exec to write directly to the container, we now create a temporary file locally, copy it to the storage container, and then delete the temporary file.
Test fails on the old version:

[Local] Use docker copy instead of docker exec when saving function to a storage

---

Makefile
pkg/processor/build/builder.go
pkg/processor/build/builder_test.go

When using `Github` code entry type with a fine-grained token, downloading the file from the URL `"https://github.com/<ORG>/<REPO>/archive/<BRANCH>.zip"` doesn't work, as the fined grained token only works with the Github API.
In this PR we replace the URL with the archive API url: `"https://api.github.com/repos/<ORG>/<REPO>/zipball/<BRANCH>"`, which works both with Github's fine-grained tokens and classic tokens.
Additionally, since the `Git` code entry type is uses the go-git client and is a lot more resilient and robust, we deprecate the `Github` code entry type and will encourage users to use `Git` instead.

[Builder] Fix Github archive url

---

docs/reference/nuctl/index.rst

We renamed the folder from `cli-docs` to `cli`. This is the place where we forgot to do this and as a result there is no proper link to generated documentation in our website.

[Docs] Fix nuctl docs link

---

Makefile
pkg/processor/build/builder.go
pkg/processor/build/builder_test.go
pkg/processor/build/runtime/test/suite/suite.go

Backports GitHub code entry type fixes in #3266 and #3269 to `1.13.x`

[Builder] Fix Github archive url [1.13.x]

---

pkg/platform/kube/ingress/ingress.go

The `ssl-redirect` nginx annotation is determined only by the value in the platform config, and if it is set on an ingress explicitly (e.g. on an API Gateway), it will always be overridden by the value from the platform config.
Instead:
- If the platform config enables SSL Redirect: set to True
- If not, only set to false if not already explicitly set
Related to https://iguazio.atlassian.net/browse/ML-7108

[Ingress] Override ssl redirect annotation only if it is not set

---

pkg/containerimagebuilderpusher/types.go

- Older versions do not support pod-identity-association auth

[ContainerImageBuilderPusher] Bump awscli and kaniko versions

---

pkg/platform/kube/functionres/lazy.go

If user wants to set one of the sidecar containers as the default container, don't override the annotation with the nuclio container.
Related to https://iguazio.atlassian.net/browse/ML-7345

[Controller] Don't override default container annotation if exists [1.13.x]

---

pkg/processor/build/builder_test.go

Periodic CI fails after merging #3304, this PR fixes the test.

[Tests] Fix periodic tests

---

pkg/platform/kube/platform.go

In this [pr](https://github.com/nuclio/nuclio/pull/3262/files) filtering by project was broken by removing `LabelSelector: getAPIGatewaysOptions.Labels` 
This change wasn't released in any version yet, so no backporting needed.

[API Gateways] Fix filtering api gateways by project

---

pkg/containerimagebuilderpusher/kaniko.go
pkg/containerimagebuilderpusher/types.go
pkg/processor/build/builder.go

This PR addresses the issue where the Kaniko pod remains in a Pending status (e.g., when it is not schedulable). Previously, no information was provided to assist users in troubleshooting this issue. With this PR, the Kubernetes events for the Kaniko pod are now checked, allowing real-time warnings to be displayed in the build logs.
Build log example: 
jira - iguazio.atlassian.net/browse/NUC-232

[Dashboard] Display kaniko pod warning events in the build logs

---

hack/k8s/helm/nuclio/Chart.yaml
hack/scripts/releaser/releaser.go
hack/scripts/releaser/releaser_test.go

The cloud-specific chart directories were already removed in v1.7.3 (https://github.com/nuclio/nuclio/pull/2407), so performing actions on those directories just causes noise in the releaser script.

[Releaser] Remove extra chart directories

---

pkg/platform/abstract/platform.go
pkg/platform/abstract/platform_test.go
pkg/platform/kube/platform_test.go
pkg/processor/trigger/kafka/trigger.go
pkg/processor/trigger/v3iostream/trigger.go

Jira - https://iguazio.atlassian.net/browse/NUC-233
This PR addresses three issues:
1. **Sharing workerAllocation between triggers of the same kind by default**. Previously, if a trigger's `WorkerAllocatorName` configuration was not defined, the same worker allocator (represented by an empty string) was used. This behavior has been changed. Now, by default, `WorkerAllocatorName` will be enriched with the `TriggerName` if it isn't explicitly defined. 
_Workaround for previous versions_: Define a unique `WorkerAllocatorName` for each trigger of the same kind.
2. **ExplicitAck on v3io.** Control messages were not filtered by shard and stream path, leading to incorrect event committing.
_Workaround for previous versions_: doesn't exist
3. **ExplicitAck on Kafka.**  Control messages were not …

[Processor] Fix ExplicitAck on 2 and more triggers of the same type

---

Makefile
pkg/nuctl/client/api.go
pkg/nuctl/command/common/patchmanifest.go
pkg/nuctl/command/redeploy.go
pkg/nuctl/test/function_test.go

Following a client failure to redeploy functions, it was impossible to understand what was the actual failure from the traceback and logs:
```
24.09.04 05:06:55.975 (W)                     nuctl Failed to patch functions {"err": "Failed to patch function", "errVerbose": "\nError - Failed to patch function\n    /nuclio/pkg/nuctl/command/redeploy.go:208\n\nCall stack:\nFailed to patch function\n    /nuclio/pkg/nuctl/command/redeploy.go:208\nFailed to patch function"}
...
Failed to redeploy function `pr-administration-notifications`.Reason: `Failed to patch function`. Retryable: false
...
```
In this case, the investigation led to the failure reason being a 412 response from the API, although it wasn't shown in the logs at all.
To improve the error handling experience, in this PR we:
1. …

[Nuctl] Fix redeploy errors and logs [1.13.x]

---

.github/workflows/benchmark.yaml
.github/workflows/ci.yaml

Following security fixes and deprecations. 
Must bump both together as v4 is not backwards compatible.
- https://github.com/actions/upload-artifact
- https://github.com/actions/download-artifact
closes #3339

[CI] Bump upload/download artifact actions

---

docs/reference/triggers/v3iostream.md
pkg/processor/trigger/v3iostream/types.go
pkg/processor/trigger/v3iostream/v3iostream_test.go

To help avoid setting explicit access keys in the v3io stream trigger configuration, we now support setting the access key as `$generate`.
In such a case, Nuclio will look for the from the `V3IO_ACCESS_KEY` env var, and take the access key from there if it exists.
The env var can be set from a secret, thus keeping all of the data secure.
Related to a [change in MLRun](https://github.com/mlrun/mlrun/pull/6307).
https://iguazio.atlassian.net/browse/ML-7779

[V3IOStream] Generate access key from env var [1.13.x]

---

pkg/processor/trigger/v3iostream/trigger.go

Jira - https://iguazio.atlassian.net/browse/NUC-256
In contrast to Kafka, where we support processing from multiple topics within a single trigger, in V3io, we only support processing from a single stream path. 
Furthermore, the v3io-go library does not require the streamPath when committing a record, as it is already configured on the `claim`. 
Therefore, we can remove this check in the V3io trigger.

[V3io] Do not filter ExplicitAck by streamPath for v3io trigger

---

pkg/processor/trigger/http/http_test.go
pkg/processor/trigger/http/types.go

Part of new async event processing feature which defines two modes for http trigger.
Jira - https://iguazio.atlassian.net/browse/NUC-244

[Async processing] Add mode to http trigger configuration

---

pkg/processor/trigger/v3iostream/trigger.go
pkg/processor/trigger/v3iostream/types.go

Part of https://iguazio.atlassian.net/browse/NUC-267
This log is important for debugging purposes mainly and is already hidden for default execution in kafka. This PR aligns the logging logic of v3io with kafka.

[Processor] Align ExplicitAck log for v3io and kafka

---

pkg/processor/trigger/v3iostream/trigger.go

Jira - https://iguazio.atlassian.net/browse/NUC-267
This PR addresses the issue of processing multiple v3io triggers when they are sharing workers. In addition to that, because of known bugs in mlrun's storey and nuclio_sdk_py, a check for `explicitAckAttributes.Topic != "/"` was added to be BC with older versions. Older versions still don't support processing of multiple triggers, this check is needed to support single trigger processing.

[Processor] Filter v3io ExplicitAck by topic if passed

---

pkg/common/k8s.go
pkg/platform/kube/apis/nuclio.io/v1beta1/types_test.go

Allows to override and ignore node selectors defined on platform/project level.
Jira - https://iguazio.atlassian.net/browse/NUC-272

[NodeSelector] Remove nodeSelector if empty string passed to function config

---

pkg/processor/runtime/python/py/requirements/common.txt

Bumps nuclio-sdk-py to the latest version: https://github.com/nuclio/nuclio-sdk-py/releases/tag/v0.5.13

[Dependencies] Bump nuclio-sdk-py to 0.5.13

---

pkg/containerimagebuilderpusher/kaniko.go
pkg/platform/kube/test/function/function_test.go
pkg/processor/build/builder.go

Reverts part of the changes made in [this PR](https://github.com/nuclio/nuclio/pull/3351), which caused a bug when running a Nuclio function with a defined `SecurityContext` (i.e., when the user is not root). The issue is that the Kaniko builder must be run as root, so we can not propagate the SecurityContext to the KanikoBuilder. As a result, all files are created as root within the container. When running a container as a non-root user, access to these files is denied due to their 700 permissions.
Jira - https://iguazio.atlassian.net/browse/NUC-263

[Security] Fix access rights for wrapper

---

pkg/nuctl/test/function_test.go
pkg/platform/abstract/platform.go
test/_imports/never_run_before_export_function.yaml

The main change in this PR is that, instead of first checking functionBuildRequired and then looking for the skip-build annotation, we will now first check for the presence of the annotation. If it exists, we will then check functionBuildRequired. This change resolves a bug that occurred when importing a function that had never been in a healthy state before export.
Also, adds a test which fails without changes.
Jira - https://iguazio.atlassian.net/browse/NUC-268

[Nuctl][Dashboard] Fix importing function that was in error or building state before export

---

pkg/nuctl/command/redeploy.go

https://iguazio.atlassian.net/browse/NUC-297
Unhealthy is not a terminal state, so a function can still become ready.

[Nuctl] Do not stop waiting for readiness after redeploy if function is unhealthy

---

pkg/processor/trigger/kafka/kafka_test.go
pkg/processor/trigger/kafka/trigger.go
pkg/processor/trigger/kafka/types.go

This change addresses the misleading default behavior by ensuring that Sarama’s `Net.SASL.Handshake` setting now defaults to true, aligning with Sarama's internal default and avoiding unexpected outcomes.
Previously, if the `SASL.Handshake` value wasn’t provided in trigger configuration, it was defaulting to false, leading to potential connection issues and unexpected behavior, especially in environments where true is required. Now, if `SASL.Handshake` isn’t specified, the `Net.SASL.Handshake` setting defaults to true.

[Processor] Change default handshake value to true

---

docs/reference/function-configuration/batching.md

Sphinx doesn't render GitHub's markdown emoji, so this file is rendered with the raw `:bangbang:`.

[Docs] Remove md emoji

---

pkg/common/helper.go
pkg/containerimagebuilderpusher/docker.go
pkg/containerimagebuilderpusher/kaniko.go
pkg/processor/build/builder.go
pkg/processor/build/runtime/test/suite/suite.go
pkg/processor/build/util/unarchive.go

Kaniko job can't be executed as non-root user and it also doesn't allow to change a file owner to another user. But we still want to be able to execute nuclio functions with `SecurityContext` set to non-root. For these, we need to revert the changes done in https://github.com/nuclio/nuclio/pull/3349/files.

[Security] Change directory access back to 755

---

docs/reference/triggers/kafka.md

The `partitions` field is not used in Kafka configuration. 
https://iguazio.atlassian.net/browse/NUC-241

[Docs] Remove `partitions` configuration from Kafka trigger doc

---

.github/styles/Nuclio/ignore.txt
README.md

Hello team,
I'm the maintainer of [Anteon](https://github.com/getanteon/anteon). We have created Gurubase.io with the mission of building a centralized, open-source tool-focused knowledge base. Essentially, each "guru" is equipped with custom knowledge to answer user questions based on collected data related to that tool.
I wanted to update you that I've manually added the [Nuclio Guru](https://gurubase.io/g/nuclio) to Gurubase. Nuclio Guru uses the data from this repo and data from the [docs](https://docs.nuclio.io/en/stable/) to answer questions by leveraging the LLM.
In this PR, I showcased the "Nuclio Guru", which highlights that Nuclio now has an AI assistant available to help users with their questions. Please let me know your thoughts on this contribution.
Additionally, if you want …

[Docs] Introducing Nuclio Guru on Gurubase.io

---

hack/scripts/releaser/releaser.go

When cloning the repo with `https` scheme, `git` commands expect username-password which is not supported anymore.
Added `git` scheme to allow using ssh keys for authentication.

[Releaser] Support `git` repository scheme

---

hack/scripts/patch-remote/patch_remote.py
pkg/common/headers/headers.go
pkg/platform/kube/functionres/lazy.go

The cron job invokes the function's service using an http request.
When a function is scaled to zero, the DLX is listening for function invocations, but it is looking for the `X-Nuclio-Target` header to know which service to invoke.
This header was missing from the Cron job's http request, and thus scaling from zero wasn't possible using a Cron trigger.
https://iguazio.atlassian.net/browse/NUC-313

[Cron] Add target name header

---

pkg/processor/trigger/http/test/suite/suite.go

python-runtime-tests fail sometimes in periodic CI and it's impossible to understand the reason because log is too big.

[Test] Do not log full request body if longer than 256

---

pkg/common/helper.go
pkg/dashboard/resource/function.go
pkg/platform/kube/platform.go
pkg/platform/local/platform.go
pkg/platform/mock/platform.go
pkg/platform/platform.go
pkg/platform/types.go
pkg/restful/resource.go

The following 2 endpoints were missing filtering by permissions, and were open to all:
- `GET /api/functions/<function name>/replicas`
- `GET /api/functions/<function name>/logs/<replica-name>`
Added filtering based on permissions for the `/replicas` endpoint, which is called in the `/logs/<replica-name>` logic too.
Also fixed custom route error logs to avoid failing on non json-able variables.
https://iguazio.atlassian.net/browse/NUC-273

[Function] Query permissions for function replica API
